// ========================================
// GRADES, SKILLS, AND GAMES EXPORTS
// ========================================

export const grades = [
  { id: "1", label: "Grade 1 (中1)", color: "bg-blue-500" },
  { id: "2", label: "Grade 2 (中2)", color: "bg-green-500" },
  { id: "3", label: "Grade 3 (中3)", color: "bg-purple-500" },
];

export const skills = [
  { id: "speaking", label: "Speaking", icon: "Mic" },
  { id: "listening", label: "Listening", icon: "Headphones" },
  { id: "reading", label: "Reading", icon: "BookOpen" },
  { id: "writing", label: "Writing", icon: "Pencil" },
  { id: "multi", label: "Multi-Skill", icon: "Star" },
];

export const games = [
  {
    id: "3-hint",
    title: "3 Hint Quiz",
    description: "Listen to hints and guess the word!",
    grades: ["1", "2"],
    skills: ["listening", "speaking"],
    color: "text-blue-500",
  },
  {
    id: "word-hunt",
    title: "Word Hunt",
    description: "Find hidden words in a pictorial word grid.",
    grades: ["1", "2", "3"],
    skills: ["reading"],
    color: "text-green-500",
  },
  {
    id: "class-quiz",
    title: "Class Quiz",
    description: "Fast-paced team battles",
    grades: ["1", "2", "3"],
    skills: ["multi"],
    color: "text-yellow-500",
  },
  {
    id: "interview-bingo",
    title: "Interview Bingo",
    description: "Ask friends questions to get bingo.",
    grades: ["1", "2"],
    skills: ["speaking", "listening"],
    color: "text-orange-500",
  },
  {
    id: "jeopardy",
    title: "Jeopardy Review",
    description: "Team battle for points!",
    grades: ["2", "3"],
    skills: ["multi"],
    color: "text-red-500",
  },
];

// ========================================
// WORD HUNT DATA - 8 TOPICS, 40 PUZZLES
// ========================================

export const wordHuntData = {
  topics: [
    {
      id: "animals",
      label: "Animals",
      color: "bg-blue-500",
      description: "Find hidden creatures",
    },
    {
      id: "food",
      label: "Food & Drinks",
      color: "bg-orange-500",
      description: "Delicious words",
    },
    {
      id: "school",
      label: "School Life",
      color: "bg-green-500",
      description: "Classroom vocabulary",
    },
    {
      id: "nature",
      label: "Nature & Weather",
      color: "bg-purple-500",
      description: "Natural world",
    },
    {
      id: "colors",
      label: "Colors & Shapes",
      color: "bg-pink-500",
      description: "Visual elements",
    },
    {
      id: "sports",
      label: "Sports & Games",
      color: "bg-red-500",
      description: "Athletic activities",
    },
    {
      id: "family",
      label: "Family & People",
      color: "bg-indigo-500",
      description: "Relationships",
    },
    {
      id: "places",
      label: "Places & Travel",
      color: "bg-teal-500",
      description: "Locations worldwide",
    },
  ],

  puzzles: {
    animals: [
      {
        id: "animals-1",
        title: "Ocean Animals",
        grade: "1",
        grid: [
          "S H A R K W D O L P H I N X",
          "E Q W H A L E R T Y U I O P",
          "A Z X C V B N M A S D F G H",
          "L J K L Q W E R T Y U I O P",
          "A S T U R T L E D F G H J K",
          "O C T O P U S Z X C V B N M",
          "F I S H Q W E R T Y U I O P",
          "Z X C R A B N M K L J H G F",
          "D S A Q W E R T Y U I O P L",
          "M N B V C X Z A S D F G H J",
          "S E A L K L M N O P Q R S T",
          "U V W X Y Z A B C D E F G H",
          "I J K L M N O P Q R S T U V",
          "W X Y Z A B C D E F G H I J",
        ],
        words: [
          "SHARK",
          "WHALE",
          "DOLPHIN",
          "SEAL",
          "TURTLE",
          "OCTOPUS",
          "FISH",
          "CRAB",
        ],
        hints: [
          "Big fish with sharp teeth (5)",
          "Largest ocean animal (5)",
          "Smart jumping animal (7)",
          "Has flippers (4)",
          "Slow with hard shell (6)",
          "Eight long arms (7)",
          "Swims in water (4)",
          "Walks sideways (4)",
        ],
      },
      {
        id: "animals-2",
        title: "Farm Animals",
        grade: "1",
        grid: [
          "P I G C O W H O R S E Q W E",
          "R T Y U I O P A S D F G H J",
          "S H E E P K L Z X C V B N M",
          "Q W E R T Y U I O P A S D F",
          "C H I C K E N G H J K L M N",
          "B V C X Z A S D F G H J K L",
          "D U C K Q W E R T Y U I O P",
          "Z X C V B N M A S D G O A T",
          "R O O S T E R F G H J K L M",
          "N B V C X Z A S D F G H J K",
          "L M N O P Q R S T U V W X Y",
          "Z A B C D E F G H I J K L M",
          "N O P Q R S T U V W X Y Z A",
          "B C D E F G H I J K L M N O",
        ],
        words: [
          "PIG",
          "COW",
          "HORSE",
          "SHEEP",
          "CHICKEN",
          "DUCK",
          "GOAT",
          "ROOSTER",
        ],
        hints: [
          "Says oink (3)",
          "Gives milk (3)",
          "You can ride (5)",
          "Has wool (5)",
          "Lays eggs (7)",
          "Swims in pond (4)",
          "Has horns (4)",
          "Crows in morning (7)",
        ],
      },
      {
        id: "animals-3",
        title: "Wild Animals",
        grade: "2",
        grid: [
          "L I O N T I G E R B E A R X",
          "E L E P H A N T Q W E R T Y",
          "O P A R D Z E B R A S D F G",
          "G I R A F F E H J K L M N B",
          "M O N K E Y V C X Z A S D F",
          "R H I N O Q W E R T Y U I O",
          "P A N D A P L K J H G F D S",
          "K A N G A R O O A Z X C V B",
          "W O L F N M Q W E R T Y U I",
          "S N A K E O P A S D F G H J",
          "K L M N O P Q R S T U V W X",
          "Y Z A B C D E F G H I J K L",
          "M N O P Q R S T U V W X Y Z",
          "A B C D E F G H I J K L M N",
        ],
        words: [
          "LION",
          "TIGER",
          "BEAR",
          "ELEPHANT",
          "LEOPARD",
          "ZEBRA",
          "GIRAFFE",
          "MONKEY",
          "RHINO",
          "PANDA",
          "KANGAROO",
          "WOLF",
          "SNAKE",
        ],
        hints: [
          "King of jungle (4)",
          "Orange with stripes (5)",
          "Loves honey (4)",
          "Has trunk (8)",
          "Spotted cat (7)",
          "Black white stripes (5)",
          "Tallest animal (7)",
          "Eats bananas (6)",
          "Big horn (5)",
          "Chinese bear (5)",
          "Hops in Australia (8)",
          "Howls at moon (4)",
          "No legs (5)",
        ],
      },
      {
        id: "animals-4",
        title: "Birds",
        grade: "2",
        grid: [
          "E A G L E P A R R O T X Y Z",
          "O W L Q W E R T Y U I O P A",
          "S P A R R O W D F G H J K L",
          "P E N G U I N Z X C V B N M",
          "H A W K Q W E R T Y U I O P",
          "D O V E A S D F G H J K L M",
          "R O B I N N B V C X Z A S D",
          "S W A N F G H J K L Q W E R",
          "C R O W T Y U I O P A S D F",
          "P E L I C A N G H J K L M N",
          "B C D E F G H I J K L M N O",
          "P Q R S T U V W X Y Z A B C",
          "D E F G H I J K L M N O P Q",
          "R S T U V W X Y Z A B C D E",
        ],
        words: [
          "EAGLE",
          "PARROT",
          "OWL",
          "SPARROW",
          "PENGUIN",
          "HAWK",
          "DOVE",
          "ROBIN",
          "SWAN",
          "CROW",
          "PELICAN",
        ],
        hints: [
          "USA symbol (5)",
          "Can talk (6)",
          "Hunts at night (3)",
          "Small brown bird (7)",
          "Cannot fly (7)",
          "Sharp eyes (4)",
          "Peace symbol (4)",
          "Red breast (5)",
          "White on lake (4)",
          "Says caw (4)",
          "Big beak (7)",
        ],
      },
      {
        id: "animals-5",
        title: "Insects",
        grade: "3",
        grid: [
          "B U T T E R F L Y Q W E R T",
          "Y D R A G O N F L Y U I O P",
          "A N T S D F G H J K L M N B",
          "B E E V C X Z A S D F G H J",
          "S P I D E R K L Q W E R T Y",
          "M O S Q U I T O U I O P A S",
          "L A D Y B U G D F G H J K L",
          "G R A S S H O P P E R Z X C",
          "C A T E R P I L L A R V B N",
          "F I R E F L Y M Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
          "L Q W E R T Y U I O P A S D",
          "F G H J K L M N B V C X Z A",
        ],
        words: [
          "BUTTERFLY",
          "DRAGONFLY",
          "ANT",
          "BEE",
          "SPIDER",
          "MOSQUITO",
          "LADYBUG",
          "GRASSHOPPER",
          "CATERPILLAR",
          "FIREFLY",
        ],
        hints: [
          "Colorful wings (9)",
          "Fast near water (9)",
          "Works in colonies (3)",
          "Makes honey (3)",
          "Eight legs (6)",
          "Bites at night (8)",
          "Red with spots (7)",
          "Jumps high (11)",
          "Baby butterfly (11)",
          "Glows dark (7)",
        ],
      },
    ],

    food: [
      {
        id: "food-1",
        title: "Fruits",
        grade: "1",
        grid: [
          "A P P L E O R A N G E Q W E",
          "B A N A N A R T Y U I O P A",
          "S T R A W B E R R Y D F G H",
          "G R A P E J K L M N B V C X",
          "P E A C H Z A S D F G H J K",
          "W A T E R M E L O N L Q W E",
          "C H E R R Y R T Y U I O P A",
          "L E M O N S D F G H J K L M",
          "M A N G O N B V C X Z A S D",
          "P I N E A P P L E F G H J K",
          "L M N O P Q R S T U V W X Y",
          "Z A B C D E F G H I J K L M",
          "N O P Q R S T U V W X Y Z A",
          "B C D E F G H I J K L M N O",
        ],
        words: [
          "APPLE",
          "ORANGE",
          "BANANA",
          "STRAWBERRY",
          "GRAPE",
          "PEACH",
          "WATERMELON",
          "CHERRY",
          "LEMON",
          "MANGO",
          "PINEAPPLE",
        ],
        hints: [
          "Red or green (5)",
          "Orange citrus (6)",
          "Yellow long (6)",
          "Red berry (10)",
          "In bunches (5)",
          "Fuzzy skin (5)",
          "Green red inside (10)",
          "Small red (6)",
          "Sour yellow (5)",
          "Tropical orange (5)",
          "Spiky skin (9)",
        ],
      },
      {
        id: "food-2",
        title: "Vegetables",
        grade: "1",
        grid: [
          "C A R R O T T O M A T O X Y",
          "O N I O N Z Q W E R T Y U I",
          "P O T A T O O P A S D F G H",
          "L E T T U C E J K L M N B V",
          "C U C U M B E R C X Z A S D",
          "B R O C C O L I F G H J K L",
          "S P I N A C H Q W E R T Y U",
          "C A B B A G E I O P A S D F",
          "P U M P K I N G H J K L M N",
          "C O R N B V C X Z A S D F G",
          "H I J K L M N O P Q R S T U",
          "V W X Y Z A B C D E F G H I",
          "J K L M N O P Q R S T U V W",
          "X Y Z A B C D E F G H I J K",
        ],
        words: [
          "CARROT",
          "TOMATO",
          "ONION",
          "POTATO",
          "LETTUCE",
          "CUCUMBER",
          "BROCCOLI",
          "SPINACH",
          "CABBAGE",
          "PUMPKIN",
          "CORN",
        ],
        hints: [
          "Orange vegetable (6)",
          "Red in salad (6)",
          "Makes you cry (5)",
          "Makes fries (6)",
          "Green salad (7)",
          "Long green (8)",
          "Like trees (8)",
          "Dark green (7)",
          "Many layers (7)",
          "Halloween orange (7)",
          "Yellow on cob (4)",
        ],
      },
      {
        id: "food-3",
        title: "Breakfast",
        grade: "2",
        grid: [
          "B R E A D T O A S T Q W E R",
          "E G G S T Y U I O P A S D F",
          "B U T T E R G H J K L M N B",
          "C E R E A L V C X Z A S D F",
          "M I L K G H J K L Q W E R T",
          "Y O G U R T Y U I O P A S D",
          "P A N C A K E F G H J K L M",
          "B A C O N N B V C X Z A S D",
          "S A U S A G E F G H J K L Q",
          "O A T M E A L W E R T Y U I",
          "O P A S D F G H J K L M N B",
          "V C X Z A S D F G H J K L Q",
          "W E R T Y U I O P A S D F G",
          "H J K L M N B V C X Z A S D",
        ],
        words: [
          "BREAD",
          "TOAST",
          "EGGS",
          "BUTTER",
          "CEREAL",
          "MILK",
          "YOGURT",
          "PANCAKE",
          "BACON",
          "SAUSAGE",
          "OATMEAL",
        ],
        hints: [
          "From flour (5)",
          "Crispy bread (5)",
          "From chickens (4)",
          "Yellow spread (6)",
          "Crunchy morning (6)",
          "From cows (4)",
          "Creamy dairy (6)",
          "Flat sweet (7)",
          "Crispy strips (5)",
          "Tube meat (7)",
          "Warm porridge (7)",
        ],
      },
      {
        id: "food-4",
        title: "Drinks",
        grade: "2",
        grid: [
          "W A T E R J U I C E Q W E R",
          "M I L K T Y U I O P A S D F",
          "C O F F E E G H J K L M N B",
          "T E A V C X Z A S D F G H J",
          "S O D A K L Q W E R T Y U I",
          "L E M O N A D E O P A S D F",
          "H O T C H O C O L A T E G H",
          "S M O O T H I E J K L M N B",
          "M I L K S H A K E V C X Z A",
          "O R A N G E J U I C E S D F",
          "G H J K L M N B V C X Z A S",
          "D F G H J K L Q W E R T Y U",
          "I O P A S D F G H J K L M N",
          "B V C X Z A S D F G H J K L",
        ],
        words: [
          "WATER",
          "JUICE",
          "MILK",
          "COFFEE",
          "TEA",
          "SODA",
          "LEMONADE",
          "HOTCHOCOLATE",
          "SMOOTHIE",
          "MILKSHAKE",
          "ORANGEJUICE",
        ],
        hints: [
          "Clear liquid (5)",
          "From fruit (5)",
          "White drink (4)",
          "Hot brown (6)",
          "Hot leaves (3)",
          "Fizzy sweet (4)",
          "Yellow sweet (8)",
          "Warm chocolate (12)",
          "Blended fruit (8)",
          "Ice cream thick (9)",
          "Orange drink (11)",
        ],
      },
      {
        id: "food-5",
        title: "World Foods",
        grade: "3",
        grid: [
          "S U S H I R A M E N Q W E R",
          "T E M P U R A T Y U I O P A",
          "U D O N S D F G H J K L M N",
          "P I Z Z A B V C X Z A S D F",
          "H A M B U R G E R G H J K L",
          "S P A G H E T T I Q W E R T",
          "C U R R Y Y U I O P A S D F",
          "T A C O G H J K L M N B V C",
          "S A N D W I C H X Z A S D F",
          "S A L A D G H J K L Q W E R",
          "T Y U I O P A S D F G H J K",
          "L M N B V C X Z A S D F G H",
          "J K L Q W E R T Y U I O P A",
          "S D F G H J K L M N B V C X",
        ],
        words: [
          "SUSHI",
          "RAMEN",
          "TEMPURA",
          "UDON",
          "PIZZA",
          "HAMBURGER",
          "SPAGHETTI",
          "CURRY",
          "TACO",
          "SANDWICH",
          "SALAD",
        ],
        hints: [
          "Rice raw fish (5)",
          "Noodle soup (5)",
          "Deep fried (7)",
          "Thick noodles (4)",
          "Cheese round (5)",
          "Beef in bun (9)",
          "Long pasta (9)",
          "Spicy sauce (5)",
          "Mexican shell (4)",
          "Bread filling (8)",
          "Mixed vegetables (5)",
        ],
      },
    ],

    school: [
      {
        id: "school-1",
        title: "Classroom",
        grade: "1",
        grid: [
          "D E S K C H A I R B O O K X",
          "P E N C I L Q W E R T Y U I",
          "E R A S E R O P A S D F G H",
          "R U L E R J K L M N B V C X",
          "N O T E B O O K Z A S D F G",
          "P A P E R H J K L Q W E R T",
          "C R A Y O N Y U I O P A S D",
          "G L U E F G H J K L M N B V",
          "S C I S S O R S C X Z A S D",
          "B A C K P A C K F G H J K L",
          "M N O P Q R S T U V W X Y Z",
          "A B C D E F G H I J K L M N",
          "O P Q R S T U V W X Y Z A B",
          "C D E F G H I J K L M N O P",
        ],
        words: [
          "DESK",
          "CHAIR",
          "BOOK",
          "PENCIL",
          "ERASER",
          "RULER",
          "NOTEBOOK",
          "PAPER",
          "CRAYON",
          "GLUE",
          "SCISSORS",
          "BACKPACK",
        ],
        hints: [
          "Study table (4)",
          "Sit here (5)",
          "Read this (4)",
          "Write with (6)",
          "Remove marks (6)",
          "Measure tool (5)",
          "Write notes (8)",
          "Thin sheets (5)",
          "Wax stick (6)",
          "Sticky paste (4)",
          "Cut tool (8)",
          "Carry books (8)",
        ],
      },
      {
        id: "school-2",
        title: "Subjects",
        grade: "2",
        grid: [
          "M A T H E N G L I S H Q W E",
          "S C I E N C E R T Y U I O P",
          "H I S T O R Y A S D F G H J",
          "M U S I C K L M N B V C X Z",
          "A R T A S D F G H J K L Q W",
          "P E G Y M E R T Y U I O P A",
          "G E O G R A P H Y S D F G H",
          "J A P A N E S E J K L M N B",
          "L U N C H V C X Z A S D F G",
          "H O M E R O O M H J K L Q W",
          "E R T Y U I O P A S D F G H",
          "J K L M N B V C X Z A S D F",
          "G H J K L Q W E R T Y U I O",
          "P A S D F G H J K L M N B V",
        ],
        words: [
          "MATH",
          "ENGLISH",
          "SCIENCE",
          "HISTORY",
          "MUSIC",
          "ART",
          "PEGYM",
          "GEOGRAPHY",
          "JAPANESE",
          "LUNCH",
          "HOMEROOM",
        ],
        hints: [
          "Numbers class (4)",
          "Language class (7)",
          "Nature study (7)",
          "Past study (7)",
          "Singing class (5)",
          "Drawing class (3)",
          "Sports class (5)",
          "Places study (9)",
          "Japanese class (8)",
          "Eating time (5)",
          "Morning class (8)",
        ],
      },
      {
        id: "school-3",
        title: "School People",
        grade: "2",
        grid: [
          "T E A C H E R Q W E R T Y U",
          "S T U D E N T I O P A S D F",
          "P R I N C I P A L G H J K L",
          "L I B R A R I A N M N B V C",
          "N U R S E X Z A S D F G H J",
          "C O A C H K L Q W E R T Y U",
          "J A N I T O R I O P A S D F",
          "C O U N S E L O R G H J K L",
          "C L A S S M A T E M N B V C",
          "F R I E N D X Z A S D F G H",
          "J K L M N O P Q R S T U V W",
          "X Y Z A B C D E F G H I J K",
          "L M N O P Q R S T U V W X Y",
          "Z A B C D E F G H I J K L M",
        ],
        words: [
          "TEACHER",
          "STUDENT",
          "PRINCIPAL",
          "LIBRARIAN",
          "NURSE",
          "COACH",
          "JANITOR",
          "COUNSELOR",
          "CLASSMATE",
          "FRIEND",
        ],
        hints: [
          "Teaches class (7)",
          "Learns here (7)",
          "School leader (9)",
          "Library worker (9)",
          "Helps sick (5)",
          "Trains sports (5)",
          "Cleans school (7)",
          "Helps problems (9)",
          "Same class (9)",
          "Close person (6)",
        ],
      },
      {
        id: "school-4",
        title: "Activities",
        grade: "3",
        grid: [
          "H O M E W O R K T E S T Q W",
          "E X A M R E P O R T E R T Y",
          "P R E S E N T A T I O N U I",
          "P R O J E C T O P A S D F G",
          "A S S I G N M E N T H J K L",
          "E S S A Y M N B V C X Z A S",
          "L E C T U R E D F G H J K L",
          "D I S C U S S I O N Q W E R",
          "E X P E R I M E N T T Y U I",
          "R E A D I N G O P A S D F G",
          "H J K L M N B V C X Z A S D",
          "F G H J K L Q W E R T Y U I",
          "O P A S D F G H J K L M N B",
          "V C X Z A S D F G H J K L M",
        ],
        words: [
          "HOMEWORK",
          "TEST",
          "EXAM",
          "REPORT",
          "PRESENTATION",
          "PROJECT",
          "ASSIGNMENT",
          "ESSAY",
          "LECTURE",
          "DISCUSSION",
          "EXPERIMENT",
          "READING",
        ],
        hints: [
          "Home study (8)",
          "Check knowledge (4)",
          "Big test (4)",
          "Written work (6)",
          "Class talk (12)",
          "Long task (7)",
          "Given work (10)",
          "Written paper (5)",
          "Teacher talk (7)",
          "Group talk (10)",
          "Science test (10)",
          "Book activity (7)",
        ],
      },
      {
        id: "school-5",
        title: "Places",
        grade: "3",
        grid: [
          "C L A S S R O O M Q W E R T",
          "L I B R A R Y Y U I O P A S",
          "G Y M N A S I U M D F G H J",
          "C A F E T E R I A K L M N B",
          "P L A Y G R O U N D V C X Z",
          "N U R S E O F F I C E A S D",
          "L A B O R A T O R Y F G H J",
          "A U D I T O R I U M K L Q W",
          "S T A F F R O O M E R T Y U",
          "E N T R A N C E I O P A S D",
          "F G H J K L M N B V C X Z A",
          "S D F G H J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
        ],
        words: [
          "CLASSROOM",
          "LIBRARY",
          "GYMNASIUM",
          "CAFETERIA",
          "PLAYGROUND",
          "NURSEOFFICE",
          "LABORATORY",
          "AUDITORIUM",
          "STAFFROOM",
          "ENTRANCE",
        ],
        hints: [
          "Study room (9)",
          "Book place (7)",
          "Sports hall (9)",
          "Eat area (9)",
          "Play outside (10)",
          "Nurse works (11)",
          "Science room (10)",
          "Meeting hall (10)",
          "Teacher room (9)",
          "School gate (8)",
        ],
      },
    ],

    nature: [
      {
        id: "nature-1",
        title: "Weather",
        grade: "1",
        grid: [
          "S U N N Y C L O U D Y Q W E",
          "R A I N Y R T Y U I O P A S",
          "S N O W Y D F G H J K L M N",
          "W I N D Y B V C X Z A S D F",
          "S T O R M G H J K L Q W E R",
          "T H U N D E R T Y U I O P A",
          "L I G H T N I N G S D F G H",
          "F O G G Y J K L M N B V C X",
          "H O T Z A S D F G H J K L Q",
          "C O L D W E R T Y U I O P A",
          "S D F G H J K L M N B V C X",
          "Z A S D F G H J K L Q W E R",
          "T Y U I O P A S D F G H J K",
          "L M N B V C X Z A S D F G H",
        ],
        words: [
          "SUNNY",
          "CLOUDY",
          "RAINY",
          "SNOWY",
          "WINDY",
          "STORM",
          "THUNDER",
          "LIGHTNING",
          "FOGGY",
          "HOT",
          "COLD",
        ],
        hints: [
          "Bright day (5)",
          "Gray sky (6)",
          "Water falls (5)",
          "White falls (5)",
          "Strong air (5)",
          "Bad weather (5)",
          "Loud sound (7)",
          "Sky flash (9)",
          "Hard see (5)",
          "Very warm (3)",
          "Very cool (4)",
        ],
      },
      {
        id: "nature-2",
        title: "Seasons",
        grade: "2",
        grid: [
          "S P R I N G S U M M E R Q W",
          "A U T U M N E R T Y U I O P",
          "W I N T E R A S D F G H J K",
          "F L O W E R L M N B V C X Z",
          "T R E E A S D F G H J K L Q",
          "L E A F W E R T Y U I O P A",
          "B L O S S O M S D F G H J K",
          "G R A S S L M N B V C X Z A",
          "F O R E S T S D F G H J K L",
          "M O U N T A I N Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
          "L Q W E R T Y U I O P A S D",
          "F G H J K L M N B V C X Z A",
        ],
        words: [
          "SPRING",
          "SUMMER",
          "AUTUMN",
          "WINTER",
          "FLOWER",
          "TREE",
          "LEAF",
          "BLOSSOM",
          "GRASS",
          "FOREST",
          "MOUNTAIN",
        ],
        hints: [
          "Cherry season (6)",
          "Hot season (6)",
          "Fall season (6)",
          "Cold season (6)",
          "Plant bloom (6)",
          "Tall plant (4)",
          "Green part (4)",
          "Tree flowers (7)",
          "Ground cover (5)",
          "Many trees (6)",
          "High land (8)",
        ],
      },
      {
        id: "nature-3",
        title: "Space",
        grade: "2",
        grid: [
          "S U N M O O N S T A R S Q W",
          "C L O U D E R T Y U I O P A",
          "S K Y S D F G H J K L M N B",
          "R A I N B O W V C X Z A S D",
          "P L A N E T F G H J K L Q W",
          "E A R T H E R T Y U I O P A",
          "M E T E O R S D F G H J K L",
          "C O M E T M N B V C X Z A S",
          "G A L A X Y D F G H J K L Q",
          "U N I V E R S E W E R T Y U",
          "I O P A S D F G H J K L M N",
          "B V C X Z A S D F G H J K L",
          "Q W E R T Y U I O P A S D F",
          "G H J K L M N B V C X Z A S",
        ],
        words: [
          "SUN",
          "MOON",
          "STARS",
          "CLOUD",
          "SKY",
          "RAINBOW",
          "PLANET",
          "EARTH",
          "METEOR",
          "COMET",
          "GALAXY",
          "UNIVERSE",
        ],
        hints: [
          "Day star (3)",
          "Night light (4)",
          "Night twinkle (5)",
          "White fluffy (5)",
          "Blue above (3)",
          "Colorful arc (7)",
          "Space ball (6)",
          "Our world (5)",
          "Shooting star (6)",
          "Tail star (5)",
          "Star group (6)",
          "Everything (8)",
        ],
      },
      {
        id: "nature-4",
        title: "Water Land",
        grade: "3",
        grid: [
          "O C E A N S E A R I V E R Q",
          "L A K E W E R T Y U I O P A",
          "P O N D S D F G H J K L M N",
          "S T R E A M B V C X Z A S D",
          "W A T E R F A L L F G H J K",
          "B E A C H L Q W E R T Y U I",
          "I S L A N D O P A S D F G H",
          "V A L L E Y J K L M N B V C",
          "H I L L X Z A S D F G H J K",
          "C A V E L Q W E R T Y U I O",
          "P A S D F G H J K L M N B V",
          "C X Z A S D F G H J K L Q W",
          "E R T Y U I O P A S D F G H",
          "J K L M N B V C X Z A S D F",
        ],
        words: [
          "OCEAN",
          "SEA",
          "RIVER",
          "LAKE",
          "POND",
          "STREAM",
          "WATERFALL",
          "BEACH",
          "ISLAND",
          "VALLEY",
          "HILL",
          "CAVE",
        ],
        hints: [
          "Biggest water (5)",
          "Salty water (3)",
          "Flows to sea (5)",
          "Fresh water (4)",
          "Small water (4)",
          "Small flow (6)",
          "Falls down (9)",
          "Sandy shore (5)",
          "Water around (6)",
          "Between hills (6)",
          "High ground (4)",
          "Underground (4)",
        ],
      },
      {
        id: "nature-5",
        title: "Natural Events",
        grade: "3",
        grid: [
          "E A R T H Q U A K E Q W E R",
          "T Y P H O O N T Y U I O P A",
          "V O L C A N O S D F G H J K",
          "T S U N A M I L M N B V C X",
          "F L O O D Z A S D F G H J K",
          "D R O U G H T L Q W E R T Y",
          "T O R N A D O U I O P A S D",
          "H U R R I C A N E F G H J K",
          "A V A L A N C H E L M N B V",
          "E R U P T I O N C X Z A S D",
          "F G H J K L M N B V C X Z A",
          "S D F G H J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
        ],
        words: [
          "EARTHQUAKE",
          "TYPHOON",
          "VOLCANO",
          "TSUNAMI",
          "FLOOD",
          "DROUGHT",
          "TORNADO",
          "HURRICANE",
          "AVALANCHE",
          "ERUPTION",
        ],
        hints: [
          "Ground shakes (10)",
          "Asian storm (7)",
          "Lava mountain (7)",
          "Giant wave (7)",
          "Too much water (5)",
          "No rain (7)",
          "Spinning wind (7)",
          "Tropical storm (9)",
          "Snow slides (9)",
          "Volcano blast (8)",
        ],
      },
    ],

    colors: [
      {
        id: "colors-1",
        title: "Basic Colors",
        grade: "1",
        grid: [
          "R E D B L U E G R E E N Q W",
          "Y E L L O W E R T Y U I O P",
          "O R A N G E A S D F G H J K",
          "P U R P L E L M N B V C X Z",
          "P I N K A S D F G H J K L Q",
          "B R O W N W E R T Y U I O P",
          "B L A C K A S D F G H J K L",
          "W H I T E M N B V C X Z A S",
          "G R A Y D F G H J K L Q W E",
          "S I L V E R R T Y U I O P A",
          "G O L D S D F G H J K L M N",
          "B E I G E B V C X Z A S D F",
          "T U R Q U O I S E G H J K L",
          "M A G E N T A Q W E R T Y U",
        ],
        words: [
          "RED",
          "BLUE",
          "GREEN",
          "YELLOW",
          "ORANGE",
          "PURPLE",
          "PINK",
          "BROWN",
          "BLACK",
          "WHITE",
          "GRAY",
          "SILVER",
          "GOLD",
          "BEIGE",
        ],
        hints: [
          "Fire color (3)",
          "Sky color (4)",
          "Grass color (5)",
          "Sun color (6)",
          "Fruit color (6)",
          "Royal color (6)",
          "Light red (4)",
          "Wood color (5)",
          "Night color (5)",
          "Snow color (5)",
          "Mix black white (4)",
          "Shiny metal (6)",
          "Precious metal (4)",
          "Cream color (5)",
        ],
      },
      {
        id: "colors-2",
        title: "Shapes",
        grade: "1",
        grid: [
          "C I R C L E S Q U A R E Q W",
          "T R I A N G L E E R T Y U I",
          "R E C T A N G L E O P A S D",
          "O V A L F G H J K L M N B V",
          "H E A R T C X Z A S D F G H",
          "S T A R J K L Q W E R T Y U",
          "D I A M O N D I O P A S D F",
          "H E X A G O N G H J K L M N",
          "P E N T A G O N B V C X Z A",
          "C U B E S D F G H J K L Q W",
          "S P H E R E E R T Y U I O P",
          "C Y L I N D E R A S D F G H",
          "C O N E J K L M N B V C X Z",
          "P Y R A M I D A S D F G H J",
        ],
        words: [
          "CIRCLE",
          "SQUARE",
          "TRIANGLE",
          "RECTANGLE",
          "OVAL",
          "HEART",
          "STAR",
          "DIAMOND",
          "HEXAGON",
          "PENTAGON",
          "CUBE",
          "SPHERE",
          "CYLINDER",
          "CONE",
          "PYRAMID",
        ],
        hints: [
          "Round shape (6)",
          "Four equal sides (6)",
          "Three sides (8)",
          "Long square (9)",
          "Egg shape (4)",
          "Love shape (5)",
          "Sky twinkle (4)",
          "Four points (7)",
          "Six sides (7)",
          "Five sides (8)",
          "Box shape (4)",
          "Ball shape (6)",
          "Can shape (8)",
          "Ice cream (4)",
          "Egypt shape (7)",
        ],
      },
      {
        id: "colors-3",
        title: "Color Mixing",
        grade: "2",
        grid: [
          "P R I M A R Y Q W E R T Y U I",
          "S E C O N D A R Y O P A S D",
          "B R I G H T F G H J K L M N",
          "D A R K B V C X Z A S D F G",
          "L I G H T H J K L Q W E R T",
          "P A L E Y U I O P A S D F G",
          "V I V I D H J K L M N B V C",
          "N E O N X Z A S D F G H J K",
          "P A S T E L L Q W E R T Y U",
          "M E T A L L I C I O P A S D",
          "F G H J K L M N B V C X Z A",
          "S D F G H J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
        ],
        words: [
          "PRIMARY",
          "SECONDARY",
          "BRIGHT",
          "DARK",
          "LIGHT",
          "PALE",
          "VIVID",
          "NEON",
          "PASTEL",
          "METALLIC",
        ],
        hints: [
          "First colors (7)",
          "Mixed colors (9)",
          "Very light (6)",
          "No light (4)",
          "Not heavy (5)",
          "Very light (4)",
          "Very bright (5)",
          "Glowing bright (4)",
          "Soft colors (6)",
          "Shiny metal (8)",
        ],
      },
      {
        id: "colors-4",
        title: "Color Names",
        grade: "2",
        grid: [
          "S C A R L E T C R I M S O N",
          "M A R O O N Q W E R T Y U I",
          "N A V Y O P A S D F G H J K",
          "T E A L L M N B V C X Z A S",
          "C Y A N D F G H J K L Q W E",
          "I N D I G O R T Y U I O P A",
          "V I O L E T S D F G H J K L",
          "L A V E N D E R M N B V C X",
          "M A U V E Z A S D F G H J K",
          "C O R A L L Q W E R T Y U I",
          "S A L M O N O P A S D F G H",
          "P E A C H J K L M N B V C X",
          "I V O R Y Z A S D F G H J K",
          "E B O N Y L Q W E R T Y U I",
        ],
        words: [
          "SCARLET",
          "CRIMSON",
          "MAROON",
          "NAVY",
          "TEAL",
          "CYAN",
          "INDIGO",
          "VIOLET",
          "LAVENDER",
          "MAUVE",
          "CORAL",
          "SALMON",
          "PEACH",
          "IVORY",
          "EBONY",
        ],
        hints: [
          "Bright red (7)",
          "Deep red (7)",
          "Dark red (6)",
          "Dark blue (4)",
          "Blue green (4)",
          "Bright blue (4)",
          "Deep blue (6)",
          "Purple flower (6)",
          "Light purple (8)",
          "Purple pink (5)",
          "Orange pink (5)",
          "Pink orange (6)",
          "Light orange (5)",
          "Cream white (5)",
          "Deep black (5)",
        ],
      },
      {
        id: "colors-5",
        title: "Rainbow Colors",
        grade: "3",
        grid: [
          "R A I N B O W Q W E R T Y U",
          "S P E C T R U M I O P A S D",
          "P R I S M F G H J K L M N B",
          "R E F R A C T I O N V C X Z",
          "W A V E L E N G T H A S D F",
          "F R E Q U E N C Y G H J K L",
          "V I S I B L E Q W E R T Y U",
          "I N V I S I B L E I O P A S",
          "U L T R A V I O L E T D F G",
          "I N F R A R E D H J K L M N",
          "B V C X Z A S D F G H J K L",
          "Q W E R T Y U I O P A S D F",
          "G H J K L M N B V C X Z A S",
          "D F G H J K L Q W E R T Y U",
        ],
        words: [
          "RAINBOW",
          "SPECTRUM",
          "PRISM",
          "REFRACTION",
          "WAVELENGTH",
          "FREQUENCY",
          "VISIBLE",
          "INVISIBLE",
          "ULTRAVIOLET",
          "INFRARED",
        ],
        hints: [
          "Seven colors (7)",
          "Color range (8)",
          "Glass triangle (5)",
          "Light bending (10)",
          "Light distance (10)",
          "Wave speed (9)",
          "Can see (7)",
          "Cannot see (9)",
          "Beyond violet (11)",
          "Below red (8)",
        ],
      },
    ],

    sports: [
      {
        id: "sports-1",
        title: "Ball Sports",
        grade: "1",
        grid: [
          "S O C C E R B A S K E T B A",
          "L L Q W E R T Y U I O P A S",
          "B A S E B A L L D F G H J K",
          "T E N N I S L M N B V C X Z",
          "V O L L E Y B A L L A S D F",
          "P I N G P O N G G H J K L Q",
          "B A D M I N T O N W E R T Y",
          "G O L F U I O P A S D F G H",
          "B O W L I N G J K L M N B V",
          "R U G B Y C X Z A S D F G H",
          "J K L M N O P Q R S T U V W",
          "X Y Z A B C D E F G H I J K",
          "L M N O P Q R S T U V W X Y",
          "Z A B C D E F G H I J K L M",
        ],
        words: [
          "SOCCER",
          "BASKETBALL",
          "BASEBALL",
          "TENNIS",
          "VOLLEYBALL",
          "PINGPONG",
          "BADMINTON",
          "GOLF",
          "BOWLING",
          "RUGBY",
        ],
        hints: [
          "Kick ball (6)",
          "Tall sport (10)",
          "Bat ball (8)",
          "Racket net (6)",
          "Beach sport (10)",
          "Table tennis (8)",
          "Shuttle sport (9)",
          "Club ball (4)",
          "Roll ball (7)",
          "Tackle ball (5)",
        ],
      },
      {
        id: "sports-2",
        title: "Water Sports",
        grade: "2",
        grid: [
          "S W I M M I N G Q W E R T Y",
          "D I V I N G U I O P A S D F",
          "S U R F I N G G H J K L M N",
          "S A I L I N G B V C X Z A S",
          "K A Y A K I N G D F G H J K",
          "R O W I N G L Q W E R T Y U",
          "W A T E R P O L O I O P A S",
          "S N O R K E L I N G D F G H",
          "S C U B A J K L M N B V C X",
          "W A T E R S K I I N G Z A S",
          "D F G H J K L M N B V C X Z",
          "A S D F G H J K L Q W E R T",
          "Y U I O P A S D F G H J K L",
          "M N B V C X Z A S D F G H J",
        ],
        words: [
          "SWIMMING",
          "DIVING",
          "SURFING",
          "SAILING",
          "KAYAKING",
          "ROWING",
          "WATERPOLO",
          "SNORKELING",
          "SCUBA",
          "WATERSKIING",
        ],
        hints: [
          "In pool (8)",
          "Jump water (6)",
          "Board wave (7)",
          "Boat wind (7)",
          "Small boat (8)",
          "Oar boat (6)",
          "Ball pool (9)",
          "Tube swim (10)",
          "Tank dive (5)",
          "Board behind boat (11)",
        ],
      },
      {
        id: "sports-3",
        title: "Winter Sports",
        grade: "2",
        grid: [
          "S K I I N G S N O W B O A R",
          "D I N G Q W E R T Y U I O P",
          "I C E S K A T I N G A S D F",
          "H O C K E Y G H J K L M N B",
          "C U R L I N G V C X Z A S D",
          "B O B S L E D F G H J K L Q",
          "L U G E W E R T Y U I O P A",
          "S L E D D I N G S D F G H J",
          "T O B O G G A N K L M N B V",
          "S N O W M O B I L E C X Z A",
          "S D F G H J K L M N B V C X",
          "Z A S D F G H J K L Q W E R",
          "T Y U I O P A S D F G H J K",
          "L M N B V C X Z A S D F G H",
        ],
        words: [
          "SKIING",
          "SNOWBOARDING",
          "ICESKATING",
          "HOCKEY",
          "CURLING",
          "BOBSLED",
          "LUGE",
          "SLEDDING",
          "TOBOGGAN",
          "SNOWMOBILE",
        ],
        hints: [
          "Snow poles (6)",
          "Snow board (12)",
          "Ice blades (10)",
          "Ice puck (6)",
          "Stone slide (7)",
          "Fast sled (7)",
          "Small sled (4)",
          "Hill slide (8)",
          "Long sled (8)",
          "Snow vehicle (10)",
        ],
      },
      {
        id: "sports-4",
        title: "Track Field",
        grade: "3",
        grid: [
          "R U N N I N G S P R I N T Q",
          "M A R A T H O N W E R T Y U",
          "J U M P I N G I O P A S D F",
          "H U R D L E S G H J K L M N",
          "R E L A Y B V C X Z A S D F",
          "J A V E L I N G H J K L Q W",
          "D I S C U S E R T Y U I O P",
          "S H O T P U T A S D F G H J",
          "H A M M E R K L M N B V C X",
          "P O L E V A U L T Z A S D F",
          "L O N G J U M P G H J K L Q",
          "H I G H J U M P W E R T Y U",
          "T R I P L E J U M P I O P A",
          "S T E E P L E C H A S E S D",
        ],
        words: [
          "RUNNING",
          "SPRINT",
          "MARATHON",
          "JUMPING",
          "HURDLES",
          "RELAY",
          "JAVELIN",
          "DISCUS",
          "SHOTPUT",
          "HAMMER",
          "POLEVAULT",
          "LONGJUMP",
          "HIGHJUMP",
          "TRIPLEJUMP",
        ],
        hints: [
          "Fast move (7)",
          "Short run (6)",
          "Long run (8)",
          "Leave ground (7)",
          "Over bars (7)",
          "Team race (5)",
          "Throw spear (7)",
          "Throw plate (6)",
          "Throw ball (7)",
          "Throw weight (6)",
          "Stick high (9)",
          "Far leap (8)",
          "Up leap (8)",
          "Three hops (10)",
        ],
      },
      {
        id: "sports-5",
        title: "Martial Arts",
        grade: "3",
        grid: [
          "K A R A T E J U D O Q W E R",
          "T A E K W O N D O T Y U I O",
          "K U N G F U P A S D F G H J",
          "B O X I N G K L M N B V C X",
          "W R E S T L I N G Z A S D F",
          "F E N C I N G G H J K L Q W",
          "A R C H E R Y E R T Y U I O",
          "S U M O P A S D F G H J K L",
          "K E N D O M N B V C X Z A S",
          "A I K I D O D F G H J K L Q",
          "W E R T Y U I O P A S D F G",
          "H J K L M N B V C X Z A S D",
          "F G H J K L Q W E R T Y U I",
          "O P A S D F G H J K L M N B",
        ],
        words: [
          "KARATE",
          "JUDO",
          "TAEKWONDO",
          "KUNGFU",
          "BOXING",
          "WRESTLING",
          "FENCING",
          "ARCHERY",
          "SUMO",
          "KENDO",
          "AIKIDO",
        ],
        hints: [
          "Japanese punch (6)",
          "Japanese throw (4)",
          "Korean kick (9)",
          "Chinese fight (6)",
          "Glove fight (6)",
          "Ground fight (9)",
          "Sword sport (7)",
          "Bow arrow (7)",
          "Japanese push (4)",
          "Stick fight (5)",
          "Harmony way (6)",
        ],
      },
    ],

    family: [
      {
        id: "family-1",
        title: "Family Members",
        grade: "1",
        grid: [
          "M O T H E R F A T H E R Q W",
          "B R O T H E R E R T Y U I O",
          "S I S T E R P A S D F G H J",
          "G R A N D M A K L M N B V C",
          "G R A N D P A X Z A S D F G",
          "A U N T H J K L Q W E R T Y",
          "U N C L E U I O P A S D F G",
          "C O U S I N H J K L M N B V",
          "N I E C E C X Z A S D F G H",
          "N E P H E W J K L Q W E R T",
          "Y U I O P A S D F G H J K L",
          "M N B V C X Z A S D F G H J",
          "K L Q W E R T Y U I O P A S",
          "D F G H J K L M N B V C X Z",
        ],
        words: [
          "MOTHER",
          "FATHER",
          "BROTHER",
          "SISTER",
          "GRANDMA",
          "GRANDPA",
          "AUNT",
          "UNCLE",
          "COUSIN",
          "NIECE",
          "NEPHEW",
        ],
        hints: [
          "Mom (6)",
          "Dad (6)",
          "Male sibling (7)",
          "Female sibling (6)",
          "Mother's mom (7)",
          "Father's dad (7)",
          "Mom's sister (4)",
          "Dad's brother (5)",
          "Aunt's child (6)",
          "Brother's daughter (5)",
          "Sister's son (6)",
        ],
      },
      {
        id: "family-2",
        title: "Relationships",
        grade: "2",
        grid: [
          "P A R E N T S C H I L D R E",
          "N Q W E R T Y U I O P A S D",
          "S I B L I N G S F G H J K L",
          "F A M I L Y M N B V C X Z A",
          "R E L A T I V E S D F G H J",
          "A N C E S T O R K L Q W E R",
          "D E S C E N D A N T T Y U I",
          "G E N E R A T I O N O P A S",
          "H U S B A N D D F G H J K L",
          "W I F E M N B V C X Z A S D",
          "F G H J K L M N B V C X Z A",
          "S D F G H J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
        ],
        words: [
          "PARENTS",
          "CHILDREN",
          "SIBLINGS",
          "FAMILY",
          "RELATIVES",
          "ANCESTOR",
          "DESCENDANT",
          "GENERATION",
          "HUSBAND",
          "WIFE",
        ],
        hints: [
          "Mom and dad (7)",
          "Sons daughters (8)",
          "Brothers sisters (8)",
          "Related group (6)",
          "Extended family (9)",
          "Past family (8)",
          "Future family (10)",
          "Age group (10)",
          "Married man (7)",
          "Married woman (4)",
        ],
      },
      {
        id: "family-3",
        title: "Ages",
        grade: "2",
        grid: [
          "B A B Y T O D D L E R Q W E",
          "C H I L D R T Y U I O P A S",
          "T E E N A G E R D F G H J K",
          "A D U L T L M N B V C X Z A",
          "Y O U T H S D F G H J K L Q",
          "E L D E R W E R T Y U I O P",
          "S E N I O R A S D F G H J K",
          "I N F A N T L M N B V C X Z",
          "J U V E N I L E A S D F G H",
          "M I N O R J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
          "N B V C X Z A S D F G H J K",
          "L Q W E R T Y U I O P A S D",
          "F G H J K L M N B V C X Z A",
        ],
        words: [
          "BABY",
          "TODDLER",
          "CHILD",
          "TEENAGER",
          "ADULT",
          "YOUTH",
          "ELDER",
          "SENIOR",
          "INFANT",
          "JUVENILE",
          "MINOR",
        ],
        hints: [
          "Very young (4)",
          "Learning walk (7)",
          "Young person (5)",
          "13-19 years (8)",
          "Grown up (5)",
          "Young adult (5)",
          "Older person (5)",
          "Very old (6)",
          "Newborn (6)",
          "Young teen (8)",
          "Under 18 (5)",
        ],
      },
      {
        id: "family-4",
        title: "Friendship",
        grade: "3",
        grid: [
          "F R I E N D B U D D Y Q W E",
          "P A L R T Y U I O P A S D F",
          "M A T E G H J K L M N B V C",
          "C O M P A N I O N X Z A S D",
          "A C Q U A I N T A N C E F G",
          "N E I G H B O R H J K L Q W",
          "C L A S S M A T E E R T Y U",
          "T E A M M A T E I O P A S D",
          "P A R T N E R F G H J K L M",
          "A L L Y N B V C X Z A S D F",
          "G H J K L M N B V C X Z A S",
          "D F G H J K L Q W E R T Y U",
          "I O P A S D F G H J K L M N",
          "B V C X Z A S D F G H J K L",
        ],
        words: [
          "FRIEND",
          "BUDDY",
          "PAL",
          "MATE",
          "COMPANION",
          "ACQUAINTANCE",
          "NEIGHBOR",
          "CLASSMATE",
          "TEAMMATE",
          "PARTNER",
          "ALLY",
        ],
        hints: [
          "Close person (6)",
          "Good friend (5)",
          "Friend (3)",
          "Companion (4)",
          "Travel friend (9)",
          "Know someone (12)",
          "Lives nearby (8)",
          "Same class (9)",
          "Same team (8)",
          "Work together (7)",
          "Helper friend (4)",
        ],
      },
      {
        id: "family-5",
        title: "Occupations",
        grade: "3",
        grid: [
          "D O C T O R N U R S E Q W E",
          "T E A C H E R R T Y U I O P",
          "E N G I N E E R A S D F G H",
          "L A W Y E R J K L M N B V C",
          "P O L I C E X Z A S D F G H",
          "F I R E F I G H T E R J K L",
          "P I L O T Q W E R T Y U I O",
          "C H E F P A S D F G H J K L",
          "A R T I S T M N B V C X Z A",
          "M U S I C I A N S D F G H J",
          "K L Q W E R T Y U I O P A S",
          "D F G H J K L M N B V C X Z",
          "A S D F G H J K L Q W E R T",
          "Y U I O P A S D F G H J K L",
        ],
        words: [
          "DOCTOR",
          "NURSE",
          "TEACHER",
          "ENGINEER",
          "LAWYER",
          "POLICE",
          "FIREFIGHTER",
          "PILOT",
          "CHEF",
          "ARTIST",
          "MUSICIAN",
        ],
        hints: [
          "Helps sick (6)",
          "Hospital helper (5)",
          "School worker (7)",
          "Builds things (8)",
          "Law expert (6)",
          "Keeps safe (6)",
          "Fights fires (11)",
          "Flies planes (5)",
          "Cooks food (4)",
          "Makes art (6)",
          "Plays music (8)",
        ],
      },
    ],

    places: [
      {
        id: "places-1",
        title: "City Places",
        grade: "1",
        grid: [
          "S C H O O L L I B R A R Y Q",
          "W E R T Y U I O P A S D F G",
          "H O S P I T A L H J K L M N",
          "P O S T O F F I C E B V C X",
          "B A N K Z A S D F G H J K L",
          "S T O R E Q W E R T Y U I O",
          "R E S T A U R A N T P A S D",
          "P A R K F G H J K L M N B V",
          "S T A T I O N C X Z A S D F",
          "A I R P O R T G H J K L Q W",
          "E R T Y U I O P A S D F G H",
          "J K L M N B V C X Z A S D F",
          "G H J K L Q W E R T Y U I O",
          "P A S D F G H J K L M N B V",
        ],
        words: [
          "SCHOOL",
          "LIBRARY",
          "HOSPITAL",
          "POSTOFFICE",
          "BANK",
          "STORE",
          "RESTAURANT",
          "PARK",
          "STATION",
          "AIRPORT",
        ],
        hints: [
          "Learn place (6)",
          "Book place (7)",
          "Sick place (8)",
          "Mail place (10)",
          "Money place (4)",
          "Buy place (5)",
          "Eat place (10)",
          "Play place (4)",
          "Train place (7)",
          "Plane place (7)",
        ],
      },
      {
        id: "places-2",
        title: "World Cities",
        grade: "2",
        grid: [
          "T O K Y O L O N D O N Q W E",
          "P A R I S R T Y U I O P A S",
          "N E W Y O R K D F G H J K L",
          "B E I J I N G M N B V C X Z",
          "R O M E A S D F G H J K L Q",
          "M A D R I D W E R T Y U I O",
          "B E R L I N P A S D F G H J",
          "M O S C O W K L M N B V C X",
          "S Y D N E Y Z A S D F G H J",
          "C A I R O K L Q W E R T Y U",
          "I O P A S D F G H J K L M N",
          "B V C X Z A S D F G H J K L",
          "Q W E R T Y U I O P A S D F",
          "G H J K L M N B V C X Z A S",
        ],
        words: [
          "TOKYO",
          "LONDON",
          "PARIS",
          "NEWYORK",
          "BEIJING",
          "ROME",
          "MADRID",
          "BERLIN",
          "MOSCOW",
          "SYDNEY",
          "CAIRO",
        ],
        hints: [
          "Japan capital (5)",
          "UK capital (6)",
          "France capital (5)",
          "USA big city (7)",
          "China capital (7)",
          "Italy capital (4)",
          "Spain capital (6)",
          "Germany capital (6)",
          "Russia capital (6)",
          "Australia city (6)",
          "Egypt capital (5)",
        ],
      },
      {
        id: "places-3",
        title: "Countries",
        grade: "2",
        grid: [
          "J A P A N C H I N A Q W E R",
          "A M E R I C A T Y U I O P A",
          "K O R E A S D F G H J K L M",
          "I N D I A N B V C X Z A S D",
          "B R A Z I L F G H J K L Q W",
          "C A N A D A E R T Y U I O P",
          "M E X I C O A S D F G H J K",
          "F R A N C E L M N B V C X Z",
          "S P A I N A S D F G H J K L",
          "I T A L Y Q W E R T Y U I O",
          "P A S D F G H J K L M N B V",
          "C X Z A S D F G H J K L Q W",
          "E R T Y U I O P A S D F G H",
          "J K L M N B V C X Z A S D F",
        ],
        words: [
          "JAPAN",
          "CHINA",
          "AMERICA",
          "KOREA",
          "INDIA",
          "BRAZIL",
          "CANADA",
          "MEXICO",
          "FRANCE",
          "SPAIN",
          "ITALY",
        ],
        hints: [
          "Island nation (5)",
          "Great Wall (5)",
          "USA (7)",
          "Two parts (5)",
          "Taj Mahal (5)",
          "Amazon forest (6)",
          "Maple leaf (6)",
          "South of USA (6)",
          "Eiffel Tower (6)",
          "Bullfighting (5)",
          "Boot shape (5)",
        ],
      },
      {
        id: "places-4",
        title: "Landmarks",
        grade: "3",
        grid: [
          "E I F F E L T O W E R Q W E",
          "R T Y U I O P A S D F G H J",
          "P Y R A M I D K L M N B V C",
          "C O L O S S E U M X Z A S D",
          "T A J M A H A L F G H J K L",
          "G R E A T W A L L Q W E R T",
          "S T A T U E L I B E R T Y Y",
          "B I G B E N U I O P A S D F",
          "S Y D N E Y O P E R A G H J",
          "S T O N E H E N G E K L M N",
          "B V C X Z A S D F G H J K L",
          "Q W E R T Y U I O P A S D F",
          "G H J K L M N B V C X Z A S",
          "D F G H J K L Q W E R T Y U",
        ],
        words: [
          "EIFFELTOWER",
          "PYRAMID",
          "COLOSSEUM",
          "TAJMAHAL",
          "GREATWALL",
          "STATUELIBERTY",
          "BIGBEN",
          "SYDNEYOPERA",
          "STONEHENGE",
        ],
        hints: [
          "Paris iron (11)",
          "Egypt tomb (7)",
          "Rome arena (9)",
          "India white (8)",
          "China long (9)",
          "New York lady (14)",
          "London clock (6)",
          "Australia sail (11)",
          "UK stones (10)",
        ],
      },
      {
        id: "places-5",
        title: "Geography",
        grade: "3",
        grid: [
          "C O N T I N E N T Q W E R T",
          "Y U I O P A S D F G H J K L",
          "E Q U A T O R M N B V C X Z",
          "T R O P I C A L A S D F G H",
          "P O L E J K L Q W E R T Y U",
          "H E M I S P H E R E I O P A",
          "L A T I T U D E S D F G H J",
          "L O N G I T U D E K L M N B",
          "M E R I D I A N V C X Z A S",
          "T I M E Z O N E D F G H J K",
          "L Q W E R T Y U I O P A S D",
          "F G H J K L M N B V C X Z A",
          "S D F G H J K L Q W E R T Y",
          "U I O P A S D F G H J K L M",
        ],
        words: [
          "CONTINENT",
          "EQUATOR",
          "TROPICAL",
          "POLE",
          "HEMISPHERE",
          "LATITUDE",
          "LONGITUDE",
          "MERIDIAN",
          "TIMEZONE",
        ],
        hints: [
          "Large land (9)",
          "Earth middle (7)",
          "Hot region (8)",
          "Earth end (4)",
          "Half Earth (10)",
          "Horizontal line (8)",
          "Vertical line (9)",
          "Prime line (8)",
          "Time area (8)",
        ],
      },
    ],
  },
};
