export const grade2 = {
  grade: "2",
  emoji: "🐵",
  label: "GRADE 2",
  description: "Building on Year 1",
  textbook: "New Horizon 2",
  weeks: [
    {
      week: 1,
      title: "My Spring Vacation",
      grammarFocus: "Past Simple · going to / will (overview)",
      questions: [
        { sentence: "I ___ to Kyoto last week.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "She ___ her homework yesterday.", correct: "did", grammar: "do → ___ (past)" },
        { sentence: "We ___ soccer after school.", correct: "played", grammar: "play → ___ (past)" },
        { sentence: "He ___ a big lunch.", correct: "ate", grammar: "eat → ___ (past)" },
        { sentence: "I ___ TV on Sunday.", correct: "watched", grammar: "watch → ___ (past)" },
        { sentence: "___ you go to the beach?", correct: "Did", grammar: "___ you go? (past Q)" },
        { sentence: "I did not ___ to the party.", correct: "go", grammar: "did not ___ (negative)" },
        { sentence: "She ___ very tired.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "They ___ happy at the party.", correct: "were", grammar: "They ___ (past be)" },
        { sentence: "I am ___ to visit Singapore.", correct: "going", grammar: "am ___ to (future)" },
        { sentence: "She ___ come tomorrow.", correct: "will", grammar: "She ___ (will)" },
        { sentence: "We ___ going to have a test.", correct: "are", grammar: "___ going to (future)" },
        { sentence: "He will ___ you some pictures.", correct: "show", grammar: "will ___ (SVOO)" },
        { sentence: "They ___ not going to play today.", correct: "are", grammar: "___ not going to" },
        { sentence: "___ you going to join us?", correct: "Are", grammar: "___ going to? (Q)" },
        { sentence: "I ___ going to study hard.", correct: "am", grammar: "I ___ going to" },
        { sentence: "She did ___ come yesterday.", correct: "not", grammar: "did ___ come (negative)" },
        { sentence: "___ she visit her grandma?", correct: "Did", grammar: "___ she visit? (past Q)" },
        { sentence: "He ___ going to the hospital.", correct: "is", grammar: "He ___ going to" },
        { sentence: "We ___ great last summer.", correct: "had", grammar: "have → ___ (past)" },
      ],
    },
    {
      week: 2,
      title: "I Am Going to Visit Singapore",
      grammarFocus: "Future — going to · positive / negative / questions",
      questions: [
        { sentence: "I am ___ to visit Singapore tomorrow.", correct: "going", grammar: "I am ___ to (future)" },
        { sentence: "I am going ___ visit Singapore.", correct: "to", grammar: "am going ___ (infinitive)" },
        { sentence: "We ___ going to have a party.", correct: "are", grammar: "___ going to (future)" },
        { sentence: "She ___ going to study hard.", correct: "is", grammar: "___ going to (3rd person)" },
        { sentence: "He is ___ to play soccer.", correct: "going", grammar: "He is ___ to (future)" },
        { sentence: "___ you going to join us?", correct: "Are", grammar: "___ going to? (Q)" },
        { sentence: "Yes, I ___ going to come.", correct: "am", grammar: "Yes, I ___ going to" },
        { sentence: "No, I ___ not going to come.", correct: "am", grammar: "No, I ___ not going to" },
        { sentence: "They are not ___ to play today.", correct: "going", grammar: "not ___ to (negative)" },
        { sentence: "She is not going ___ join us.", correct: "to", grammar: "not going ___ (negative)" },
        { sentence: "It ___ going to rain today.", correct: "is", grammar: "It ___ going to (weather)" },
        { sentence: "We are ___ to have a test next week.", correct: "going", grammar: "We are ___ to" },
        { sentence: "___ they going to come?", correct: "Are", grammar: "___ they going to? (Q)" },
        { sentence: "He ___ going to be late.", correct: "is", grammar: "He ___ going to" },
        { sentence: "I am going to ___ Kyoto this spring.", correct: "visit", grammar: "going to ___ (verb)" },
        { sentence: "She is going to ___ a doctor.", correct: "become", grammar: "going to ___ (verb)" },
        { sentence: "We are going to ___ on a trip.", correct: "go", grammar: "going to ___ (verb)" },
        { sentence: "He is going ___ be 14 tomorrow.", correct: "to", grammar: "going ___ be (infinitive)" },
        { sentence: "Are you going to ___ the festival?", correct: "attend", grammar: "going to ___ (verb)" },
        { sentence: "She ___ not going to miss class.", correct: "is", grammar: "She ___ not going to" },
      ],
    },
    {
      week: 3,
      title: "I Will Make a Reservation",
      grammarFocus: "Future — will · SVOO (show / give / tell / send / buy)",
      questions: [
        { sentence: "I ___ make a reservation.", correct: "will", grammar: "I ___ (will future)" },
        { sentence: "She ___ help you.", correct: "will", grammar: "She ___ (will future)" },
        { sentence: "I ___ not come tomorrow.", correct: "won't", grammar: "I ___ not (negative will)" },
        { sentence: "He ___ not be late.", correct: "won't", grammar: "He ___ not (negative will)" },
        { sentence: "___ you help me?", correct: "Will", grammar: "___ you? (will Q)" },
        { sentence: "Yes, I ___.", correct: "will", grammar: "Yes, I ___" },
        { sentence: "No, I ___ not.", correct: "won't", grammar: "No, I ___ not" },
        { sentence: "___ they come to the party?", correct: "Will", grammar: "___ they? (will Q)" },
        { sentence: "It ___ be sunny tomorrow.", correct: "will", grammar: "It ___ (will future)" },
        { sentence: "We ___ not forget your help.", correct: "will", grammar: "We ___ not forget" },
        { sentence: "I will ___ you some pictures.", correct: "show", grammar: "will show + person + thing" },
        { sentence: "She will ___ me a present.", correct: "give", grammar: "will give + person + thing" },
        { sentence: "He will ___ us the answer.", correct: "tell", grammar: "will tell + person + thing" },
        { sentence: "I will ___ you a letter.", correct: "send", grammar: "will send + person + thing" },
        { sentence: "She will ___ him a book.", correct: "buy", grammar: "will buy + person + thing" },
        { sentence: "He will show ___ the photos.", correct: "us", grammar: "will show ___ (indirect obj.)" },
        { sentence: "I will give ___ the ticket.", correct: "you", grammar: "will give ___ (indirect obj.)" },
        { sentence: "She will send ___ a message.", correct: "him", grammar: "will send ___ (indirect obj.)" },
        { sentence: "He will tell ___ the news.", correct: "her", grammar: "will tell ___ (indirect obj.)" },
        { sentence: "They will bring ___ some food.", correct: "us", grammar: "will bring ___ (indirect obj.)" },
      ],
    },
    {
      week: 4,
      title: "People Call This Area Little India",
      grammarFocus: "SVOC — call / find / make / keep / leave + complement",
      questions: [
        { sentence: "People ___ this area Little India.", correct: "call", grammar: "Subject ___ Obj + Comp" },
        { sentence: "They ___ him a genius.", correct: "call", grammar: "They ___ him + name" },
        { sentence: "We ___ him Ken.", correct: "call", grammar: "We ___ him + nickname" },
        { sentence: "I ___ this movie interesting.", correct: "find", grammar: "I ___ it + adjective" },
        { sentence: "She ___ the test difficult.", correct: "found", grammar: "She ___ it + adj. (past)" },
        { sentence: "He ___ the food delicious.", correct: "found", grammar: "He ___ it + adj. (past)" },
        { sentence: "Music ___ me happy.", correct: "makes", grammar: "A ___ me + adjective" },
        { sentence: "The rain ___ her sad.", correct: "made", grammar: "A ___ her + adj. (past)" },
        { sentence: "Exercise ___ you healthy.", correct: "keeps", grammar: "___ you + adjective" },
        { sentence: "Good sleep ___ you energetic.", correct: "keeps", grammar: "___ you + adjective" },
        { sentence: "They ___ the cat Nemo.", correct: "named", grammar: "They ___ it + name (past)" },
        { sentence: "She ___ the dog Shiro.", correct: "named", grammar: "She ___ it + name (past)" },
        { sentence: "The song ___ me relaxed.", correct: "leaves", grammar: "___ me + adjective" },
        { sentence: "The bad news ___ us surprised.", correct: "left", grammar: "___ us + adj. (past)" },
        { sentence: "Good food ___ you strong.", correct: "makes", grammar: "___ you + adjective" },
        { sentence: "I ___ English important.", correct: "find", grammar: "I ___ it + adjective" },
        { sentence: "She ___ her teacher kind.", correct: "finds", grammar: "She ___ sb + adj. (3rd)" },
        { sentence: "People ___ Japan a safe country.", correct: "call", grammar: "___ Obj + Complement" },
        { sentence: "We ___ it a success.", correct: "called", grammar: "We ___ it + noun (past)" },
        { sentence: "I ___ learning English fun.", correct: "find", grammar: "I ___ + gerund + adj." },
      ],
    },
    {
      week: 5,
      title: "When I Go / If You Have Time",
      grammarFocus: "When conjunction · If conditional · Time and condition clauses",
      questions: [
        { sentence: "___ I go to a ramen shop, I order tonkotsu.", correct: "When", grammar: "___ + clause + clause" },
        { sentence: "When I ___ hungry, I eat rice.", correct: "am", grammar: "When I ___ (be verb)" },
        { sentence: "When it ___, I use an umbrella.", correct: "rains", grammar: "When it ___ (3rd person)" },
        { sentence: "I listen to music ___ I study.", correct: "when", grammar: "... ___ I ... (time clause)" },
        { sentence: "She cooks ___ she gets home.", correct: "when", grammar: "... ___ she ... (time clause)" },
        { sentence: "He studies ___ he watches TV.", correct: "when", grammar: "... ___ he ... (time clause)" },
        { sentence: "When I ___ bored, I call a friend.", correct: "am", grammar: "When I ___ (be verb)" },
        { sentence: "___ I have free time, I play games.", correct: "When", grammar: "___ + clause + clause" },
        { sentence: "She smiles ___ she meets friends.", correct: "when", grammar: "___ when (time clause)" },
        { sentence: "He works hard ___ he has a deadline.", correct: "when", grammar: "... ___ he has" },
        { sentence: "___ you have time, you can come.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "If ___ rains, we'll stay inside.", correct: "it", grammar: "If ___ (subject)" },
        { sentence: "If you ___ hard, you'll pass.", correct: "study", grammar: "If you ___ (verb)" },
        { sentence: "___ you like it, you can have it.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "If she ___ sick, she stays home.", correct: "is", grammar: "If she ___ (be verb)" },
        { sentence: "We'll be late ___ we don't hurry.", correct: "if", grammar: "... ___ (conditional clause)" },
        { sentence: "You'll get better ___ you rest.", correct: "if", grammar: "... ___ (conditional)" },
        { sentence: "If you ___ vegetables, you stay healthy.", correct: "eat", grammar: "If you ___ (verb)" },
        { sentence: "I'll help you ___ you need it.", correct: "if", grammar: "... ___ (conditional)" },
        { sentence: "___ I have time, I'll call you.", correct: "If", grammar: "___ + clause (conditional)" },
      ],
    },
    {
      week: 6,
      title: "Because / I Think That…",
      grammarFocus: "Because (reason) · I think that / I believe that (declarative clause)",
      questions: [
        { sentence: "I like Sapporo ramen ___ the soup is thick.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "She is happy ___ she got an A.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "He is tired ___ he stayed up late.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "___ the weather is nice, we play outside.", correct: "Because", grammar: "___ (start reason)" },
        { sentence: "I didn't go ___ I was sick.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "She studies hard ___ she wants to pass.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "Why were you late? ___ I missed the bus.", correct: "Because", grammar: "Why? → ___ ..." },
        { sentence: "I love Japan ___ the food is amazing.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "He can't come ___ he is busy.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "I like her ___ she is kind.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "I ___ that food travels around the world.", correct: "think", grammar: "I ___ that ... (opinion)" },
        { sentence: "I think ___ she is right.", correct: "that", grammar: "I think ___ (conjunction)" },
        { sentence: "She thinks ___ English is important.", correct: "that", grammar: "She thinks ___ ..." },
        { sentence: "We think ___ sports are fun.", correct: "that", grammar: "We think ___ ..." },
        { sentence: "I believe ___ kindness matters.", correct: "that", grammar: "I believe ___ ..." },
        { sentence: "He thinks ___ she is wrong.", correct: "that", grammar: "He thinks ___ ..." },
        { sentence: "I am sure ___ she will come.", correct: "that", grammar: "I am sure ___ ..." },
        { sentence: "Do you think ___ it will rain?", correct: "that", grammar: "think ___ (Q)" },
        { sentence: "I feel ___ we can win.", correct: "that", grammar: "I feel ___ ..." },
        { sentence: "She hopes ___ we pass the test.", correct: "that", grammar: "She hopes ___ ..." },
      ],
    },
    {
      week: 7,
      title: "I Use a Computer to Study English",
      grammarFocus: "Infinitive — adverbial (purpose: to + verb) · adj. + to (feeling)",
      questions: [
        { sentence: "I use a computer ___ study English.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "She went to the store ___ buy milk.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "He studies hard ___ pass the test.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "I am happy ___ hear that.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "She was surprised ___ see him.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "He was glad ___ meet you.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "We are sad ___ say goodbye.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "I am sorry ___ be late.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "She went to the library ___ read.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "He called me ___ say thank you.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "I am ___ to meet you.", correct: "glad", grammar: "I am ___ to (feeling)" },
        { sentence: "I am ___ to hear that.", correct: "happy", grammar: "I am ___ to (feeling)" },
        { sentence: "She is ___ to try it.", correct: "ready", grammar: "She is ___ to (feeling)" },
        { sentence: "I went to the park ___ take photos.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "She studied hard ___ become a doctor.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "He opened the window ___ get fresh air.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "I was excited ___ visit Tokyo.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "She was lucky ___ win the prize.", correct: "to", grammar: "adj. + ___ + verb (feeling)" },
        { sentence: "We are here ___ learn English.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "I called her ___ check on her.", correct: "to", grammar: "... ___ + verb (purpose)" },
      ],
    },
    {
      week: 8,
      title: "She Has a Lot of Work to Do",
      grammarFocus: "Infinitive — adjectival (noun + to) · general (It is … to …)",
      questions: [
        { sentence: "She has a lot of work ___ do.", correct: "to", grammar: "work ___ do (adj. inf.)" },
        { sentence: "I have many things ___ buy.", correct: "to", grammar: "things ___ buy (adj. inf.)" },
        { sentence: "Is there anything ___ eat?", correct: "to", grammar: "anything ___ eat?" },
        { sentence: "She has a book ___ read tonight.", correct: "to", grammar: "book ___ read (adj. inf.)" },
        { sentence: "He has no time ___ play.", correct: "to", grammar: "time ___ play (adj. inf.)" },
        { sentence: "There is nothing ___ do here.", correct: "to", grammar: "nothing ___ do (adj. inf.)" },
        { sentence: "It is important ___ exercise every day.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "It is fun ___ learn new words.", correct: "to", grammar: "It is fun ___ ..." },
        { sentence: "It ___ important to study hard.", correct: "is", grammar: "It ___ important to" },
        { sentence: "It is easy ___ make sushi.", correct: "to", grammar: "It is easy ___ ..." },
        { sentence: "It is hard ___ wake up early.", correct: "to", grammar: "It is hard ___ ..." },
        { sentence: "It is necessary ___ drink water.", correct: "to", grammar: "It is necessary ___ ..." },
        { sentence: "It is dangerous ___ run in the hallway.", correct: "to", grammar: "It is dangerous ___ ..." },
        { sentence: "It is exciting ___ travel abroad.", correct: "to", grammar: "It is exciting ___ ..." },
        { sentence: "She wants something ___ drink.", correct: "to", grammar: "something ___ drink (adj. inf.)" },
        { sentence: "He needs a pen ___ write with.", correct: "to", grammar: "pen ___ write (adj. inf.)" },
        { sentence: "Is there a place ___ sit?", correct: "to", grammar: "place ___ sit (adj. inf.)" },
        { sentence: "I have something ___ tell you.", correct: "to", grammar: "something ___ tell" },
        { sentence: "She has a dream ___ realize.", correct: "to", grammar: "dream ___ realize (adj. inf.)" },
        { sentence: "It is nice ___ meet you.", correct: "to", grammar: "It is nice ___ ..." },
      ],
    },
    {
      week: 9,
      title: "You Have to Speak English · We Must Save Water",
      grammarFocus: "Must · Have to · Mustn't · Don't have to",
      questions: [
        { sentence: "You ___ speak English in class.", correct: "must", grammar: "You ___ (obligation)" },
        { sentence: "We ___ save water.", correct: "must", grammar: "We ___ (obligation)" },
        { sentence: "She ___ to practice every day.", correct: "has", grammar: "She ___ to (have to)" },
        { sentence: "I ___ to finish my homework.", correct: "have", grammar: "I ___ to (have to)" },
        { sentence: "You ___ not run in the hallway.", correct: "must", grammar: "You ___ not (prohibition)" },
        { sentence: "We ___ not be late.", correct: "must", grammar: "We ___ not (prohibition)" },
        { sentence: "You don't ___ come if you're busy.", correct: "have", grammar: "don't ___ to (no obligation)" },
        { sentence: "She doesn't have ___ come tomorrow.", correct: "to", grammar: "doesn't have ___ (no oblig.)" },
        { sentence: "He ___ to wear a uniform.", correct: "has", grammar: "He ___ to (3rd person have to)" },
        { sentence: "They must ___ in English today.", correct: "speak", grammar: "must ___ (base verb)" },
        { sentence: "I ___ finish this by Friday.", correct: "must", grammar: "I ___ (obligation)" },
        { sentence: "You ___ not touch that.", correct: "must", grammar: "You ___ not (prohibition)" },
        { sentence: "She has ___ study for the test.", correct: "to", grammar: "She has ___ study" },
        { sentence: "We have ___ leave now.", correct: "to", grammar: "We have ___ leave" },
        { sentence: "He ___ to go to the dentist.", correct: "has", grammar: "He ___ to (have to)" },
        { sentence: "Do I ___ to bring my textbook?", correct: "have", grammar: "Do I ___ to? (Q)" },
        { sentence: "Yes, you ___ to bring it.", correct: "have", grammar: "Yes, you ___ to" },
        { sentence: "You don't have ___ worry.", correct: "to", grammar: "don't have ___ worry" },
        { sentence: "She ___ not have to come early.", correct: "does", grammar: "she ___ not have to" },
        { sentence: "They ___ submit the report today.", correct: "must", grammar: "They ___ (obligation)" },
      ],
    },
    {
      week: 10,
      title: "They Enjoy Reading Books · Talking Was Fun",
      grammarFocus: "Gerunds after verbs (enjoy / stop / finish) · Gerund as subject",
      questions: [
        { sentence: "They enjoy ___ books.", correct: "reading", grammar: "enjoy ___ (gerund)" },
        { sentence: "She enjoys ___.", correct: "singing", grammar: "enjoy ___ (gerund)" },
        { sentence: "He enjoys ___ in the pool.", correct: "swimming", grammar: "enjoy ___ (gerund)" },
        { sentence: "I enjoy ___ English.", correct: "studying", grammar: "enjoy ___ (gerund)" },
        { sentence: "She stopped ___.", correct: "talking", grammar: "stop ___ (gerund)" },
        { sentence: "He finished ___ his homework.", correct: "doing", grammar: "finish ___ (gerund)" },
        { sentence: "I started ___ English when I was 5.", correct: "learning", grammar: "start ___ (gerund)" },
        { sentence: "She loves ___ photos.", correct: "taking", grammar: "love ___ (gerund)" },
        { sentence: "He likes ___ YouTube.", correct: "watching", grammar: "like ___ (gerund)" },
        { sentence: "We practice ___ English every day.", correct: "speaking", grammar: "practice ___ (gerund)" },
        { sentence: "___ with him was fun.", correct: "Talking", grammar: "___ (gerund subject)" },
        { sentence: "___ English is important.", correct: "Learning", grammar: "___ (gerund subject)" },
        { sentence: "___ in the morning is good for you.", correct: "Running", grammar: "___ (gerund subject)" },
        { sentence: "___ manga is one of my hobbies.", correct: "Reading", grammar: "___ (gerund subject)" },
        { sentence: "___ every day will improve your English.", correct: "Studying", grammar: "___ (gerund subject)" },
        { sentence: "___ music makes me happy.", correct: "Listening", grammar: "___ (gerund subject)" },
        { sentence: "Thank you for ___.", correct: "coming", grammar: "for ___ (gerund after prep.)" },
        { sentence: "I'm good at ___.", correct: "cooking", grammar: "at ___ (gerund after prep.)" },
        { sentence: "She's interested in ___ abroad.", correct: "studying", grammar: "in ___ (gerund after prep.)" },
        { sentence: "He is thinking about ___ the club.", correct: "joining", grammar: "about ___ (gerund after prep.)" },
      ],
    },
    {
      week: 11,
      title: "I Know How to Use These Products",
      grammarFocus: "Indirect questions — how to / where to / what to / which to",
      questions: [
        { sentence: "I know ___ to use these products.", correct: "how", grammar: "___ to (indirect Q)" },
        { sentence: "I can show you ___ to use it.", correct: "how", grammar: "show you ___ to" },
        { sentence: "She doesn't know ___ to start.", correct: "how", grammar: "___ to start" },
        { sentence: "I don't know ___ to go.", correct: "where", grammar: "___ to go (indirect Q)" },
        { sentence: "Tell me ___ to study.", correct: "how", grammar: "Tell me ___ to" },
        { sentence: "She knows ___ to say.", correct: "what", grammar: "___ to say (indirect Q)" },
        { sentence: "I'm not sure ___ to choose.", correct: "which", grammar: "___ to choose" },
        { sentence: "She learned ___ to cook ramen.", correct: "how", grammar: "___ to cook" },
        { sentence: "Tell me ___ to sit.", correct: "where", grammar: "Tell me ___ to sit" },
        { sentence: "He doesn't know ___ to do.", correct: "what", grammar: "___ to do" },
        { sentence: "I know how ___ make sushi.", correct: "to", grammar: "how ___ (infinitive)" },
        { sentence: "She knows where ___ go.", correct: "to", grammar: "where ___ (infinitive)" },
        { sentence: "I don't know what ___ say.", correct: "to", grammar: "what ___ (infinitive)" },
        { sentence: "Can you tell me how ___ spell it?", correct: "to", grammar: "how ___ (infinitive)" },
        { sentence: "She doesn't know when ___ leave.", correct: "to", grammar: "when ___ (infinitive)" },
        { sentence: "I understand how ___ use chopsticks.", correct: "to", grammar: "how ___ (infinitive)" },
        { sentence: "Tell me what ___ do next.", correct: "to", grammar: "what ___ (infinitive)" },
        { sentence: "She knows which ___ take.", correct: "to", grammar: "which ___ (infinitive)" },
        { sentence: "I know how ___ fix this.", correct: "to", grammar: "how ___ (infinitive)" },
        { sentence: "I am sure ___ these ideas help people.", correct: "that", grammar: "sure ___ (declarative)" },
      ],
    },
    {
      week: 12,
      title: "A Volleyball Is Smaller Than a Basketball",
      grammarFocus: "Comparative — adj-er than · more + adjective + than",
      questions: [
        { sentence: "A volleyball is ___ than a basketball.", correct: "smaller", grammar: "adj-er ___ (comparative)" },
        { sentence: "He is ___ than me.", correct: "taller", grammar: "tall → ___ (comparative)" },
        { sentence: "She is ___ than her sister.", correct: "younger", grammar: "young → ___ (comparative)" },
        { sentence: "Math is ___ than English for me.", correct: "harder", grammar: "hard → ___ (comparative)" },
        { sentence: "This bag is ___ than that one.", correct: "heavier", grammar: "heavy → ___ (comparative)" },
        { sentence: "A dog is ___ than a cat.", correct: "bigger", grammar: "big → ___ (comparative)" },
        { sentence: "Summer is ___ than winter here.", correct: "hotter", grammar: "hot → ___ (comparative)" },
        { sentence: "My room is ___ than yours.", correct: "smaller", grammar: "small → ___ (comparative)" },
        { sentence: "She runs ___ than me.", correct: "faster", grammar: "fast → ___ (comparative adv.)" },
        { sentence: "He is ___ than he looks.", correct: "older", grammar: "old → ___ (comparative)" },
        { sentence: "This movie is ___ interesting than that one.", correct: "more", grammar: "___ interesting (comp.)" },
        { sentence: "English is ___ useful than I thought.", correct: "more", grammar: "___ useful (comparative)" },
        { sentence: "This problem is ___ difficult than the last.", correct: "more", grammar: "___ difficult (comp.)" },
        { sentence: "She is ___ careful than her brother.", correct: "more", grammar: "___ careful (comparative)" },
        { sentence: "This road is ___ dangerous than that one.", correct: "more", grammar: "___ dangerous (comp.)" },
        { sentence: "He works ___ efficiently than before.", correct: "more", grammar: "___ efficiently (comp.)" },
        { sentence: "Soccer is ___ popular than tennis.", correct: "more", grammar: "___ popular (comparative)" },
        { sentence: "This hotel is ___ expensive than that one.", correct: "more", grammar: "___ expensive (comp.)" },
        { sentence: "She sings ___ beautifully than him.", correct: "more", grammar: "___ beautifully (comp.)" },
        { sentence: "This test is ___ difficult than yesterday's.", correct: "more", grammar: "___ difficult (comp.)" },
      ],
    },
    {
      week: 13,
      title: "A Volleyball Is the Smallest of the Three",
      grammarFocus: "Superlative — the adj-est · the most + adjective",
      questions: [
        { sentence: "A volleyball is the ___ of the three.", correct: "smallest", grammar: "the ___ (superlative)" },
        { sentence: "He is the ___ in our class.", correct: "tallest", grammar: "the ___ (superlative)" },
        { sentence: "She is the ___ student in school.", correct: "youngest", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ test of the year.", correct: "hardest", grammar: "the ___ (superlative)" },
        { sentence: "That building is the ___ in the city.", correct: "highest", grammar: "the ___ (superlative)" },
        { sentence: "She runs the ___ in the class.", correct: "fastest", grammar: "the ___ (superlative adv.)" },
        { sentence: "He is the ___ of all my friends.", correct: "oldest", grammar: "the ___ (superlative)" },
        { sentence: "This bag is the ___ of all.", correct: "cheapest", grammar: "the ___ (superlative)" },
        { sentence: "Mt. Fuji is the ___ mountain in Japan.", correct: "highest", grammar: "the ___ (superlative)" },
        { sentence: "January is the ___ month of the year.", correct: "coldest", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ interesting sport of all.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "She is the ___ beautiful singer in the group.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "It is the ___ dangerous road in the city.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ popular song this year.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "He is the ___ talented player on the team.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "English is the ___ important subject for me.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ expensive bag in the store.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "She is the ___ careful person I know.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "That was the ___ exciting game of the season.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ difficult puzzle in the book.", correct: "most", grammar: "the ___ (superlative)" },
      ],
    },
    {
      week: 14,
      title: "Soccer Is as Popular as Tennis",
      grammarFocus: "As ~ as · better than · like ~ better · like ~ the best",
      questions: [
        { sentence: "Soccer is as popular ___ tennis.", correct: "as", grammar: "as popular ___ (as ~ as)" },
        { sentence: "She is as tall ___ her mother.", correct: "as", grammar: "as tall ___ (as ~ as)" },
        { sentence: "This book is ___ interesting as that one.", correct: "as", grammar: "___ interesting as" },
        { sentence: "He runs as fast ___ me.", correct: "as", grammar: "as fast ___ (as ~ as)" },
        { sentence: "This test is not ___ hard as the last.", correct: "as", grammar: "not ___ hard as" },
        { sentence: "She is as smart ___ her brother.", correct: "as", grammar: "as smart ___ (as ~ as)" },
        { sentence: "Japan is not ___ big as China.", correct: "as", grammar: "not ___ big as" },
        { sentence: "This ramen is as ___ as the one in Sapporo.", correct: "good", grammar: "as ___ as (equal)" },
        { sentence: "He is not ___ young as he looks.", correct: "as", grammar: "not ___ young as" },
        { sentence: "Is English as useful ___ Japanese?", correct: "as", grammar: "as useful ___ (as ~ as)" },
        { sentence: "She likes math ___ than English.", correct: "better", grammar: "___ than (prefer)" },
        { sentence: "I like summer ___ than winter.", correct: "better", grammar: "___ than (prefer)" },
        { sentence: "She likes cats ___ than dogs.", correct: "better", grammar: "___ than (prefer)" },
        { sentence: "He plays soccer ___ than before.", correct: "better", grammar: "___ than (improvement)" },
        { sentence: "Seven of them like tennis the ___.", correct: "best", grammar: "the ___ (prefer most)" },
        { sentence: "She likes swimming the ___.", correct: "best", grammar: "the ___ (prefer most)" },
        { sentence: "I like summer the ___.", correct: "best", grammar: "the ___ (prefer most)" },
        { sentence: "Many students like other sports ___ than basketball.", correct: "better", grammar: "___ than (prefer)" },
        { sentence: "Which season do you like ___?", correct: "best", grammar: "like ___ ? (prefer most)" },
        { sentence: "She can run ___ after training.", correct: "better", grammar: "___ (improvement)" },
      ],
    },
    {
      week: 15,
      title: "This Place Is Selected as a World Heritage Site",
      grammarFocus: "Passive voice — is / are / was / were + past participle · by + agent",
      questions: [
        { sentence: "This place ___ selected as a World Heritage site.", correct: "is", grammar: "___ selected (passive)" },
        { sentence: "It ___ called the Cape Floral Region.", correct: "is", grammar: "is ___ (passive)" },
        { sentence: "The Taj Mahal ___ loved by many people.", correct: "is", grammar: "___ loved (passive)" },
        { sentence: "Mt. Fuji will be enjoyed ___ people forever.", correct: "by", grammar: "enjoyed ___ (passive agent)" },
        { sentence: "This book was ___ by Natsume Soseki.", correct: "written", grammar: "was ___ (passive past part.)" },
        { sentence: "English ___ spoken in many countries.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "Rice ___ eaten in Japan every day.", correct: "is", grammar: "___ eaten (passive)" },
        { sentence: "The school was ___ in 1950.", correct: "built", grammar: "was ___ (passive past)" },
        { sentence: "The song ___ sung by the whole class.", correct: "was", grammar: "___ sung (passive past)" },
        { sentence: "Sushi ___ loved all over the world.", correct: "is", grammar: "___ loved (passive)" },
        { sentence: "These photos were taken ___ my father.", correct: "by", grammar: "taken ___ (passive agent)" },
        { sentence: "Japanese ___ spoken in Japan.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "The cake ___ made by my mother.", correct: "was", grammar: "___ made (passive past)" },
        { sentence: "The temple ___ built 500 years ago.", correct: "was", grammar: "___ built (passive past)" },
        { sentence: "This magazine ___ published every month.", correct: "is", grammar: "___ published (passive)" },
        { sentence: "The letter was ___ in English.", correct: "written", grammar: "was ___ (passive past part.)" },
        { sentence: "Cars ___ made in that factory.", correct: "are", grammar: "___ made (passive plural)" },
        { sentence: "The rules were ___ by the teacher.", correct: "explained", grammar: "were ___ (passive past)" },
        { sentence: "French is ___ in Canada too.", correct: "spoken", grammar: "is ___ (passive)" },
        { sentence: "This dish ___ prepared fresh every morning.", correct: "is", grammar: "___ prepared (passive)" },
      ],
    },
    {
      week: 16,
      title: "Past Simple — More Irregular Verbs",
      grammarFocus: "Irregular past: put / hit / kept / thought / left / heard / taught / met",
      questions: [
        { sentence: "She ___ her pencil on the desk.", correct: "put", grammar: "put → ___ (past irregular)" },
        { sentence: "He ___ the ball over the fence.", correct: "hit", grammar: "hit → ___ (past irregular)" },
        { sentence: "She ___ her promise.", correct: "kept", grammar: "keep → ___ (past)" },
        { sentence: "He ___ Japanese well until last year.", correct: "knew", grammar: "know → ___ (past)" },
        { sentence: "She ___ her bag at the café.", correct: "left", grammar: "leave → ___ (past)" },
        { sentence: "He ___ the news from his friend.", correct: "heard", grammar: "hear → ___ (past)" },
        { sentence: "I ___ that she was right all along.", correct: "knew", grammar: "know → ___ (past)" },
        { sentence: "She ___ him how to cook.", correct: "taught", grammar: "teach → ___ (past)" },
        { sentence: "___ she bring her dictionary?", correct: "Did", grammar: "___ she bring? (past Q)" },
        { sentence: "Yes, she ___ it to class.", correct: "brought", grammar: "bring → ___ (past)" },
        { sentence: "They ___ about it for a long time.", correct: "thought", grammar: "think → ___ (past)" },
        { sentence: "She ___ her old friend at the station.", correct: "met", grammar: "meet → ___ (past)" },
        { sentence: "He ___ the window by accident.", correct: "broke", grammar: "break → ___ (past)" },
        { sentence: "I ___ the train by one minute.", correct: "missed", grammar: "miss → ___ (past)" },
        { sentence: "She ___ the difficult question correctly.", correct: "answered", grammar: "answer → ___ (past)" },
        { sentence: "He ___ us everything he knew.", correct: "told", grammar: "tell → ___ (past)" },
        { sentence: "I ___ a photo of the sunset.", correct: "took", grammar: "take → ___ (past)" },
        { sentence: "She ___ the project by herself.", correct: "did", grammar: "do → ___ (past)" },
        { sentence: "He ___ sick for a week.", correct: "was", grammar: "He ___ (past be)" },
        { sentence: "We ___ about the problem for hours.", correct: "thought", grammar: "think → ___ (past)" },
      ],
    },
    {
      week: 17,
      title: "Going to vs Will — Contrast",
      grammarFocus: "Going to (plan) vs Will (spontaneous/prediction) — contrast",
      questions: [
        { sentence: "I am ___ to visit Singapore. (I planned this.)", correct: "going", grammar: "am ___ to (plan)" },
        { sentence: "I ___ help you. (I just decided.)", correct: "will", grammar: "___ (spontaneous decision)" },
        { sentence: "She is going ___ become a nurse. (her plan)", correct: "to", grammar: "going ___ (plan)" },
        { sentence: "He ___ probably be late. (prediction)", correct: "will", grammar: "___ (prediction)" },
        { sentence: "Are you ___ to study tonight? (plan)", correct: "going", grammar: "___ to? (plan Q)" },
        { sentence: "Yes, I ___ study for two hours.", correct: "will", grammar: "___ (decision now)" },
        { sentence: "The weather forecast says it ___ rain.", correct: "will", grammar: "___ (prediction)" },
        { sentence: "I am going to ___ the club meeting. (plan)", correct: "attend", grammar: "going to ___ (plan)" },
        { sentence: "She ___ bring snacks. (she just decided)", correct: "will", grammar: "___ (spontaneous)" },
        { sentence: "I think it ___ be a great trip.", correct: "will", grammar: "___ (prediction)" },
        { sentence: "___ it snow tomorrow? (prediction)", correct: "Will", grammar: "___ (prediction Q)" },
        { sentence: "Are they ___ to move to Tokyo? (plan)", correct: "going", grammar: "___ to? (plan Q)" },
        { sentence: "She is ___ to cook dinner tonight. (plan)", correct: "going", grammar: "___ to (plan)" },
        { sentence: "He ___ make a reservation now. (just decided)", correct: "will", grammar: "___ (spontaneous)" },
        { sentence: "I am going to ___ abroad next year. (plan)", correct: "study", grammar: "going to ___ (plan)" },
        { sentence: "___ you be at school tomorrow?", correct: "Will", grammar: "___ (Q)" },
        { sentence: "She is not ___ to attend the meeting. (plan change)", correct: "going", grammar: "___ to (plan neg.)" },
        { sentence: "He ___ not be ready by noon. (prediction)", correct: "will", grammar: "___ (prediction neg.)" },
        { sentence: "I am ___ to try my best. (plan)", correct: "going", grammar: "am ___ to (plan)" },
        { sentence: "I ___ answer that question. (spontaneous)", correct: "will", grammar: "___ (spontaneous)" },
      ],
    },
    {
      week: 18,
      title: "SVOO — Give / Show / Tell / Send / Buy + Pronouns",
      grammarFocus: "SVOO — indirect objects: me / you / him / her / us / them",
      questions: [
        { sentence: "She gave ___ a present.", correct: "me", grammar: "gave ___ (indirect obj.)" },
        { sentence: "He showed ___ the photos.", correct: "us", grammar: "showed ___ (indirect obj.)" },
        { sentence: "I'll send ___ an email.", correct: "you", grammar: "send ___ (indirect obj.)" },
        { sentence: "She told ___ a secret.", correct: "him", grammar: "told ___ (indirect obj.)" },
        { sentence: "They taught ___ English.", correct: "her", grammar: "taught ___ (indirect obj.)" },
        { sentence: "He bought ___ flowers.", correct: "her", grammar: "bought ___ (indirect obj.)" },
        { sentence: "I made ___ a sandwich.", correct: "them", grammar: "made ___ (indirect obj.)" },
        { sentence: "She lent ___ her book.", correct: "me", grammar: "lent ___ (indirect obj.)" },
        { sentence: "He wrote ___ a letter.", correct: "us", grammar: "wrote ___ (indirect obj.)" },
        { sentence: "I'll bring ___ some food.", correct: "you", grammar: "bring ___ (indirect obj.)" },
        { sentence: "She ___ me a ticket for the concert.", correct: "gave", grammar: "___ me (SVOO verb)" },
        { sentence: "He ___ us how to play.", correct: "showed", grammar: "___ us (SVOO verb)" },
        { sentence: "I ___ her the address.", correct: "sent", grammar: "___ her (SVOO verb)" },
        { sentence: "She ___ him the rules.", correct: "explained", grammar: "___ him (SVOO verb)" },
        { sentence: "He ___ me a great song.", correct: "taught", grammar: "___ me (SVOO verb)" },
        { sentence: "I will ___ you my notes.", correct: "lend", grammar: "will ___ you (SVOO verb)" },
        { sentence: "She ___ them a story every night.", correct: "tells", grammar: "___ them (SVOO verb, 3rd)" },
        { sentence: "He ___ me good advice.", correct: "gave", grammar: "___ me (SVOO verb, past)" },
        { sentence: "I ___ you a message yesterday.", correct: "sent", grammar: "___ you (SVOO verb, past)" },
        { sentence: "She ___ them the right direction.", correct: "showed", grammar: "___ them (SVOO verb)" },
      ],
    },
    {
      week: 19,
      title: "All Conjunctions Review",
      grammarFocus: "When / If / Because / That / Before / After / While — all mixed",
      questions: [
        { sentence: "I study ___ I'm on the train.", correct: "when", grammar: "... ___ (time clause)" },
        { sentence: "Call me ___ you get home.", correct: "when", grammar: "... ___ (time clause)" },
        { sentence: "I think ___ she is right.", correct: "that", grammar: "I think ___ (declarative)" },
        { sentence: "He was late ___ he missed the train.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "She studies hard ___ she wants to pass.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "I'll help you ___ you need it.", correct: "if", grammar: "... ___ (conditional)" },
        { sentence: "I brush my teeth ___ I go to bed.", correct: "before", grammar: "... ___ (sequence)" },
        { sentence: "She listens to music ___ she cooks.", correct: "while", grammar: "... ___ (simultaneous)" },
        { sentence: "I believe ___ we can win.", correct: "that", grammar: "I believe ___ (declarative)" },
        { sentence: "He'll come ___ he's not busy.", correct: "if", grammar: "... ___ (conditional)" },
        { sentence: "___ it rains, we'll cancel the match.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "She was happy ___ she got the news.", correct: "when", grammar: "... ___ (time clause)" },
        { sentence: "I'm tired ___ I stayed up too late.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "He arrived ___ she was cooking.", correct: "while", grammar: "... ___ (simultaneous)" },
        { sentence: "I'll eat dinner ___ I finish studying.", correct: "after", grammar: "... ___ (sequence)" },
        { sentence: "She knows ___ he's coming.", correct: "that", grammar: "She knows ___ (declarative)" },
        { sentence: "___ you like it, I'll give you more.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "I'm sure ___ it'll be fine.", correct: "that", grammar: "I'm sure ___ (declarative)" },
        { sentence: "He called me ___ he arrived.", correct: "when", grammar: "... ___ (time clause)" },
        { sentence: "Study hard ___ you want to pass.", correct: "if", grammar: "... ___ (conditional)" },
      ],
    },
    {
      week: 20,
      title: "Infinitives — All Types Review",
      grammarFocus: "Infinitive: purpose / feeling / adjectival / It is … to …",
      questions: [
        { sentence: "I want ___ visit Canada someday.", correct: "to", grammar: "want ___ (infinitive)" },
        { sentence: "She has something important ___ tell you.", correct: "to", grammar: "noun + ___ (adj. inf.)" },
        { sentence: "It is great ___ work with you.", correct: "to", grammar: "It is great ___ ..." },
        { sentence: "He went to the store ___ buy milk.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "I am pleased ___ see you again.", correct: "to", grammar: "adj. + ___ (feeling)" },
        { sentence: "She has no time ___ relax.", correct: "to", grammar: "time ___ (adj. inf.)" },
        { sentence: "It is fun ___ learn new words.", correct: "to", grammar: "It is fun ___ ..." },
        { sentence: "I use apps ___ study vocabulary.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "She needs a notebook ___ write in.", correct: "to", grammar: "noun + ___ (adj. inf.)" },
        { sentence: "He was surprised ___ hear the news.", correct: "to", grammar: "adj. + ___ (feeling)" },
        { sentence: "It is important ___ stay healthy.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "I have a lot of things ___ do today.", correct: "to", grammar: "things ___ (adj. inf.)" },
        { sentence: "She was excited ___ start the project.", correct: "to", grammar: "adj. + ___ (feeling)" },
        { sentence: "He is working hard ___ become a champion.", correct: "to", grammar: "... ___ + verb (purpose)" },
        { sentence: "It is easy ___ make mistakes.", correct: "to", grammar: "It is easy ___ ..." },
        { sentence: "I was happy ___ receive your message.", correct: "to", grammar: "adj. + ___ (feeling)" },
        { sentence: "She found a good place ___ study.", correct: "to", grammar: "place ___ (adj. inf.)" },
        { sentence: "It is necessary ___ practice every day.", correct: "to", grammar: "It is necessary ___ ..." },
        { sentence: "He looked for something ___ eat.", correct: "to", grammar: "something ___ (adj. inf.)" },
        { sentence: "I have a dream ___ achieve.", correct: "to", grammar: "dream ___ (adj. inf.)" },
      ],
    },
    {
      week: 21,
      title: "Gerunds vs Infinitives",
      grammarFocus: "Gerunds (enjoy -ing / stop -ing) vs Infinitives (want to / decide to)",
      questions: [
        { sentence: "I enjoy ___ English movies.", correct: "watching", grammar: "enjoy ___ (gerund)" },
        { sentence: "She wants ___ become a nurse.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "He stopped ___ when the teacher came in.", correct: "talking", grammar: "stopped ___ (gerund)" },
        { sentence: "I like ___ to music in the morning.", correct: "listening", grammar: "like ___ (gerund)" },
        { sentence: "She needs ___ study harder.", correct: "to", grammar: "needs ___ (infinitive)" },
        { sentence: "He finished ___ his homework.", correct: "doing", grammar: "finished ___ (gerund)" },
        { sentence: "I started ___ at age 6.", correct: "practicing", grammar: "started ___ (gerund)" },
        { sentence: "She decided ___ quit the club.", correct: "to", grammar: "decided ___ (infinitive)" },
        { sentence: "He loves ___ on the weekends.", correct: "camping", grammar: "loves ___ (gerund)" },
        { sentence: "I hope ___ visit Paris someday.", correct: "to", grammar: "hope ___ (infinitive)" },
        { sentence: "She is good at ___ in English.", correct: "speaking", grammar: "good at ___ (gerund)" },
        { sentence: "He practiced ___ in front of a mirror.", correct: "speaking", grammar: "practiced ___ (gerund)" },
        { sentence: "I look forward to ___ abroad.", correct: "studying", grammar: "forward to ___ (gerund)" },
        { sentence: "She agreed ___ come to the party.", correct: "to", grammar: "agreed ___ (infinitive)" },
        { sentence: "He couldn't stop ___ once he started.", correct: "reading", grammar: "couldn't stop ___ (gerund)" },
        { sentence: "I plan ___ visit my grandmother.", correct: "to", grammar: "plan ___ (infinitive)" },
        { sentence: "She avoids ___ difficult situations.", correct: "facing", grammar: "avoids ___ (gerund)" },
        { sentence: "He managed ___ finish the test.", correct: "to", grammar: "managed ___ (infinitive)" },
        { sentence: "I suggest ___ early tomorrow.", correct: "leaving", grammar: "suggest ___ (gerund)" },
        { sentence: "She offered ___ help us.", correct: "to", grammar: "offered ___ (infinitive)" },
      ],
    },
    {
      week: 22,
      title: "Passive Voice — Extended",
      grammarFocus: "Passive voice — various verbs and tenses",
      questions: [
        { sentence: "This book ___ written by Soseki.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "The temple ___ visited by many tourists.", correct: "is", grammar: "___ visited (passive pres.)" },
        { sentence: "Our school ___ built in 1965.", correct: "was", grammar: "___ built (passive past)" },
        { sentence: "Rice ___ grown all over Japan.", correct: "is", grammar: "___ grown (passive pres.)" },
        { sentence: "The letter ___ sent yesterday.", correct: "was", grammar: "___ sent (passive past)" },
        { sentence: "English ___ spoken in many countries.", correct: "is", grammar: "___ spoken (passive pres.)" },
        { sentence: "Cars ___ manufactured in this city.", correct: "are", grammar: "___ manufactured (passive pl.)" },
        { sentence: "The game ___ canceled because of rain.", correct: "was", grammar: "___ canceled (passive past)" },
        { sentence: "The results ___ announced tomorrow.", correct: "will be", grammar: "___ announced (future passive)" },
        { sentence: "Sushi ___ loved all over the world.", correct: "is", grammar: "___ loved (passive pres.)" },
        { sentence: "The rules ___ explained by the teacher.", correct: "were", grammar: "___ explained (passive past)" },
        { sentence: "New products ___ released every year.", correct: "are", grammar: "___ released (passive pres.)" },
        { sentence: "The song ___ sung at every ceremony.", correct: "is", grammar: "___ sung (passive pres.)" },
        { sentence: "Many students ___ chosen for the program.", correct: "were", grammar: "___ chosen (passive past)" },
        { sentence: "The news ___ reported worldwide.", correct: "was", grammar: "___ reported (passive past)" },
        { sentence: "Japanese ___ used in the meeting.", correct: "was", grammar: "___ used (passive past)" },
        { sentence: "These shoes ___ made in Italy.", correct: "were", grammar: "___ made (passive past)" },
        { sentence: "The bridge ___ designed by a famous architect.", correct: "was", grammar: "___ designed (passive past)" },
        { sentence: "The award ___ given to the best team.", correct: "was", grammar: "___ given (passive past)" },
        { sentence: "All the tickets ___ sold out.", correct: "were", grammar: "___ sold (passive past)" },
      ],
    },
    {
      week: 23,
      title: "Review — Past Simple & Future",
      grammarFocus: "Past Simple + Going to / Will — mixed review",
      questions: [
        { sentence: "She ___ to Paris last year.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "He ___ going to study harder next term.", correct: "is", grammar: "He ___ going to (future)" },
        { sentence: "I ___ my wallet at the station.", correct: "left", grammar: "leave → ___ (past)" },
        { sentence: "___ you come to the party tomorrow?", correct: "Will", grammar: "___ you come? (future Q)" },
        { sentence: "They ___ not come because of the storm.", correct: "did", grammar: "They ___ not come (past neg.)" },
        { sentence: "She ___ going to graduate next spring.", correct: "is", grammar: "She ___ going to (future)" },
        { sentence: "He ___ the test last month.", correct: "passed", grammar: "pass → ___ (past)" },
        { sentence: "I ___ call you after school.", correct: "will", grammar: "I ___ (will future)" },
        { sentence: "___ she go on the trip?", correct: "Did", grammar: "___ she go? (past Q)" },
        { sentence: "Yes, she ___ a great time.", correct: "had", grammar: "have → ___ (past)" },
        { sentence: "We ___ not going to be late.", correct: "are", grammar: "___ not going to (future)" },
        { sentence: "He ___ his homework before dinner.", correct: "did", grammar: "do → ___ (past)" },
        { sentence: "___ it rain tomorrow?", correct: "Will", grammar: "___ it rain? (future Q)" },
        { sentence: "I ___ not finish in time.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "She ___ going to present her project.", correct: "is", grammar: "She ___ going to (future)" },
        { sentence: "He ___ the wrong bus by mistake.", correct: "took", grammar: "take → ___ (past)" },
        { sentence: "___ they going to move?", correct: "Are", grammar: "___ they going to? (future Q)" },
        { sentence: "I ___ the news last night.", correct: "heard", grammar: "hear → ___ (past)" },
        { sentence: "She ___ come if she can.", correct: "will", grammar: "She ___ (will future)" },
        { sentence: "We ___ a lot of fun on the trip.", correct: "had", grammar: "have → ___ (past)" },
      ],
    },
    {
      week: 24,
      title: "Review — SVOO & SVOC & Conjunctions",
      grammarFocus: "SVOO (give/show/tell) · SVOC (make/find/call) · when/if/because/that",
      questions: [
        { sentence: "She gave ___ a good book.", correct: "him", grammar: "gave ___ (indirect obj.)" },
        { sentence: "I ___ this task interesting.", correct: "find", grammar: "I ___ (SVOC verb)" },
        { sentence: "He told ___ the truth.", correct: "her", grammar: "told ___ (indirect obj.)" },
        { sentence: "Music ___ me happy.", correct: "makes", grammar: "A ___ me (SVOC)" },
        { sentence: "I think ___ she is talented.", correct: "that", grammar: "I think ___ (declarative)" },
        { sentence: "When I ___ bored, I draw.", correct: "am", grammar: "When I ___ (be verb)" },
        { sentence: "She bought ___ a souvenir.", correct: "him", grammar: "bought ___ (indirect obj.)" },
        { sentence: "If you ___ hard, you'll succeed.", correct: "work", grammar: "If you ___ (conditional)" },
        { sentence: "I believe ___ honesty is important.", correct: "that", grammar: "I believe ___ (declarative)" },
        { sentence: "He showed ___ the new route.", correct: "us", grammar: "showed ___ (indirect obj.)" },
        { sentence: "The result ___ us surprised.", correct: "left", grammar: "___ us (SVOC)" },
        { sentence: "Because it was late, she ___ home.", correct: "went", grammar: "Because ..., she ___ (past)" },
        { sentence: "I will send ___ a message.", correct: "you", grammar: "send ___ (indirect obj.)" },
        { sentence: "When the teacher arrived, we ___ quiet.", correct: "were", grammar: "we ___ (past be)" },
        { sentence: "She ___ him the score.", correct: "told", grammar: "___ him (SVOO verb)" },
        { sentence: "I think ___ you're right.", correct: "that", grammar: "I think ___ (declarative)" },
        { sentence: "They ___ him captain.", correct: "called", grammar: "They ___ (SVOC verb, past)" },
        { sentence: "If she's free, she ___ come.", correct: "will", grammar: "If ..., she ___ (will future)" },
        { sentence: "I sent ___ an email.", correct: "her", grammar: "sent ___ (indirect obj.)" },
        { sentence: "He thinks ___ she is kind.", correct: "that", grammar: "He thinks ___ (declarative)" },
      ],
    },
    {
      week: 25,
      title: "Review — Infinitives, Gerunds & Indirect Questions",
      grammarFocus: "All three grammar points mixed — to / -ing / how to / where to",
      questions: [
        { sentence: "I know how ___ use this app.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "She enjoys ___ in the rain.", correct: "walking", grammar: "enjoys ___ (gerund)" },
        { sentence: "He told me what ___ do next.", correct: "to", grammar: "what ___ (indirect Q)" },
        { sentence: "I want ___ visit New York.", correct: "to", grammar: "want ___ (infinitive)" },
        { sentence: "She stopped ___ and went to bed.", correct: "studying", grammar: "stopped ___ (gerund)" },
        { sentence: "It is good ___ exercise every day.", correct: "to", grammar: "It is good ___ ..." },
        { sentence: "Can you show me how ___ do it?", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "She is good at ___ others.", correct: "helping", grammar: "good at ___ (gerund)" },
        { sentence: "He doesn't know where ___ go.", correct: "to", grammar: "where ___ (indirect Q)" },
        { sentence: "I enjoy ___ with friends.", correct: "studying", grammar: "enjoy ___ (gerund)" },
        { sentence: "It is important ___ be honest.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "She taught me how ___ make sushi.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "I don't know which ___ choose.", correct: "to", grammar: "which ___ (indirect Q)" },
        { sentence: "He loves ___ his grandmother.", correct: "visiting", grammar: "loves ___ (gerund)" },
        { sentence: "It is fun ___ try new foods.", correct: "to", grammar: "It is fun ___ ..." },
        { sentence: "She doesn't know what ___ say.", correct: "to", grammar: "what ___ (indirect Q)" },
        { sentence: "I have many things ___ prepare.", correct: "to", grammar: "things ___ (adj. inf.)" },
        { sentence: "He enjoys ___ manga.", correct: "reading", grammar: "enjoys ___ (gerund)" },
        { sentence: "Do you know how ___ make ramen?", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "She likes ___ new places.", correct: "visiting", grammar: "likes ___ (gerund)" },
      ],
    },
    {
      week: 26,
      title: "Review — Comparatives, Superlatives & Passive",
      grammarFocus: "Comparative · Superlative · As ~ as · Passive voice — all mixed",
      questions: [
        { sentence: "English is ___ than Japanese for me.", correct: "easier", grammar: "adj-er ___ (comparative)" },
        { sentence: "He is the ___ in the class.", correct: "tallest", grammar: "the ___ (superlative)" },
        { sentence: "This is the ___ interesting book of all.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "Rice ___ grown all over Japan.", correct: "is", grammar: "___ grown (passive)" },
        { sentence: "She is as ___ as her mother.", correct: "tall", grammar: "as ___ as (equal)" },
        { sentence: "This temple ___ built in the 8th century.", correct: "was", grammar: "___ built (passive past)" },
        { sentence: "He runs ___ than anyone.", correct: "faster", grammar: "adj-er ___ (comparative)" },
        { sentence: "She is the ___ student in school.", correct: "youngest", grammar: "the ___ (superlative)" },
        { sentence: "Cars ___ made here.", correct: "are", grammar: "___ made (passive pres.)" },
        { sentence: "This is not as ___ as that one.", correct: "good", grammar: "not as ___ as" },
        { sentence: "He is ___ careful than before.", correct: "more", grammar: "___ careful (comparative)" },
        { sentence: "The Taj Mahal ___ visited by millions.", correct: "is", grammar: "___ visited (passive)" },
        { sentence: "She is the ___ hardworking of all.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "This house is as ___ as that one.", correct: "big", grammar: "as ___ as (equal)" },
        { sentence: "French ___ spoken in Quebec.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "She speaks English ___ than last year.", correct: "better", grammar: "___ (comparative irreg.)" },
        { sentence: "This is the ___ expensive item.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "The letter ___ written in English.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "He works as ___ as anyone.", correct: "hard", grammar: "as ___ as (equal)" },
        { sentence: "This building ___ designed by Tadao Ando.", correct: "was", grammar: "___ designed (passive past)" },
      ],
    },
    {
      week: 27,
      title: "You Should Drink More Water",
      grammarFocus: "Should — advice, suggestions, and mild obligation",
      questions: [
        { sentence: "You ___ drink more water.", correct: "should", grammar: "You ___ (advice)" },
        { sentence: "She ___ get enough sleep.", correct: "should", grammar: "She ___ (advice)" },
        { sentence: "He ___ not stay up so late.", correct: "should", grammar: "He ___ not (advice neg.)" },
        { sentence: "___ I call the doctor?", correct: "Should", grammar: "___ I? (advice Q)" },
        { sentence: "Yes, you ___ go right away.", correct: "should", grammar: "Yes, you ___ (advice)" },
        { sentence: "You ___ exercise regularly.", correct: "should", grammar: "You ___ (advice)" },
        { sentence: "She ___ not skip breakfast.", correct: "should", grammar: "She ___ not (advice neg.)" },
        { sentence: "He ___ study for the test.", correct: "should", grammar: "He ___ (advice)" },
        { sentence: "___ we tell him the truth?", correct: "Should", grammar: "___ we? (advice Q)" },
        { sentence: "I think you ___ apologize.", correct: "should", grammar: "I think you ___ (advice)" },
        { sentence: "She ___ take better care of herself.", correct: "should", grammar: "She ___ (advice)" },
        { sentence: "He ___ not eat so much junk food.", correct: "should", grammar: "He ___ not (advice neg.)" },
        { sentence: "___ I bring an umbrella?", correct: "Should", grammar: "___ I? (advice Q)" },
        { sentence: "You ___ listen more carefully.", correct: "should", grammar: "You ___ (advice)" },
        { sentence: "She ___ try harder next time.", correct: "should", grammar: "She ___ (advice)" },
        { sentence: "He ___ not waste time.", correct: "should", grammar: "He ___ not (advice neg.)" },
        { sentence: "They ___ work together as a team.", correct: "should", grammar: "They ___ (advice)" },
        { sentence: "You ___ be more careful.", correct: "should", grammar: "You ___ (advice)" },
        { sentence: "___ she see a doctor?", correct: "Should", grammar: "___ she? (advice Q)" },
        { sentence: "Yes, she ___ not ignore her symptoms.", correct: "should", grammar: "she ___ not (advice)" },
      ],
    },
    {
      week: 28,
      title: "Could — Past Ability & Polite Requests",
      grammarFocus: "Could — past ability (she could run) · polite request (Could you…?)",
      questions: [
        { sentence: "She ___ run very fast when she was young.", correct: "could", grammar: "___ (past ability)" },
        { sentence: "He ___ not speak English at all before.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you please open the window?", correct: "Could", grammar: "___ you? (polite request)" },
        { sentence: "I ___ swim when I was 5.", correct: "could", grammar: "___ (past ability)" },
        { sentence: "She ___ not lift the box alone.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you help me with this?", correct: "Could", grammar: "___ you? (polite request)" },
        { sentence: "He ___ play the piano very well as a child.", correct: "could", grammar: "___ (past ability)" },
        { sentence: "I ___ not sleep last night.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you repeat that, please?", correct: "Could", grammar: "___ you? (polite request)" },
        { sentence: "She ___ draw beautifully when she was little.", correct: "could", grammar: "___ (past ability)" },
        { sentence: "He ___ not come because he was sick.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you speak more slowly?", correct: "Could", grammar: "___ you? (polite request)" },
        { sentence: "I ___ not understand the question.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "She ___ not find her keys.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ we use your dictionary?", correct: "Could", grammar: "___ we? (polite request)" },
        { sentence: "He ___ not decide what to choose.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you give me an example?", correct: "Could", grammar: "___ you? (polite request)" },
        { sentence: "She ___ sing perfectly as a child.", correct: "could", grammar: "___ (past ability)" },
        { sentence: "I ___ not finish the task in time.", correct: "could", grammar: "___ not (past ability neg.)" },
        { sentence: "___ you tell me the way to the library?", correct: "Could", grammar: "___ you? (polite request)" },
      ],
    },
    {
      week: 29,
      title: "Would — Polite Requests & Preferences",
      grammarFocus: "Would — Would you like? · I would love to · I would rather",
      questions: [
        { sentence: "___ you like some tea?", correct: "Would", grammar: "___ you like? (polite offer)" },
        { sentence: "Yes, I ___ love some, thank you.", correct: "would", grammar: "I ___ love (polite)" },
        { sentence: "___ you mind closing the door?", correct: "Would", grammar: "___ you mind? (polite)" },
        { sentence: "I ___ like to try that restaurant.", correct: "would", grammar: "I ___ like to (polite)" },
        { sentence: "She ___ prefer coffee to tea.", correct: "would", grammar: "She ___ prefer (polite)" },
        { sentence: "He ___ like to visit Canada someday.", correct: "would", grammar: "He ___ like to (polite)" },
        { sentence: "___ you help me, please?", correct: "Would", grammar: "___ you help? (polite request)" },
        { sentence: "I ___ appreciate your help.", correct: "would", grammar: "I ___ appreciate (polite)" },
        { sentence: "___ she like to come?", correct: "Would", grammar: "___ she like? (polite Q)" },
        { sentence: "Yes, she ___ love to.", correct: "would", grammar: "she ___ love to (polite)" },
        { sentence: "___ you mind waiting?", correct: "Would", grammar: "___ you mind? (polite)" },
        { sentence: "He ___ not like that idea.", correct: "would", grammar: "He ___ not (polite neg.)" },
        { sentence: "___ it be okay if I borrowed this?", correct: "Would", grammar: "___ it be okay? (polite)" },
        { sentence: "I ___ rather eat at home.", correct: "would", grammar: "I ___ rather (preference)" },
        { sentence: "She ___ be happy to help.", correct: "would", grammar: "She ___ be (polite)" },
        { sentence: "___ you like to try again?", correct: "Would", grammar: "___ you like? (polite offer)" },
        { sentence: "He ___ not mind at all.", correct: "would", grammar: "He ___ not mind (polite)" },
        { sentence: "I ___ love to meet her.", correct: "would", grammar: "I ___ love to (polite)" },
        { sentence: "___ you like me to explain?", correct: "Would", grammar: "___ you like? (polite offer)" },
        { sentence: "She ___ prefer a different option.", correct: "would", grammar: "She ___ prefer (preference)" },
      ],
    },
    {
      week: 30,
      title: "Prepositions of Time — At / On / In / Since / For / By",
      grammarFocus: "At (time) · On (day/date) · In (month/season/year) · Since / For / By",
      questions: [
        { sentence: "I wake up ___ 7 in the morning.", correct: "at", grammar: "___ 7 (clock time)" },
        { sentence: "School starts ___ Monday.", correct: "on", grammar: "___ Monday (day)" },
        { sentence: "She was born ___ April.", correct: "in", grammar: "___ April (month)" },
        { sentence: "We have summer vacation ___ August.", correct: "in", grammar: "___ August (month)" },
        { sentence: "The meeting starts ___ noon.", correct: "at", grammar: "___ noon (time)" },
        { sentence: "He goes to the gym ___ Tuesdays.", correct: "on", grammar: "___ Tuesdays (day)" },
        { sentence: "I have been here ___ last April.", correct: "since", grammar: "___ (starting point)" },
        { sentence: "She will finish ___ three days.", correct: "in", grammar: "___ three days (duration future)" },
        { sentence: "He has studied English ___ 5 years.", correct: "for", grammar: "___ 5 years (duration)" },
        { sentence: "The test is ___ Friday morning.", correct: "on", grammar: "___ Friday (day)" },
        { sentence: "I usually nap ___ the afternoon.", correct: "in", grammar: "___ the afternoon" },
        { sentence: "She got home ___ midnight.", correct: "at", grammar: "___ midnight (time)" },
        { sentence: "I'll see you ___ two weeks.", correct: "in", grammar: "___ two weeks (future duration)" },
        { sentence: "The cherry blossoms come ___ spring.", correct: "in", grammar: "___ spring (season)" },
        { sentence: "I finish work ___ 5 p.m.", correct: "at", grammar: "___ 5 p.m. (time)" },
        { sentence: "We'll meet again ___ December.", correct: "in", grammar: "___ December (month)" },
        { sentence: "She has worked here ___ 2019.", correct: "since", grammar: "___ 2019 (starting point)" },
        { sentence: "He'll be ready ___ 30 minutes.", correct: "in", grammar: "___ 30 minutes (future duration)" },
        { sentence: "The concert is ___ Sunday evening.", correct: "on", grammar: "___ Sunday (day)" },
        { sentence: "I have not eaten ___ this morning.", correct: "since", grammar: "___ this morning (since)" },
      ],
    },
    {
      week: 31,
      title: "Real Conditionals — If + Present, Will / Can",
      grammarFocus: "If + simple present → will / can (real future conditional)",
      questions: [
        { sentence: "___ you practice every day, you will improve.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "If it rains tomorrow, we ___ cancel the game.", correct: "will", grammar: "we ___ (will future)" },
        { sentence: "She will succeed ___ she works hard.", correct: "if", grammar: "... ___ (conditional clause)" },
        { sentence: "If he ___ on time, we can start.", correct: "arrives", grammar: "If he ___ (simple pres.)" },
        { sentence: "I ___ help you if you ask.", correct: "will", grammar: "I ___ (will future)" },
        { sentence: "If they don't ___, they'll fail.", correct: "study", grammar: "don't ___ (negative cond.)" },
        { sentence: "___ I have enough money, I'll buy it.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "She ___ be angry if you lie.", correct: "will", grammar: "She ___ (will future)" },
        { sentence: "If the weather is nice, we ___ go hiking.", correct: "will", grammar: "we ___ (will future)" },
        { sentence: "I ___ be late if I don't hurry.", correct: "will", grammar: "I ___ (will future)" },
        { sentence: "___ you join the club, you'll make friends.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "She ___ feel better if she rests.", correct: "will", grammar: "She ___ (will future)" },
        { sentence: "If we leave now, we ___ catch the bus.", correct: "will", grammar: "we ___ (will future)" },
        { sentence: "He ___ improve if he practices.", correct: "will", grammar: "He ___ (will future)" },
        { sentence: "___ she be upset if I cancel?", correct: "Will", grammar: "___ she? (future Q)" },
        { sentence: "If I ___ the exam, I'll be so happy.", correct: "pass", grammar: "If I ___ (simple pres.)" },
        { sentence: "I can call you ___ you give me your number.", correct: "if", grammar: "... ___ (conditional)" },
        { sentence: "She'll help ___ you ask nicely.", correct: "if", grammar: "She'll help ___ (conditional)" },
        { sentence: "If he's well, ___ come to class.", correct: "he'll", grammar: "If ..., ___ (will future)" },
        { sentence: "You'll miss the train ___ you don't hurry.", correct: "if", grammar: "... ___ (conditional)" },
      ],
    },
    {
      week: 32,
      title: "Question Tags",
      grammarFocus: "Question tags — isn't it? / don't you? / didn't she? / won't they?",
      questions: [
        { sentence: "It's a nice day, ___ it?", correct: "isn't", grammar: "isn't ___ ? (tag)" },
        { sentence: "She likes sushi, ___ she?", correct: "doesn't", grammar: "doesn't ___ ? (tag)" },
        { sentence: "They are students, ___ they?", correct: "aren't", grammar: "aren't ___ ? (tag)" },
        { sentence: "He can swim, ___ he?", correct: "can't", grammar: "can't ___ ? (tag)" },
        { sentence: "You have a pet, ___ you?", correct: "don't", grammar: "don't ___ ? (tag)" },
        { sentence: "She went to Tokyo, ___ she?", correct: "didn't", grammar: "didn't ___ ? (tag)" },
        { sentence: "It was fun, ___ it?", correct: "wasn't", grammar: "wasn't ___ ? (tag)" },
        { sentence: "They will come, ___ they?", correct: "won't", grammar: "won't ___ ? (tag)" },
        { sentence: "You're from Osaka, ___ you?", correct: "aren't", grammar: "aren't ___ ? (tag)" },
        { sentence: "She can speak French, ___ she?", correct: "can't", grammar: "can't ___ ? (tag)" },
        { sentence: "He doesn't like cold food, ___ he?", correct: "does", grammar: "does ___ ? (tag)" },
        { sentence: "They haven't finished, ___ they?", correct: "have", grammar: "have ___ ? (tag)" },
        { sentence: "It isn't raining, ___ it?", correct: "is", grammar: "is ___ ? (tag)" },
        { sentence: "You weren't there, ___ you?", correct: "were", grammar: "were ___ ? (tag)" },
        { sentence: "She didn't go, ___ she?", correct: "did", grammar: "did ___ ? (tag)" },
        { sentence: "He isn't your teacher, ___ he?", correct: "is", grammar: "is ___ ? (tag)" },
        { sentence: "We should study more, ___ we?", correct: "shouldn't", grammar: "shouldn't ___ ? (tag)" },
        { sentence: "You've done this before, ___ you?", correct: "haven't", grammar: "haven't ___ ? (tag)" },
        { sentence: "She won't be late, ___ she?", correct: "will", grammar: "will ___ ? (tag)" },
        { sentence: "They were happy, ___ they?", correct: "weren't", grammar: "weren't ___ ? (tag)" },
      ],
    },
    {
      week: 33,
      title: "Linking Words — However / Therefore / In Addition / As a Result",
      grammarFocus: "Contrast (However) · Result (Therefore / As a result) · Addition (In addition)",
      questions: [
        { sentence: "She studied hard. ___, she passed the test.", correct: "Therefore", grammar: "___ (result)" },
        { sentence: "He likes sports. ___, he doesn't like running.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She is smart. ___ she is kind.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "It was raining. ___, we stayed home.", correct: "Therefore", grammar: "___ (result)" },
        { sentence: "The food was cold. ___, I didn't eat it.", correct: "Therefore", grammar: "___ (result)" },
        { sentence: "He is tired. ___, he keeps studying.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She failed the test. ___, she worked harder.", correct: "As a result,", grammar: "___ (result)" },
        { sentence: "I enjoy soccer. ___, I play tennis.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "He didn't study. ___, he didn't pass.", correct: "As a result,", grammar: "___ (result)" },
        { sentence: "I was tired. ___, I went to bed early.", correct: "Therefore", grammar: "___ (result)" },
        { sentence: "She likes cooking. ___, she's a terrible cook.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He did his homework. ___, he forgot to bring it.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She exercises daily. ___, she eats well.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "I missed the bus. ___, I was late.", correct: "As a result,", grammar: "___ (result)" },
        { sentence: "He is quiet. ___, he has a good sense of humor.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "I enjoy English. ___, I want to study abroad.", correct: "Therefore", grammar: "___ (result)" },
        { sentence: "She speaks English. ___, she speaks French.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "The plan sounds good. ___, it has some problems.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He is very organized. ___, he always finishes late.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "The weather was nice. ___, we had a picnic.", correct: "Therefore", grammar: "___ (result)" },
      ],
    },
    {
      week: 34,
      title: "Theme — Environment",
      grammarFocus: "Grammar review with environment topics — should / passive / if / that",
      questions: [
        { sentence: "We ___ save energy every day.", correct: "should", grammar: "We ___ (should + advice)" },
        { sentence: "Plastic ___ recycled properly.", correct: "should be", grammar: "___ recycled (passive + modal)" },
        { sentence: "If we ___ act now, it will be too late.", correct: "don't", grammar: "If we ___ (negative cond.)" },
        { sentence: "Global warming ___ a serious problem.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "Many animals ___ endangered.", correct: "are", grammar: "___ (be verb + adjective)" },
        { sentence: "She thinks ___ we should reduce waste.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is important ___ protect the environment.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "Plastic bottles ___ used millions of times a day.", correct: "are", grammar: "___ used (passive)" },
        { sentence: "The ocean ___ polluted by plastic.", correct: "is", grammar: "___ polluted (passive)" },
        { sentence: "We ___ to recycle more.", correct: "need", grammar: "We ___ to (need to)" },
        { sentence: "Forests ___ being destroyed.", correct: "are", grammar: "___ being (passive continuous)" },
        { sentence: "She believes ___ we can solve climate change.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is our responsibility ___ protect the Earth.", correct: "to", grammar: "It is ... ___ ..." },
        { sentence: "Renewable energy ___ becoming more popular.", correct: "is", grammar: "___ becoming (present cont.)" },
        { sentence: "If we ___ care of nature, it will help us.", correct: "take", grammar: "If we ___ (conditional)" },
        { sentence: "Animals ___ becoming extinct faster than ever.", correct: "are", grammar: "___ becoming (present cont.)" },
        { sentence: "I think ___ we all have a role to play.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "We ___ not ignore environmental issues.", correct: "should", grammar: "___ not (should neg.)" },
        { sentence: "Trees ___ cut down unnecessarily.", correct: "should not be", grammar: "___ cut down (passive + modal)" },
        { sentence: "If everyone ___, we can make a difference.", correct: "helps", grammar: "If everyone ___ (3rd person)" },
      ],
    },
    {
      week: 35,
      title: "Theme — Technology",
      grammarFocus: "Grammar review with technology topics — mixed grammar",
      questions: [
        { sentence: "Smartphones ___ used by billions of people.", correct: "are", grammar: "___ used (passive)" },
        { sentence: "She ___ her phone to study vocabulary.", correct: "uses", grammar: "She ___ (3rd person)" },
        { sentence: "I think ___ AI will change the world.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is important ___ use technology wisely.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "The internet ___ invented in the 1960s.", correct: "was", grammar: "___ invented (passive past)" },
        { sentence: "Social media ___ become very popular.", correct: "has", grammar: "___ become (present perfect)" },
        { sentence: "She is ___ to buy a new laptop.", correct: "going", grammar: "She is ___ to (future)" },
        { sentence: "If you ___ too much time online, it can be harmful.", correct: "spend", grammar: "If you ___ (cond.)" },
        { sentence: "Technology ___ us communicate more easily.", correct: "helps", grammar: "___ us (causative)" },
        { sentence: "I enjoy ___ educational videos online.", correct: "watching", grammar: "enjoy ___ (gerund)" },
        { sentence: "He ___ not use social media.", correct: "does", grammar: "He ___ not (negative)" },
        { sentence: "___ AI be able to replace teachers?", correct: "Will", grammar: "___ AI? (future Q)" },
        { sentence: "I know how ___ program in Python.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "Online games ___ played by millions.", correct: "are", grammar: "___ played (passive)" },
        { sentence: "She showed ___ how to use the app.", correct: "me", grammar: "showed ___ (SVOO)" },
        { sentence: "I think ___ technology is both helpful and dangerous.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "He ___ to buy the latest smartphone.", correct: "wants", grammar: "He ___ to (3rd person)" },
        { sentence: "If I ___ a better computer, I could study more.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She told me ___ AI had passed the test.", correct: "that", grammar: "told me ___ (reported)" },
        { sentence: "New apps ___ developed every day.", correct: "are", grammar: "___ developed (passive)" },
      ],
    },
    {
      week: 36,
      title: "Theme — Japanese & Global Culture",
      grammarFocus: "Grammar review with culture topics — passive / that / for~to / if",
      questions: [
        { sentence: "Sushi ___ loved all over the world.", correct: "is", grammar: "___ loved (passive)" },
        { sentence: "Japan ___ famous for its festivals.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "She thinks ___ Japanese culture is unique.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "Traditional crafts ___ made by skilled artisans.", correct: "are", grammar: "___ made (passive)" },
        { sentence: "It is important ___ preserve cultural heritage.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "Manga ___ read by people of all ages.", correct: "is", grammar: "___ read (passive)" },
        { sentence: "If you ___ Japan, you should try a hot spring.", correct: "visit", grammar: "If you ___ (cond.)" },
        { sentence: "She enjoys ___ new cultures.", correct: "exploring", grammar: "enjoys ___ (gerund)" },
        { sentence: "The tea ceremony ___ performed carefully.", correct: "is", grammar: "___ performed (passive)" },
        { sentence: "He thinks ___ we should learn about other cultures.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "Kimono ___ worn on special occasions.", correct: "are", grammar: "___ worn (passive)" },
        { sentence: "It is interesting ___ learn about different customs.", correct: "to", grammar: "It is ... ___ ..." },
        { sentence: "She wants ___ experience life in another country.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "Mount Fuji ___ visited by many tourists.", correct: "is", grammar: "___ visited (passive)" },
        { sentence: "I believe ___ every culture has something to teach us.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "If I ___ a chance, I would travel the world.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She is going ___ study Japanese history.", correct: "to", grammar: "going ___ (future)" },
        { sentence: "Japanese ___ spoken in many countries worldwide.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "Traditional music ___ been handed down for generations.", correct: "has", grammar: "___ been (pres. perf. passive)" },
        { sentence: "Anime ___ become popular worldwide.", correct: "has", grammar: "___ become (present perfect)" },
      ],
    },
    {
      week: 37,
      title: "Theme — Career & Future",
      grammarFocus: "Grammar review with career topics — want to / going to / should / if",
      questions: [
        { sentence: "I ___ to be a teacher someday.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "She is going ___ study medicine.", correct: "to", grammar: "going ___ (future)" },
        { sentence: "He thinks ___ he will become an engineer.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is important ___ choose a job you love.", correct: "to", grammar: "It is important ___ ..." },
        { sentence: "She ___ working hard to achieve her dreams.", correct: "is", grammar: "She ___ (present cont.)" },
        { sentence: "If you ___ hard, you can achieve anything.", correct: "work", grammar: "If you ___ (cond.)" },
        { sentence: "My dream ___ to open my own restaurant.", correct: "is", grammar: "My dream ___ (be verb)" },
        { sentence: "She wants ___ become a professional athlete.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "He is ___ to apply to university next year.", correct: "going", grammar: "He is ___ to (future)" },
        { sentence: "I believe ___ everyone has unique talents.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "Many people ___ work from home these days.", correct: "can", grammar: "___ (modal)" },
        { sentence: "She is good at ___ new ideas.", correct: "creating", grammar: "good at ___ (gerund)" },
        { sentence: "I know ___ to use many computer programs.", correct: "how", grammar: "___ to (indirect Q)" },
        { sentence: "She ___ hard to reach her goals.", correct: "works", grammar: "She ___ (3rd person)" },
        { sentence: "If I were you, I ___ study harder.", correct: "would", grammar: "I ___ (2nd cond.)" },
        { sentence: "The salary ___ decided by your skills.", correct: "is", grammar: "___ decided (passive)" },
        { sentence: "I enjoy ___ with different people.", correct: "working", grammar: "enjoy ___ (gerund)" },
        { sentence: "She ___ her goal after years of hard work.", correct: "achieved", grammar: "achieve → ___ (past)" },
        { sentence: "He ___ to get a job abroad someday.", correct: "wants", grammar: "He ___ to (3rd person)" },
        { sentence: "What ___ you want to do in the future?", correct: "do", grammar: "What ___ you want?" },
      ],
    },
    {
      week: 38,
      title: "Mixed Review — Questions & Negatives",
      grammarFocus: "Do / Does / Did / Can / Will / Is / Are / Was / Were — Q & negatives",
      questions: [
        { sentence: "___ she like classical music?", correct: "Does", grammar: "___ she like? (Q)" },
        { sentence: "No, she ___ like it.", correct: "doesn't", grammar: "No, she ___ (negative)" },
        { sentence: "___ he at school yesterday?", correct: "Was", grammar: "___ he? (past be Q)" },
        { sentence: "No, he ___ not come.", correct: "did", grammar: "No, he ___ not (past neg.)" },
        { sentence: "___ you ever tried skydiving?", correct: "Have", grammar: "___ you ever? (pres. perf. Q)" },
        { sentence: "No, I ___ not done that.", correct: "have", grammar: "No, I ___ not (pres. perf. neg.)" },
        { sentence: "___ they going to move?", correct: "Are", grammar: "___ they going to? (future Q)" },
        { sentence: "No, they ___ not moving.", correct: "are", grammar: "No, they ___ not (present cont.)" },
        { sentence: "___ this be done by Friday?", correct: "Can", grammar: "___ this be? (ability Q)" },
        { sentence: "No, it ___ not be ready.", correct: "will", grammar: "No, it ___ not (future neg.)" },
        { sentence: "___ she speak Italian?", correct: "Can", grammar: "___ she speak? (ability Q)" },
        { sentence: "No, she ___ speak it.", correct: "can't", grammar: "No, she ___ (negative)" },
        { sentence: "___ I borrow your book?", correct: "Can", grammar: "___ I? (permission Q)" },
        { sentence: "Yes, you ___ borrow it.", correct: "can", grammar: "Yes, you ___ (permission)" },
        { sentence: "___ they friends?", correct: "Are", grammar: "___ they? (be Q)" },
        { sentence: "No, they ___ not friends.", correct: "are", grammar: "No, they ___ not (be neg.)" },
        { sentence: "___ it rain tomorrow?", correct: "Will", grammar: "___ it rain? (future Q)" },
        { sentence: "No, it ___ not rain.", correct: "will", grammar: "No, it ___ not (future neg.)" },
        { sentence: "___ she going to the party?", correct: "Is", grammar: "___ she going to? (future Q)" },
        { sentence: "No, she ___ not going.", correct: "is", grammar: "No, she ___ not going (future neg.)" },
      ],
    },
    {
      week: 39,
      title: "Year Review A",
      grammarFocus: "All Grade 2 grammar — mixed (easier level)",
      questions: [
        { sentence: "I ___ to Kyoto last spring.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "She ___ going to be a nurse.", correct: "is", grammar: "She ___ going to (future)" },
        { sentence: "He ___ very well.", correct: "studies", grammar: "He ___ (3rd person)" },
        { sentence: "I ___ not understand at first.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "She enjoys ___ new places.", correct: "visiting", grammar: "enjoys ___ (gerund)" },
        { sentence: "It is fun ___ learn together.", correct: "to", grammar: "It is fun ___ ..." },
        { sentence: "He shows ___ the right way.", correct: "us", grammar: "shows ___ (SVOO)" },
        { sentence: "Music ___ her feel better.", correct: "makes", grammar: "___ her (SVOC)" },
        { sentence: "I think ___ she is talented.", correct: "that", grammar: "I think ___ (declarative)" },
        { sentence: "When I ___ free, I cook.", correct: "am", grammar: "When I ___ (when clause)" },
        { sentence: "She is ___ than her sister.", correct: "taller", grammar: "___ (comparative)" },
        { sentence: "This is the ___ interesting movie of all.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "English ___ spoken worldwide.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "She knows how ___ make ramen.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "They ___ hard.", correct: "worked", grammar: "work → ___ (past)" },
        { sentence: "He must ___ his homework.", correct: "do", grammar: "must ___ (modal + base)" },
        { sentence: "I enjoy ___ with my friends.", correct: "studying", grammar: "enjoy ___ (gerund)" },
        { sentence: "She is ___ careful than before.", correct: "more", grammar: "___ careful (comparative)" },
        { sentence: "I ___ to be a scientist someday.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "The building ___ built in the Meiji era.", correct: "was", grammar: "___ built (passive past)" },
      ],
    },
    {
      week: 40,
      title: "Year Review B",
      grammarFocus: "All Grade 2 grammar — mixed (harder level)",
      questions: [
        { sentence: "If she ___ harder, she would pass.", correct: "studied", grammar: "If she ___ (2nd cond.)" },
        { sentence: "She should ___ more water.", correct: "drink", grammar: "should ___ (modal + base)" },
        { sentence: "He ___ me the photos yesterday.", correct: "showed", grammar: "___ me (SVOO past)" },
        { sentence: "I know how ___ fix this.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "The letter ___ written in English.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "This is the ___ difficult test.", correct: "most", grammar: "the ___ (superlative)" },
        { sentence: "She ___ him a genius.", correct: "called", grammar: "___ him (SVOC past)" },
        { sentence: "She enjoys ___ books.", correct: "reading", grammar: "enjoys ___ (gerund)" },
        { sentence: "Could you ___ more slowly?", correct: "speak", grammar: "Could you ___ ? (polite request)" },
        { sentence: "I stopped ___ late.", correct: "studying", grammar: "stopped ___ (gerund)" },
        { sentence: "The song ___ performed beautifully.", correct: "was", grammar: "___ performed (passive)" },
        { sentence: "I ___ you should see a doctor.", correct: "think", grammar: "I ___ (declarative)" },
        { sentence: "She was ___ to pass the test.", correct: "happy", grammar: "She was ___ to (adj + inf.)" },
        { sentence: "He ___ not have to come early.", correct: "does", grammar: "He ___ not have to" },
        { sentence: "I would ___ to try that.", correct: "like", grammar: "I would ___ to (polite)" },
        { sentence: "When she ___ stressed, she listens to music.", correct: "is", grammar: "When she ___ (when clause)" },
        { sentence: "She has been ___ here for 3 years.", correct: "working", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "___ you ever traveled abroad?", correct: "Have", grammar: "___ you ever? (pres. perf. Q)" },
        { sentence: "As a result, she ___ very confident.", correct: "became", grammar: "became ___ (past)" },
        { sentence: "He ___ going to change the world.", correct: "is", grammar: "He ___ going to (future)" },
      ],
    },
  ],
} as const;
