export const grade1 = {
  grade: "1",
  emoji: "🐣",
  label: "GRADE 1",
  description: "Welcome to Junior High!",
  textbook: "Here We Go! 1",
  weeks: [
    {
      week: 1,
      title: "Let's Be Friends!",
      grammarFocus: "Be verbs · Simple Present · Can · Let's",
      questions: [
        { sentence: "I ___ a student.", correct: "am", grammar: "I ___ (be verb)" },
        { sentence: "You ___ my friend.", correct: "are", grammar: "You ___ (be verb)" },
        { sentence: "She ___ my sister.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "He ___ from Osaka.", correct: "is", grammar: "He ___ (be verb)" },
        { sentence: "We ___ classmates.", correct: "are", grammar: "We ___ (be verb)" },
        { sentence: "They ___ happy.", correct: "are", grammar: "They ___ (be verb)" },
        { sentence: "I ___ play the guitar.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "She ___ swim well.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "___ you like music?", correct: "Do", grammar: "___ you like?" },
        { sentence: "I ___ like spicy food.", correct: "don't", grammar: "I ___ like (negative)" },
        { sentence: "She ___ like cold weather.", correct: "doesn't", grammar: "She ___ like (negative)" },
        { sentence: "Let's ___ to the park.", correct: "go", grammar: "Let's ___ (verb)" },
        { sentence: "___ is your name?", correct: "What", grammar: "___ is your name?" },
        { sentence: "___ are you from?", correct: "Where", grammar: "___ are you from?" },
        { sentence: "I ___ 13 years old.", correct: "am", grammar: "I ___ (age)" },
        { sentence: "My bag ___ red.", correct: "is", grammar: "My bag ___ (colour)" },
        { sentence: "___ he your teacher?", correct: "Is", grammar: "___ he? (question)" },
        { sentence: "___ she play soccer?", correct: "Does", grammar: "___ she play?" },
        { sentence: "I ___ speak Chinese.", correct: "can't", grammar: "I ___ (negative ability)" },
        { sentence: "Let's ___ a song!", correct: "sing", grammar: "Let's ___ (verb)" },
      ],
    },
    {
      week: 2,
      title: "I'm Lost! / Do You Like…?",
      grammarFocus: "Be verb questions · Do you like? · Does she like?",
      questions: [
        { sentence: "I ___ a new student here.", correct: "am", grammar: "I ___ (be verb)" },
        { sentence: "___ you in Class 1?", correct: "Are", grammar: "___ you? (question)" },
        { sentence: "She ___ my English teacher.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "___ this the school library?", correct: "Is", grammar: "___ this? (question)" },
        { sentence: "No, it ___ not.", correct: "is", grammar: "No, it ___ not" },
        { sentence: "I ___ not from this town.", correct: "am", grammar: "I ___ not" },
        { sentence: "___ he in your class?", correct: "Is", grammar: "___ he? (question)" },
        { sentence: "Yes, he ___.", correct: "is", grammar: "Yes, he ___" },
        { sentence: "We ___ in the same group.", correct: "are", grammar: "We ___ (be verb)" },
        { sentence: "They ___ my new classmates.", correct: "are", grammar: "They ___ (be verb)" },
        { sentence: "___ you like sports?", correct: "Do", grammar: "___ you like?" },
        { sentence: "I ___ like hot weather.", correct: "don't", grammar: "I ___ like (negative)" },
        { sentence: "She ___ like cold food.", correct: "doesn't", grammar: "She ___ like (3rd neg.)" },
        { sentence: "Do you ___ summer?", correct: "like", grammar: "Do you ___?" },
        { sentence: "I like manga. ___ you?", correct: "Do", grammar: "___ you? (follow-up)" },
        { sentence: "___ she like English?", correct: "Does", grammar: "___ she like?" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "No, she ___ not like it.", correct: "does", grammar: "she ___ not (negative)" },
        { sentence: "What do you ___ for lunch?", correct: "like", grammar: "What do you ___?" },
        { sentence: "Do ___ like dogs or cats?", correct: "you", grammar: "Do ___? (subject)" },
      ],
    },
    {
      week: 3,
      title: "I Can & I Can't · Are You…?",
      grammarFocus: "Can / Can't · Be verb questions · Good at / Bad at",
      questions: [
        { sentence: "I ___ play the violin.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "She ___ speak French.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "I ___ swim very well.", correct: "can't", grammar: "I ___ (no ability)" },
        { sentence: "He ___ run fast.", correct: "can't", grammar: "He ___ (no ability)" },
        { sentence: "___ you play the piano?", correct: "Can", grammar: "Can ___? (question)" },
        { sentence: "Yes, I ___.", correct: "can", grammar: "Yes, I ___" },
        { sentence: "No, I ___ not play it.", correct: "can", grammar: "No, I ___ not" },
        { sentence: "She ___ cook very well.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "___ he read kanji?", correct: "Can", grammar: "Can he ___?" },
        { sentence: "They ___ speak English well.", correct: "can", grammar: "They ___ (ability)" },
        { sentence: "___ you a baseball player?", correct: "Are", grammar: "Are ___? (question)" },
        { sentence: "Yes, I ___.", correct: "am", grammar: "Yes, I ___" },
        { sentence: "No, I ___ not a player.", correct: "am", grammar: "No, I ___ not" },
        { sentence: "___ they your classmates?", correct: "Are", grammar: "Are ___? (question)" },
        { sentence: "We ___ in the same club.", correct: "are", grammar: "We ___ (be verb)" },
        { sentence: "___ you good at math?", correct: "Are", grammar: "Are you good at?" },
        { sentence: "She ___ good at drawing.", correct: "is", grammar: "She ___ good at" },
        { sentence: "I ___ bad at cooking.", correct: "am", grammar: "I ___ bad at" },
        { sentence: "He ___ not in the soccer club.", correct: "is", grammar: "He ___ not" },
        { sentence: "___ she in the art club?", correct: "Is", grammar: "Is ___ in ...?" },
      ],
    },
    {
      week: 4,
      title: "Do You Play? · Can You Read?",
      grammarFocus: "Simple Present (3rd person) · Does / Doesn't · Can you read?",
      questions: [
        { sentence: "Do you ___ an instrument?", correct: "play", grammar: "Do you ___?" },
        { sentence: "I ___ the trumpet.", correct: "play", grammar: "I ___ (instrument)" },
        { sentence: "She ___ the piano every day.", correct: "plays", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ not play sports.", correct: "does", grammar: "He ___ not play" },
        { sentence: "___ she play volleyball?", correct: "Does", grammar: "Does ___ play?" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "No, he ___ not.", correct: "does", grammar: "No, he ___ not" },
        { sentence: "I play soccer ___ tennis.", correct: "and", grammar: "A ___ B (and)" },
        { sentence: "We ___ board games on Sundays.", correct: "play", grammar: "We ___ (play)" },
        { sentence: "Do you play ___ guitar?", correct: "the", grammar: "play ___ guitar" },
        { sentence: "Can you ___ this kanji?", correct: "read", grammar: "Can you ___?" },
        { sentence: "Yes, I ___ read it.", correct: "can", grammar: "Yes, I ___ (can)" },
        { sentence: "I ___ read English books.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "She ___ not read French.", correct: "can", grammar: "She ___ not read" },
        { sentence: "___ he read the menu?", correct: "Can", grammar: "Can ___?" },
        { sentence: "They ___ speak and read English.", correct: "can", grammar: "They ___ (ability)" },
        { sentence: "I can play, ___ I can't read music.", correct: "but", grammar: "I can ..., ___ I can't" },
        { sentence: "She ___ write kanji yet.", correct: "can't", grammar: "She ___ (no ability)" },
        { sentence: "Can you ___ my English?", correct: "check", grammar: "Can you ___ ?" },
        { sentence: "___ we read this together?", correct: "Can", grammar: "Can we ___?" },
      ],
    },
    {
      week: 5,
      title: "Enjoy the Summer · Gerunds",
      grammarFocus: "What do you do? · Gerunds (-ing) · Good at / Love / Enjoy",
      questions: [
        { sentence: "What do you ___ on the weekend?", correct: "do", grammar: "What do you ___?" },
        { sentence: "I ___ judo after school.", correct: "do", grammar: "I ___ judo" },
        { sentence: "___ does he do on Sundays?", correct: "What", grammar: "___ does he do?" },
        { sentence: "What ___ she do at home?", correct: "does", grammar: "What ___ she do?" },
        { sentence: "She ___ basketball three times a week.", correct: "plays", grammar: "She ___ (3rd person)" },
        { sentence: "I enjoy swim___.", correct: "ming", grammar: "swim___ (gerund suffix)" },
        { sentence: "She enjoys sing___.", correct: "ing", grammar: "sing___ (gerund suffix)" },
        { sentence: "He loves cook___.", correct: "ing", grammar: "cook___ (gerund suffix)" },
        { sentence: "I like danc___.", correct: "ing", grammar: "danc___ (gerund suffix)" },
        { sentence: "I enjoy ___.", correct: "swimming", grammar: "swim → ___ (gerund)" },
        { sentence: "She is good at ___.", correct: "singing", grammar: "sing → ___ (gerund)" },
        { sentence: "They like ___ manga.", correct: "reading", grammar: "read → ___ (gerund)" },
        { sentence: "Do you like ___ in the rain?", correct: "running", grammar: "run → ___ (gerund)" },
        { sentence: "He enjoys ___ English games.", correct: "playing", grammar: "play → ___ (gerund)" },
        { sentence: "We love ___ to music.", correct: "listening", grammar: "listen → ___ (gerund)" },
        { sentence: "She doesn't enjoy ___ early.", correct: "waking", grammar: "wake → ___ (gerund)" },
        { sentence: "Are you good at ___?", correct: "drawing", grammar: "draw → ___ (gerund)" },
        { sentence: "I'm bad at ___ in English.", correct: "speaking", grammar: "speak → ___ (gerund)" },
        { sentence: "He likes ___ YouTube videos.", correct: "watching", grammar: "watch → ___ (gerund)" },
        { sentence: "I dislike ___ my room.", correct: "cleaning", grammar: "clean → ___ (gerund)" },
      ],
    },
    {
      week: 6,
      title: "I Want To · This Is / She's / He's",
      grammarFocus: "Want to + verb · He / She pronouns · Introducing people",
      questions: [
        { sentence: "I ___ to try kendo.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "She wants ___ join the club.", correct: "to", grammar: "She wants ___ join" },
        { sentence: "I want ___ visit Tokyo.", correct: "to", grammar: "I want ___ (infinitive)" },
        { sentence: "He wants ___ be a teacher.", correct: "to", grammar: "He wants ___ (infinitive)" },
        { sentence: "Do you ___ to play tennis?", correct: "want", grammar: "Do you ___ to?" },
        { sentence: "___ is my new friend, Taro.", correct: "This", grammar: "___ is (introduce)" },
        { sentence: "___ is my sister, Aiko.", correct: "This", grammar: "___ is (introduce)" },
        { sentence: "This ___ my brother, Kota.", correct: "is", grammar: "This ___ (be verb)" },
        { sentence: "His name ___ Kota.", correct: "is", grammar: "His name ___ (be verb)" },
        { sentence: "Her name ___ Aiko.", correct: "is", grammar: "Her name ___ (be verb)" },
        { sentence: "___ is from Okinawa.", correct: "She", grammar: "___ is from (pronoun)" },
        { sentence: "___ is my homeroom teacher.", correct: "He", grammar: "___ is (pronoun)" },
        { sentence: "She ___ 13 years old.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "He ___ not a student.", correct: "is", grammar: "He ___ not" },
        { sentence: "___ she your friend?", correct: "Is", grammar: "Is ___ ? (question)" },
        { sentence: "This ___ my pencil case.", correct: "is", grammar: "This ___ (be verb)" },
        { sentence: "___ that your eraser?", correct: "Is", grammar: "Is ___ ? (question)" },
        { sentence: "That ___ my notebook.", correct: "is", grammar: "That ___ (be verb)" },
        { sentence: "___ she good at sports?", correct: "Is", grammar: "Is ___ ? (question)" },
        { sentence: "He wants to ___ an engineer.", correct: "be", grammar: "wants to ___ (infinitive)" },
      ],
    },
    {
      week: 7,
      title: "Who's That? · Is This Our Classroom?",
      grammarFocus: "Who / Whose · Is this / that? · Yes it is / No it isn't",
      questions: [
        { sentence: "___ is that girl?", correct: "Who", grammar: "___ is that? (person)" },
        { sentence: "___ is he?", correct: "Who", grammar: "___ is he?" },
        { sentence: "Is ___ your teacher?", correct: "that", grammar: "Is ___ your ...?" },
        { sentence: "___ that your friend?", correct: "Is", grammar: "___ that? (question)" },
        { sentence: "Yes, ___ is.", correct: "that", grammar: "Yes, ___ is" },
        { sentence: "No, ___ is not.", correct: "that", grammar: "No, ___ is not" },
        { sentence: "Is ___ your classroom?", correct: "this", grammar: "Is ___ ? (near)" },
        { sentence: "Yes, ___ is our room.", correct: "this", grammar: "Yes, ___ is" },
        { sentence: "No, ___ is not our room.", correct: "this", grammar: "No, ___ is not" },
        { sentence: "___ bag is this?", correct: "Whose", grammar: "___ bag? (possessive)" },
        { sentence: "___ is this?", correct: "What", grammar: "___ is this? (thing)" },
        { sentence: "Is ___ a library?", correct: "this", grammar: "Is ___ a?" },
        { sentence: "___ is that building?", correct: "What", grammar: "___ is that?" },
        { sentence: "Is ___ your eraser?", correct: "this", grammar: "Is ___ your?" },
        { sentence: "___ this yours?", correct: "Is", grammar: "___ this yours?" },
        { sentence: "No, it ___.", correct: "isn't", grammar: "No, it ___ (negative)" },
        { sentence: "Yes, ___ is mine.", correct: "it", grammar: "Yes, ___ is mine" },
        { sentence: "___ is that person?", correct: "Who", grammar: "___ is that person?" },
        { sentence: "She ___ my P.E. teacher.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "___ notebook is this?", correct: "Whose", grammar: "___ notebook? (possessive)" },
      ],
    },
    {
      week: 8,
      title: "Imperative · Where's Your School?",
      grammarFocus: "Imperative (Open / Don't) · Where questions · Please + verb",
      questions: [
        { sentence: "___ on your camera, please.", correct: "Turn", grammar: "___ on (command)" },
        { sentence: "___ your textbook to page 10.", correct: "Open", grammar: "___ (command)" },
        { sentence: "Don't ___ in the library.", correct: "run", grammar: "Don't ___ (negative command)" },
        { sentence: "Don't ___ in class.", correct: "sleep", grammar: "Don't ___ (negative command)" },
        { sentence: "___ quiet, please.", correct: "Be", grammar: "___ (command + adjective)" },
        { sentence: "___ up! It's time for class.", correct: "Stand", grammar: "___ up (command)" },
        { sentence: "___ down, everyone.", correct: "Sit", grammar: "___ down (command)" },
        { sentence: "Please ___ at the board.", correct: "look", grammar: "Please ___ (polite command)" },
        { sentence: "Please ___ here.", correct: "come", grammar: "Please ___ (polite command)" },
        { sentence: "Don't be ___.", correct: "shy", grammar: "Don't be ___ (adj)" },
        { sentence: "___ is your school?", correct: "Where", grammar: "___ is ...? (location)" },
        { sentence: "Where ___ the gym?", correct: "is", grammar: "Where ___ ? (be verb)" },
        { sentence: "Where ___ you from?", correct: "are", grammar: "Where ___ you from?" },
        { sentence: "Where ___ he live?", correct: "does", grammar: "Where ___ he live?" },
        { sentence: "___ does she study?", correct: "Where", grammar: "___ does she study?" },
        { sentence: "Where ___ the station?", correct: "is", grammar: "Where ___ ? (be verb)" },
        { sentence: "Where ___ they go after school?", correct: "do", grammar: "Where ___ they go?" },
        { sentence: "___ do you want to go?", correct: "Where", grammar: "___ do you want?" },
        { sentence: "Where ___ your school bag?", correct: "is", grammar: "Where ___ ? (be verb)" },
        { sentence: "___ is the nearest station?", correct: "Where", grammar: "___ is (location Q)" },
      ],
    },
    {
      week: 9,
      title: "When's Your Match? · She Likes Singing",
      grammarFocus: "Wh- questions (When / How / Why) · 3rd person singular",
      questions: [
        { sentence: "___ is your birthday?", correct: "When", grammar: "___ is? (time Q)" },
        { sentence: "___ is your next match?", correct: "When", grammar: "___ is? (time Q)" },
        { sentence: "___ is your favorite food?", correct: "What", grammar: "___ is? (thing Q)" },
        { sentence: "___ do you study English?", correct: "When", grammar: "___ do you? (time Q)" },
        { sentence: "___ do you go to school?", correct: "How", grammar: "___ do you go? (method Q)" },
        { sentence: "She ___ singing in the chorus.", correct: "likes", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ soccer after school.", correct: "plays", grammar: "He ___ (3rd person)" },
        { sentence: "She ___ anime every night.", correct: "watches", grammar: "She ___ (3rd person -es)" },
        { sentence: "He ___ piano lessons on Mondays.", correct: "has", grammar: "He ___ (3rd person)" },
        { sentence: "She ___ up early every day.", correct: "gets", grammar: "She ___ (3rd person)" },
        { sentence: "___ she like running?", correct: "Does", grammar: "___ she like?" },
        { sentence: "She ___ to school by bicycle.", correct: "goes", grammar: "She ___ (3rd person -es)" },
        { sentence: "He ___ a cold today.", correct: "has", grammar: "He ___ (3rd person have)" },
        { sentence: "He ___ not like homework.", correct: "does", grammar: "He ___ not like" },
        { sentence: "She ___ English very well.", correct: "speaks", grammar: "She ___ (3rd person)" },
        { sentence: "___ he like reading?", correct: "Does", grammar: "Does ___ like?" },
        { sentence: "___ does she live?", correct: "Where", grammar: "___ does she live?" },
        { sentence: "___ does he come from?", correct: "Where", grammar: "___ does he come from?" },
        { sentence: "She ___ in Kyoto.", correct: "lives", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ to the gym three times a week.", correct: "goes", grammar: "He ___ (3rd person -es)" },
      ],
    },
    {
      week: 10,
      title: "Does She Have? · She Doesn't",
      grammarFocus: "Does / Doesn't · Have (3rd person) · Yes / No short answers",
      questions: [
        { sentence: "___ she have a pet?", correct: "Does", grammar: "___ she have?" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "___ he have a brother?", correct: "Does", grammar: "___ he have?" },
        { sentence: "No, he ___ not.", correct: "does", grammar: "No, he ___ not" },
        { sentence: "She ___ a big family.", correct: "has", grammar: "She ___ (3rd person have)" },
        { sentence: "He ___ not have a sister.", correct: "does", grammar: "He ___ not have" },
        { sentence: "She ___ not go to school on Saturdays.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "He ___ a cold today.", correct: "has", grammar: "He ___ (3rd person have)" },
        { sentence: "___ she have any hobbies?", correct: "Does", grammar: "___ she have?" },
        { sentence: "She ___ basketball practice on Tuesdays.", correct: "has", grammar: "She ___ practice" },
        { sentence: "He ___ go to cram school.", correct: "doesn't", grammar: "He ___ (negative)" },
        { sentence: "She ___ not like mornings.", correct: "does", grammar: "She ___ not like" },
        { sentence: "She ___ like horror movies.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "___ he play piano?", correct: "Does", grammar: "___ he play?" },
        { sentence: "He ___ every day.", correct: "practices", grammar: "He ___ (3rd person)" },
        { sentence: "She ___ not want to go.", correct: "does", grammar: "She ___ not want" },
        { sentence: "He ___ school on Mondays.", correct: "has", grammar: "He ___ school" },
        { sentence: "She ___ live near here.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "___ he have a bicycle?", correct: "Does", grammar: "___ he have?" },
        { sentence: "No, he ___ not have one.", correct: "does", grammar: "No, he ___ not" },
      ],
    },
    {
      week: 11,
      title: "I Watched TV · Did You Eat?",
      grammarFocus: "Past Simple · Did / Didn't · Irregular verbs",
      questions: [
        { sentence: "I ___ TV with my family.", correct: "watched", grammar: "watch → ___ (past)" },
        { sentence: "She ___ sushi for dinner.", correct: "ate", grammar: "eat → ___ (past)" },
        { sentence: "We ___ to the shrine.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "He ___ soccer at the park.", correct: "played", grammar: "play → ___ (past)" },
        { sentence: "I ___ a good time.", correct: "had", grammar: "have → ___ (past)" },
        { sentence: "She ___ a famous movie.", correct: "saw", grammar: "see → ___ (past)" },
        { sentence: "He ___ up late on Sunday.", correct: "got", grammar: "get → ___ (past)" },
        { sentence: "I ___ a letter to my friend.", correct: "wrote", grammar: "write → ___ (past)" },
        { sentence: "She ___ a cake last night.", correct: "made", grammar: "make → ___ (past)" },
        { sentence: "I ___ this book in one day.", correct: "read", grammar: "read → ___ (past)" },
        { sentence: "___ you eat breakfast?", correct: "Did", grammar: "___ you eat? (past Q)" },
        { sentence: "Yes, I ___ eat breakfast.", correct: "did", grammar: "Yes, I ___" },
        { sentence: "I ___ not eat lunch.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "___ she go to school?", correct: "Did", grammar: "___ she go?" },
        { sentence: "She ___ not go to the party.", correct: "didn't", grammar: "She ___ (negative past)" },
        { sentence: "We ___ not play outside.", correct: "did", grammar: "We ___ not (past neg.)" },
        { sentence: "___ he study for the test?", correct: "Did", grammar: "___ he study?" },
        { sentence: "No, he ___ not study.", correct: "did", grammar: "No, he ___ not" },
        { sentence: "I ___ not sleep well.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "She ___ not like it.", correct: "didn't", grammar: "She ___ (negative past)" },
      ],
    },
    {
      week: 12,
      title: "Was & Were · I'm Baking Right Now",
      grammarFocus: "Was / Were (past be) · Present Continuous (-ing) · Past Continuous",
      questions: [
        { sentence: "It ___ fun!", correct: "was", grammar: "It ___ (past be)" },
        { sentence: "They ___ beautiful.", correct: "were", grammar: "They ___ (past be)" },
        { sentence: "The weather ___ great.", correct: "was", grammar: "The weather ___ (past be)" },
        { sentence: "We ___ happy.", correct: "were", grammar: "We ___ (past be)" },
        { sentence: "She ___ at home.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "___ it fun?", correct: "Was", grammar: "___ it? (past Q)" },
        { sentence: "Yes, it ___ great.", correct: "was", grammar: "Yes, it ___ (past be)" },
        { sentence: "They ___ not at school.", correct: "were", grammar: "They ___ not (past be)" },
        { sentence: "___ you at home?", correct: "Were", grammar: "___ you? (past Q)" },
        { sentence: "No, we ___ not.", correct: "were", grammar: "No, we ___ not" },
        { sentence: "I ___ baking a cake now.", correct: "am", grammar: "I ___ (present continuous)" },
        { sentence: "She ___ reading a book.", correct: "is", grammar: "She ___ (present continuous)" },
        { sentence: "We ___ studying English.", correct: "are", grammar: "We ___ (present continuous)" },
        { sentence: "He ___ playing soccer now.", correct: "is", grammar: "He ___ (present continuous)" },
        { sentence: "They ___ watching TV.", correct: "are", grammar: "They ___ (present continuous)" },
        { sentence: "We ___ not studying.", correct: "are", grammar: "We ___ (present continuous)" },
        { sentence: "___ he sleeping?", correct: "Is", grammar: "___ he? (present continuous Q)" },
        { sentence: "___ they playing?", correct: "Are", grammar: "___ they? (present continuous Q)" },
        { sentence: "What ___ you doing?", correct: "were", grammar: "What ___ you doing? (past cont.)" },
        { sentence: "I ___ reading when she called.", correct: "was", grammar: "I ___ reading (past cont.)" },
      ],
    },
    {
      week: 13,
      title: "Be Verbs Review",
      grammarFocus: "Am / Is / Are / Was / Were — all subjects, all contexts",
      questions: [
        { sentence: "My favorite subject ___ math.", correct: "is", grammar: "subject ___ (be verb)" },
        { sentence: "We ___ in the library yesterday.", correct: "were", grammar: "We ___ (past be)" },
        { sentence: "The weather ___ cold last week.", correct: "was", grammar: "The weather ___ (past be)" },
        { sentence: "___ your parents teachers?", correct: "Are", grammar: "___ your parents? (Q)" },
        { sentence: "Yes, they ___.", correct: "are", grammar: "Yes, they ___" },
        { sentence: "I ___ nervous before the speech.", correct: "was", grammar: "I ___ (past be)" },
        { sentence: "___ you ready?", correct: "Are", grammar: "___ you? (question)" },
        { sentence: "She ___ not at school today.", correct: "is", grammar: "She ___ not (present)" },
        { sentence: "He ___ not here yesterday.", correct: "was", grammar: "He ___ not (past be)" },
        { sentence: "___ the test difficult?", correct: "Was", grammar: "___ the test? (past Q)" },
        { sentence: "No, it ___ not.", correct: "was", grammar: "No, it ___ not" },
        { sentence: "They ___ excited about the trip.", correct: "were", grammar: "They ___ (past be)" },
        { sentence: "My dog ___ very small.", correct: "is", grammar: "My dog ___ (be verb)" },
        { sentence: "I ___ happy when I got an A.", correct: "was", grammar: "I ___ (past be)" },
        { sentence: "___ it your birthday?", correct: "Is", grammar: "___ it? (question)" },
        { sentence: "We ___ on the same team.", correct: "are", grammar: "We ___ (be verb)" },
        { sentence: "Our classroom ___ on the second floor.", correct: "is", grammar: "classroom ___ (be verb)" },
        { sentence: "The flowers ___ beautiful.", correct: "are", grammar: "The flowers ___ (be verb)" },
        { sentence: "___ he at the gym?", correct: "Is", grammar: "___ he? (question)" },
        { sentence: "She ___ happy when she got an A.", correct: "was", grammar: "She ___ (past be)" },
      ],
    },
    {
      week: 14,
      title: "Simple Present Review",
      grammarFocus: "Do / Does / Don't / Doesn't — positive, negative, questions",
      questions: [
        { sentence: "I ___ to school at 8 o'clock.", correct: "go", grammar: "I ___ (simple present)" },
        { sentence: "She ___ English on Tuesdays.", correct: "studies", grammar: "She ___ (3rd person)" },
        { sentence: "We ___ lunch at noon.", correct: "have", grammar: "We ___ (simple present)" },
        { sentence: "He ___ not like coffee.", correct: "does", grammar: "He ___ not like" },
        { sentence: "___ she eat breakfast?", correct: "Does", grammar: "___ she? (question)" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "I ___ not play video games on weekdays.", correct: "do", grammar: "I ___ not" },
        { sentence: "___ you have homework today?", correct: "Do", grammar: "___ you? (question)" },
        { sentence: "My cat ___ a lot.", correct: "sleeps", grammar: "My cat ___ (3rd person)" },
        { sentence: "She ___ to music every morning.", correct: "listens", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ his room every weekend.", correct: "cleans", grammar: "He ___ (3rd person)" },
        { sentence: "They ___ to school by train.", correct: "go", grammar: "They ___ (simple present)" },
        { sentence: "She ___ English well.", correct: "speaks", grammar: "She ___ (3rd person)" },
        { sentence: "I ___ not understand this problem.", correct: "do", grammar: "I ___ not understand" },
        { sentence: "___ he live near school?", correct: "Does", grammar: "___ he? (question)" },
        { sentence: "No, he ___ not.", correct: "does", grammar: "No, he ___ not" },
        { sentence: "We ___ have class on Sundays.", correct: "don't", grammar: "We ___ (negative)" },
        { sentence: "She ___ piano for one hour every day.", correct: "practices", grammar: "She ___ (3rd person)" },
        { sentence: "___ they walk to school?", correct: "Do", grammar: "___ they? (question)" },
        { sentence: "My mother ___ dinner at 6 p.m.", correct: "cooks", grammar: "My mother ___ (3rd person)" },
      ],
    },
    {
      week: 15,
      title: "Can / Can't Review",
      grammarFocus: "Can / Can't — ability, permission, questions, short answers",
      questions: [
        { sentence: "I ___ ride a bicycle.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "She ___ speak three languages.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "He ___ draw very well.", correct: "can", grammar: "He ___ (ability)" },
        { sentence: "We ___ hear you!", correct: "can't", grammar: "We ___ (no ability)" },
        { sentence: "___ you help me, please?", correct: "Can", grammar: "Can ___? (question)" },
        { sentence: "I ___ dance, but I can sing.", correct: "can't", grammar: "I ___ (no ability)" },
        { sentence: "She ___ cook pasta very well.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "He ___ play chess.", correct: "can", grammar: "He ___ (ability)" },
        { sentence: "___ they join our team?", correct: "Can", grammar: "Can ___? (question)" },
        { sentence: "Yes, they ___.", correct: "can", grammar: "Yes, they ___" },
        { sentence: "No, he ___ not come today.", correct: "can", grammar: "No, he ___ not" },
        { sentence: "I ___ understand this kanji.", correct: "can't", grammar: "I ___ (no ability)" },
        { sentence: "She ___ type very fast.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "___ I borrow your pencil?", correct: "Can", grammar: "Can I ___?" },
        { sentence: "Yes, you ___.", correct: "can", grammar: "Yes, you ___" },
        { sentence: "They ___ ski in winter.", correct: "can", grammar: "They ___ (ability)" },
        { sentence: "We ___ finish this by tomorrow.", correct: "can", grammar: "We ___ (ability)" },
        { sentence: "___ she sing in English?", correct: "Can", grammar: "Can ___? (question)" },
        { sentence: "I ___ run 5 km without stopping.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "He ___ not come to practice today.", correct: "can", grammar: "He ___ not come" },
      ],
    },
    {
      week: 16,
      title: "Past Simple — Irregular Verbs",
      grammarFocus: "Irregular past: came / gave / knew / bought / won / broke / met / sang",
      questions: [
        { sentence: "She ___ to the school festival yesterday.", correct: "came", grammar: "come → ___ (past)" },
        { sentence: "He ___ me a great idea.", correct: "gave", grammar: "give → ___ (past)" },
        { sentence: "I ___ her name but now I forgot.", correct: "knew", grammar: "know → ___ (past)" },
        { sentence: "She ___ the test was easy.", correct: "thought", grammar: "think → ___ (past)" },
        { sentence: "I ___ a present for my mother.", correct: "bought", grammar: "buy → ___ (past)" },
        { sentence: "He ___ the race!", correct: "won", grammar: "win → ___ (past)" },
        { sentence: "She ___ her friend at the station.", correct: "met", grammar: "meet → ___ (past)" },
        { sentence: "He ___ the window this morning.", correct: "broke", grammar: "break → ___ (past)" },
        { sentence: "I ___ a funny video online.", correct: "saw", grammar: "see → ___ (past)" },
        { sentence: "She ___ a beautiful song.", correct: "sang", grammar: "sing → ___ (past)" },
        { sentence: "We ___ a lot of fun last year.", correct: "had", grammar: "have → ___ (past)" },
        { sentence: "He ___ the taxi to the station.", correct: "took", grammar: "take → ___ (past)" },
        { sentence: "She ___ her keys at home.", correct: "left", grammar: "leave → ___ (past)" },
        { sentence: "I ___ her an email yesterday.", correct: "sent", grammar: "send → ___ (past)" },
        { sentence: "He ___ very fast but missed the bus.", correct: "ran", grammar: "run → ___ (past)" },
        { sentence: "She ___ me everything she knew.", correct: "told", grammar: "tell → ___ (past)" },
        { sentence: "I ___ a picture of the sunset.", correct: "took", grammar: "take → ___ (past)" },
        { sentence: "He ___ the news from his friend.", correct: "heard", grammar: "hear → ___ (past)" },
        { sentence: "She ___ how to make ramen.", correct: "taught", grammar: "teach → ___ (past)" },
        { sentence: "We ___ Japanese food for the first time.", correct: "tried", grammar: "try → ___ (past)" },
      ],
    },
    {
      week: 17,
      title: "Questions — All Types",
      grammarFocus: "Be / Do / Does / Did / Can + Wh- questions — all mixed",
      questions: [
        { sentence: "___ is your English teacher?", correct: "Who", grammar: "___ is? (person)" },
        { sentence: "___ do you go to school?", correct: "How", grammar: "___ do you? (method)" },
        { sentence: "___ does school start?", correct: "When", grammar: "___ does? (time)" },
        { sentence: "___ is your favorite subject?", correct: "What", grammar: "___ is? (thing)" },
        { sentence: "___ old are you?", correct: "How", grammar: "___ old? (age)" },
        { sentence: "___ is your birthday?", correct: "When", grammar: "___ is? (time)" },
        { sentence: "___ did you do last weekend?", correct: "What", grammar: "___ did you? (past Q)" },
        { sentence: "___ is the gym?", correct: "Where", grammar: "___ is? (location)" },
        { sentence: "___ you have a pet?", correct: "Do", grammar: "___ you have? (question)" },
        { sentence: "___ she like English?", correct: "Does", grammar: "___ she like? (3rd Q)" },
        { sentence: "___ he go to school?", correct: "Did", grammar: "___ he go? (past Q)" },
        { sentence: "___ you swim?", correct: "Can", grammar: "___ you swim? (ability Q)" },
        { sentence: "___ the test easy?", correct: "Was", grammar: "___ the test? (past be Q)" },
        { sentence: "___ they your friends?", correct: "Are", grammar: "___ they? (be Q)" },
        { sentence: "___ you study last night?", correct: "Did", grammar: "___ you study? (past Q)" },
        { sentence: "___ many students are in your class?", correct: "How", grammar: "___ many? (quantity Q)" },
        { sentence: "___ it rain yesterday?", correct: "Did", grammar: "___ it rain? (past Q)" },
        { sentence: "___ she good at singing?", correct: "Is", grammar: "___ she good at? (be Q)" },
        { sentence: "___ do you like most?", correct: "What", grammar: "___ do you like?" },
        { sentence: "___ far is your school?", correct: "How", grammar: "___ far? (distance Q)" },
      ],
    },
    {
      week: 18,
      title: "Continuous Tenses Review",
      grammarFocus: "Present Continuous (am/is/are -ing) · Past Continuous (was/were -ing)",
      questions: [
        { sentence: "I ___ playing video games right now.", correct: "am", grammar: "I ___ (present cont.)" },
        { sentence: "She ___ reading a manga.", correct: "is", grammar: "She ___ (present cont.)" },
        { sentence: "They ___ studying for the test.", correct: "are", grammar: "They ___ (present cont.)" },
        { sentence: "He ___ listening to music.", correct: "is", grammar: "He ___ (present cont.)" },
        { sentence: "We ___ talking about tomorrow's trip.", correct: "are", grammar: "We ___ (present cont.)" },
        { sentence: "___ you eating lunch?", correct: "Are", grammar: "___ you eating? (Q)" },
        { sentence: "Yes, I ___.", correct: "am", grammar: "Yes, I ___" },
        { sentence: "No, she ___ not sleeping.", correct: "is", grammar: "she ___ not (present cont.)" },
        { sentence: "___ it raining?", correct: "Is", grammar: "___ it raining? (Q)" },
        { sentence: "They ___ not playing outside.", correct: "are", grammar: "They ___ not (present cont.)" },
        { sentence: "I ___ cooking when she called.", correct: "was", grammar: "I ___ (past cont.)" },
        { sentence: "She ___ sleeping when I arrived.", correct: "was", grammar: "She ___ (past cont.)" },
        { sentence: "They ___ running when it started to rain.", correct: "were", grammar: "They ___ (past cont.)" },
        { sentence: "He ___ watching TV all evening.", correct: "was", grammar: "He ___ (past cont.)" },
        { sentence: "We ___ practicing when the teacher came in.", correct: "were", grammar: "We ___ (past cont.)" },
        { sentence: "___ you sleeping at 9 p.m.?", correct: "Were", grammar: "___ you sleeping? (past Q)" },
        { sentence: "No, I ___ not sleeping.", correct: "was", grammar: "No, I ___ not" },
        { sentence: "What ___ you doing at noon?", correct: "were", grammar: "What ___ you doing? (past Q)" },
        { sentence: "She ___ singing when I heard her.", correct: "was", grammar: "She ___ (past cont.)" },
        { sentence: "They ___ not watching the game.", correct: "were", grammar: "They ___ not (past cont.)" },
      ],
    },
    {
      week: 19,
      title: "There Is / There Are",
      grammarFocus: "There is (singular) · There are (plural) · Is there? / Are there?",
      questions: [
        { sentence: "There ___ a cat under the desk.", correct: "is", grammar: "There ___ a (singular)" },
        { sentence: "There ___ many trees in the park.", correct: "are", grammar: "There ___ many (plural)" },
        { sentence: "There ___ not a bookstore near here.", correct: "is", grammar: "There ___ not a" },
        { sentence: "___ there a hospital near here?", correct: "Is", grammar: "___ there a? (Q)" },
        { sentence: "Yes, there ___.", correct: "is", grammar: "Yes, there ___" },
        { sentence: "There ___ 35 students in my class.", correct: "are", grammar: "There ___ (plural)" },
        { sentence: "___ there any apples?", correct: "Are", grammar: "___ there any? (Q)" },
        { sentence: "No, there ___ not.", correct: "are", grammar: "No, there ___ not" },
        { sentence: "There ___ a library on the second floor.", correct: "is", grammar: "There ___ a (singular)" },
        { sentence: "___ there a vending machine?", correct: "Is", grammar: "___ there a? (Q)" },
        { sentence: "There ___ five floors in this school.", correct: "are", grammar: "There ___ (plural)" },
        { sentence: "There ___ not many boys in this club.", correct: "are", grammar: "There ___ not many" },
        { sentence: "Is there ___ convenience store near here?", correct: "a", grammar: "Is there ___ ? (article)" },
        { sentence: "There ___ a big festival this weekend.", correct: "is", grammar: "There ___ a (singular)" },
        { sentence: "There ___ not any milk in the fridge.", correct: "is", grammar: "There ___ not any" },
        { sentence: "___ any students absent today?", correct: "Are", grammar: "___ any? (Q)" },
        { sentence: "There ___ three cats and two dogs.", correct: "are", grammar: "There ___ (plural)" },
        { sentence: "There ___ a new student in our class.", correct: "is", grammar: "There ___ a (singular)" },
        { sentence: "Is there ___ park near here?", correct: "a", grammar: "Is there ___ ? (article)" },
        { sentence: "There ___ seats available.", correct: "are", grammar: "There ___ (plural)" },
      ],
    },
    {
      week: 20,
      title: "Adjectives & Descriptions",
      grammarFocus: "Adjective + be verb · descriptive sentences · not + adjective",
      questions: [
        { sentence: "This cake ___ very delicious!", correct: "is", grammar: "This cake ___ (be verb)" },
        { sentence: "The test ___ easy this time.", correct: "was", grammar: "The test ___ (past be)" },
        { sentence: "She ___ tall and kind.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "The weather ___ terrible yesterday.", correct: "was", grammar: "The weather ___ (past be)" },
        { sentence: "His English ___ getting better.", correct: "is", grammar: "His English ___ (be verb)" },
        { sentence: "These shoes ___ too small.", correct: "are", grammar: "These shoes ___ (be verb)" },
        { sentence: "That movie ___ boring.", correct: "was", grammar: "That movie ___ (past be)" },
        { sentence: "The food ___ really hot.", correct: "is", grammar: "The food ___ (be verb)" },
        { sentence: "My room ___ not big enough.", correct: "is", grammar: "My room ___ not" },
        { sentence: "Her answer ___ correct.", correct: "was", grammar: "Her answer ___ (past be)" },
        { sentence: "The questions ___ difficult.", correct: "are", grammar: "The questions ___ (be verb)" },
        { sentence: "You ___ very creative!", correct: "are", grammar: "You ___ (be verb)" },
        { sentence: "It ___ dark outside already.", correct: "is", grammar: "It ___ (be verb)" },
        { sentence: "The view ___ amazing from here.", correct: "is", grammar: "The view ___ (be verb)" },
        { sentence: "Their uniforms ___ blue and white.", correct: "are", grammar: "Their uniforms ___ (be verb)" },
        { sentence: "He ___ good at everything.", correct: "is", grammar: "He ___ (be verb)" },
        { sentence: "The music ___ too loud.", correct: "was", grammar: "The music ___ (past be)" },
        { sentence: "These exercises ___ helpful.", correct: "are", grammar: "These exercises ___ (be verb)" },
        { sentence: "My score ___ higher than usual.", correct: "was", grammar: "My score ___ (past be)" },
        { sentence: "The answer ___ obvious!", correct: "is", grammar: "The answer ___ (be verb)" },
      ],
    },
    {
      week: 21,
      title: "Prepositions of Place",
      grammarFocus: "In / On / At / Under / Next to / Behind / By — location",
      questions: [
        { sentence: "My pencil is ___ my bag.", correct: "in", grammar: "___ (inside)" },
        { sentence: "The book is ___ the table.", correct: "on", grammar: "___ (surface)" },
        { sentence: "She studies ___ the library.", correct: "in", grammar: "___ the library (inside)" },
        { sentence: "He sits ___ the front row.", correct: "in", grammar: "___ the front row" },
        { sentence: "The school is ___ Station Street.", correct: "on", grammar: "___ (on a street)" },
        { sentence: "Wait for me ___ the entrance.", correct: "at", grammar: "___ (specific point)" },
        { sentence: "The gym is ___ the second floor.", correct: "on", grammar: "___ the floor" },
        { sentence: "My house is ___ the park.", correct: "near", grammar: "___ (proximity)" },
        { sentence: "The cat is sleeping ___ the sofa.", correct: "on", grammar: "___ (surface)" },
        { sentence: "Put your bag ___ your desk.", correct: "under", grammar: "___ (below)" },
        { sentence: "She is waiting ___ the bus stop.", correct: "at", grammar: "___ (specific point)" },
        { sentence: "They are sitting ___ the back.", correct: "at", grammar: "___ the back" },
        { sentence: "The teacher's desk is ___ the front.", correct: "at", grammar: "___ the front" },
        { sentence: "My locker is ___ the hallway.", correct: "in", grammar: "___ (inside an area)" },
        { sentence: "He lives ___ Osaka.", correct: "in", grammar: "___ (city/country)" },
        { sentence: "We met ___ the park.", correct: "at", grammar: "___ (specific place)" },
        { sentence: "The poster is ___ the wall.", correct: "on", grammar: "___ (surface)" },
        { sentence: "Her book is ___ her desk.", correct: "on", grammar: "___ (surface)" },
        { sentence: "The store is ___ the corner.", correct: "on", grammar: "___ the corner" },
        { sentence: "I left my bag ___ the door.", correct: "by", grammar: "___ (beside)" },
      ],
    },
    {
      week: 22,
      title: "Prepositions of Time",
      grammarFocus: "At (clock time) · On (day/date) · In (month/season/year)",
      questions: [
        { sentence: "School starts ___ April.", correct: "in", grammar: "___ April (month)" },
        { sentence: "We have PE ___ Wednesdays.", correct: "on", grammar: "___ Wednesday (day)" },
        { sentence: "My birthday is ___ March 15th.", correct: "on", grammar: "___ (date)" },
        { sentence: "I wake up ___ 7 o'clock.", correct: "at", grammar: "___ 7 o'clock (time)" },
        { sentence: "She goes to bed ___ night.", correct: "at", grammar: "___ night" },
        { sentence: "It gets cold ___ winter.", correct: "in", grammar: "___ winter (season)" },
        { sentence: "The game starts ___ 3 p.m.", correct: "at", grammar: "___ 3 p.m. (time)" },
        { sentence: "We have a test ___ Monday.", correct: "on", grammar: "___ Monday (day)" },
        { sentence: "I study ___ the afternoon.", correct: "in", grammar: "___ the afternoon" },
        { sentence: "She was born ___ 2012.", correct: "in", grammar: "___ 2012 (year)" },
        { sentence: "He calls me ___ Sunday evenings.", correct: "on", grammar: "___ Sunday evenings (day)" },
        { sentence: "We have vacation ___ summer.", correct: "in", grammar: "___ summer (season)" },
        { sentence: "The meeting is ___ noon.", correct: "at", grammar: "___ noon (time)" },
        { sentence: "I practice ___ the morning.", correct: "in", grammar: "___ the morning" },
        { sentence: "The cherry blossoms bloom ___ spring.", correct: "in", grammar: "___ spring (season)" },
        { sentence: "The festival is ___ Saturday night.", correct: "on", grammar: "___ Saturday (day)" },
        { sentence: "It's cold ___ January.", correct: "in", grammar: "___ January (month)" },
        { sentence: "The library closes ___ 8 p.m.", correct: "at", grammar: "___ 8 p.m. (time)" },
        { sentence: "She has piano lessons ___ Fridays.", correct: "on", grammar: "___ Fridays (day)" },
        { sentence: "I'll be back ___ 5 minutes.", correct: "in", grammar: "___ 5 minutes (duration)" },
      ],
    },
    {
      week: 23,
      title: "Connectors — And / But / So / Because / Or",
      grammarFocus: "Connecting sentences with and / but / so / because / or",
      questions: [
        { sentence: "I like cats ___ dogs.", correct: "and", grammar: "A ___ B (addition)" },
        { sentence: "She wants to come, ___ she is busy.", correct: "but", grammar: "... ___ (contrast)" },
        { sentence: "I was hungry, ___ I ate a sandwich.", correct: "so", grammar: "... ___ (result)" },
        { sentence: "He didn't come ___ he was sick.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "Do you want tea ___ coffee?", correct: "or", grammar: "A ___ B (choice)" },
        { sentence: "She studies hard, ___ she always gets good grades.", correct: "so", grammar: "... ___ (result)" },
        { sentence: "I like summer ___ I don't like the heat.", correct: "but", grammar: "... ___ (contrast)" },
        { sentence: "He was late ___ he missed the train.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "She can sing ___ dance.", correct: "and", grammar: "A ___ B (addition)" },
        { sentence: "I tried, ___ I couldn't do it.", correct: "but", grammar: "... ___ (contrast)" },
        { sentence: "It was raining, ___ we stayed inside.", correct: "so", grammar: "... ___ (result)" },
        { sentence: "She didn't eat ___ she wasn't hungry.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "We can go by bus ___ by train.", correct: "or", grammar: "A ___ B (choice)" },
        { sentence: "I like reading ___ I hate tests.", correct: "but", grammar: "... ___ (contrast)" },
        { sentence: "He forgot his book, ___ he borrowed mine.", correct: "so", grammar: "... ___ (result)" },
        { sentence: "She sang ___ played the guitar.", correct: "and", grammar: "A ___ B (addition)" },
        { sentence: "I study English ___ I want to travel.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "Was it hot ___ cold yesterday?", correct: "or", grammar: "A ___ B (choice)" },
        { sentence: "He was tired ___ happy at the same time.", correct: "but", grammar: "... ___ (contrast)" },
        { sentence: "She missed the bus, ___ she was late.", correct: "so", grammar: "... ___ (result)" },
      ],
    },
    {
      week: 24,
      title: "This / These / That / Those",
      grammarFocus: "Demonstrative pronouns — near (this/these) vs. far (that/those)",
      questions: [
        { sentence: "___ is my new pencil (in my hand).", correct: "This", grammar: "___ (near singular)" },
        { sentence: "___ are my best friends (next to me).", correct: "These", grammar: "___ (near plural)" },
        { sentence: "Look at ___ bird way up in the sky!", correct: "that", grammar: "___ (far singular)" },
        { sentence: "___ old building over there is our school.", correct: "That", grammar: "___ (far singular)" },
        { sentence: "___ book right here is mine.", correct: "This", grammar: "___ (near singular)" },
        { sentence: "___ students next to me are very helpful.", correct: "These", grammar: "___ (near plural)" },
        { sentence: "Who made ___ mess over there?", correct: "that", grammar: "___ (far singular)" },
        { sentence: "___ shirt I'm wearing is from Osaka.", correct: "This", grammar: "___ (near singular)" },
        { sentence: "___ mountains far away are beautiful.", correct: "Those", grammar: "___ (far plural)" },
        { sentence: "I like ___ shoes in front of me.", correct: "these", grammar: "___ (near plural)" },
        { sentence: "Is ___ your bag over there?", correct: "that", grammar: "___ (far singular)" },
        { sentence: "___ was an amazing performance just now!", correct: "That", grammar: "___ (far singular, event)" },
        { sentence: "___ are the questions for today.", correct: "These", grammar: "___ (near plural)" },
        { sentence: "Can you pass me ___ book at the far end?", correct: "that", grammar: "___ (far singular)" },
        { sentence: "___ children playing over there are my students.", correct: "Those", grammar: "___ (far plural)" },
        { sentence: "___ days are getting shorter in autumn.", correct: "These", grammar: "___ (near plural, current)" },
        { sentence: "Remember ___ song we sang last year?", correct: "that", grammar: "___ (far, past reference)" },
        { sentence: "Don't forget ___ things right here.", correct: "these", grammar: "___ (near plural)" },
        { sentence: "___ was a great movie!", correct: "That", grammar: "___ (far, past event)" },
        { sentence: "I want to try ___ cake on the table in front of me.", correct: "this", grammar: "___ (near singular)" },
      ],
    },
    {
      week: 25,
      title: "Frequency Adverbs",
      grammarFocus: "Always / Usually / Often / Sometimes / Never — with do/does",
      questions: [
        { sentence: "I brush my teeth every morning and night. I ___ brush my teeth.", correct: "always", grammar: "___ (100%)" },
        { sentence: "She eats breakfast 6 out of 7 days. She ___ eats breakfast.", correct: "usually", grammar: "___ (about 80%)" },
        { sentence: "He plays soccer twice a week. He ___ plays soccer.", correct: "often", grammar: "___ (about 60%)" },
        { sentence: "I eat meat about once a month. I ___ eat meat.", correct: "sometimes", grammar: "___ (about 30%)" },
        { sentence: "We go hiking every weekend. We ___ go hiking.", correct: "always", grammar: "___ (100%)" },
        { sentence: "She hates horror movies. She ___ watches them.", correct: "never", grammar: "___ (0%)" },
        { sentence: "He studies the night before a test. He ___ does this.", correct: "usually", grammar: "___ (about 80%)" },
        { sentence: "I ___ forget my umbrella when it rains.", correct: "always", grammar: "___ (every time)" },
        { sentence: "She ___ reads before going to bed, every night.", correct: "always", grammar: "___ (100%)" },
        { sentence: "He ___ uses a dictionary when he reads.", correct: "often", grammar: "___ (frequently)" },
        { sentence: "We ___ have parties at school, maybe twice a year.", correct: "sometimes", grammar: "___ (occasionally)" },
        { sentence: "I ___ eat junk food at school. It is not allowed.", correct: "never", grammar: "___ (0%)" },
        { sentence: "She ___ helps her friends when they need her.", correct: "always", grammar: "___ (every time)" },
        { sentence: "He ___ does his homework on time, most of the time.", correct: "usually", grammar: "___ (about 80%)" },
        { sentence: "I ___ speak English outside class. I should try more.", correct: "rarely", grammar: "___ (almost never)" },
        { sentence: "She ___ comes to school late. She is very punctual.", correct: "never", grammar: "___ (0%)" },
        { sentence: "I ___ understand everything in English, not always.", correct: "sometimes", grammar: "___ (occasionally)" },
        { sentence: "He ___ says thank you. He is very polite.", correct: "always", grammar: "___ (100%)" },
        { sentence: "They ___ meet on Saturdays, most weeks.", correct: "usually", grammar: "___ (about 80%)" },
        { sentence: "I ___ remember what I dreamed.", correct: "never", grammar: "___ (0%)" },
      ],
    },
    {
      week: 26,
      title: "How Many / How Much / How Long / How Often / How Old / How Far",
      grammarFocus: "How + adjective/adverb — quantity questions",
      questions: [
        { sentence: "How ___ students are in your class?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ time do you need?", correct: "much", grammar: "How ___ (uncountable)" },
        { sentence: "How ___ do you exercise?", correct: "often", grammar: "How ___ (frequency)" },
        { sentence: "How ___ is your walk to school?", correct: "long", grammar: "How ___ (duration)" },
        { sentence: "How ___ is your sister?", correct: "old", grammar: "How ___ (age)" },
        { sentence: "How ___ is it from here to school?", correct: "far", grammar: "How ___ (distance)" },
        { sentence: "How ___ money do you spend each week?", correct: "much", grammar: "How ___ (uncountable)" },
        { sentence: "How ___ people live in your house?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ does it take by train?", correct: "long", grammar: "How ___ (duration)" },
        { sentence: "How ___ times a week do you practice?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ do you go to the dentist?", correct: "often", grammar: "How ___ (frequency)" },
        { sentence: "How ___ homework do you have?", correct: "much", grammar: "How ___ (uncountable)" },
        { sentence: "How ___ languages can you speak?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ have you studied English?", correct: "long", grammar: "How ___ (duration)" },
        { sentence: "How ___ is your English teacher?", correct: "old", grammar: "How ___ (age)" },
        { sentence: "How ___ books do you read per month?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ does a new smartphone cost?", correct: "much", grammar: "How ___ (uncountable)" },
        { sentence: "How ___ students won the quiz?", correct: "many", grammar: "How ___ (countable)" },
        { sentence: "How ___ would you say it takes to walk there?", correct: "long", grammar: "How ___ (duration)" },
        { sentence: "How ___ days until the school trip?", correct: "many", grammar: "How ___ (countable)" },
      ],
    },
    {
      week: 27,
      title: "Theme — School Life",
      grammarFocus: "Grammar review in a school context — do/does/did + simple present/past",
      questions: [
        { sentence: "I ___ my homework every night.", correct: "do", grammar: "I ___ (simple present)" },
        { sentence: "She ___ very carefully in class.", correct: "listens", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ to school by bicycle.", correct: "goes", grammar: "He ___ (3rd person)" },
        { sentence: "We ___ English on Tuesdays.", correct: "have", grammar: "We ___ (simple present)" },
        { sentence: "___ she like science?", correct: "Does", grammar: "___ she like? (question)" },
        { sentence: "Yes, she ___ like it.", correct: "does", grammar: "Yes, she ___ (short answer)" },
        { sentence: "I ___ not understand this problem.", correct: "do", grammar: "I ___ not understand" },
        { sentence: "He ___ his pencil again.", correct: "forgot", grammar: "forget → ___ (past)" },
        { sentence: "We ___ a field trip last month.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "She ___ first in the math contest.", correct: "came", grammar: "come → ___ (past)" },
        { sentence: "___ you study before the test?", correct: "Did", grammar: "___ you study? (past Q)" },
        { sentence: "I ___ late because I missed the bus.", correct: "was", grammar: "I ___ (past be)" },
        { sentence: "He ___ not study hard last year.", correct: "did", grammar: "He ___ not (past neg.)" },
        { sentence: "The school ___ very noisy during lunch.", correct: "is", grammar: "The school ___ (be verb)" },
        { sentence: "___ she finish the assignment?", correct: "Did", grammar: "___ she? (past Q)" },
        { sentence: "I ___ studying for the exam right now.", correct: "am", grammar: "I ___ (present cont.)" },
        { sentence: "She ___ up early to review her notes.", correct: "got", grammar: "get → ___ (past)" },
        { sentence: "___ he good at spelling?", correct: "Is", grammar: "___ he? (be Q)" },
        { sentence: "We ___ all pass the test!", correct: "will", grammar: "We ___ (will future)" },
        { sentence: "I ___ to the library every lunch break.", correct: "go", grammar: "I ___ (simple present)" },
      ],
    },
    {
      week: 28,
      title: "Theme — Food & Meals",
      grammarFocus: "Grammar review in a food context — eat/drink/like/cook + all tenses",
      questions: [
        { sentence: "I ___ rice every morning.", correct: "eat", grammar: "I ___ (simple present)" },
        { sentence: "She ___ not like spicy food.", correct: "does", grammar: "She ___ not like" },
        { sentence: "___ he eat vegetables?", correct: "Does", grammar: "___ he? (question)" },
        { sentence: "We ___ ramen last night.", correct: "ate", grammar: "eat → ___ (past)" },
        { sentence: "___ you try natto?", correct: "Did", grammar: "___ you? (past Q)" },
        { sentence: "Yes, I ___ it once.", correct: "tried", grammar: "try → ___ (past)" },
        { sentence: "She ___ to bake cakes.", correct: "loves", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ not drink coffee.", correct: "does", grammar: "He ___ not drink" },
        { sentence: "I ___ eating out with my family.", correct: "enjoy", grammar: "I ___ (enjoy + gerund)" },
        { sentence: "She ___ cook breakfast for us.", correct: "can", grammar: "She ___ (ability)" },
        { sentence: "We ___ cooking for 30 minutes.", correct: "were", grammar: "We ___ (past cont.)" },
        { sentence: "___ this taste good to you?", correct: "Does", grammar: "___ this taste? (3rd Q)" },
        { sentence: "Yes, it ___ delicious!", correct: "tastes", grammar: "it ___ (3rd person)" },
        { sentence: "I ___ the food at this restaurant.", correct: "like", grammar: "I ___ (simple present)" },
        { sentence: "___ there any dessert left?", correct: "Is", grammar: "___ there? (Q)" },
        { sentence: "No, there ___ not.", correct: "is", grammar: "No, there ___ not" },
        { sentence: "I ___ not hungry right now.", correct: "am", grammar: "I ___ not (be verb)" },
        { sentence: "She ___ very fast because she was hungry.", correct: "ate", grammar: "eat → ___ (past)" },
        { sentence: "He ___ going to try sushi for the first time.", correct: "is", grammar: "He ___ going to" },
        { sentence: "I ___ three glasses of water today.", correct: "drank", grammar: "drink → ___ (past)" },
      ],
    },
    {
      week: 29,
      title: "Theme — Sports & Hobbies",
      grammarFocus: "Grammar review in a sports context — can/did/does + all tenses",
      questions: [
        { sentence: "I ___ the soccer team.", correct: "joined", grammar: "join → ___ (past)" },
        { sentence: "She ___ volleyball on Mondays.", correct: "plays", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ not like running.", correct: "does", grammar: "He ___ not like" },
        { sentence: "We ___ hard for the tournament.", correct: "practiced", grammar: "practice → ___ (past)" },
        { sentence: "___ she play in the school team?", correct: "Does", grammar: "___ she? (question)" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "I ___ not like losing.", correct: "do", grammar: "I ___ not like" },
        { sentence: "They ___ the tournament last year.", correct: "won", grammar: "win → ___ (past)" },
        { sentence: "___ you ever tried kendo?", correct: "Did", grammar: "___ you? (past Q)" },
        { sentence: "I ___ swimming for an hour.", correct: "was", grammar: "I ___ (past cont.)" },
        { sentence: "She ___ very tired after the match.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "He ___ well in the relay race.", correct: "ran", grammar: "run → ___ (past)" },
        { sentence: "___ there a game today?", correct: "Is", grammar: "___ there? (Q)" },
        { sentence: "I ___ join the club next year.", correct: "will", grammar: "I ___ (will future)" },
        { sentence: "She ___ going to compete in the tournament.", correct: "is", grammar: "She ___ going to" },
        { sentence: "___ they win the championship?", correct: "Did", grammar: "___ they? (past Q)" },
        { sentence: "I ___ to be on the soccer team.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "She ___ kendo since she was little.", correct: "has", grammar: "She ___ (present perfect)" },
        { sentence: "He ___ every day to improve.", correct: "trains", grammar: "He ___ (3rd person)" },
        { sentence: "___ you swim 100 meters?", correct: "Can", grammar: "___ you? (ability Q)" },
      ],
    },
    {
      week: 30,
      title: "Theme — Family & Friends",
      grammarFocus: "Grammar review in family context — 3rd person / possessives / does",
      questions: [
        { sentence: "My father ___ a doctor.", correct: "is", grammar: "My father ___ (be verb)" },
        { sentence: "Her sister ___ music.", correct: "loves", grammar: "Her sister ___ (3rd person)" },
        { sentence: "His brother ___ not like studying.", correct: "does", grammar: "His brother ___ not" },
        { sentence: "___ your mother work?", correct: "Does", grammar: "___ your mother? (Q)" },
        { sentence: "Yes, she ___ at a hospital.", correct: "works", grammar: "Yes, she ___ (3rd person)" },
        { sentence: "My grandmother ___ 72 years old.", correct: "is", grammar: "My grandmother ___ (be verb)" },
        { sentence: "Their parents ___ very strict.", correct: "are", grammar: "Their parents ___ (be verb)" },
        { sentence: "___ your parents like Japanese food?", correct: "Do", grammar: "___ your parents? (Q)" },
        { sentence: "I ___ two sisters and one brother.", correct: "have", grammar: "I ___ (simple present)" },
        { sentence: "She ___ very close to her grandfather.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "His mother ___ for him every night.", correct: "cooks", grammar: "His mother ___ (3rd person)" },
        { sentence: "My father ___ home late.", correct: "comes", grammar: "My father ___ (3rd person)" },
        { sentence: "___ she have any siblings?", correct: "Does", grammar: "___ she have? (Q)" },
        { sentence: "No, she ___ not. She's an only child.", correct: "does", grammar: "No, she ___ not" },
        { sentence: "They ___ best friends since elementary school.", correct: "are", grammar: "They ___ (be verb)" },
        { sentence: "My older sister ___ very helpful.", correct: "is", grammar: "My older sister ___ (be verb)" },
        { sentence: "His father ___ a guitar.", correct: "plays", grammar: "His father ___ (3rd person)" },
        { sentence: "___ your family eat dinner together?", correct: "Does", grammar: "___ your family? (Q)" },
        { sentence: "We ___ having a family dinner tonight.", correct: "are", grammar: "We ___ (present cont.)" },
        { sentence: "My little brother ___ always make me laugh.", correct: "can", grammar: "My brother ___ (ability)" },
      ],
    },
    {
      week: 31,
      title: "Theme — Daily Routine",
      grammarFocus: "Simple present verbs for routine actions — 1st and 3rd person",
      questions: [
        { sentence: "I ___ up at 7 every morning.", correct: "wake", grammar: "I ___ up (routine)" },
        { sentence: "She ___ breakfast before school.", correct: "eats", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ to school at 8:30.", correct: "goes", grammar: "He ___ (3rd person)" },
        { sentence: "I ___ home at 4 o'clock.", correct: "come", grammar: "I ___ home (routine)" },
        { sentence: "She ___ homework before dinner.", correct: "does", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ TV after dinner.", correct: "watches", grammar: "He ___ (3rd person)" },
        { sentence: "I ___ to bed at 11 p.m.", correct: "go", grammar: "I ___ to bed (routine)" },
        { sentence: "She ___ a shower at night.", correct: "takes", grammar: "She ___ a shower (3rd person)" },
        { sentence: "___ you brush your teeth before bed?", correct: "Do", grammar: "___ you? (question)" },
        { sentence: "Yes, I ___.", correct: "do", grammar: "Yes, I ___" },
        { sentence: "He ___ not sleep enough on weekdays.", correct: "does", grammar: "He ___ not sleep" },
        { sentence: "I ___ coffee in the morning.", correct: "drink", grammar: "I ___ (routine)" },
        { sentence: "She ___ her dog every morning.", correct: "walks", grammar: "She ___ (3rd person)" },
        { sentence: "What ___ you usually do after school?", correct: "do", grammar: "What ___ you do?" },
        { sentence: "I ___ to the gym after school.", correct: "go", grammar: "I ___ (routine)" },
        { sentence: "She ___ the guitar before dinner.", correct: "practices", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ home around 6 p.m.", correct: "arrives", grammar: "He ___ (3rd person)" },
        { sentence: "I ___ English for an hour every evening.", correct: "study", grammar: "I ___ (routine)" },
        { sentence: "She ___ her room every weekend.", correct: "cleans", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ to music while he studies.", correct: "listens", grammar: "He ___ (3rd person)" },
      ],
    },
    {
      week: 32,
      title: "Theme — Weather & Seasons",
      grammarFocus: "Grammar review with weather/seasons — be verbs, simple present, past",
      questions: [
        { sentence: "It ___ hot in summer.", correct: "is", grammar: "It ___ (be verb, general)" },
        { sentence: "It ___ very cold last winter.", correct: "was", grammar: "It ___ (past be)" },
        { sentence: "___ it snowing outside?", correct: "Is", grammar: "___ it? (present cont. Q)" },
        { sentence: "Yes, it ___ heavily.", correct: "is", grammar: "Yes, it ___ (present cont.)" },
        { sentence: "It ___ not rain much in this area.", correct: "does", grammar: "It ___ not rain" },
        { sentence: "The weather ___ nice yesterday.", correct: "was", grammar: "The weather ___ (past be)" },
        { sentence: "___ it going to rain tomorrow?", correct: "Is", grammar: "___ it going to? (Q)" },
        { sentence: "It ___ windy in March.", correct: "is", grammar: "It ___ (be verb, general)" },
        { sentence: "She ___ not like cold weather.", correct: "does", grammar: "She ___ not like" },
        { sentence: "I love summer ___ I can go to the beach.", correct: "because", grammar: "... ___ (reason)" },
        { sentence: "The leaves ___ red and yellow in autumn.", correct: "are", grammar: "The leaves ___ (be verb)" },
        { sentence: "___ it snow a lot last year?", correct: "Did", grammar: "___ it snow? (past Q)" },
        { sentence: "It gets cold ___ autumn.", correct: "in", grammar: "___ autumn (preposition)" },
        { sentence: "Summer ___ here finally!", correct: "is", grammar: "Summer ___ (be verb)" },
        { sentence: "I ___ summer better than winter.", correct: "like", grammar: "I ___ (simple present)" },
        { sentence: "She ___ a jacket because it was cold.", correct: "wore", grammar: "wear → ___ (past)" },
        { sentence: "Cherry blossoms ___ in April.", correct: "bloom", grammar: "Cherry blossoms ___ (3rd pl.)" },
        { sentence: "The rain ___ very heavy last night.", correct: "was", grammar: "The rain ___ (past be)" },
        { sentence: "It ___ sunny and warm tomorrow.", correct: "will", grammar: "It ___ (will future)" },
        { sentence: "We ___ inside because of the snow.", correct: "stayed", grammar: "stay → ___ (past)" },
      ],
    },
    {
      week: 33,
      title: "Theme — Health & Body",
      grammarFocus: "Grammar review with health topics — feel/have/do/was + all tenses",
      questions: [
        { sentence: "I ___ not feel well today.", correct: "do", grammar: "I ___ not feel" },
        { sentence: "She ___ a headache.", correct: "has", grammar: "She ___ (3rd person have)" },
        { sentence: "He ___ very tired after PE.", correct: "was", grammar: "He ___ (past be)" },
        { sentence: "___ you sleep well last night?", correct: "Did", grammar: "___ you sleep? (past Q)" },
        { sentence: "No, I ___ not sleep enough.", correct: "did", grammar: "No, I ___ not" },
        { sentence: "I ___ for 30 minutes every morning.", correct: "exercise", grammar: "I ___ (routine)" },
        { sentence: "She ___ sick last week.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "He ___ to the doctor yesterday.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "___ you have a fever?", correct: "Do", grammar: "___ you have? (Q)" },
        { sentence: "Yes, I ___ a cold.", correct: "have", grammar: "Yes, I ___ (have)" },
        { sentence: "I ___ better now, thank you.", correct: "feel", grammar: "I ___ (simple present)" },
        { sentence: "She ___ drink enough water.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "He ___ every morning to stay healthy.", correct: "runs", grammar: "He ___ (3rd person)" },
        { sentence: "I ___ a bone when I was young.", correct: "broke", grammar: "break → ___ (past)" },
        { sentence: "She ___ to bed early when she's sick.", correct: "goes", grammar: "She ___ (3rd person)" },
        { sentence: "He ___ not eat enough vegetables.", correct: "does", grammar: "He ___ not eat" },
        { sentence: "Getting enough sleep ___ important.", correct: "is", grammar: "Getting sleep ___ (be verb)" },
        { sentence: "Exercise ___ you feel better.", correct: "makes", grammar: "Exercise ___ you (causative)" },
        { sentence: "She ___ not sleep well when she's stressed.", correct: "does", grammar: "She ___ not sleep" },
        { sentence: "He ___ a lot of water every day.", correct: "drinks", grammar: "He ___ (3rd person)" },
      ],
    },
    {
      week: 34,
      title: "Theme — Dreams & Goals",
      grammarFocus: "Want to / Going to / Will — talking about future plans and dreams",
      questions: [
        { sentence: "I ___ to be a doctor.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "She ___ to become a singer.", correct: "wants", grammar: "She ___ to (3rd person)" },
        { sentence: "He ___ going to study abroad.", correct: "is", grammar: "He ___ going to (future)" },
        { sentence: "I am ___ to work hard this year.", correct: "going", grammar: "I am ___ to (future)" },
        { sentence: "My dream ___ to visit New York.", correct: "is", grammar: "My dream ___ (be verb)" },
        { sentence: "She ___ to travel the world someday.", correct: "wants", grammar: "She ___ to (3rd person)" },
        { sentence: "He ___ going to practice more.", correct: "is", grammar: "He ___ going to (future)" },
        { sentence: "She ___ to be a teacher someday.", correct: "wants", grammar: "She ___ to (3rd person)" },
        { sentence: "I am going to ___ harder next term.", correct: "try", grammar: "going to ___ (base verb)" },
        { sentence: "My goal ___ to read 20 books this year.", correct: "is", grammar: "My goal ___ (be verb)" },
        { sentence: "I ___ to go to university in Tokyo.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "He ___ to get a perfect score next time.", correct: "wants", grammar: "He ___ to (3rd person)" },
        { sentence: "She ___ studying to become a nurse.", correct: "is", grammar: "She ___ (present cont.)" },
        { sentence: "I am going ___ try my best.", correct: "to", grammar: "am going ___ (infinitive)" },
        { sentence: "We ___ to win the championship.", correct: "want", grammar: "We ___ to (want)" },
        { sentence: "My dream job ___ being a game designer.", correct: "is", grammar: "My dream job ___ (be verb)" },
        { sentence: "I ___ not give up on my dream.", correct: "will", grammar: "I ___ (will + negative)" },
        { sentence: "She is ___ to apply to a good high school.", correct: "going", grammar: "She is ___ to (future)" },
        { sentence: "He ___ become a professional player one day.", correct: "will", grammar: "He ___ (will future)" },
        { sentence: "What ___ you want to do in the future?", correct: "do", grammar: "What ___ you want?" },
      ],
    },
    {
      week: 35,
      title: "Mixed Review A — Be Verbs & Simple Present",
      grammarFocus: "Am / Is / Are / Was / Were + Do / Does / Don't / Doesn't — mixed",
      questions: [
        { sentence: "I ___ 13 years old.", correct: "am", grammar: "I ___ (be verb)" },
        { sentence: "She ___ not like mornings.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "They ___ happy today.", correct: "are", grammar: "They ___ (be verb)" },
        { sentence: "He ___ to school at 8 every day.", correct: "goes", grammar: "He ___ (3rd person)" },
        { sentence: "It ___ cold yesterday.", correct: "was", grammar: "It ___ (past be)" },
        { sentence: "___ she like English?", correct: "Does", grammar: "___ she like? (Q)" },
        { sentence: "Yes, she ___.", correct: "does", grammar: "Yes, she ___" },
        { sentence: "We ___ students.", correct: "are", grammar: "We ___ (be verb)" },
        { sentence: "I ___ not from here.", correct: "am", grammar: "I ___ not (be verb)" },
        { sentence: "___ you have a pet?", correct: "Do", grammar: "___ you have? (Q)" },
        { sentence: "He ___ a cat.", correct: "has", grammar: "He ___ (3rd person have)" },
        { sentence: "She ___ not live near here.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "___ they your classmates?", correct: "Are", grammar: "___ they? (Q)" },
        { sentence: "Yes, they ___.", correct: "are", grammar: "Yes, they ___" },
        { sentence: "The test ___ very easy.", correct: "was", grammar: "The test ___ (past be)" },
        { sentence: "I ___ not understand this.", correct: "do", grammar: "I ___ not understand" },
        { sentence: "She ___ good at cooking.", correct: "is", grammar: "She ___ (be verb)" },
        { sentence: "___ he like pizza?", correct: "Does", grammar: "___ he like? (Q)" },
        { sentence: "No, he ___ not.", correct: "does", grammar: "No, he ___ not" },
        { sentence: "We ___ happy with the results.", correct: "were", grammar: "We ___ (past be)" },
      ],
    },
    {
      week: 36,
      title: "Mixed Review B — Past Simple",
      grammarFocus: "Past Simple — positive, negative, and questions — various verbs",
      questions: [
        { sentence: "I ___ a letter to my friend.", correct: "wrote", grammar: "write → ___ (past)" },
        { sentence: "She ___ sushi for lunch.", correct: "ate", grammar: "eat → ___ (past)" },
        { sentence: "He ___ the race!", correct: "won", grammar: "win → ___ (past)" },
        { sentence: "We ___ to the beach last summer.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "___ you see that movie?", correct: "Did", grammar: "___ you see? (past Q)" },
        { sentence: "Yes, I ___ it.", correct: "saw", grammar: "Yes, I ___" },
        { sentence: "No, I ___ not see it.", correct: "did", grammar: "No, I ___ not" },
        { sentence: "She ___ very tired after the test.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "He ___ late because of the train.", correct: "was", grammar: "He ___ (past be)" },
        { sentence: "___ she cook dinner?", correct: "Did", grammar: "___ she cook? (past Q)" },
        { sentence: "I ___ for 2 hours.", correct: "studied", grammar: "study → ___ (past)" },
        { sentence: "She ___ up early to go shopping.", correct: "got", grammar: "get → ___ (past)" },
        { sentence: "They ___ a lot of fun.", correct: "had", grammar: "have → ___ (past)" },
        { sentence: "He ___ not come to school.", correct: "did", grammar: "He ___ not (past neg.)" },
        { sentence: "I ___ not understand the question.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "She ___ a beautiful dress to the party.", correct: "wore", grammar: "wear → ___ (past)" },
        { sentence: "___ he play in the tournament?", correct: "Did", grammar: "___ he play? (past Q)" },
        { sentence: "Yes, he ___ well!", correct: "played", grammar: "Yes, he ___ (past)" },
        { sentence: "They ___ home very late.", correct: "came", grammar: "come → ___ (past)" },
        { sentence: "I ___ three books over vacation.", correct: "read", grammar: "read → ___ (past)" },
      ],
    },
    {
      week: 37,
      title: "Mixed Review C — Questions & Negatives",
      grammarFocus: "Do / Does / Did / Can / Is / Are / Was / Were — questions and negatives",
      questions: [
        { sentence: "___ you like horror movies?", correct: "Do", grammar: "___ you like? (Q)" },
        { sentence: "No, I ___ like them.", correct: "don't", grammar: "No, I ___ (negative)" },
        { sentence: "___ she play tennis?", correct: "Does", grammar: "___ she play? (Q)" },
        { sentence: "No, she ___ not.", correct: "does", grammar: "No, she ___ not" },
        { sentence: "___ he come to school today?", correct: "Did", grammar: "___ he come? (past Q)" },
        { sentence: "No, he ___ not come.", correct: "did", grammar: "No, he ___ not" },
        { sentence: "___ you swim?", correct: "Can", grammar: "___ you swim? (ability Q)" },
        { sentence: "No, I ___.", correct: "can't", grammar: "No, I ___ (negative)" },
        { sentence: "___ they friends?", correct: "Are", grammar: "___ they? (be Q)" },
        { sentence: "Yes, they ___.", correct: "are", grammar: "Yes, they ___" },
        { sentence: "___ it cold?", correct: "Is", grammar: "___ it? (be Q)" },
        { sentence: "No, it ___ not.", correct: "is", grammar: "No, it ___ not" },
        { sentence: "___ she happy?", correct: "Was", grammar: "___ she? (past be Q)" },
        { sentence: "No, she ___ not happy.", correct: "was", grammar: "No, she ___ not" },
        { sentence: "Where ___ she from?", correct: "is", grammar: "Where ___ she? (be verb)" },
        { sentence: "Who ___ that person?", correct: "is", grammar: "Who ___ that? (be verb)" },
        { sentence: "When ___ you study?", correct: "do", grammar: "When ___ you? (do Q)" },
        { sentence: "Why ___ he not here?", correct: "is", grammar: "Why ___ he? (be verb)" },
        { sentence: "How ___ she get to school?", correct: "does", grammar: "How ___ she? (does Q)" },
        { sentence: "What ___ you doing?", correct: "are", grammar: "What ___ you doing? (cont.)" },
      ],
    },
    {
      week: 38,
      title: "Mixed Review D — -ing Focus",
      grammarFocus: "Present Continuous · Gerunds · Was/Were + -ing · Good at -ing",
      questions: [
        { sentence: "I am ___ a book right now.", correct: "reading", grammar: "am ___ (present cont.)" },
        { sentence: "She is ___ in the gym.", correct: "practicing", grammar: "is ___ (present cont.)" },
        { sentence: "He was ___ a cake when I arrived.", correct: "making", grammar: "was ___ (past cont.)" },
        { sentence: "We are ___ to music.", correct: "listening", grammar: "are ___ (present cont.)" },
        { sentence: "___ English is important.", correct: "Learning", grammar: "___ (gerund subject)" },
        { sentence: "She enjoys ___ movies.", correct: "watching", grammar: "enjoys ___ (gerund)" },
        { sentence: "I love ___.", correct: "swimming", grammar: "love ___ (gerund)" },
        { sentence: "He is good at ___ pictures.", correct: "drawing", grammar: "good at ___ (gerund)" },
        { sentence: "She stopped ___.", correct: "talking", grammar: "stopped ___ (gerund)" },
        { sentence: "I am not ___ well today.", correct: "feeling", grammar: "am not ___ (present cont.)" },
        { sentence: "They are ___ the park.", correct: "cleaning", grammar: "are ___ (present cont.)" },
        { sentence: "She was ___ for the bus.", correct: "waiting", grammar: "was ___ (past cont.)" },
        { sentence: "He is ___ to music while walking.", correct: "listening", grammar: "is ___ (present cont.)" },
        { sentence: "We are ___ dinner together.", correct: "having", grammar: "are ___ (present cont.)" },
        { sentence: "She was ___ the window when it broke.", correct: "cleaning", grammar: "was ___ (past cont.)" },
        { sentence: "I enjoy ___ new things.", correct: "learning", grammar: "enjoy ___ (gerund)" },
        { sentence: "He is ___ better at English.", correct: "getting", grammar: "is ___ (present cont.)" },
        { sentence: "Are you ___ your homework?", correct: "doing", grammar: "Are you ___? (present cont. Q)" },
        { sentence: "I love ___ abroad.", correct: "traveling", grammar: "love ___ (gerund)" },
        { sentence: "___ music makes me happy.", correct: "Listening", grammar: "___ (gerund subject)" },
      ],
    },
    {
      week: 39,
      title: "Year Review A",
      grammarFocus: "All Grade 1 grammar — mixed (easier level)",
      questions: [
        { sentence: "I ___ 13 years old.", correct: "am", grammar: "I ___ (be verb)" },
        { sentence: "She ___ not like cold food.", correct: "does", grammar: "She ___ not like" },
        { sentence: "I ___ play tennis.", correct: "can", grammar: "I ___ (ability)" },
        { sentence: "___ you from Tokyo?", correct: "Are", grammar: "___ you? (Q)" },
        { sentence: "We ___ to the shrine last year.", correct: "went", grammar: "go → ___ (past)" },
        { sentence: "He ___ not come to school today.", correct: "did", grammar: "He ___ not (past neg.)" },
        { sentence: "I ___ happy to meet you!", correct: "am", grammar: "I ___ (be verb)" },
        { sentence: "___ she read English books?", correct: "Can", grammar: "___ she? (ability Q)" },
        { sentence: "Yes, she ___.", correct: "can", grammar: "Yes, she ___" },
        { sentence: "I ___ a test tomorrow.", correct: "have", grammar: "I ___ (simple present)" },
        { sentence: "We ___ very tired after the game.", correct: "were", grammar: "We ___ (past be)" },
        { sentence: "___ you like sushi?", correct: "Do", grammar: "___ you like? (Q)" },
        { sentence: "She ___ going to join the art club.", correct: "is", grammar: "She ___ going to (future)" },
        { sentence: "He ___ not here yesterday.", correct: "was", grammar: "He ___ not (past be)" },
        { sentence: "I ___ not sleep well.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "___ this your pen?", correct: "Is", grammar: "___ this? (Q)" },
        { sentence: "No, it ___ not mine.", correct: "is", grammar: "No, it ___ not" },
        { sentence: "I ___ to become a doctor.", correct: "want", grammar: "I ___ to (want)" },
        { sentence: "They ___ soccer yesterday.", correct: "played", grammar: "play → ___ (past)" },
        { sentence: "I am ___ to try harder!", correct: "going", grammar: "I am ___ to (future)" },
      ],
    },
    {
      week: 40,
      title: "Year Review B",
      grammarFocus: "All Grade 1 grammar — mixed (harder level)",
      questions: [
        { sentence: "She ___ English well, but she can't speak it.", correct: "reads", grammar: "She ___ (3rd person)" },
        { sentence: "I ___ not go because I was sick.", correct: "did", grammar: "I ___ not (past neg.)" },
        { sentence: "___ you practicing now?", correct: "Are", grammar: "___ you? (present cont. Q)" },
        { sentence: "He ___ up early every morning.", correct: "gets", grammar: "He ___ (3rd person)" },
        { sentence: "She ___ the door when I knocked.", correct: "opened", grammar: "open → ___ (past)" },
        { sentence: "We ___ having a great time!", correct: "are", grammar: "We ___ (present cont.)" },
        { sentence: "___ he like vegetables?", correct: "Does", grammar: "___ he like? (Q)" },
        { sentence: "No, he ___ not like them.", correct: "does", grammar: "No, he ___ not" },
        { sentence: "The weather ___ beautiful today.", correct: "is", grammar: "The weather ___ (be verb)" },
        { sentence: "She ___ not eat fish.", correct: "doesn't", grammar: "She ___ (negative)" },
        { sentence: "What ___ you doing here?", correct: "are", grammar: "What ___ you doing? (present cont.)" },
        { sentence: "I ___ very nervous yesterday.", correct: "was", grammar: "I ___ (past be)" },
        { sentence: "She ___ the match!", correct: "won", grammar: "win → ___ (past)" },
        { sentence: "___ this your bag?", correct: "Is", grammar: "___ this? (Q)" },
        { sentence: "No, it ___ not.", correct: "is", grammar: "No, it ___ not" },
        { sentence: "They ___ great friends.", correct: "are", grammar: "They ___ (be verb)" },
        { sentence: "I ___ my homework before dinner every day.", correct: "do", grammar: "I ___ (routine)" },
        { sentence: "She ___ very tired after the long day.", correct: "was", grammar: "She ___ (past be)" },
        { sentence: "We ___ going to win this game!", correct: "are", grammar: "We ___ going to (future)" },
        { sentence: "He ___ to the park when it rained.", correct: "was going", grammar: "was ___ when (past cont.)" },
      ],
    },
  ],
} as const;
