export const grade3 = {
  grade: "3",
  emoji: "🦁",
  label: "GRADE 3",
  description: "Second Year Review",
  textbook: "New Horizon 3",
  weeks: [
    {
      week: 1,
      title: "Have You Ever Been to Guam?",
      grammarFocus: "Present Perfect — experience · have/has + past participle · ever / never",
      questions: [
        { sentence: "Have you ever ___ to Guam?", correct: "been", grammar: "ever ___ (past participle)" },
        { sentence: "Yes, I have ___ to Guam twice.", correct: "been", grammar: "have ___ (past participle)" },
        { sentence: "I have never ___ sushi before.", correct: "tried", grammar: "never ___ (past participle)" },
        { sentence: "Have you ___ seen a shooting star?", correct: "ever", grammar: "have ___ seen (ever)" },
        { sentence: "She ___ visited many countries.", correct: "has", grammar: "She ___ (has + past part.)" },
        { sentence: "I have ___ eaten raw fish before.", correct: "never", grammar: "have ___ (never)" },
        { sentence: "He ___ never been to Canada.", correct: "has", grammar: "He ___ never (has)" },
        { sentence: "___ she ever climbed Mt. Fuji?", correct: "Has", grammar: "___ she ever? (Q)" },
        { sentence: "No, she has ___.", correct: "never", grammar: "No, she has ___ (negative)" },
        { sentence: "We have ___ met before.", correct: "never", grammar: "have ___ (never)" },
        { sentence: "Have they ___ played basketball?", correct: "ever", grammar: "have ___ (ever)" },
        { sentence: "I ___ been to this restaurant three times.", correct: "have", grammar: "I ___ (have + past part.)" },
        { sentence: "He has ___ the movie twice.", correct: "seen", grammar: "has ___ (past participle)" },
        { sentence: "___ you ever tried octopus?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "Yes, I ___.", correct: "have", grammar: "Yes, I ___ (short answer)" },
        { sentence: "No, I ___ not.", correct: "have", grammar: "No, I ___ not (negative)" },
        { sentence: "She has ___ studied French before.", correct: "never", grammar: "has ___ (never)" },
        { sentence: "Have ___ ever visited Hokkaido?", correct: "you", grammar: "Have ___ ever? (subject)" },
        { sentence: "I have already ___ that book.", correct: "read", grammar: "already ___ (past participle)" },
        { sentence: "He has ___ been to a famous concert.", correct: "never", grammar: "has ___ been (never)" },
      ],
    },
    {
      week: 2,
      title: "I Will Call You a Taxi / The Music Makes Me Relaxed",
      grammarFocus: "SVOO — call/find/make/keep + complement · SVOC review",
      questions: [
        { sentence: "I will call ___ a taxi.", correct: "you", grammar: "call ___ a taxi (SVOO)" },
        { sentence: "He found ___ a seat.", correct: "her", grammar: "found ___ a seat (SVOO)" },
        { sentence: "She gave ___ the tickets.", correct: "us", grammar: "gave ___ (SVOO)" },
        { sentence: "I will ___ you a message.", correct: "send", grammar: "will ___ you (SVOO verb)" },
        { sentence: "He showed ___ his work.", correct: "me", grammar: "showed ___ (SVOO)" },
        { sentence: "The music ___ me relaxed.", correct: "makes", grammar: "___ me (SVOC)" },
        { sentence: "Good food ___ me happy.", correct: "makes", grammar: "___ me (SVOC)" },
        { sentence: "Cold water ___ me awake.", correct: "keeps", grammar: "___ me (SVOC)" },
        { sentence: "She ___ the room clean.", correct: "keeps", grammar: "___ room (SVOC)" },
        { sentence: "I ___ this idea interesting.", correct: "find", grammar: "I ___ (SVOC)" },
        { sentence: "He ___ the task difficult.", correct: "found", grammar: "He ___ (SVOC past)" },
        { sentence: "The news ___ us shocked.", correct: "left", grammar: "___ us (SVOC)" },
        { sentence: "They ___ him captain.", correct: "called", grammar: "They ___ him (SVOC past)" },
        { sentence: "The journey ___ us exhausted.", correct: "left", grammar: "___ us (SVOC)" },
        { sentence: "Exercise ___ you energetic.", correct: "keeps", grammar: "___ you (SVOC)" },
        { sentence: "Stress ___ you tired.", correct: "makes", grammar: "___ you (SVOC)" },
        { sentence: "Her friends ___ her Ami.", correct: "call", grammar: "___ her (SVOC)" },
        { sentence: "I ___ learning English fun.", correct: "find", grammar: "I ___ (SVOC)" },
        { sentence: "Good friends ___ you happy.", correct: "make", grammar: "___ you (SVOC)" },
        { sentence: "Music ___ her calm.", correct: "keeps", grammar: "___ her (SVOC)" },
      ],
    },
    {
      week: 3,
      title: "I Have Just Finished / He Has Never Eaten Natto",
      grammarFocus: "Present Perfect — just / yet / already · for / since",
      questions: [
        { sentence: "I have ___ finished my homework.", correct: "just", grammar: "have ___ (just)" },
        { sentence: "She has ___ come back.", correct: "just", grammar: "has ___ (just)" },
        { sentence: "I have not finished ___.", correct: "yet", grammar: "have not ... ___ (yet)" },
        { sentence: "Has he finished ___?", correct: "yet", grammar: "Has he ... ___? (yet)" },
        { sentence: "She has ___ eaten lunch.", correct: "already", grammar: "has ___ (already)" },
        { sentence: "I have ___ seen this movie.", correct: "already", grammar: "have ___ (already)" },
        { sentence: "He has ___ eaten natto.", correct: "never", grammar: "has ___ (never)" },
        { sentence: "I have lived here ___ 2020.", correct: "since", grammar: "___ (since + year)" },
        { sentence: "She has studied English ___ three years.", correct: "for", grammar: "___ (for + duration)" },
        { sentence: "He has been sick ___ last Monday.", correct: "since", grammar: "___ (since + day)" },
        { sentence: "I have known her ___ 10 years.", correct: "for", grammar: "___ (for + duration)" },
        { sentence: "They have not called ___.", correct: "yet", grammar: "have not ... ___ (yet)" },
        { sentence: "Have you done it ___?", correct: "yet", grammar: "Have you ... ___? (yet)" },
        { sentence: "She has ___ finished the report.", correct: "already", grammar: "has ___ (already)" },
        { sentence: "I have ___ been waiting for an hour.", correct: "already", grammar: "have ___ (already)" },
        { sentence: "We have been friends ___ we were children.", correct: "since", grammar: "___ (since + clause)" },
        { sentence: "He has worked here ___ 5 years.", correct: "for", grammar: "___ (for + duration)" },
        { sentence: "Has she eaten ___?", correct: "yet", grammar: "Has she ... ___? (yet)" },
        { sentence: "I have ___ bought a ticket.", correct: "already", grammar: "have ___ (already)" },
        { sentence: "She has been waiting ___ noon.", correct: "since", grammar: "___ (since + time)" },
      ],
    },
    {
      week: 4,
      title: "She Has Been Cleaning the Room Since Morning",
      grammarFocus: "Present Perfect Continuous — has/have been + -ing · for / since",
      questions: [
        { sentence: "She has been ___ the room since morning.", correct: "cleaning", grammar: "has been ___ (-ing)" },
        { sentence: "I have been ___ English for 5 years.", correct: "studying", grammar: "have been ___ (-ing)" },
        { sentence: "He ___ been waiting for an hour.", correct: "has", grammar: "___ been waiting (have/has)" },
        { sentence: "We ___ been practicing since 9 a.m.", correct: "have", grammar: "___ been practicing" },
        { sentence: "She has been ___ all morning.", correct: "working", grammar: "has been ___ (-ing)" },
        { sentence: "It has been ___ for three hours.", correct: "raining", grammar: "has been ___ (-ing)" },
        { sentence: "How long ___ you been studying?", correct: "have", grammar: "___ you been? (Q)" },
        { sentence: "They have been ___ since lunch.", correct: "talking", grammar: "have been ___ (-ing)" },
        { sentence: "I ___ been living here for two years.", correct: "have", grammar: "___ been living (have/has)" },
        { sentence: "She ___ been sleeping since noon.", correct: "has", grammar: "___ been sleeping (have/has)" },
        { sentence: "He has been ___ a novel this week.", correct: "writing", grammar: "has been ___ (-ing)" },
        { sentence: "We have been ___ for the test.", correct: "preparing", grammar: "have been ___ (-ing)" },
        { sentence: "___ she been feeling well?", correct: "Has", grammar: "___ she been? (Q)" },
        { sentence: "No, she ___ been sick.", correct: "has", grammar: "No, she ___ been (have/has)" },
        { sentence: "I have been ___ every day to get better.", correct: "exercising", grammar: "have been ___ (-ing)" },
        { sentence: "He has been ___ the piano since he was 5.", correct: "playing", grammar: "has been ___ (-ing)" },
        { sentence: "___ they been working on the project?", correct: "Have", grammar: "___ they been? (Q)" },
        { sentence: "Yes, they ___ been working for a week.", correct: "have", grammar: "Yes, they ___ (have/has)" },
        { sentence: "She has been ___ us since the beginning.", correct: "helping", grammar: "has been ___ (-ing)" },
        { sentence: "I have been ___ for you for 20 minutes!", correct: "waiting", grammar: "have been ___ (-ing)" },
      ],
    },
    {
      week: 5,
      title: "It Is Important for Us to Take Action",
      grammarFocus: "It is … for … to … · want someone to · ask someone to",
      questions: [
        { sentence: "It is important ___ us to take action.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "It is necessary ___ everyone to study.", correct: "for", grammar: "It is ... ___ everyone to ..." },
        { sentence: "It is fun ___ children to play outside.", correct: "for", grammar: "It is ... ___ children to ..." },
        { sentence: "It is difficult ___ me to wake up early.", correct: "for", grammar: "It is ... ___ me to ..." },
        { sentence: "It is unusual ___ him to be late.", correct: "for", grammar: "It is ... ___ him to ..." },
        { sentence: "It is good ___ us to exercise.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "I want you ___ understand my point.", correct: "to", grammar: "I want you ___ (infinitive)" },
        { sentence: "I want ___ to come to the party.", correct: "them", grammar: "I want ___ to (object)" },
        { sentence: "She wants him ___ study harder.", correct: "to", grammar: "wants him ___ (infinitive)" },
        { sentence: "He wants us ___ join the club.", correct: "to", grammar: "wants us ___ (infinitive)" },
        { sentence: "She asked me ___ open the window.", correct: "to", grammar: "asked me ___ (infinitive)" },
        { sentence: "He asked her ___ help him.", correct: "to", grammar: "asked her ___ (infinitive)" },
        { sentence: "I told ___ to be quiet.", correct: "him", grammar: "told ___ to (object)" },
        { sentence: "She told me ___ wait here.", correct: "to", grammar: "told me ___ (infinitive)" },
        { sentence: "He encouraged ___ to try again.", correct: "me", grammar: "encouraged ___ to (object)" },
        { sentence: "She encouraged me ___ keep going.", correct: "to", grammar: "encouraged me ___ (infinitive)" },
        { sentence: "It is natural ___ people to make mistakes.", correct: "for", grammar: "It is ... ___ people to ..." },
        { sentence: "It was nice ___ you to help us.", correct: "of", grammar: "It was nice ___ you to (of)" },
        { sentence: "It is possible ___ anyone to learn English.", correct: "for", grammar: "It is ... ___ anyone to ..." },
        { sentence: "I expect ___ to finish on time.", correct: "them", grammar: "I expect ___ to (object)" },
      ],
    },
    {
      week: 6,
      title: "She Let Me Use the Computer",
      grammarFocus: "Causative verbs — let / make / help + object + base verb",
      questions: [
        { sentence: "She let me ___ the computer.", correct: "use", grammar: "let me ___ (base verb)" },
        { sentence: "He made ___ run extra laps.", correct: "us", grammar: "made ___ (object)" },
        { sentence: "Please let ___ handle this.", correct: "me", grammar: "let ___ (object)" },
        { sentence: "She ___ the children clean up.", correct: "made", grammar: "She ___ (causative verb)" },
        { sentence: "He helped ___ move the furniture.", correct: "us", grammar: "helped ___ (object)" },
        { sentence: "Let ___ show you how it works.", correct: "me", grammar: "Let ___ (object)" },
        { sentence: "Don't ___ this chance go to waste.", correct: "let", grammar: "Don't ___ (causative verb)" },
        { sentence: "She helped me ___ the boxes.", correct: "carry", grammar: "helped me ___ (base verb)" },
        { sentence: "Don't ___ others influence your decisions.", correct: "let", grammar: "Don't ___ (causative verb)" },
        { sentence: "The documentary ___ me think about my life.", correct: "made", grammar: "___ me (causative past)" },
        { sentence: "The trainer ___ them exercise for two hours.", correct: "made", grammar: "___ them (causative past)" },
        { sentence: "Please ___ me know when you're ready.", correct: "let", grammar: "Please ___ me (causative)" },
        { sentence: "The experience ___ us grow as people.", correct: "helped", grammar: "___ us (causative past)" },
        { sentence: "She ___ me stay up late.", correct: "let", grammar: "She ___ me (causative past)" },
        { sentence: "I ___ my little brother use my phone.", correct: "let", grammar: "I ___ my brother (causative)" },
        { sentence: "The noise ___ me unable to sleep.", correct: "made", grammar: "___ me (causative past)" },
        { sentence: "He helped ___ understand the concept.", correct: "me", grammar: "helped ___ (object)" },
        { sentence: "She ___ him practice every day.", correct: "made", grammar: "She ___ him (causative past)" },
        { sentence: "The coach ___ the team work harder.", correct: "made", grammar: "___ the team (causative past)" },
        { sentence: "I ___ my brother watch the movie.", correct: "let", grammar: "I ___ brother (causative)" },
      ],
    },
    {
      week: 7,
      title: "Do You Know Where the Post Office Is?",
      grammarFocus: "Indirect questions — Do you know where/what/who/how/when + clause",
      questions: [
        { sentence: "Do you know where the post office ___?", correct: "is", grammar: "where ... ___ (indirect Q)" },
        { sentence: "I know how ___ use this.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "Can you tell me where ___ station is?", correct: "the", grammar: "where ___ (indirect Q)" },
        { sentence: "Do you know ___ the train leaves?", correct: "when", grammar: "___ (indirect Q word)" },
        { sentence: "I don't know what she ___.", correct: "said", grammar: "what she ___ (indirect Q)" },
        { sentence: "Can you tell me how long it ___?", correct: "takes", grammar: "how long it ___ (indirect Q)" },
        { sentence: "Do you know ___ she lives?", correct: "where", grammar: "___ (indirect Q word)" },
        { sentence: "I'm not sure ___ it is open.", correct: "if", grammar: "___ (indirect yes/no Q)" },
        { sentence: "Can you tell me what time it ___?", correct: "is", grammar: "what time it ___ (indirect Q)" },
        { sentence: "Do you know ___ this word means?", correct: "what", grammar: "___ (indirect Q word)" },
        { sentence: "I know who ___ her.", correct: "helped", grammar: "who ___ (indirect Q)" },
        { sentence: "Do you know ___ long the speech is?", correct: "how", grammar: "how ___ (indirect Q)" },
        { sentence: "I wonder ___ she passed the test.", correct: "if", grammar: "___ (indirect yes/no Q)" },
        { sentence: "Can you show me where ___ sit?", correct: "to", grammar: "where ___ (indirect Q + inf.)" },
        { sentence: "I know how ___ solve it.", correct: "to", grammar: "how ___ (indirect Q + inf.)" },
        { sentence: "Do you know ___ he said?", correct: "what", grammar: "___ (indirect Q word)" },
        { sentence: "I'm not sure ___ to believe.", correct: "what", grammar: "not sure ___ (indirect Q + inf.)" },
        { sentence: "Can you tell me ___ the library closes?", correct: "when", grammar: "___ (indirect Q word)" },
        { sentence: "I don't know ___ they came here.", correct: "why", grammar: "___ (indirect Q word)" },
        { sentence: "Do you know ___ I can buy a ticket?", correct: "where", grammar: "___ (indirect Q word)" },
      ],
    },
    {
      week: 8,
      title: "I Like a Place Called Guam",
      grammarFocus: "Reduced relative clauses — called / named / known as",
      questions: [
        { sentence: "I like a place ___ Guam.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a sport ___ kendo.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She reads a book ___ Harry Potter.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "Have you heard of a dish ___ okonomiyaki?", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a plant ___ pitcher plant.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "He plays a game ___ chess.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She visited a place ___ Shirakawa-go.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a festival ___ Obon.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She uses an app ___ Duolingo.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a bridge ___ Rainbow Bridge.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "They saw an animal ___ a capybara.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She taught me a technique ___ shadowing.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a city ___ Kanazawa.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "He told me about a method ___ pomodoro.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She bought a flower ___ a peony.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "I watched a show ___ Midnight Diner.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "There is a style of art ___ ukiyo-e.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "He visited a shrine ___ Fushimi Inari.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "She learned a dance ___ Bon Odori.", correct: "called", grammar: "___ (reduced relative clause)" },
        { sentence: "I tried a drink ___ amazake.", correct: "called", grammar: "___ (reduced relative clause)" },
      ],
    },
    {
      week: 9,
      title: "This Is a Movie That Won Many Awards",
      grammarFocus: "Relative pronouns — who (people) · that / which (things) — subject role",
      questions: [
        { sentence: "This is a movie ___ won many awards.", correct: "that", grammar: "___ won (subject relative)" },
        { sentence: "She is the person ___ helped me most.", correct: "who", grammar: "___ helped (subject relative)" },
        { sentence: "This is the song ___ made me cry.", correct: "that", grammar: "___ made (subject relative)" },
        { sentence: "He is the student ___ got full marks.", correct: "who", grammar: "___ got (subject relative)" },
        { sentence: "This is the app ___ helps you study.", correct: "that", grammar: "___ helps (subject relative)" },
        { sentence: "She is the teacher ___ inspired me.", correct: "who", grammar: "___ inspired (subject relative)" },
        { sentence: "This is the machine ___ saves energy.", correct: "that", grammar: "___ saves (subject relative)" },
        { sentence: "He is the player ___ scored the winning goal.", correct: "who", grammar: "___ scored (subject relative)" },
        { sentence: "This is the book ___ changed my life.", correct: "that", grammar: "___ changed (subject relative)" },
        { sentence: "She is the doctor ___ treated me.", correct: "who", grammar: "___ treated (subject relative)" },
        { sentence: "This is a problem ___ affects everyone.", correct: "that", grammar: "___ affects (subject relative)" },
        { sentence: "He is someone ___ always keeps promises.", correct: "who", grammar: "___ keeps (subject relative)" },
        { sentence: "This is the news ___ surprised everyone.", correct: "that", grammar: "___ surprised (subject relative)" },
        { sentence: "She is an author ___ writes mystery novels.", correct: "who", grammar: "___ writes (subject relative)" },
        { sentence: "This is the reason ___ I study English.", correct: "that", grammar: "___ I study (subject relative)" },
        { sentence: "He is the boy ___ lives next door.", correct: "who", grammar: "___ lives (subject relative)" },
        { sentence: "This is a dish ___ has a 500-year history.", correct: "that", grammar: "___ has (subject relative)" },
        { sentence: "She is the only person ___ knows the truth.", correct: "who", grammar: "___ knows (subject relative)" },
        { sentence: "This is a product ___ is popular worldwide.", correct: "that", grammar: "___ is (subject relative)" },
        { sentence: "He is someone ___ you can trust.", correct: "who", grammar: "___ you can trust (object relative)" },
      ],
    },
    {
      week: 10,
      title: "If I Were You, I Would Study More",
      grammarFocus: "Second conditional — If + past simple, would + base · I wish",
      questions: [
        { sentence: "If I ___ you, I would study more.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "If he ___ harder, he would succeed.", correct: "worked", grammar: "If he ___ (2nd cond.)" },
        { sentence: "I ___ be happy if I won the prize.", correct: "would", grammar: "I ___ be (2nd cond.)" },
        { sentence: "If she ___ time, she would travel.", correct: "had", grammar: "If she ___ (2nd cond.)" },
        { sentence: "What ___ you do if you could fly?", correct: "would", grammar: "___ you do (2nd cond. Q)" },
        { sentence: "If I ___ more money, I would save it.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ come if she were invited.", correct: "would", grammar: "She ___ (2nd cond.)" },
        { sentence: "If we ___ earlier, we would not be late.", correct: "left", grammar: "If we ___ (2nd cond.)" },
        { sentence: "I wish I ___ speak Japanese better.", correct: "could", grammar: "I wish I ___ (wish)" },
        { sentence: "She wishes she ___ more time.", correct: "had", grammar: "She wishes she ___ (wish)" },
        { sentence: "I wish he ___ here now.", correct: "were", grammar: "I wish he ___ (wish, be verb)" },
        { sentence: "He wishes he ___ swim.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "I wish it ___ not so cold.", correct: "were", grammar: "I wish it ___ (wish, be verb)" },
        { sentence: "If I ___ more time, I would read more.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "I wish I ___ the answer.", correct: "knew", grammar: "I wish I ___ (wish)" },
        { sentence: "She wishes her English ___ better.", correct: "were", grammar: "She wishes ___ (wish, be verb)" },
        { sentence: "He wishes he ___ afford a trip abroad.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "If I ___ more confident, I would speak up.", correct: "were", grammar: "If I ___ (2nd cond., be)" },
        { sentence: "I wish the test ___ not tomorrow.", correct: "were", grammar: "I wish it ___ (wish, be verb)" },
        { sentence: "___ you help me if I needed it?", correct: "Would", grammar: "___ you? (2nd cond. Q)" },
      ],
    },
    {
      week: 11,
      title: "Present Perfect — All Uses Review",
      grammarFocus: "Have / Has + past participle — experience / completion / duration / news",
      questions: [
        { sentence: "She ___ worked here for ten years.", correct: "has", grammar: "She ___ worked (have/has)" },
        { sentence: "Have they finished ___?", correct: "yet", grammar: "Have they ... ___? (yet)" },
        { sentence: "I ___ never tried octopus.", correct: "have", grammar: "I ___ never (have/has)" },
        { sentence: "He has ___ won three awards.", correct: "already", grammar: "has ___ (already)" },
        { sentence: "___ you ever lived abroad?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "She has been studying ___ early morning.", correct: "since", grammar: "___ (since)" },
        { sentence: "I have been working ___ 9 a.m.", correct: "since", grammar: "___ (since)" },
        { sentence: "Has he ever ___ abroad?", correct: "traveled", grammar: "Has he ever ___ (past part.)" },
        { sentence: "We have ___ living in Osaka for 5 years.", correct: "been", grammar: "have ___ living (been)" },
        { sentence: "She has just ___ the report.", correct: "finished", grammar: "has just ___ (past part.)" },
        { sentence: "How long ___ you been waiting?", correct: "have", grammar: "___ you been? (Q)" },
        { sentence: "He ___ not eaten since morning.", correct: "has", grammar: "He ___ not (has/have)" },
        { sentence: "I have already ___ that book.", correct: "read", grammar: "have already ___ (past part.)" },
        { sentence: "___ she ever visited the US?", correct: "Has", grammar: "___ she ever? (Q)" },
        { sentence: "We ___ known each other for 20 years.", correct: "have", grammar: "We ___ known (have/has)" },
        { sentence: "She has been studying ___ three hours.", correct: "for", grammar: "___ (for)" },
        { sentence: "Have you ___ solved the problem?", correct: "already", grammar: "Have you ___ (already)" },
        { sentence: "He ___ not found the answer yet.", correct: "has", grammar: "He ___ not (has/have)" },
        { sentence: "I have just ___ a letter from her.", correct: "received", grammar: "have just ___ (past part.)" },
        { sentence: "___ they been waiting long?", correct: "Have", grammar: "___ they been? (Q)" },
      ],
    },
    {
      week: 12,
      title: "SVOC — Extended Practice",
      grammarFocus: "Make / Find / Keep / Leave / Call / Name + object + complement",
      questions: [
        { sentence: "She ___ the task easy.", correct: "found", grammar: "She ___ (SVOC past)" },
        { sentence: "Good sleep ___ you energetic.", correct: "keeps", grammar: "___ you (SVOC)" },
        { sentence: "The journey ___ us exhausted.", correct: "left", grammar: "___ us (SVOC past)" },
        { sentence: "I ___ this rule unfair.", correct: "find", grammar: "I ___ (SVOC)" },
        { sentence: "Music ___ her calm.", correct: "keeps", grammar: "___ her (SVOC)" },
        { sentence: "Studying ___ you focused.", correct: "keeps", grammar: "___ you (SVOC)" },
        { sentence: "Her friends ___ her Mimi.", correct: "call", grammar: "___ her (SVOC)" },
        { sentence: "They ___ him the best player.", correct: "called", grammar: "___ him (SVOC past)" },
        { sentence: "The cold air ___ me awake.", correct: "kept", grammar: "___ me (SVOC past)" },
        { sentence: "I ___ the experience priceless.", correct: "found", grammar: "I ___ (SVOC past)" },
        { sentence: "Hard work ___ you strong.", correct: "makes", grammar: "___ you (SVOC)" },
        { sentence: "The sad movie ___ me emotional.", correct: "made", grammar: "___ me (SVOC past)" },
        { sentence: "She ___ the problem impossible.", correct: "found", grammar: "She ___ (SVOC past)" },
        { sentence: "They ___ it a success.", correct: "called", grammar: "___ it (SVOC past)" },
        { sentence: "The news ___ us confused.", correct: "left", grammar: "___ us (SVOC past)" },
        { sentence: "Exercise ___ your mind clear.", correct: "keeps", grammar: "___ your mind (SVOC)" },
        { sentence: "I ___ the movie boring.", correct: "found", grammar: "I ___ (SVOC past)" },
        { sentence: "The coach ___ the team motivated.", correct: "kept", grammar: "___ the team (SVOC past)" },
        { sentence: "She ___ the idea crazy.", correct: "called", grammar: "She ___ (SVOC past)" },
        { sentence: "Good music ___ me relaxed.", correct: "makes", grammar: "___ me (SVOC)" },
      ],
    },
    {
      week: 13,
      title: "Passive Voice — Review",
      grammarFocus: "Is / Are / Was / Were + past participle · passive across tenses",
      questions: [
        { sentence: "This dish ___ prepared fresh each morning.", correct: "is", grammar: "___ prepared (passive pres.)" },
        { sentence: "The novel ___ written 100 years ago.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "Many lives ___ saved by the new medicine.", correct: "were", grammar: "___ saved (passive past)" },
        { sentence: "English ___ taught in schools worldwide.", correct: "is", grammar: "___ taught (passive pres.)" },
        { sentence: "The results ___ announced last week.", correct: "were", grammar: "___ announced (passive past)" },
        { sentence: "The project ___ completed on time.", correct: "was", grammar: "___ completed (passive past)" },
        { sentence: "New laws ___ passed by the government.", correct: "are", grammar: "___ passed (passive pres.)" },
        { sentence: "This product ___ used by millions.", correct: "is", grammar: "___ used (passive pres.)" },
        { sentence: "The prize ___ given to the best team.", correct: "was", grammar: "___ given (passive past)" },
        { sentence: "Traditional crafts ___ handed down for centuries.", correct: "have been", grammar: "___ handed down (passive perf.)" },
        { sentence: "The song ___ performed beautifully.", correct: "was", grammar: "___ performed (passive past)" },
        { sentence: "New products ___ released every season.", correct: "are", grammar: "___ released (passive pres.)" },
        { sentence: "The temple ___ visited by many tourists.", correct: "is", grammar: "___ visited (passive pres.)" },
        { sentence: "All the food ___ eaten by the end of the party.", correct: "was", grammar: "___ eaten (passive past)" },
        { sentence: "Many forests ___ destroyed each year.", correct: "are", grammar: "___ destroyed (passive pres.)" },
        { sentence: "This bridge ___ built by local people.", correct: "was", grammar: "___ built (passive past)" },
        { sentence: "The problem ___ solved by a student.", correct: "was", grammar: "___ solved (passive past)" },
        { sentence: "The ceremony ___ held annually.", correct: "is", grammar: "___ held (passive pres.)" },
        { sentence: "Her artwork ___ admired by everyone.", correct: "is", grammar: "___ admired (passive pres.)" },
        { sentence: "The letter ___ read by the whole class.", correct: "was", grammar: "___ read (passive past)" },
      ],
    },
    {
      week: 14,
      title: "Infinitives in Complex Sentences",
      grammarFocus: "It is ... for ... to · want/ask/tell + someone + to · seem/appear + to",
      questions: [
        { sentence: "It is vital ___ us to act quickly.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "I want you ___ understand my point.", correct: "to", grammar: "want you ___ (infinitive)" },
        { sentence: "She needs him ___ help her.", correct: "to", grammar: "needs him ___ (infinitive)" },
        { sentence: "It is natural ___ children to make mistakes.", correct: "for", grammar: "It is ... ___ children to ..." },
        { sentence: "He asked me ___ speak at the event.", correct: "to", grammar: "asked me ___ (infinitive)" },
        { sentence: "She encouraged me ___ keep going.", correct: "to", grammar: "encouraged me ___ (infinitive)" },
        { sentence: "It is rare ___ see snow here.", correct: "to", grammar: "It is rare ___ ..." },
        { sentence: "I expect the project ___ finish by noon.", correct: "to", grammar: "expect ___ to (infinitive)" },
        { sentence: "It is dangerous ___ walk alone at night.", correct: "to", grammar: "It is dangerous ___ ..." },
        { sentence: "She wants me ___ read the report.", correct: "to", grammar: "wants me ___ (infinitive)" },
        { sentence: "It was nice ___ you to help us.", correct: "of", grammar: "It was nice ___ you to (of)" },
        { sentence: "I am determined ___ succeed.", correct: "to", grammar: "___ to (infinitive)" },
        { sentence: "She seems ___ be happy.", correct: "to", grammar: "seems ___ (infinitive)" },
        { sentence: "He appears ___ understand.", correct: "to", grammar: "appears ___ (infinitive)" },
        { sentence: "It is unusual ___ see him so quiet.", correct: "to", grammar: "It is unusual ___ ..." },
        { sentence: "I find it difficult ___ concentrate.", correct: "to", grammar: "find it ... ___ (infinitive)" },
        { sentence: "She managed ___ finish the report.", correct: "to", grammar: "managed ___ (infinitive)" },
        { sentence: "He decided ___ change his approach.", correct: "to", grammar: "decided ___ (infinitive)" },
        { sentence: "It is important for everyone ___ participate.", correct: "to", grammar: "for everyone ___ (infinitive)" },
        { sentence: "I encourage you ___ try new things.", correct: "to", grammar: "encourage you ___ (infinitive)" },
      ],
    },
    {
      week: 15,
      title: "Causatives — Extended Practice",
      grammarFocus: "Make / Let / Help + object + base verb — extended contexts",
      questions: [
        { sentence: "Let ___ try again.", correct: "me", grammar: "Let ___ (object)" },
        { sentence: "She ___ the students leave early.", correct: "let", grammar: "She ___ (causative verb)" },
        { sentence: "I made ___ work overtime.", correct: "him", grammar: "made ___ (object)" },
        { sentence: "Please let ___ handle this.", correct: "us", grammar: "let ___ (object)" },
        { sentence: "The coach ___ the team run extra laps.", correct: "made", grammar: "___ the team (causative)" },
        { sentence: "Let me ___ you how it works.", correct: "show", grammar: "Let me ___ (base verb)" },
        { sentence: "Don't let ___ the opportunity pass.", correct: "it", grammar: "Don't let ___ (object)" },
        { sentence: "She helped me ___ the concept.", correct: "understand", grammar: "helped me ___ (base verb)" },
        { sentence: "Don't ___ others control you.", correct: "let", grammar: "Don't ___ (causative verb)" },
        { sentence: "The story ___ me think about kindness.", correct: "made", grammar: "___ me (causative past)" },
        { sentence: "Please ___ me know if you need help.", correct: "let", grammar: "Please ___ me (causative)" },
        { sentence: "The experience ___ us stronger.", correct: "made", grammar: "___ us (causative past + SVOC)" },
        { sentence: "She ___ him practice the speech.", correct: "made", grammar: "She ___ him (causative)" },
        { sentence: "He helped ___ carry the heavy boxes.", correct: "her", grammar: "helped ___ (object)" },
        { sentence: "The teacher ___ us ask questions anytime.", correct: "let", grammar: "___ us (causative past)" },
        { sentence: "I'll ___ you know when it's ready.", correct: "let", grammar: "I'll ___ you (causative)" },
        { sentence: "The challenge ___ them grow.", correct: "helped", grammar: "___ them (causative past)" },
        { sentence: "She ___ her son study at his own pace.", correct: "let", grammar: "She ___ her son (causative)" },
        { sentence: "The accident ___ us more careful.", correct: "made", grammar: "___ us (causative past + SVOC)" },
        { sentence: "He helped ___ with the project.", correct: "me", grammar: "helped ___ (object)" },
      ],
    },
    {
      week: 16,
      title: "Relative Pronouns — Subject Clauses",
      grammarFocus: "Who (people) / That / Which (things) — subject position",
      questions: [
        { sentence: "She is the woman ___ started this company.", correct: "who", grammar: "___ started (subject rel.)" },
        { sentence: "This is the book ___ won the award.", correct: "that", grammar: "___ won (subject rel.)" },
        { sentence: "He is the only person ___ knows the truth.", correct: "who", grammar: "___ knows (subject rel.)" },
        { sentence: "I found a bag ___ belongs to you.", correct: "that", grammar: "___ belongs (subject rel.)" },
        { sentence: "This is the app ___ helps you study.", correct: "that", grammar: "___ helps (subject rel.)" },
        { sentence: "She is the teacher ___ helped me most.", correct: "who", grammar: "___ helped (subject rel.)" },
        { sentence: "I know a scientist ___ studies the ocean.", correct: "who", grammar: "___ studies (subject rel.)" },
        { sentence: "This is a machine ___ saves energy.", correct: "that", grammar: "___ saves (subject rel.)" },
        { sentence: "He is the student ___ got the highest score.", correct: "who", grammar: "___ got (subject rel.)" },
        { sentence: "This is the movie ___ made me cry.", correct: "that", grammar: "___ made (subject rel.)" },
        { sentence: "She is a person ___ always keeps her promises.", correct: "who", grammar: "___ keeps (subject rel.)" },
        { sentence: "This is a product ___ is popular worldwide.", correct: "that", grammar: "___ is (subject rel.)" },
        { sentence: "He is someone ___ you can trust.", correct: "who", grammar: "___ you can trust (rel.)" },
        { sentence: "This is the news ___ surprised everyone.", correct: "that", grammar: "___ surprised (subject rel.)" },
        { sentence: "She is the athlete ___ won three gold medals.", correct: "who", grammar: "___ won (subject rel.)" },
        { sentence: "This is a dish ___ has a 500-year history.", correct: "that", grammar: "___ has (subject rel.)" },
        { sentence: "He is the only student ___ finished early.", correct: "who", grammar: "___ finished (subject rel.)" },
        { sentence: "These are the questions ___ most students got wrong.", correct: "that", grammar: "___ got (subject rel.)" },
        { sentence: "She is the author ___ writes mystery novels.", correct: "who", grammar: "___ writes (subject rel.)" },
        { sentence: "This is the reason ___ I came here.", correct: "that", grammar: "___ I came (object rel.)" },
      ],
    },
    {
      week: 17,
      title: "Relative Pronouns — Object Clauses",
      grammarFocus: "Who / That — object position (the person who I trust / the book that I read)",
      questions: [
        { sentence: "This is the book ___ I recommended.", correct: "that", grammar: "___ I recommended (object rel.)" },
        { sentence: "She is the person ___ I trust most.", correct: "who", grammar: "___ I trust (object rel.)" },
        { sentence: "This is the movie ___ we watched last night.", correct: "that", grammar: "___ we watched (object rel.)" },
        { sentence: "Is this the bag ___ you lost?", correct: "that", grammar: "___ you lost (object rel.)" },
        { sentence: "She is the artist ___ I most admire.", correct: "who", grammar: "___ I admire (object rel.)" },
        { sentence: "This is the answer ___ I was looking for.", correct: "that", grammar: "___ I was looking for (obj.)" },
        { sentence: "This is the restaurant ___ I love.", correct: "that", grammar: "___ I love (object rel.)" },
        { sentence: "Is this the song ___ you wrote?", correct: "that", grammar: "___ you wrote (object rel.)" },
        { sentence: "She is the teacher ___ students respect most.", correct: "who", grammar: "___ students respect (obj.)" },
        { sentence: "This is the idea ___ I had in mind.", correct: "that", grammar: "___ I had (object rel.)" },
        { sentence: "He is the person ___ I told you about.", correct: "who", grammar: "___ I told you about (obj.)" },
        { sentence: "This is the room ___ we cleaned.", correct: "that", grammar: "___ we cleaned (object rel.)" },
        { sentence: "She is the only friend ___ I can talk to.", correct: "who", grammar: "___ I can talk to (obj.)" },
        { sentence: "This is the information ___ I needed.", correct: "that", grammar: "___ I needed (object rel.)" },
        { sentence: "He is someone ___ I have known for years.", correct: "who", grammar: "___ I have known (obj.)" },
        { sentence: "Is this the place ___ you mentioned?", correct: "that", grammar: "___ you mentioned (obj.)" },
        { sentence: "She is the nurse ___ took care of me.", correct: "who", grammar: "___ took care (subject rel.)" },
        { sentence: "This is the approach ___ we tried.", correct: "that", grammar: "___ we tried (object rel.)" },
        { sentence: "He is the man ___ she married.", correct: "who", grammar: "___ she married (object rel.)" },
        { sentence: "Many things ___ we see are not real.", correct: "that", grammar: "___ we see (object rel.)" },
      ],
    },
    {
      week: 18,
      title: "Second Conditional — Extended",
      grammarFocus: "If + past simple, would + base verb — varied contexts",
      questions: [
        { sentence: "If I ___ a teacher, I would not give too much homework.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ travel more if she had the time.", correct: "would", grammar: "She ___ (2nd cond.)" },
        { sentence: "If he ___ harder, he would achieve more.", correct: "worked", grammar: "If he ___ (2nd cond.)" },
        { sentence: "I ___ be so happy if I won the lottery.", correct: "would", grammar: "I ___ be (2nd cond.)" },
        { sentence: "If she ___ here, she would help us.", correct: "were", grammar: "If she ___ (2nd cond., be)" },
        { sentence: "What ___ you do if you could fly?", correct: "would", grammar: "___ you do? (2nd cond. Q)" },
        { sentence: "If I ___ more money, I would save it.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "He ___ not come even if he were invited.", correct: "would", grammar: "He ___ not (2nd cond.)" },
        { sentence: "If we ___ earlier, we would not be late.", correct: "left", grammar: "If we ___ (2nd cond.)" },
        { sentence: "She ___ be a great leader if she tried.", correct: "would", grammar: "She ___ (2nd cond.)" },
        { sentence: "If the weather ___ better, we would go.", correct: "were", grammar: "If the weather ___ (2nd cond.)" },
        { sentence: "I ___ visit Japan again if I could.", correct: "would", grammar: "I ___ (2nd cond.)" },
        { sentence: "If he ___ you, he would apologize.", correct: "were", grammar: "If he ___ (2nd cond., be)" },
        { sentence: "What ___ she say if she knew the truth?", correct: "would", grammar: "___ she say? (2nd cond. Q)" },
        { sentence: "If I ___ the answer, I would tell you.", correct: "knew", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ not lie even if it helped her.", correct: "would", grammar: "She ___ not (2nd cond.)" },
        { sentence: "If we ___ the opportunity, we should take it.", correct: "had", grammar: "If we ___ (2nd cond.)" },
        { sentence: "He ___ be famous if he kept singing.", correct: "would", grammar: "He ___ be (2nd cond.)" },
        { sentence: "If I ___ more time, I'd study another language.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "___ you help me if I needed it?", correct: "Would", grammar: "___ you? (2nd cond. Q)" },
      ],
    },
    {
      week: 19,
      title: "I Wish I Could Help — Extended",
      grammarFocus: "I wish + past simple / could — expressing unreal wishes",
      questions: [
        { sentence: "I wish I ___ speak Japanese perfectly.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "She wishes she ___ more time.", correct: "had", grammar: "She wishes she ___ (wish)" },
        { sentence: "I wish he ___ here now.", correct: "were", grammar: "I wish he ___ (wish, be verb)" },
        { sentence: "He wishes he ___ swim.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "I wish it ___ not so cold.", correct: "were", grammar: "I wish it ___ (wish, be verb)" },
        { sentence: "She wishes she ___ a better singer.", correct: "were", grammar: "She wishes she ___ (wish)" },
        { sentence: "I wish we ___ live closer to school.", correct: "could", grammar: "I wish we ___ (wish + ability)" },
        { sentence: "He wishes he ___ more confident.", correct: "were", grammar: "He wishes he ___ (wish, be verb)" },
        { sentence: "I wish I ___ the answer.", correct: "knew", grammar: "I wish I ___ (wish)" },
        { sentence: "She wishes her English ___ better.", correct: "were", grammar: "She wishes ___ (wish, be verb)" },
        { sentence: "He wishes he ___ afford a trip abroad.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "I wish the test ___ not tomorrow.", correct: "were", grammar: "I wish ___ not (wish, be verb)" },
        { sentence: "She wishes she ___ fly like a bird.", correct: "could", grammar: "She wishes she ___ (wish + ability)" },
        { sentence: "I wish I ___ go with them.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "He wishes he ___ in the school team.", correct: "were", grammar: "He wishes he ___ (wish, be verb)" },
        { sentence: "I wish we ___ more time together.", correct: "had", grammar: "I wish we ___ (wish)" },
        { sentence: "She wishes she ___ the star of the show.", correct: "were", grammar: "She wishes she ___ (wish, be verb)" },
        { sentence: "I wish she ___ here to see this.", correct: "were", grammar: "I wish she ___ (wish, be verb)" },
        { sentence: "He wishes he ___ play any musical instrument.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "I wish I ___ the right thing to say.", correct: "knew", grammar: "I wish I ___ (wish)" },
      ],
    },
    {
      week: 20,
      title: "Reported Speech — Statements",
      grammarFocus: "Said that / Told + person + that — reporting what someone said",
      questions: [
        { sentence: "She said ___ she was tired.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told me ___ he would be late.", correct: "that", grammar: "told me ___ (conjunction)" },
        { sentence: "I said ___ I didn't know.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "She told me ___ she had finished.", correct: "that", grammar: "told me ___ (conjunction)" },
        { sentence: "He said ___ it was delicious.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "She told him ___ she was happy.", correct: "that", grammar: "told him ___ (conjunction)" },
        { sentence: "I said ___ I would help.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told us ___ he was leaving.", correct: "that", grammar: "told us ___ (conjunction)" },
        { sentence: "She said ___ she loved the movie.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told me ___ he understood.", correct: "that", grammar: "told me ___ (conjunction)" },
        { sentence: "I said ___ I was sorry.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "She told them ___ she would come.", correct: "that", grammar: "told them ___ (conjunction)" },
        { sentence: "He said ___ the weather was nice.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "I told her ___ I had forgotten.", correct: "that", grammar: "told her ___ (conjunction)" },
        { sentence: "She said ___ she had lived there for years.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told us ___ he couldn't come.", correct: "that", grammar: "told us ___ (conjunction)" },
        { sentence: "She said ___ it was not her fault.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "I told him ___ the exam was tomorrow.", correct: "that", grammar: "told him ___ (conjunction)" },
        { sentence: "He said ___ he was looking for work.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "She told me ___ she had already left.", correct: "that", grammar: "told me ___ (conjunction)" },
      ],
    },
    {
      week: 21,
      title: "Reported Questions — If / Whether / Wh-words",
      grammarFocus: "Asked if/whether (yes/no) · asked what/where/when/why/how (Wh-)",
      questions: [
        { sentence: "She asked ___ I liked sushi.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "He asked me where ___ was going.", correct: "I", grammar: "where ___ was going (reported Q)" },
        { sentence: "I asked her ___ she was feeling well.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "She asked ___ they had finished.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "He asked me what ___ thought.", correct: "I", grammar: "what ___ thought (reported Q)" },
        { sentence: "I asked her ___ she could help.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "She asked ___ I had eaten lunch.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "He asked me ___ I was doing.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "I asked her where ___ was going.", correct: "she", grammar: "where ___ (reported Q)" },
        { sentence: "She asked ___ the answer was correct.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "I asked ___ I had been studying long.", correct: "how", grammar: "___ (reported Wh- Q)" },
        { sentence: "He asked me ___ I would come.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "She asked ___ had happened.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "He asked me ___ I knew the answer.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "I asked her ___ she was crying.", correct: "why", grammar: "___ (reported Wh- Q)" },
        { sentence: "She asked ___ he had been waiting long.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "He asked ___ I had seen the movie.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "She asked me ___ I lived.", correct: "where", grammar: "___ (reported Wh- Q)" },
        { sentence: "I asked him ___ he had finished.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "He asked me ___ I was leaving so soon.", correct: "why", grammar: "___ (reported Wh- Q)" },
      ],
    },
    {
      week: 22,
      title: "Passive with Modals",
      grammarFocus: "Should be / Must be / Can be / Will be + past participle",
      questions: [
        { sentence: "This work ___ be finished by noon.", correct: "must", grammar: "___ be (modal + passive)" },
        { sentence: "The problem ___ be solved easily.", correct: "can", grammar: "___ be (modal + passive)" },
        { sentence: "This letter ___ be written in English.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "The results ___ be announced tomorrow.", correct: "will", grammar: "___ be (modal + passive)" },
        { sentence: "These rules ___ be followed.", correct: "must", grammar: "___ be (modal + passive)" },
        { sentence: "This issue ___ not be ignored.", correct: "should", grammar: "___ not be (modal + passive)" },
        { sentence: "The medicine ___ be taken after meals.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "The form ___ be submitted by Friday.", correct: "must", grammar: "___ be (modal + passive)" },
        { sentence: "This task ___ not be done by one person.", correct: "can", grammar: "___ be (modal + passive)" },
        { sentence: "The package ___ be delivered tomorrow.", correct: "will", grammar: "___ be (modal + passive)" },
        { sentence: "This topic ___ be discussed carefully.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "All students ___ be treated fairly.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "The data ___ be protected.", correct: "must", grammar: "___ be (modal + passive)" },
        { sentence: "The event ___ be canceled if it rains.", correct: "will", grammar: "___ be (modal + passive)" },
        { sentence: "This book ___ be read by everyone.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "The information ___ not be shared.", correct: "must", grammar: "___ not be (modal + passive)" },
        { sentence: "New medicines ___ be developed quickly.", correct: "must", grammar: "___ be (modal + passive)" },
        { sentence: "These mistakes ___ not be repeated.", correct: "should", grammar: "___ not be (modal + passive)" },
        { sentence: "The match ___ be played on Saturday.", correct: "will", grammar: "___ be (modal + passive)" },
        { sentence: "All evidence ___ be examined carefully.", correct: "must", grammar: "___ be (modal + passive)" },
      ],
    },
    {
      week: 23,
      title: "Although / Even Though / Despite",
      grammarFocus: "Concession — Although/Even though + clause · Despite + noun/gerund",
      questions: [
        { sentence: "___ she was tired, she kept working.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "He passed the test ___ it was difficult.", correct: "although", grammar: "... ___ (concession clause)" },
        { sentence: "___ they tried hard, they lost.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "She went out ___ the rain.", correct: "despite", grammar: "___ (despite + noun)" },
        { sentence: "He was happy ___ failing the test.", correct: "despite", grammar: "___ (despite + gerund)" },
        { sentence: "___ the weather was bad, we had fun.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "She kept smiling ___ she was upset.", correct: "although", grammar: "... ___ (concession clause)" },
        { sentence: "___ working hard, he didn't succeed.", correct: "Despite", grammar: "___ (despite + gerund)" },
        { sentence: "She helped him ___ she was busy.", correct: "although", grammar: "... ___ (concession clause)" },
        { sentence: "___ all the difficulties, they finished.", correct: "Despite", grammar: "___ (despite + noun)" },
        { sentence: "___ it was cold, she wore a T-shirt.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "He arrived on time ___ the traffic.", correct: "despite", grammar: "___ (despite + noun)" },
        { sentence: "___ she didn't study much, she passed.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "She stayed positive ___ the bad news.", correct: "despite", grammar: "___ (despite + noun)" },
        { sentence: "___ he doesn't like sports, he plays soccer.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "___ the long journey, they arrived safely.", correct: "Despite", grammar: "___ (despite + noun)" },
        { sentence: "She speaks well ___ being nervous.", correct: "despite", grammar: "___ (despite + gerund)" },
        { sentence: "___ it was late, he kept studying.", correct: "Although", grammar: "___ (concession)" },
        { sentence: "___ the noise, she slept well.", correct: "Despite", grammar: "___ (despite + noun)" },
        { sentence: "He remained calm ___ the pressure.", correct: "despite", grammar: "___ (despite + noun)" },
      ],
    },
    {
      week: 24,
      title: "In Order to / So That",
      grammarFocus: "Purpose — in order to + verb · so that + subject + can/could",
      questions: [
        { sentence: "She studied hard ___ order to pass.", correct: "in", grammar: "___ order to (purpose)" },
        { sentence: "He saved money in order ___ buy a car.", correct: "to", grammar: "in order ___ (infinitive)" },
        { sentence: "I practice every day ___ order to improve.", correct: "in", grammar: "___ order to (purpose)" },
        { sentence: "She went early in order ___ get a seat.", correct: "to", grammar: "in order ___ (infinitive)" },
        { sentence: "He studied medicine ___ order to help people.", correct: "in", grammar: "___ order to (purpose)" },
        { sentence: "In order to succeed, you ___ work hard.", correct: "must", grammar: "In order to ... you ___ ..." },
        { sentence: "She writes notes ___ order to remember.", correct: "in", grammar: "___ order to (purpose)" },
        { sentence: "He exercises daily in order ___ stay healthy.", correct: "to", grammar: "in order ___ (infinitive)" },
        { sentence: "I read widely in order ___ learn more.", correct: "to", grammar: "in order ___ (infinitive)" },
        { sentence: "She joined the club in order ___ make friends.", correct: "to", grammar: "in order ___ (infinitive)" },
        { sentence: "She speaks clearly ___ that everyone can understand.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "He wrote it down ___ that he wouldn't forget.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "I'll explain it again ___ that you understand.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "She saved the file ___ that she could use it later.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "He practiced ___ that he could play in the concert.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "She repeated it ___ that everyone heard.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "I'll call ahead ___ that they know we're coming.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "He worked overtime ___ that the project could finish.", correct: "so", grammar: "___ that (purpose)" },
        { sentence: "___ that she doesn't forget, she sets an alarm.", correct: "So", grammar: "___ that (purpose, opener)" },
        { sentence: "She set a reminder ___ that she wouldn't miss the meeting.", correct: "so", grammar: "___ that (purpose)" },
      ],
    },
    {
      week: 25,
      title: "However / On the Other Hand / While",
      grammarFocus: "Contrast linking — However · On the other hand · While / Whereas",
      questions: [
        { sentence: "She is very smart. ___, she often makes mistakes.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "I like hiking. ___, I hate getting lost.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She studies hard. ___, her test scores are low.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He is kind. ___ the other hand, he can be strict.", correct: "On", grammar: "___ the other hand" },
        { sentence: "I love summer. ___, I hate the heat.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She is energetic. ___ the other hand, he is quiet.", correct: "On", grammar: "___ the other hand" },
        { sentence: "The food was delicious. ___, the service was terrible.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She is shy. ___, she's confident on stage.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He is good at math. ___ the other hand, he struggles with languages.", correct: "On", grammar: "___ the other hand" },
        { sentence: "She wants to become a doctor. ___, she isn't good at science.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He loves traveling. ___, he hates long flights.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She eats healthy food. ___ the other hand, she never exercises.", correct: "On", grammar: "___ the other hand" },
        { sentence: "The plan sounds good. ___, it has some problems.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He is very organized. ___, he always finishes late.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "The price is high. ___ the other hand, the quality is excellent.", correct: "On", grammar: "___ the other hand" },
        { sentence: "She won the competition. ___, she wasn't satisfied.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "He is confident. ___ the other hand, she is hesitant.", correct: "On", grammar: "___ the other hand" },
        { sentence: "The movie got bad reviews. ___, it made a lot of money.", correct: "However", grammar: "___ (contrast)" },
        { sentence: "She is friendly. ___ the other hand, he is reserved.", correct: "On", grammar: "___ the other hand" },
        { sentence: "The task looked simple. ___, it was very challenging.", correct: "However", grammar: "___ (contrast)" },
      ],
    },
    {
      week: 26,
      title: "In Addition / Furthermore / Moreover / Also",
      grammarFocus: "Addition linking — In addition · Furthermore · Moreover · Also",
      questions: [
        { sentence: "She is smart. ___, she is kind.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "He studies hard. ___, he exercises daily.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "The hotel is comfortable. ___, it has a great view.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "She can sing. ___, she can dance.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "He is skilled. ___, he is hardworking.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "The plan saves money. ___, it saves time.", correct: "Furthermore,", grammar: "___ (addition)" },
        { sentence: "She finished early. ___, she helped others.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "He speaks Japanese. ___, he understands Chinese.", correct: "Furthermore,", grammar: "___ (addition)" },
        { sentence: "The food was cheap. ___, it was delicious.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "She studies every day. ___, she attends extra classes.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "He exercises daily. ___, he watches his diet.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "The project was successful. ___, it came in under budget.", correct: "Furthermore,", grammar: "___ (addition)" },
        { sentence: "She is creative. ___, she is very practical.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "He is polite. ___, he is generous.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "The book was informative. ___, it was well written.", correct: "Furthermore,", grammar: "___ (addition)" },
        { sentence: "I enjoy cooking. ___, I enjoy baking.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "She can speak English well. ___, she can write it well.", correct: "Furthermore,", grammar: "___ (addition)" },
        { sentence: "He helped me study. ___, he tutored me weekly.", correct: "In addition,", grammar: "___ (addition)" },
        { sentence: "She is talented. ___, she has years of experience.", correct: "Moreover", grammar: "___ (addition)" },
        { sentence: "The results are promising. ___, they are consistent.", correct: "Furthermore,", grammar: "___ (addition)" },
      ],
    },
    {
      week: 27,
      title: "Review — Present Perfect All Forms",
      grammarFocus: "Have/Has + past participle — all forms: experience / just-yet / for-since",
      questions: [
        { sentence: "She ___ worked here for ten years.", correct: "has", grammar: "She ___ worked (have/has)" },
        { sentence: "Have they finished ___?", correct: "yet", grammar: "Have they ... ___? (yet)" },
        { sentence: "I ___ never tried octopus.", correct: "have", grammar: "I ___ never (have/has)" },
        { sentence: "He has ___ won three awards.", correct: "already", grammar: "has ___ (already)" },
        { sentence: "___ you ever lived abroad?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "She has been studying ___ early morning.", correct: "since", grammar: "___ (since)" },
        { sentence: "I have been working ___ 9 a.m.", correct: "since", grammar: "___ (since)" },
        { sentence: "Has he ever ___ abroad?", correct: "traveled", grammar: "Has he ever ___ (past part.)" },
        { sentence: "We have ___ living in Osaka for 5 years.", correct: "been", grammar: "have ___ living (been)" },
        { sentence: "She has just ___ the report.", correct: "finished", grammar: "has just ___ (past part.)" },
        { sentence: "How long ___ you been waiting?", correct: "have", grammar: "___ you been? (Q)" },
        { sentence: "He ___ not eaten since morning.", correct: "has", grammar: "He ___ not (has/have)" },
        { sentence: "I have already ___ that book.", correct: "read", grammar: "have already ___ (past part.)" },
        { sentence: "___ she ever visited the US?", correct: "Has", grammar: "___ she ever? (Q)" },
        { sentence: "We ___ known each other for 20 years.", correct: "have", grammar: "We ___ known (have/has)" },
        { sentence: "She has been studying ___ three hours.", correct: "for", grammar: "___ (for)" },
        { sentence: "Have you ___ solved the problem?", correct: "already", grammar: "Have you ___ (already)" },
        { sentence: "He ___ not found the answer yet.", correct: "has", grammar: "He ___ not (has/have)" },
        { sentence: "I have just ___ a letter from her.", correct: "received", grammar: "have just ___ (past part.)" },
        { sentence: "___ they been waiting long?", correct: "Have", grammar: "___ they been? (Q)" },
      ],
    },
    {
      week: 28,
      title: "Review — Relative Clauses",
      grammarFocus: "Who / That / Which / Called — all relative clause types",
      questions: [
        { sentence: "She is the person ___ saved my life.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the car ___ I bought.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "He is someone ___ you can rely on.", correct: "who", grammar: "___ (object rel.)" },
        { sentence: "This is the movie ___ everyone is talking about.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "She is the doctor ___ treated me.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the problem ___ we need to solve.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "He is the man ___ invented this product.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "The book ___ I read changed my view.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "She is the athlete ___ broke the world record.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the restaurant ___ I recommended.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "He is someone ___ always keeps promises.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the story ___ inspired me.", correct: "that", grammar: "___ (subject rel.)" },
        { sentence: "She is the teacher ___ made me love English.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the letter ___ she wrote to me.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "He is the one ___ always arrives late.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "This is the park ___ we used to play in.", correct: "that", grammar: "___ (object rel.)" },
        { sentence: "She is the leader ___ everyone trusts.", correct: "who", grammar: "___ (object rel.)" },
        { sentence: "This is the news ___ surprised everyone.", correct: "that", grammar: "___ (subject rel.)" },
        { sentence: "He is the student ___ scored highest.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "There is a dish ___ okonomiyaki.", correct: "called", grammar: "___ (reduced rel. clause)" },
      ],
    },
    {
      week: 29,
      title: "Review — Conditionals",
      grammarFocus: "Second conditional (If + past, would) · I wish — mixed review",
      questions: [
        { sentence: "I wish I ___ more time.", correct: "had", grammar: "I wish I ___ (wish)" },
        { sentence: "If I ___ you, I would apologize.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ come if she could.", correct: "would", grammar: "She ___ (2nd cond.)" },
        { sentence: "I wish he ___ here with us.", correct: "were", grammar: "I wish he ___ (wish, be verb)" },
        { sentence: "If they ___ harder, they would win.", correct: "worked", grammar: "If they ___ (2nd cond.)" },
        { sentence: "He wishes he ___ speak Chinese.", correct: "could", grammar: "He wishes he ___ (wish + ability)" },
        { sentence: "If I ___ the chance, I would take it.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ be amazing if she tried.", correct: "would", grammar: "She ___ be (2nd cond.)" },
        { sentence: "I wish I ___ the right answer.", correct: "knew", grammar: "I wish I ___ (wish)" },
        { sentence: "If we ___ together, we could solve this.", correct: "worked", grammar: "If we ___ (2nd cond.)" },
        { sentence: "He wishes he ___ more talented.", correct: "were", grammar: "He wishes he ___ (wish, be verb)" },
        { sentence: "She ___ succeed if she believed in herself.", correct: "would", grammar: "She ___ (2nd cond.)" },
        { sentence: "I wish the world ___ more peaceful.", correct: "were", grammar: "I wish ___ (wish, be verb)" },
        { sentence: "If they ___ listening, they would understand.", correct: "were", grammar: "If they ___ (2nd cond.)" },
        { sentence: "She wishes she ___ travel more often.", correct: "could", grammar: "She wishes ___ (wish + ability)" },
        { sentence: "If I ___ more confident, I would speak up.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "He ___ help you if he knew how.", correct: "would", grammar: "He ___ (2nd cond.)" },
        { sentence: "I wish I ___ do more.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "If she ___ here, she would know what to do.", correct: "were", grammar: "If she ___ (2nd cond.)" },
        { sentence: "He wishes he ___ luckier.", correct: "were", grammar: "He wishes he ___ (wish, be verb)" },
      ],
    },
    {
      week: 30,
      title: "Review — Reported Speech",
      grammarFocus: "Said that / Told + person + that · Asked if/whether / Wh-word",
      questions: [
        { sentence: "She said ___ she liked sushi.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told me ___ he would be late.", correct: "that", grammar: "told me ___ (conjunction)" },
        { sentence: "She asked ___ I was hungry.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "He said ___ it was beautiful.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "I told her ___ the exam was cancelled.", correct: "that", grammar: "told her ___ (conjunction)" },
        { sentence: "She asked me ___ I had finished.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "He said ___ he didn't understand.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "I asked him ___ he was feeling.", correct: "how", grammar: "___ (reported Wh- Q)" },
        { sentence: "She told us ___ she was moving.", correct: "that", grammar: "told us ___ (conjunction)" },
        { sentence: "He asked ___ the answer was correct.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "I said ___ I would think about it.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "She asked me ___ I was going.", correct: "where", grammar: "___ (reported Wh- Q)" },
        { sentence: "He told them ___ he was the manager.", correct: "that", grammar: "told them ___ (conjunction)" },
        { sentence: "I asked her ___ she had done.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "She said ___ she had never been to Europe.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told me ___ I should call him later.", correct: "that", grammar: "told me ___ (conjunction)" },
        { sentence: "She asked ___ we could help her.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "I said ___ I was sorry.", correct: "that", grammar: "said ___ (conjunction)" },
        { sentence: "He told us ___ the meeting was cancelled.", correct: "that", grammar: "told us ___ (conjunction)" },
        { sentence: "She asked me ___ I had heard the news.", correct: "if", grammar: "___ (reported yes/no Q)" },
      ],
    },
    {
      week: 31,
      title: "Theme — Social Issues",
      grammarFocus: "Grammar review with social topics — should / passive / for~to / if / that",
      questions: [
        { sentence: "Education ___ important for everyone.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "Many children ___ denied access to education.", correct: "are", grammar: "___ denied (passive)" },
        { sentence: "I believe ___ poverty can be reduced.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is essential ___ everyone to have equal rights.", correct: "for", grammar: "It is ... ___ everyone to ..." },
        { sentence: "Every child ___ the right to study.", correct: "has", grammar: "___ (simple present 3rd)" },
        { sentence: "The problem ___ be solved through cooperation.", correct: "can", grammar: "___ be (modal + passive)" },
        { sentence: "If we ___ act now, things will get worse.", correct: "don't", grammar: "If we ___ (conditional neg.)" },
        { sentence: "She thinks ___ inequality is wrong.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "More people ___ becoming aware of the issue.", correct: "are", grammar: "___ becoming (present cont.)" },
        { sentence: "Many countries are ___ to reduce hunger.", correct: "trying", grammar: "are ___ (present cont.)" },
        { sentence: "It is unfair ___ some people to have so little.", correct: "for", grammar: "It is ... ___ people to ..." },
        { sentence: "We ___ protect the rights of children.", correct: "must", grammar: "We ___ (modal)" },
        { sentence: "Social media has ___ people more aware.", correct: "made", grammar: "has ___ (SVOC, pres. perf.)" },
        { sentence: "___ we work together, we can make a difference.", correct: "If", grammar: "___ (conditional)" },
        { sentence: "Education ___ been shown to reduce poverty.", correct: "has", grammar: "___ been (pres. perf. passive)" },
        { sentence: "She hopes ___ everyone can live in dignity.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "I think ___ everyone deserves a fair chance.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "The situation ___ improving slowly.", correct: "is", grammar: "___ improving (present cont.)" },
        { sentence: "These issues ___ not be ignored.", correct: "should", grammar: "___ not be (modal + passive)" },
        { sentence: "If I ___ power, I would change these laws.", correct: "had", grammar: "If I ___ (2nd cond.)" },
      ],
    },
    {
      week: 32,
      title: "Theme — Technology & AI",
      grammarFocus: "Grammar review with technology topics — mixed Grade 3 grammar",
      questions: [
        { sentence: "AI ___ changing the world rapidly.", correct: "is", grammar: "___ changing (present cont.)" },
        { sentence: "I think ___ technology can help or hurt us.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "She believes ___ AI will replace some jobs.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "If AI ___ smarter, it would be more dangerous.", correct: "were", grammar: "If AI ___ (2nd cond.)" },
        { sentence: "New apps ___ developed every day.", correct: "are", grammar: "___ developed (passive)" },
        { sentence: "She knows how ___ use AI tools.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "I wish I ___ understand how AI works.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "Technology ___ us connect more easily.", correct: "helps", grammar: "___ us (causative)" },
        { sentence: "This program ___ created by a student.", correct: "was", grammar: "___ created (passive past)" },
        { sentence: "He told me ___ AI had passed the test.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "It is important ___ us to use technology responsibly.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "She showed me how ___ use the software.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "Many jobs ___ be automated in the future.", correct: "will", grammar: "___ be (modal + passive)" },
        { sentence: "I ___ technology fascinating.", correct: "find", grammar: "I ___ (SVOC)" },
        { sentence: "If we ___ careful, technology could harm us.", correct: "aren't", grammar: "If we ___ (conditional)" },
        { sentence: "The app ___ designed to make studying easier.", correct: "was", grammar: "___ designed (passive past)" },
        { sentence: "She wants ___ become a software engineer.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "He asked me ___ I thought about AI.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "This robot ___ been programmed to talk.", correct: "has", grammar: "___ been (present perf. passive)" },
        { sentence: "I believe ___ humans and AI can coexist.", correct: "that", grammar: "___ (declarative)" },
      ],
    },
    {
      week: 33,
      title: "Theme — Culture & Identity",
      grammarFocus: "Grammar review with culture topics — mixed Grade 3 grammar",
      questions: [
        { sentence: "Japanese culture ___ rich with tradition.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "Traditional arts ___ passed down for generations.", correct: "have been", grammar: "___ passed down (passive perf.)" },
        { sentence: "I think ___ culture shapes who we are.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is important ___ us to preserve our traditions.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "Many customs ___ influenced by history.", correct: "are", grammar: "___ influenced (passive)" },
        { sentence: "She wishes she ___ more about her ancestors.", correct: "knew", grammar: "She wishes she ___ (wish)" },
        { sentence: "If I ___ in a different country, I would learn the local language.", correct: "lived", grammar: "If I ___ (2nd cond.)" },
        { sentence: "Japanese ___ spoken by about 125 million people.", correct: "is", grammar: "___ spoken (passive)" },
        { sentence: "She believes ___ cultural exchange is important.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "Anime ___ become popular worldwide.", correct: "has", grammar: "___ become (present perfect)" },
        { sentence: "Manga ___ read in over 40 countries.", correct: "is", grammar: "___ read (passive)" },
        { sentence: "He asked me ___ I thought about Japanese culture.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "Festivals ___ celebrated differently in each region.", correct: "are", grammar: "___ celebrated (passive)" },
        { sentence: "She wants everyone ___ respect different cultures.", correct: "to", grammar: "wants everyone ___ (infinitive)" },
        { sentence: "I wish I ___ speak another language fluently.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "Traditional music ___ composed centuries ago.", correct: "was", grammar: "___ composed (passive past)" },
        { sentence: "He thinks ___ bilingualism is a superpower.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "If we ___ more open-minded, we'd learn more.", correct: "were", grammar: "If we ___ (2nd cond.)" },
        { sentence: "I believe ___ every culture has value.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "Traditions ___ often misunderstood by outsiders.", correct: "are", grammar: "___ misunderstood (passive)" },
      ],
    },
    {
      week: 34,
      title: "Theme — Global Citizenship",
      grammarFocus: "Grammar review with global topics — mixed Grade 3 grammar",
      questions: [
        { sentence: "I ___ that everyone has a responsibility to the planet.", correct: "believe", grammar: "I ___ (declarative)" },
        { sentence: "If we don't change our habits, the planet ___ suffer.", correct: "will", grammar: "If ..., ___ (real cond.)" },
        { sentence: "She wants ___ make a difference in the world.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "It is essential ___ us to work together.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "Climate change ___ caused by human activity.", correct: "is", grammar: "___ caused (passive)" },
        { sentence: "Many species ___ been lost forever.", correct: "have", grammar: "___ been lost (present perf. passive)" },
        { sentence: "I wish I ___ stop pollution alone.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "She believes ___ small actions can create big change.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "He told me ___ the situation was serious.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "Forests ___ be protected by international laws.", correct: "should", grammar: "___ be (modal + passive)" },
        { sentence: "If every person ___ one tree, it would help.", correct: "planted", grammar: "If every person ___ (2nd cond.)" },
        { sentence: "She ___ the documentary inspiring.", correct: "found", grammar: "She ___ (SVOC past)" },
        { sentence: "We ___ not ignore these problems.", correct: "should", grammar: "We ___ not (modal)" },
        { sentence: "The treaty ___ signed by 190 countries.", correct: "was", grammar: "___ signed (passive past)" },
        { sentence: "I know ___ important it is to act now.", correct: "how", grammar: "___ (indirect Q)" },
        { sentence: "He asked ___ we were doing to help.", correct: "what", grammar: "___ (reported Wh- Q)" },
        { sentence: "Together, we ___ make the world a better place.", correct: "can", grammar: "we ___ (modal)" },
        { sentence: "She teaches that we ___ all connected.", correct: "are", grammar: "___ (be verb)" },
        { sentence: "If I ___ the chance, I would join a global project.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "The world ___ made better through kindness.", correct: "can be", grammar: "___ made (modal + passive)" },
      ],
    },
    {
      week: 35,
      title: "Theme — Health & Well-being",
      grammarFocus: "Grammar review with health topics — mixed Grade 3 grammar",
      questions: [
        { sentence: "Exercise ___ us feel better.", correct: "makes", grammar: "___ us (causative)" },
        { sentence: "She believes ___ sleep is crucial for health.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "It is important ___ us to exercise regularly.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "If I ___ healthier, I would have more energy.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "Good nutrition ___ the key to a long life.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "Many diseases ___ caused by unhealthy habits.", correct: "are", grammar: "___ caused (passive)" },
        { sentence: "She knows how ___ manage stress.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "He told me ___ he had quit smoking.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "Mental health ___ often overlooked.", correct: "is", grammar: "___ overlooked (passive)" },
        { sentence: "I wish I ___ sleep more.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "She is determined ___ improve her fitness.", correct: "to", grammar: "___ to (infinitive)" },
        { sentence: "Healthy food ___ sold in the school cafeteria.", correct: "is", grammar: "___ sold (passive)" },
        { sentence: "He asked me ___ I exercised.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "She has been ___ every day for six months.", correct: "exercising", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "___ you ever tried meditation?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "I ___ yoga very relaxing.", correct: "find", grammar: "I ___ (SVOC)" },
        { sentence: "If everyone ___ a healthy lifestyle, hospitals would be less crowded.", correct: "lived", grammar: "If everyone ___ (2nd cond.)" },
        { sentence: "The medicine ___ prescribed by a doctor.", correct: "was", grammar: "___ prescribed (passive past)" },
        { sentence: "She believes that rest ___ as important as exercise.", correct: "is", grammar: "___ (be verb)" },
        { sentence: "He helps his patients ___ better.", correct: "feel", grammar: "helps ___ feel (causative)" },
      ],
    },
    {
      week: 36,
      title: "Mixed Grammar Review A",
      grammarFocus: "All Grade 3 grammar — mixed (easier level)",
      questions: [
        { sentence: "She ___ been studying since morning.", correct: "has", grammar: "She ___ been (pres. perf. cont.)" },
        { sentence: "He ___ the problem difficult.", correct: "found", grammar: "He ___ (SVOC past)" },
        { sentence: "___ you ever been to Kyoto?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "She asked me ___ I was going.", correct: "where", grammar: "___ (reported Wh- Q)" },
        { sentence: "If I ___ more time, I would read more.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "I wish she ___ here.", correct: "were", grammar: "I wish she ___ (wish, be verb)" },
        { sentence: "The book ___ written by a famous author.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "She is the person ___ helped me most.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "I want everyone ___ understand this.", correct: "to", grammar: "want everyone ___ (infinitive)" },
        { sentence: "Music ___ me feel calm.", correct: "makes", grammar: "___ me (causative)" },
        { sentence: "He has been ___ English for ten years.", correct: "studying", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "There is a store ___ The Book House.", correct: "called", grammar: "___ (reduced rel. clause)" },
        { sentence: "She asked ___ we would join.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "I know ___ the nearest station is.", correct: "where", grammar: "___ (indirect Q)" },
        { sentence: "If she ___ harder, she'd improve.", correct: "worked", grammar: "If she ___ (2nd cond.)" },
        { sentence: "___ you tired?", correct: "Are", grammar: "___ you? (be Q)" },
        { sentence: "The event ___ held last Saturday.", correct: "was", grammar: "___ held (passive past)" },
        { sentence: "She told me ___ she had won.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "He is the student ___ got full marks.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "I believe ___ we can succeed.", correct: "that", grammar: "___ (declarative)" },
      ],
    },
    {
      week: 37,
      title: "Mixed Grammar Review B",
      grammarFocus: "All Grade 3 grammar — mixed (intermediate level)",
      questions: [
        { sentence: "She ___ been working here since April.", correct: "has", grammar: "She ___ been (pres. perf. cont.)" },
        { sentence: "The trophy ___ won by our school team.", correct: "was", grammar: "___ won (passive past)" },
        { sentence: "He ___ learning easy.", correct: "finds", grammar: "He ___ (SVOC)" },
        { sentence: "I asked her ___ she had any time.", correct: "if", grammar: "___ (reported yes/no Q)" },
        { sentence: "She is the artist ___ painted that mural.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "I wish I ___ travel anywhere for free.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "If they ___ more prepared, they would have won.", correct: "were", grammar: "If they ___ (2nd cond.)" },
        { sentence: "He told us ___ the meeting was canceled.", correct: "that", grammar: "told us ___ (reported speech)" },
        { sentence: "There's a restaurant ___ Sakura.", correct: "called", grammar: "___ (reduced rel. clause)" },
        { sentence: "I know how ___ handle this situation.", correct: "to", grammar: "how ___ (indirect Q)" },
        { sentence: "She has been ___ for the exam since last month.", correct: "preparing", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "It is essential ___ us to act now.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "The law ___ changed to protect animals.", correct: "was", grammar: "___ changed (passive past)" },
        { sentence: "___ you ever faced a difficult decision?", correct: "Have", grammar: "___ you ever? (Q)" },
        { sentence: "She wants ___ become a diplomat.", correct: "to", grammar: "wants ___ (infinitive)" },
        { sentence: "I wish the world ___ simpler.", correct: "were", grammar: "I wish ___ (wish, be verb)" },
        { sentence: "He told me ___ I should not give up.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "This is the book ___ changed my life.", correct: "that", grammar: "___ (subject rel.)" },
        { sentence: "If I ___ her, I would listen carefully.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She ___ the project amazing.", correct: "found", grammar: "She ___ (SVOC past)" },
      ],
    },
    {
      week: 38,
      title: "Mixed Grammar Review C",
      grammarFocus: "All Grade 3 grammar — mixed (harder level)",
      questions: [
        { sentence: "She has been ___ since early morning.", correct: "studying", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "The plan ___ discussed at the meeting.", correct: "was", grammar: "___ discussed (passive past)" },
        { sentence: "He ___ the news shocking.", correct: "found", grammar: "He ___ (SVOC past)" },
        { sentence: "I asked her ___ she had applied.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "She is a leader ___ inspires everyone.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "If I ___ the opportunity, I would study abroad.", correct: "had", grammar: "If I ___ (2nd cond.)" },
        { sentence: "I wish things ___ different.", correct: "were", grammar: "I wish things ___ (wish, be verb)" },
        { sentence: "He told me ___ the results were out.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "There is a bridge ___ Rainbow Bridge.", correct: "called", grammar: "___ (reduced rel. clause)" },
        { sentence: "I understand ___ you feel.", correct: "how", grammar: "___ (indirect Q)" },
        { sentence: "She has been ___ her own business for five years.", correct: "running", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "It is critical ___ all nations to cooperate.", correct: "for", grammar: "It is ... ___ all nations to ..." },
        { sentence: "The treaty ___ signed by world leaders.", correct: "was", grammar: "___ signed (passive past)" },
        { sentence: "___ they ever reached an agreement?", correct: "Have", grammar: "___ they ever? (Q)" },
        { sentence: "She needs you ___ support her.", correct: "to", grammar: "needs you ___ (infinitive)" },
        { sentence: "I wish I ___ do more.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "He said ___ he would not give up.", correct: "that", grammar: "said ___ (reported speech)" },
        { sentence: "This is the reason ___ I believe in education.", correct: "that", grammar: "___ (rel. clause)" },
        { sentence: "If she ___ me, she would understand.", correct: "were", grammar: "If she ___ (2nd cond.)" },
        { sentence: "She ___ the project a success.", correct: "called", grammar: "She ___ (SVOC past)" },
      ],
    },
    {
      week: 39,
      title: "Year Review A",
      grammarFocus: "All Grade 3 grammar — mixed (easier level)",
      questions: [
        { sentence: "I ___ watched this anime three times.", correct: "have", grammar: "I ___ (present perfect)" },
        { sentence: "Music ___ her feel calm.", correct: "makes", grammar: "___ her (causative)" },
        { sentence: "She is the teacher ___ inspired me.", correct: "who", grammar: "___ (subject rel.)" },
        { sentence: "He told me ___ the plan had changed.", correct: "that", grammar: "told me ___ (reported speech)" },
        { sentence: "I wish I ___ go back in time.", correct: "could", grammar: "I wish I ___ (wish + ability)" },
        { sentence: "The letter ___ written in French.", correct: "was", grammar: "___ written (passive past)" },
        { sentence: "It is important ___ us to stay informed.", correct: "for", grammar: "It is ... ___ us to ..." },
        { sentence: "Have you ___ tried Indian curry?", correct: "ever", grammar: "Have you ___ (ever)" },
        { sentence: "She has been ___ since 8 a.m.", correct: "working", grammar: "has been ___ (pres. perf. cont.)" },
        { sentence: "There is a store ___ The Book House.", correct: "called", grammar: "___ (reduced rel. clause)" },
        { sentence: "If I ___ you, I would be more careful.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "She asked me ___ I had eaten.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "He ___ the task challenging.", correct: "found", grammar: "He ___ (SVOC past)" },
        { sentence: "I know ___ to use this program.", correct: "how", grammar: "___ (indirect Q)" },
        { sentence: "She is someone ___ you can always trust.", correct: "who", grammar: "___ (rel. clause)" },
        { sentence: "Music ___ us forget our troubles.", correct: "helps", grammar: "___ us (causative)" },
        { sentence: "The new law ___ passed last year.", correct: "was", grammar: "___ passed (passive past)" },
        { sentence: "He has ___ studying since noon.", correct: "been", grammar: "He has ___ (pres. perf. cont.)" },
        { sentence: "I believe ___ good things take time.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "If she ___ more support, she would succeed.", correct: "had", grammar: "If she ___ (2nd cond.)" },
      ],
    },
    {
      week: 40,
      title: "Year Review B",
      grammarFocus: "All Grade 3 grammar — mixed (harder level)",
      questions: [
        { sentence: "She ___ been working here for a decade.", correct: "has", grammar: "She ___ been (pres. perf. cont.)" },
        { sentence: "This is the book ___ changed my perspective.", correct: "that", grammar: "___ (subject rel.)" },
        { sentence: "He told the team ___ the match was rescheduled.", correct: "that", grammar: "told ___ (reported speech)" },
        { sentence: "I wish I ___ the courage to speak up.", correct: "had", grammar: "I wish I ___ (wish)" },
        { sentence: "The problem ___ solved through negotiation.", correct: "was", grammar: "___ solved (passive past)" },
        { sentence: "She is someone ___ everyone looks up to.", correct: "who", grammar: "___ (rel. clause)" },
        { sentence: "If I ___ more talented, I would perform on stage.", correct: "were", grammar: "If I ___ (2nd cond.)" },
        { sentence: "He knows ___ to handle difficult situations.", correct: "how", grammar: "___ (indirect Q)" },
        { sentence: "It is vital ___ all of us to take action.", correct: "for", grammar: "It is ... ___ all of us to ..." },
        { sentence: "She ___ the experience life-changing.", correct: "found", grammar: "She ___ (SVOC past)" },
        { sentence: "The program ___ designed to help students.", correct: "was", grammar: "___ designed (passive past)" },
        { sentence: "Have they ___ reached a decision?", correct: "already", grammar: "Have they ___ (already)" },
        { sentence: "She asked him ___ he would stay.", correct: "whether", grammar: "___ (reported yes/no Q)" },
        { sentence: "I wish technology ___ solve all our problems.", correct: "could", grammar: "I wish ___ (wish + ability)" },
        { sentence: "There is a dish ___ Oden.", correct: "called", grammar: "___ (reduced rel. clause)" },
        { sentence: "He has ___ training for six months.", correct: "been", grammar: "He has ___ (pres. perf. cont.)" },
        { sentence: "I know ___ she means.", correct: "what", grammar: "___ (indirect Q)" },
        { sentence: "If we ___ more united, we could achieve more.", correct: "were", grammar: "If we ___ (2nd cond.)" },
        { sentence: "She believes ___ change is possible.", correct: "that", grammar: "___ (declarative)" },
        { sentence: "The world ___ made better through kindness.", correct: "can be", grammar: "___ made (modal + passive)" },
      ],
    },
  ],
} as const;
