export interface FCCard {
  word: string;
  emoji: string;
  hint: string;
}

export interface FCWeek {
  week: number;
  title: string;
  topic: string;
  grammarFocus: string;
  cards: FCCard[];
}

// 40 weeks following MEXT JHS grammar progression (New Horizon / Here We Go / Sunshine)
// 中1 Weeks 1-13 → 中2 Weeks 14-26 → 中3 Weeks 27-40
export const flashCardWeeks: FCWeek[] = [
  {
    week: 1, title: "Introductions", topic: "People at School", grammarFocus: "I am / She is / We are",
    cards: [
      { word: "Student", emoji: "🎒", hint: "A young person who studies at school" },
      { word: "Teacher", emoji: "👩‍🏫", hint: "The person who helps you learn in class" },
      { word: "Classmate", emoji: "👥", hint: "Someone who is in the same class as you" },
      { word: "Principal", emoji: "🏫", hint: "The leader of the school" },
      { word: "Librarian", emoji: "📚", hint: "The person who works in the library" },
      { word: "Nurse", emoji: "🏥", hint: "The person who takes care of sick students at school" },
      { word: "Coach", emoji: "🎽", hint: "The person who trains a sports team" },
      { word: "Club leader", emoji: "⭐", hint: "The head student of a school club" },
      { word: "Exchange student", emoji: "✈️", hint: "A student from another country studying at your school" },
      { word: "Homeroom teacher", emoji: "📋", hint: "The teacher who is in charge of your class" },
    ],
  },
  {
    week: 2, title: "School Supplies", topic: "Possessions", grammarFocus: "I have / Do you have?",
    cards: [
      { word: "Textbook", emoji: "📗", hint: "The main book you use in class" },
      { word: "Dictionary", emoji: "📘", hint: "A book that explains the meaning of words" },
      { word: "Notebook", emoji: "📓", hint: "A book with blank pages for writing notes" },
      { word: "Calculator", emoji: "🔢", hint: "A device for doing math quickly" },
      { word: "Compass", emoji: "🔵", hint: "A tool for drawing perfect circles in math class" },
      { word: "Ruler", emoji: "📏", hint: "A flat stick for measuring and drawing straight lines" },
      { word: "Pencil case", emoji: "✏️", hint: "A container for keeping pens and pencils" },
      { word: "Eraser", emoji: "🧹", hint: "Used to remove pencil marks from paper" },
      { word: "Scissors", emoji: "✂️", hint: "A tool with two sharp blades for cutting paper" },
      { word: "Timetable", emoji: "📅", hint: "A chart showing your class schedule for each day" },
    ],
  },
  {
    week: 3, title: "Hobbies & Activities", topic: "Leisure", grammarFocus: "I like / I don't like / Do you like?",
    cards: [
      { word: "Soccer", emoji: "⚽", hint: "A team sport where players kick a ball into a goal" },
      { word: "Tennis", emoji: "🎾", hint: "A sport played with a racket and a small yellow ball" },
      { word: "Swimming", emoji: "🏊", hint: "Moving through water using your arms and legs" },
      { word: "Reading", emoji: "📖", hint: "Looking at words in a book and understanding them" },
      { word: "Cooking", emoji: "🍳", hint: "Preparing food using heat" },
      { word: "Drawing", emoji: "🎨", hint: "Making pictures with a pencil or pen" },
      { word: "Dancing", emoji: "💃", hint: "Moving your body to music" },
      { word: "Camping", emoji: "⛺", hint: "Sleeping outside in a tent in nature" },
      { word: "Gaming", emoji: "🎮", hint: "Playing video or computer games" },
      { word: "Cycling", emoji: "🚴", hint: "Riding a bicycle for exercise or fun" },
    ],
  },
  {
    week: 4, title: "School Spaces", topic: "Classroom & School", grammarFocus: "This is / That is / It is",
    cards: [
      { word: "Gymnasium", emoji: "🏋️", hint: "The large room where PE class is held" },
      { word: "Library", emoji: "📚", hint: "The school room full of books you can borrow" },
      { word: "Cafeteria", emoji: "🍱", hint: "The room where students eat lunch" },
      { word: "Science lab", emoji: "🔬", hint: "The room with equipment for science experiments" },
      { word: "Music room", emoji: "🎵", hint: "The room where students learn to play instruments" },
      { word: "Art room", emoji: "🎨", hint: "The room where students create paintings and sculptures" },
      { word: "Computer lab", emoji: "💻", hint: "The room with many computers for students to use" },
      { word: "Blackboard", emoji: "📋", hint: "The dark board at the front of the class that teachers write on" },
      { word: "Projector", emoji: "📽️", hint: "A machine that shows images or videos on a big screen" },
      { word: "Locker", emoji: "🔒", hint: "A small locked cupboard where students store their belongings" },
    ],
  },
  {
    week: 5, title: "Abilities", topic: "Skills", grammarFocus: "Can / Can't + ability verb",
    cards: [
      { word: "Swim", emoji: "🏊", hint: "Move through water without sinking" },
      { word: "Cook", emoji: "👨‍🍳", hint: "Prepare and make food" },
      { word: "Sing", emoji: "🎤", hint: "Make musical sounds with your voice" },
      { word: "Draw", emoji: "✏️", hint: "Create a picture with a pen or pencil" },
      { word: "Speak", emoji: "🗣️", hint: "Use your voice to say words in a language" },
      { word: "Jump", emoji: "🦘", hint: "Push yourself up off the ground with your legs" },
      { word: "Climb", emoji: "🧗", hint: "Go up a mountain, tree, or ladder" },
      { word: "Whistle", emoji: "😙", hint: "Make a high sound by blowing through your lips" },
      { word: "Skateboard", emoji: "🛹", hint: "Ride on a flat board with four wheels" },
      { word: "Juggle", emoji: "🤹", hint: "Keep several objects in the air at the same time" },
    ],
  },
  {
    week: 6, title: "Community Places", topic: "Places", grammarFocus: "What is? / Where is?",
    cards: [
      { word: "Hospital", emoji: "🏥", hint: "A building where sick people are treated by doctors" },
      { word: "Station", emoji: "🚉", hint: "A place where trains stop to let passengers on and off" },
      { word: "Pharmacy", emoji: "💊", hint: "A shop where you buy medicine" },
      { word: "Post office", emoji: "📮", hint: "A place where you send letters and packages" },
      { word: "Police station", emoji: "🚔", hint: "Where police officers work" },
      { word: "Bank", emoji: "🏦", hint: "A place where people keep and borrow money" },
      { word: "Shrine", emoji: "⛩️", hint: "A traditional Japanese religious building — a place of worship" },
      { word: "Park", emoji: "🌳", hint: "An outdoor area with grass and trees for relaxing and playing" },
      { word: "Convenience store", emoji: "🏪", hint: "A small shop open 24 hours — very common in Japan" },
      { word: "Swimming pool", emoji: "🏊", hint: "An outdoor or indoor area filled with water for swimming" },
    ],
  },
  {
    week: 7, title: "Frequency Words", topic: "How Often?", grammarFocus: "Who / When / How often?",
    cards: [
      { word: "Always", emoji: "🔁", hint: "Every single time — 100% of the time" },
      { word: "Usually", emoji: "✅", hint: "Most of the time — about 80% of the time" },
      { word: "Often", emoji: "📈", hint: "Many times — more than half the time" },
      { word: "Sometimes", emoji: "⏰", hint: "Occasionally — not always, not never" },
      { word: "Rarely", emoji: "🌙", hint: "Not very often — almost never" },
      { word: "Never", emoji: "🚫", hint: "Not at any time — 0% of the time" },
      { word: "Daily", emoji: "📅", hint: "Every single day without exception" },
      { word: "Weekly", emoji: "📆", hint: "Once a week" },
      { word: "Monthly", emoji: "🗓️", hint: "Once a month" },
      { word: "Occasionally", emoji: "🎲", hint: "Now and then — not on a regular schedule" },
    ],
  },
  {
    week: 8, title: "School Subjects", topic: "Subjects", grammarFocus: "I study / I enjoy (present simple)",
    cards: [
      { word: "Mathematics", emoji: "📐", hint: "The subject about numbers, shapes, and calculations" },
      { word: "Science", emoji: "🔬", hint: "The subject about the natural world — biology, chemistry, physics" },
      { word: "English", emoji: "🇬🇧", hint: "The subject where you learn to speak and write in English" },
      { word: "Social Studies", emoji: "🌍", hint: "The subject about history, geography, and society" },
      { word: "Physical Education", emoji: "⚽", hint: "The subject where you exercise and play sports — P.E." },
      { word: "Music", emoji: "🎵", hint: "The subject where you sing and play instruments" },
      { word: "Art", emoji: "🎨", hint: "The subject where you draw, paint, and create things" },
      { word: "Technology", emoji: "💻", hint: "The subject about computers and how things work" },
      { word: "Home Economics", emoji: "🍳", hint: "The subject where you learn cooking and sewing" },
      { word: "Moral Education", emoji: "💭", hint: "The subject about values, feelings, and being a good person" },
    ],
  },
  {
    week: 9, title: "Jobs & Professions", topic: "Careers", grammarFocus: "She works / He teaches (3rd person -s)",
    cards: [
      { word: "Doctor", emoji: "👨‍⚕️", hint: "A person trained to treat sick or injured people" },
      { word: "Engineer", emoji: "🔧", hint: "A person who designs and builds machines or structures" },
      { word: "Scientist", emoji: "🔬", hint: "A person who studies the natural world and does experiments" },
      { word: "Journalist", emoji: "📰", hint: "A person who writes news articles or reports for TV or radio" },
      { word: "Athlete", emoji: "🏃", hint: "A person who does sports professionally" },
      { word: "Architect", emoji: "🏛️", hint: "A person who designs buildings" },
      { word: "Chef", emoji: "👨‍🍳", hint: "A trained professional cook at a restaurant" },
      { word: "Pilot", emoji: "✈️", hint: "A person who flies an airplane" },
      { word: "Firefighter", emoji: "🧑‍🚒", hint: "A person who puts out fires and rescues people" },
      { word: "Veterinarian", emoji: "🐾", hint: "A doctor for animals — often called a vet" },
    ],
  },
  {
    week: 10, title: "Action Words", topic: "Ongoing Actions", grammarFocus: "I am -ing / She is -ing (present progressive)",
    cards: [
      { word: "Running", emoji: "🏃", hint: "Moving very fast on foot right now" },
      { word: "Eating", emoji: "🍽️", hint: "Putting food in your mouth and chewing it" },
      { word: "Writing", emoji: "✍️", hint: "Making words on paper with a pen or pencil" },
      { word: "Listening", emoji: "👂", hint: "Paying attention to sounds or speech" },
      { word: "Watching", emoji: "👀", hint: "Looking at something carefully — like a video or game" },
      { word: "Building", emoji: "🏗️", hint: "Constructing something — putting things together" },
      { word: "Painting", emoji: "🖌️", hint: "Applying paint to a surface to create a picture" },
      { word: "Discussing", emoji: "💬", hint: "Talking about a topic with other people to share ideas" },
      { word: "Presenting", emoji: "📊", hint: "Showing or explaining something to an audience" },
      { word: "Practicing", emoji: "🔄", hint: "Doing something repeatedly to get better at it" },
    ],
  },
  {
    week: 11, title: "Months & Seasons", topic: "Dates & Time", grammarFocus: "Ordinal numbers / on + date / in + month",
    cards: [
      { word: "January", emoji: "❄️", hint: "The first month — winter in Japan, New Year's season" },
      { word: "February", emoji: "💝", hint: "The second month — Valentine's Day and Setsubun" },
      { word: "March", emoji: "🌸", hint: "The third month — graduation season and cherry blossoms" },
      { word: "April", emoji: "🌷", hint: "The fourth month — the new school year starts in Japan" },
      { word: "May", emoji: "🎏", hint: "The fifth month — Golden Week holidays in Japan" },
      { word: "June", emoji: "🌧️", hint: "The sixth month — the rainy season (tsuyu) in Japan" },
      { word: "July", emoji: "🎆", hint: "The seventh month — summer begins, Tanabata festival" },
      { word: "August", emoji: "☀️", hint: "The eighth month — the hottest month of summer in Japan" },
      { word: "September", emoji: "🍁", hint: "The ninth month — autumn begins" },
      { word: "October", emoji: "🎃", hint: "The tenth month — sports festivals and Halloween" },
    ],
  },
  {
    week: 12, title: "Feelings & States", topic: "Emotions", grammarFocus: "I was / She was (past be verb)",
    cards: [
      { word: "Happy", emoji: "😊", hint: "Feeling joy and pleasure" },
      { word: "Tired", emoji: "😴", hint: "Feeling that you need to rest or sleep" },
      { word: "Nervous", emoji: "😬", hint: "Feeling worried or anxious before a big event" },
      { word: "Excited", emoji: "🤩", hint: "Feeling very eager and enthusiastic about something" },
      { word: "Surprised", emoji: "😲", hint: "Feeling sudden shock because something unexpected happened" },
      { word: "Disappointed", emoji: "😞", hint: "Feeling sad because something did not turn out as hoped" },
      { word: "Proud", emoji: "😤", hint: "Feeling satisfied and pleased about your achievement" },
      { word: "Scared", emoji: "😨", hint: "Feeling afraid or frightened" },
      { word: "Bored", emoji: "😑", hint: "Feeling uninterested because there is nothing interesting to do" },
      { word: "Embarrassed", emoji: "😳", hint: "Feeling uncomfortable and shy because of something awkward" },
    ],
  },
  {
    week: 13, title: "Weekend Destinations", topic: "Going Out", grammarFocus: "I visited / We went (past simple - regular)",
    cards: [
      { word: "Museum", emoji: "🏛️", hint: "A building where you can see historical objects and art" },
      { word: "Aquarium", emoji: "🐠", hint: "A place where you can see fish and sea creatures in water" },
      { word: "Theme park", emoji: "🎢", hint: "An entertainment park with rides and attractions" },
      { word: "Festival", emoji: "🎎", hint: "A special celebration with food, music, and activities" },
      { word: "Concert", emoji: "🎸", hint: "A live performance of music" },
      { word: "Sports day", emoji: "🏅", hint: "A school event where students compete in athletic activities — undokai" },
      { word: "Movie theater", emoji: "🎬", hint: "A place where you go to watch films on a big screen" },
      { word: "Shopping mall", emoji: "🛍️", hint: "A large building with many shops inside" },
      { word: "Camping trip", emoji: "⛺", hint: "A trip where you sleep outside in tents" },
      { word: "Barbecue", emoji: "🍖", hint: "An outdoor cooking event where food is grilled" },
    ],
  },
  {
    week: 14, title: "Irregular Past Verbs", topic: "Past Actions", grammarFocus: "Irregular past tense forms (went, saw, had...)",
    cards: [
      { word: "Went", emoji: "🚶", hint: "Past tense of 'go' — I ___ to the park yesterday" },
      { word: "Saw", emoji: "👁️", hint: "Past tense of 'see' — I ___ a great movie last weekend" },
      { word: "Had", emoji: "🍽️", hint: "Past tense of 'have' — I ___ lunch with my friends" },
      { word: "Ate", emoji: "🍱", hint: "Past tense of 'eat' — We ___ pizza at the party" },
      { word: "Got", emoji: "📦", hint: "Past tense of 'get' — I ___ a new bag for my birthday" },
      { word: "Took", emoji: "📸", hint: "Past tense of 'take' — She ___ many photos on the field trip" },
      { word: "Bought", emoji: "🛍️", hint: "Past tense of 'buy' — He ___ a souvenir for his family" },
      { word: "Came", emoji: "🚪", hint: "Past tense of 'come' — They ___ to my house on Saturday" },
      { word: "Made", emoji: "🍳", hint: "Past tense of 'make' — She ___ a cake for the party" },
      { word: "Gave", emoji: "🎁", hint: "Past tense of 'give' — I ___ my friend a birthday present" },
    ],
  },
  {
    week: 15, title: "Time Expressions", topic: "When?", grammarFocus: "Did you...? / I didn't... (past questions & negatives)",
    cards: [
      { word: "Yesterday", emoji: "📅", hint: "The day before today" },
      { word: "Last week", emoji: "📆", hint: "The week before the current week" },
      { word: "Last month", emoji: "🗓️", hint: "The month before the current month" },
      { word: "Last summer", emoji: "☀️", hint: "The summer vacation that has already passed" },
      { word: "This morning", emoji: "🌅", hint: "Earlier today, in the morning hours" },
      { word: "After school", emoji: "🎒", hint: "The time period after school ends and evening begins" },
      { word: "Before dinner", emoji: "🍽️", hint: "The time just before you eat your evening meal" },
      { word: "During vacation", emoji: "✈️", hint: "At some point within the holiday period" },
      { word: "Just now", emoji: "⏱️", hint: "A moment ago — very recently, in the last few minutes" },
      { word: "A long time ago", emoji: "🕰️", hint: "Many years in the past — far before now" },
    ],
  },
  {
    week: 16, title: "Measurements", topic: "Quantities", grammarFocus: "How many / How much / How long / How often?",
    cards: [
      { word: "Kilometer", emoji: "🗺️", hint: "A unit of distance — 1,000 meters; used in Japan" },
      { word: "Kilogram", emoji: "⚖️", hint: "A unit of weight — 1,000 grams" },
      { word: "Liter", emoji: "💧", hint: "A unit for measuring liquid — a large water bottle is about 2 liters" },
      { word: "Meter", emoji: "📏", hint: "A unit of length — a door is about 2 meters tall" },
      { word: "Centimeter", emoji: "📐", hint: "A unit of length — 100 centimeters in one meter" },
      { word: "Degree", emoji: "🌡️", hint: "A unit for measuring temperature — 37 degrees is a fever" },
      { word: "Percentage", emoji: "💯", hint: "A way of showing a number as a part of 100 — 50% means half" },
      { word: "Minute", emoji: "⏱️", hint: "A unit of time — 60 minutes in one hour" },
      { word: "Hour", emoji: "🕐", hint: "A unit of time — 24 hours in one day" },
      { word: "Gram", emoji: "⚗️", hint: "A very small unit of weight — a paperclip weighs about 1 gram" },
    ],
  },
  {
    week: 17, title: "Comparing Things", topic: "Comparatives", grammarFocus: "Bigger / More interesting than (comparative adjectives)",
    cards: [
      { word: "Faster", emoji: "💨", hint: "Moving at greater speed than something else — ___ than" },
      { word: "Stronger", emoji: "💪", hint: "Having greater physical power — ___ than" },
      { word: "Taller", emoji: "📏", hint: "Greater height — ___ than" },
      { word: "Heavier", emoji: "⚖️", hint: "Greater weight — ___ than" },
      { word: "Cheaper", emoji: "💴", hint: "Lower cost or price — ___ than" },
      { word: "Healthier", emoji: "🥗", hint: "Better for your body — ___ than" },
      { word: "Smarter", emoji: "🧠", hint: "Having greater intelligence or cleverness — ___ than" },
      { word: "Warmer", emoji: "🌡️", hint: "Higher temperature — ___ than" },
      { word: "Noisier", emoji: "🔊", hint: "Making more sound — ___ than" },
      { word: "Safer", emoji: "🛡️", hint: "With less danger — ___ than" },
    ],
  },
  {
    week: 18, title: "Superlatives & Records", topic: "Extremes", grammarFocus: "The fastest / The most popular (superlative adjectives)",
    cards: [
      { word: "Largest", emoji: "🌏", hint: "The biggest — nothing else is bigger — the ___ ocean" },
      { word: "Smallest", emoji: "🔬", hint: "The tiniest — nothing else is smaller" },
      { word: "Fastest", emoji: "🚅", hint: "Moving at the greatest speed — the Shinkansen is one of the ___" },
      { word: "Tallest", emoji: "🗼", hint: "The greatest height — the ___ building in Japan" },
      { word: "Deepest", emoji: "🌊", hint: "Going down the furthest — the ___ part of the ocean" },
      { word: "Hottest", emoji: "🌋", hint: "The highest temperature — summer in Japan is one of the ___ seasons" },
      { word: "Coldest", emoji: "🧊", hint: "The lowest temperature — Hokkaido has the ___ winters in Japan" },
      { word: "Most popular", emoji: "⭐", hint: "Liked by the greatest number of people — the ___ game in school" },
      { word: "Most crowded", emoji: "👥", hint: "With the most people packed into a space — Shibuya is the ___ crossing" },
      { word: "Most expensive", emoji: "💎", hint: "Costing the most money — Japanese wagyu is one of the ___ meats" },
    ],
  },
  {
    week: 19, title: "Future Events", topic: "What Will Happen?", grammarFocus: "I will / It will (future – predictions & promises)",
    cards: [
      { word: "Tournament", emoji: "🏆", hint: "A competition between many teams or players" },
      { word: "Competition", emoji: "🥇", hint: "An event where people or teams try to win" },
      { word: "Ceremony", emoji: "🎓", hint: "A formal event to celebrate something important" },
      { word: "Presentation", emoji: "📊", hint: "When you explain or show something to an audience" },
      { word: "Interview", emoji: "🎤", hint: "A meeting where someone asks you questions" },
      { word: "Examination", emoji: "📝", hint: "A formal test to check your knowledge — also called a test or exam" },
      { word: "Performance", emoji: "🎭", hint: "When you act, sing, or play music in front of an audience" },
      { word: "Exhibition", emoji: "🖼️", hint: "A public display of art, science projects, or other items" },
      { word: "Graduation", emoji: "🎓", hint: "The ceremony when you finish school" },
      { word: "Election", emoji: "🗳️", hint: "A process where people vote to choose a leader" },
    ],
  },
  {
    week: 20, title: "Plans & Intentions", topic: "What Are You Going to Do?", grammarFocus: "I am going to / She is going to (future plans)",
    cards: [
      { word: "Trip", emoji: "🧳", hint: "A journey to another place" },
      { word: "Campaign", emoji: "📢", hint: "A plan of activities to achieve a goal — like a school cleanup" },
      { word: "Project", emoji: "📋", hint: "A planned piece of work with a specific goal" },
      { word: "Renovation", emoji: "🔨", hint: "Repairs and improvements to a building" },
      { word: "Celebration", emoji: "🎉", hint: "A special event to mark something happy" },
      { word: "Training", emoji: "🏋️", hint: "Practice sessions to improve your skills or fitness" },
      { word: "Research", emoji: "🔍", hint: "Careful study to find new information" },
      { word: "Experiment", emoji: "🧪", hint: "A scientific test to find out if something is true" },
      { word: "Survey", emoji: "📊", hint: "A set of questions asked to many people to collect information" },
      { word: "Application", emoji: "📄", hint: "A formal request — for a job, school program, or contest" },
    ],
  },
  {
    week: 21, title: "Rules & Requirements", topic: "Obligations", grammarFocus: "Have to / Has to / Don't have to",
    cards: [
      { word: "Uniform", emoji: "👔", hint: "Standard clothes all students must wear at school in Japan" },
      { word: "Permission", emoji: "✋", hint: "Official approval to do something — you need ___ to leave school early" },
      { word: "Deadline", emoji: "⏰", hint: "The last date or time by which something must be done" },
      { word: "Regulation", emoji: "📜", hint: "An official rule made by a school or government" },
      { word: "Registration", emoji: "📝", hint: "The process of signing up officially for something" },
      { word: "Attendance", emoji: "✅", hint: "Being present at school — students must have good ___ in Japan" },
      { word: "Submission", emoji: "📨", hint: "Handing in your work — the act of submitting homework" },
      { word: "Certificate", emoji: "🏅", hint: "An official document showing you completed something" },
      { word: "Homework", emoji: "📚", hint: "School assignments you must complete at home" },
      { word: "Schedule", emoji: "📅", hint: "A plan showing when things will happen" },
    ],
  },
  {
    week: 22, title: "Health & Wellness", topic: "Healthy Living", grammarFocus: "You should / You must / You shouldn't",
    cards: [
      { word: "Exercise", emoji: "🏃", hint: "Physical activity done to stay healthy and strong" },
      { word: "Nutrition", emoji: "🥗", hint: "The study of food and how it affects your body" },
      { word: "Hydration", emoji: "💧", hint: "Keeping your body full of water — drinking enough fluids" },
      { word: "Meditation", emoji: "🧘", hint: "A practice of focusing your mind and breathing to relax" },
      { word: "Prevention", emoji: "🛡️", hint: "Stopping something bad — like disease — before it happens" },
      { word: "Vaccine", emoji: "💉", hint: "A medicine that helps your body fight a specific disease" },
      { word: "Hygiene", emoji: "🧼", hint: "Keeping yourself clean to stay healthy" },
      { word: "Sleep", emoji: "😴", hint: "The rest your body needs every night — 8 hours is recommended for teens" },
      { word: "First aid", emoji: "🩹", hint: "Basic medical help given immediately to an injured person" },
      { word: "Posture", emoji: "🧍", hint: "The position of your body when sitting or standing" },
    ],
  },
  {
    week: 23, title: "Goals & Dreams", topic: "Aspirations", grammarFocus: "I want to / I need to / I try to (to-infinitive)",
    cards: [
      { word: "Career", emoji: "💼", hint: "Your job or profession over many years" },
      { word: "University", emoji: "🎓", hint: "A college or higher education institution" },
      { word: "Scholarship", emoji: "📜", hint: "Money given to a student to pay for their education" },
      { word: "Language", emoji: "🌐", hint: "A system of words and grammar used by a group of people" },
      { word: "Achievement", emoji: "🏆", hint: "Something great that you worked hard to accomplish" },
      { word: "Dream", emoji: "💭", hint: "A strong wish or hope for the future" },
      { word: "Goal", emoji: "🎯", hint: "Something specific you plan and work to achieve" },
      { word: "Ambition", emoji: "🔝", hint: "A strong desire to be successful at something" },
      { word: "Challenge", emoji: "💪", hint: "A difficult task that tests your abilities" },
      { word: "Opportunity", emoji: "🚪", hint: "A chance to do something good — don't miss this ___!" },
    ],
  },
  {
    week: 24, title: "Hobbies as Gerunds", topic: "Gerund Nouns", grammarFocus: "I enjoy -ing / I'm good at -ing (gerunds after verbs)",
    cards: [
      { word: "Swimming", emoji: "🏊", hint: "Moving through water using your arms and legs (as a hobby)" },
      { word: "Cooking", emoji: "👨‍🍳", hint: "Preparing food — a popular hobby for people who love food" },
      { word: "Drawing", emoji: "✏️", hint: "Creating pictures with a pen or pencil" },
      { word: "Gaming", emoji: "🎮", hint: "Playing video or computer games" },
      { word: "Cycling", emoji: "🚴", hint: "Riding a bicycle for exercise or fun" },
      { word: "Hiking", emoji: "🥾", hint: "Walking long distances in nature, usually on trails" },
      { word: "Knitting", emoji: "🧶", hint: "Making clothes or cloth by looping wool with two needles" },
      { word: "Painting", emoji: "🖌️", hint: "Using paint and a brush to create artwork" },
      { word: "Photography", emoji: "📷", hint: "Taking pictures with a camera" },
      { word: "Volunteering", emoji: "🤝", hint: "Working for free to help other people or a cause" },
    ],
  },
  {
    week: 25, title: "Buildings & Spaces", topic: "Locations", grammarFocus: "There is / There are / Is there...?",
    cards: [
      { word: "Elevator", emoji: "🛗", hint: "A machine that carries people up and down between floors" },
      { word: "Reception desk", emoji: "🏨", hint: "The front desk where visitors check in or ask for help" },
      { word: "Emergency exit", emoji: "🚪", hint: "A special door used to escape quickly in an emergency" },
      { word: "Lobby", emoji: "🏛️", hint: "The main entrance hall of a building" },
      { word: "Parking lot", emoji: "🚗", hint: "An area where cars are parked" },
      { word: "Rooftop", emoji: "🏙️", hint: "The top of a building — some schools have rooftop gardens" },
      { word: "Basement", emoji: "⬇️", hint: "The floor below ground level" },
      { word: "Meeting room", emoji: "🤝", hint: "A room used for group discussions and presentations" },
      { word: "Corridor", emoji: "🚶", hint: "A long narrow hallway connecting rooms in a building" },
      { word: "Vending machine", emoji: "🥤", hint: "A machine that sells drinks or snacks automatically" },
    ],
  },
  {
    week: 26, title: "Giving & Receiving", topic: "Gifts", grammarFocus: "Give me / Show her / Buy him (SVOO – double object)",
    cards: [
      { word: "Present", emoji: "🎁", hint: "A gift given to someone on a special occasion" },
      { word: "Souvenir", emoji: "🗺️", hint: "A small item bought to remember a trip or place" },
      { word: "Letter", emoji: "✉️", hint: "A written message sent to someone — on paper or by email" },
      { word: "Message", emoji: "💬", hint: "A short piece of communication sent to someone" },
      { word: "Ticket", emoji: "🎟️", hint: "A small card that allows entry to an event or transport" },
      { word: "Certificate", emoji: "📜", hint: "An official document showing you achieved something" },
      { word: "Medal", emoji: "🥇", hint: "A small metal disc given as an award for winning" },
      { word: "Trophy", emoji: "🏆", hint: "A prize — usually a cup or statue — given to the winner" },
      { word: "Bouquet", emoji: "💐", hint: "A bunch of flowers tied together, often given as a gift" },
      { word: "Advice", emoji: "💡", hint: "A recommendation or suggestion you give to help someone" },
    ],
  },
  {
    week: 27, title: "Life Experiences", topic: "Things You Have Done", grammarFocus: "I have visited / She has won (present perfect – experience)",
    cards: [
      { word: "Climbed", emoji: "🏔️", hint: "Past participle of 'climb' — I have ___ Mt. Fuji" },
      { word: "Performed", emoji: "🎭", hint: "Past participle of 'perform' — She has ___ on stage" },
      { word: "Volunteered", emoji: "🤝", hint: "Past participle of 'volunteer' — He has ___ at a shelter" },
      { word: "Won", emoji: "🏆", hint: "Past participle of 'win' — They have ___ the tournament" },
      { word: "Caught", emoji: "🐟", hint: "Past participle of 'catch' — I have never ___ a fish" },
      { word: "Lost", emoji: "😓", hint: "Past participle of 'lose' — I have ___ my wallet once" },
      { word: "Met", emoji: "🤝", hint: "Past participle of 'meet' — Have you ever ___ a foreigner?" },
      { word: "Tasted", emoji: "😋", hint: "Past participle of 'taste' — I have ___ many kinds of food" },
      { word: "Achieved", emoji: "🎯", hint: "Past participle of 'achieve' — She has ___ her goal" },
      { word: "Explored", emoji: "🗺️", hint: "Past participle of 'explore' — We have ___ the old town" },
    ],
  },
  {
    week: 28, title: "Perfect Markers", topic: "Experience Words", grammarFocus: "ever / never / already / yet (present perfect adverbs)",
    cards: [
      { word: "Ever", emoji: "🌟", hint: "At any time — used in questions: Have you ___ been to Tokyo?" },
      { word: "Never", emoji: "🚫", hint: "Not at any time — I have ___ eaten natto" },
      { word: "Already", emoji: "✅", hint: "Before now — I have ___ finished my homework" },
      { word: "Yet", emoji: "⏳", hint: "Up to now — Have you eaten breakfast ___?" },
      { word: "Before", emoji: "⏮️", hint: "At some time in the past — I have seen this movie ___" },
      { word: "Once", emoji: "1️⃣", hint: "One time — I have only been to Okinawa ___" },
      { word: "Twice", emoji: "2️⃣", hint: "Two times — I have visited that museum ___" },
      { word: "Recently", emoji: "📅", hint: "In the past short period of time — I have ___ started a new hobby" },
      { word: "Just", emoji: "⚡", hint: "A very short time ago — I have ___ arrived at school" },
      { word: "Several times", emoji: "🔢", hint: "More than twice but not many — I have read that book ___" },
    ],
  },
  {
    week: 29, title: "Time Durations", topic: "How Long?", grammarFocus: "for + duration / since + point in time (present perfect)",
    cards: [
      { word: "Since", emoji: "📍", hint: "From a specific point in time until now — ___ I was in elementary school" },
      { word: "For", emoji: "⏱️", hint: "A length of time — ___ three years / ___ a long time" },
      { word: "Decade", emoji: "🔟", hint: "A period of ten years" },
      { word: "Century", emoji: "💯", hint: "A period of one hundred years" },
      { word: "Generation", emoji: "👨‍👩‍👧‍👦", hint: "The period of time between parents and their children — about 30 years" },
      { word: "Semester", emoji: "📚", hint: "One half of the school year" },
      { word: "Era", emoji: "🕰️", hint: "A long period of time in history marked by special features" },
      { word: "Period", emoji: "📆", hint: "A length of time with a beginning and an end" },
      { word: "Lifetime", emoji: "🌱", hint: "The whole of someone's life from birth to death" },
      { word: "Duration", emoji: "⏳", hint: "The length of time that something lasts" },
    ],
  },
  {
    week: 30, title: "Products & Processes", topic: "How Things Are Made", grammarFocus: "is made / are produced (passive voice – present)",
    cards: [
      { word: "Manufactured", emoji: "🏭", hint: "Made in a factory — This car is ___ in Toyota City" },
      { word: "Produced", emoji: "🌾", hint: "Created or grown — Rice is ___ in many regions of Japan" },
      { word: "Grown", emoji: "🌱", hint: "Cultivated from the earth — Vegetables are ___ in greenhouses" },
      { word: "Designed", emoji: "✏️", hint: "Planned and created — This product was ___ by a famous company" },
      { word: "Recycled", emoji: "♻️", hint: "Processed to be used again — Bottles are ___ into new materials" },
      { word: "Exported", emoji: "📦", hint: "Sent to another country to sell — Japanese cars are ___ worldwide" },
      { word: "Imported", emoji: "🚢", hint: "Brought in from another country — Coffee is ___ to Japan" },
      { word: "Distributed", emoji: "🚚", hint: "Spread out to many places — Food is ___ by trucks every day" },
      { word: "Operated", emoji: "⚙️", hint: "Run or managed — The train is ___ by the railway company" },
      { word: "Maintained", emoji: "🔧", hint: "Kept in good condition — The machines are ___ by engineers" },
    ],
  },
  {
    week: 31, title: "History Words", topic: "Historical Events", grammarFocus: "was built / were established (passive voice – past)",
    cards: [
      { word: "Founded", emoji: "🏛️", hint: "Started or established — This school was ___ 100 years ago" },
      { word: "Established", emoji: "📜", hint: "Set up officially — The rule was ___ long ago" },
      { word: "Constructed", emoji: "🔨", hint: "Built — The castle was ___ in the 16th century" },
      { word: "Invented", emoji: "💡", hint: "Created for the first time — The telephone was ___ by Bell" },
      { word: "Discovered", emoji: "🔭", hint: "Found for the first time — New lands were ___ by explorers" },
      { word: "Destroyed", emoji: "💥", hint: "Completely ruined — The town was ___ in the earthquake" },
      { word: "Rebuilt", emoji: "🏗️", hint: "Constructed again after being damaged — The shrine was ___ after the fire" },
      { word: "United", emoji: "🤝", hint: "Joined together — Japan was ___ under one government in the Edo era" },
      { word: "Abolished", emoji: "🚫", hint: "Officially ended — A law was ___ after many years of debate" },
      { word: "Liberated", emoji: "🕊️", hint: "Freed — The people were ___ after years of hardship" },
    ],
  },
  {
    week: 32, title: "Describing People & Things", topic: "Relative Nouns", grammarFocus: "who / which / that (relative pronoun – subject)",
    cards: [
      { word: "Landmark", emoji: "🗼", hint: "A famous building or place people use as a reference — Tokyo Tower is a ___" },
      { word: "Champion", emoji: "🏆", hint: "A person or team who wins a competition" },
      { word: "Ambassador", emoji: "🌐", hint: "An official representative from one country to another" },
      { word: "Volunteer", emoji: "🤝", hint: "A person who works for free to help others" },
      { word: "Inventor", emoji: "💡", hint: "A person who creates a new device or idea for the first time" },
      { word: "Species", emoji: "🦋", hint: "A group of animals or plants that are similar and can reproduce" },
      { word: "Phenomenon", emoji: "🌈", hint: "Something that happens in nature that is remarkable or unusual" },
      { word: "Institution", emoji: "🏛️", hint: "An important organization, like a school or hospital" },
      { word: "Masterpiece", emoji: "🖼️", hint: "A work of art considered the best of its kind" },
      { word: "Heritage", emoji: "🏯", hint: "Traditions and culture passed down from previous generations" },
    ],
  },
  {
    week: 33, title: "Famous Places", topic: "Special Locations", grammarFocus: "where + clause (relative pronoun – place)",
    cards: [
      { word: "Birthplace", emoji: "🗺️", hint: "The city or town where someone was born" },
      { word: "Headquarters", emoji: "🏢", hint: "The main office or center of an organization" },
      { word: "Sanctuary", emoji: "🕊️", hint: "A safe, protected place — often for animals or worship" },
      { word: "Observatory", emoji: "🔭", hint: "A place with equipment for watching stars and the sky" },
      { word: "Marketplace", emoji: "🏪", hint: "A place where people buy and sell goods" },
      { word: "Memorial", emoji: "🕯️", hint: "A structure or place built to remember something important" },
      { word: "Shrine", emoji: "⛩️", hint: "A sacred religious place, especially in Japan — jinja" },
      { word: "Capital", emoji: "🏙️", hint: "The city where the government of a country is located" },
      { word: "Harbor", emoji: "⚓", hint: "A body of water where ships can dock safely" },
      { word: "Venue", emoji: "🎪", hint: "The place where an event, concert, or match is held" },
    ],
  },
  {
    week: 34, title: "Extreme Adjectives", topic: "Degrees", grammarFocus: "too ___ to / so ___ that (degree expressions)",
    cards: [
      { word: "Exhausted", emoji: "😩", hint: "So tired that you cannot do anything more" },
      { word: "Enormous", emoji: "🐘", hint: "Extremely large in size" },
      { word: "Microscopic", emoji: "🔬", hint: "So small that it can only be seen with a microscope" },
      { word: "Tremendous", emoji: "💥", hint: "Very large, great, or powerful" },
      { word: "Unbearable", emoji: "😖", hint: "Too unpleasant or difficult to tolerate" },
      { word: "Extraordinary", emoji: "✨", hint: "Very unusual and remarkable — beyond what is normal" },
      { word: "Overwhelming", emoji: "🌊", hint: "So much or so intense that it is very difficult to handle" },
      { word: "Remarkable", emoji: "🌟", hint: "Worthy of attention — surprisingly impressive" },
      { word: "Brilliant", emoji: "💡", hint: "Extremely clever or very bright" },
      { word: "Magnificent", emoji: "🏰", hint: "Impressively beautiful, grand, or stunning" },
    ],
  },
  {
    week: 35, title: "Abstract Concepts", topic: "It is + adjective", grammarFocus: "It is important to / It is difficult to (it construction)",
    cards: [
      { word: "Essential", emoji: "🔑", hint: "Absolutely necessary — it is ___ to eat balanced meals" },
      { word: "Necessary", emoji: "✅", hint: "Needed — it is ___ to have a passport to travel abroad" },
      { word: "Difficult", emoji: "💪", hint: "Hard to do or understand — it is ___ to learn kanji quickly" },
      { word: "Possible", emoji: "🟢", hint: "Able to be done — it is ___ to speak English fluently with practice" },
      { word: "Exciting", emoji: "🎉", hint: "Causing happiness and enthusiasm — it is ___ to try new things" },
      { word: "Dangerous", emoji: "⚠️", hint: "Likely to cause harm — it is ___ to run near the pool" },
      { word: "Helpful", emoji: "🤝", hint: "Making something easier — it is ___ to study a little every day" },
      { word: "Beneficial", emoji: "✨", hint: "Having a positive effect — it is ___ to read English books" },
      { word: "Reasonable", emoji: "⚖️", hint: "Fair and sensible — it is ___ to take short breaks while studying" },
      { word: "Worthwhile", emoji: "🌟", hint: "Worth doing because of the benefits — it is ___ to volunteer" },
    ],
  },
  {
    week: 36, title: "Environmental Issues", topic: "Conditions & Results", grammarFocus: "If + present simple + will (real conditional)",
    cards: [
      { word: "Climate", emoji: "🌍", hint: "The usual pattern of weather in an area over a long time" },
      { word: "Disaster", emoji: "🌪️", hint: "A very bad event that causes great damage or suffering" },
      { word: "Emergency", emoji: "🚨", hint: "A sudden serious situation that needs immediate action" },
      { word: "Solution", emoji: "💡", hint: "An answer to a problem or difficulty" },
      { word: "Alternative", emoji: "🔄", hint: "Another choice or option if the first one is not possible" },
      { word: "Strategy", emoji: "♟️", hint: "A careful plan to achieve a goal" },
      { word: "Policy", emoji: "📜", hint: "An official plan or set of rules made by a government" },
      { word: "Resource", emoji: "🌿", hint: "Something that can be used — water, oil, and trees are natural resources" },
      { word: "Consequence", emoji: "⚡", hint: "The result or effect of an action" },
      { word: "Prevention", emoji: "🛡️", hint: "Stopping something bad from happening before it occurs" },
    ],
  },
  {
    week: 37, title: "Future Technology", topic: "Tomorrow's World", grammarFocus: "When I grow up / If technology advances (when / if + future)",
    cards: [
      { word: "Robot", emoji: "🤖", hint: "A machine that can do tasks automatically, sometimes like a human" },
      { word: "Artificial intelligence", emoji: "🧠", hint: "Computer systems that can learn and make decisions like humans — AI" },
      { word: "Renewable energy", emoji: "☀️", hint: "Power from sources that naturally replenish — solar, wind, water" },
      { word: "Space travel", emoji: "🚀", hint: "Journeys beyond Earth's atmosphere to outer space" },
      { word: "Virtual reality", emoji: "🥽", hint: "A computer experience that simulates a real or imaginary world — VR" },
      { word: "Sustainable", emoji: "🌱", hint: "Able to continue long-term without harming the environment" },
      { word: "Innovation", emoji: "🔬", hint: "A new idea or method that improves something" },
      { word: "Autonomous", emoji: "🚗", hint: "Able to work independently without human control — self-driving" },
      { word: "Discovery", emoji: "🔭", hint: "Finding or learning something new for the first time" },
      { word: "Revolution", emoji: "🌀", hint: "A complete and fundamental change in the way people think or live" },
    ],
  },
  {
    week: 38, title: "Reporting Verbs", topic: "What Did They Say?", grammarFocus: "He said that / She told me that (indirect speech)",
    cards: [
      { word: "Announced", emoji: "📢", hint: "Said publicly to many people — The principal ___ the new schedule" },
      { word: "Explained", emoji: "💬", hint: "Made something clear by giving details — The teacher ___ the rule" },
      { word: "Promised", emoji: "🤞", hint: "Said you will definitely do something — She ___ to help me" },
      { word: "Warned", emoji: "⚠️", hint: "Told someone about danger ahead of time — He ___ us about the test" },
      { word: "Suggested", emoji: "💡", hint: "Put forward an idea — She ___ that we try a different approach" },
      { word: "Admitted", emoji: "😔", hint: "Confessed to something — He ___ that he had forgotten his homework" },
      { word: "Denied", emoji: "🙅", hint: "Said that something is not true — She ___ breaking the rule" },
      { word: "Confirmed", emoji: "✅", hint: "Made certain — The teacher ___ that the test is on Friday" },
      { word: "Reported", emoji: "📰", hint: "Gave information about something that happened — He ___ the incident" },
      { word: "Mentioned", emoji: "💭", hint: "Briefly said something — She ___ that she was moving to a new city" },
    ],
  },
  {
    week: 39, title: "Wishes & Dreams", topic: "Hypothetical Thoughts", grammarFocus: "I wish I could / If I were (subjunctive – unreal situations)",
    cards: [
      { word: "Freedom", emoji: "🕊️", hint: "The right to live, think, or act without restriction" },
      { word: "Justice", emoji: "⚖️", hint: "Fairness — giving people what they deserve" },
      { word: "Equality", emoji: "🤝", hint: "Everyone having the same rights and opportunities" },
      { word: "Peace", emoji: "☮️", hint: "A state of no war or conflict — calm and harmony" },
      { word: "Harmony", emoji: "🌈", hint: "Living together in a friendly, peaceful way" },
      { word: "Courage", emoji: "🦁", hint: "The ability to do something difficult or scary despite fear" },
      { word: "Wisdom", emoji: "🦉", hint: "The ability to make good decisions from knowledge and experience" },
      { word: "Creativity", emoji: "🎨", hint: "The ability to make new and original things" },
      { word: "Compassion", emoji: "❤️", hint: "Feeling sympathy and care for others who are suffering" },
      { word: "Perseverance", emoji: "💪", hint: "Continuing to try despite difficulties — never giving up" },
    ],
  },
  {
    week: 40, title: "Grand Review", topic: "Mixed JHS Vocabulary", grammarFocus: "All grammar — mixed challenge",
    cards: [
      { word: "Communication", emoji: "🗣️", hint: "The process of sharing information and ideas with others" },
      { word: "Cooperation", emoji: "🤝", hint: "Working together toward a common goal" },
      { word: "Environment", emoji: "🌍", hint: "The natural world around us — we must protect it" },
      { word: "Achievement", emoji: "🏆", hint: "Something great that you worked hard to accomplish" },
      { word: "Responsibility", emoji: "🧭", hint: "A duty or obligation — something you are expected to do" },
      { word: "Contribution", emoji: "🎯", hint: "Something you give or do to help others or a shared goal" },
      { word: "Diversity", emoji: "🌈", hint: "The variety of different people, ideas, or cultures in a group" },
      { word: "Sustainability", emoji: "🌱", hint: "The ability to be maintained without damaging the environment" },
      { word: "Leadership", emoji: "⭐", hint: "The ability to guide and inspire others" },
      { word: "Democracy", emoji: "🗳️", hint: "A system where people vote to choose their leaders and laws" },
    ],
  },
];

export function getWeek(weekNumber: number): FCWeek | undefined {
  return flashCardWeeks.find((w) => w.week === weekNumber);
}

export function generateOptions(week: FCWeek, correctWord: string): string[] {
  const otherWords = week.cards
    .map((c) => c.word)
    .filter((w) => w !== correctWord);
  const shuffled = otherWords.sort(() => Math.random() - 0.5).slice(0, 3);
  const options = [...shuffled, correctWord].sort(() => Math.random() - 0.5);
  return options;
}
