export interface SBSentence {
  words: string[];
  grammarNote: string;
}
export interface SBWeek {
  week: number;
  title: string;
  grammarFocus: string;
  sentences: SBSentence[];
}

// 40 weeks following MEXT JHS grammar progression (New Horizon / Here We Go / Sunshine)
// 中1 Weeks 1-13 → 中2 Weeks 14-26 → 中3 Weeks 27-40
export const sentenceWeeks: SBWeek[] = [
  { week: 1, title: "Self-Introduction", grammarFocus: "I am / She is / We are (be verb)",
    sentences: [
      { words: ["I", "am", "a", "Grade", "7", "student", "."], grammarNote: "I am + noun phrase" },
      { words: ["She", "is", "my", "English", "teacher", "."], grammarNote: "She is + possessive + noun" },
      { words: ["We", "are", "in", "the", "same", "class", "."], grammarNote: "We are + prepositional phrase" },
      { words: ["My", "name", "is", "Yuki", "."], grammarNote: "My name is + proper noun" },
      { words: ["Are", "you", "from", "America", "?"], grammarNote: "Are you from + place?" },
      { words: ["I", "am", "not", "good", "at", "English", "yet", "."], grammarNote: "I am not + adjective + yet" },
      { words: ["He", "is", "the", "captain", "of", "the", "soccer", "team", "."], grammarNote: "He is the + noun + of the + noun" },
      { words: ["Nice", "to", "meet", "you", ".", "I", "am", "Kenji", "."], grammarNote: "Nice to meet you / I am + name" },
    ]},
  { week: 2, title: "Having Things", grammarFocus: "I have / She has / Do you have? (have/has)",
    sentences: [
      { words: ["I", "have", "a", "Japanese-English", "dictionary", "."], grammarNote: "I have + article + noun" },
      { words: ["She", "has", "many", "books", "in", "her", "bag", "."], grammarNote: "She has + quantifier + noun" },
      { words: ["Do", "you", "have", "a", "calculator", "for", "math", "class", "?"], grammarNote: "Do you have + article + noun + for + noun?" },
      { words: ["Our", "school", "has", "a", "large", "swimming", "pool", "."], grammarNote: "Our + noun + has + article + adjective + noun" },
      { words: ["He", "does", "not", "have", "his", "textbook", "today", "."], grammarNote: "He does not have + possessive + noun" },
      { words: ["I", "have", "two", "sisters", "and", "one", "brother", "."], grammarNote: "I have + number + noun + and + number + noun" },
      { words: ["Does", "she", "have", "any", "questions", "about", "the", "homework", "?"], grammarNote: "Does she have + any + noun?" },
      { words: ["We", "have", "club", "practice", "every", "Tuesday", "and", "Thursday", "."], grammarNote: "We have + noun + every + day + and + day" },
    ]},
  { week: 3, title: "Likes and Dislikes", grammarFocus: "I like / I don't like / Do you like?",
    sentences: [
      { words: ["I", "like", "playing", "soccer", "with", "my", "friends", "after", "school", "."], grammarNote: "I like + gerund + with + noun" },
      { words: ["Do", "you", "like", "Japanese", "food", "?"], grammarNote: "Do you like + adjective + noun?" },
      { words: ["She", "doesn't", "like", "getting", "up", "early", "in", "the", "morning", "."], grammarNote: "She doesn't like + gerund phrase" },
      { words: ["I", "like", "English", "but", "I", "don't", "like", "math", "."], grammarNote: "I like + noun + but + I don't like + noun" },
      { words: ["What", "kind", "of", "music", "do", "you", "like", "?"], grammarNote: "What kind of + noun + do you like?" },
      { words: ["He", "likes", "reading", "manga", "and", "playing", "video", "games", "."], grammarNote: "He likes + gerund + and + gerund" },
      { words: ["I", "really", "like", "living", "in", "Japan", "."], grammarNote: "I really like + gerund" },
      { words: ["Do", "you", "like", "anime", "?", "I", "love", "it", "!"], grammarNote: "Do you like + noun? / I love it!" },
    ]},
  { week: 4, title: "This and That", grammarFocus: "This is / That is / It is (demonstratives)",
    sentences: [
      { words: ["This", "is", "my", "Japanese", "textbook", "."], grammarNote: "This is + possessive + noun" },
      { words: ["That", "is", "the", "gymnasium", "over", "there", "."], grammarNote: "That is + article + noun + location" },
      { words: ["What", "is", "this", "?", "It", "is", "a", "compass", "."], grammarNote: "What is this? / It is + article + noun" },
      { words: ["Is", "this", "your", "pencil", "case", "?"], grammarNote: "Is this + possessive + noun?" },
      { words: ["That", "is", "a", "very", "interesting", "question", "."], grammarNote: "That is + article + adjective + noun" },
      { words: ["This", "is", "Yuki", ".", "She", "is", "my", "best", "friend", "."], grammarNote: "This is + name / She is + possessive + noun" },
      { words: ["It", "is", "a", "beautiful", "day", "today", "."], grammarNote: "It is + article + adjective + noun + time" },
      { words: ["Is", "that", "the", "new", "science", "lab", "?"], grammarNote: "Is that + article + adjective + noun?" },
    ]},
  { week: 5, title: "Abilities", grammarFocus: "I can / I can't (can + ability verb)",
    sentences: [
      { words: ["I", "can", "speak", "English", "and", "Japanese", "."], grammarNote: "I can + verb + and + verb" },
      { words: ["Can", "you", "play", "any", "musical", "instruments", "?"], grammarNote: "Can you + verb + any + noun?" },
      { words: ["She", "can", "swim", "very", "fast", "."], grammarNote: "She can + verb + adverb" },
      { words: ["I", "can't", "ride", "a", "bicycle", ",", "but", "I", "want", "to", "learn", "."], grammarNote: "I can't + verb, but I want to + verb" },
      { words: ["Can", "I", "use", "your", "dictionary", ",", "please", "?"], grammarNote: "Can I + verb + possessive + noun, please?" },
      { words: ["He", "can", "cook", "delicious", "meals", "for", "his", "family", "."], grammarNote: "He can + verb + adjective + noun + for + noun" },
      { words: ["What", "can", "you", "do", "well", "?"], grammarNote: "What can you + verb + adverb?" },
      { words: ["She", "can't", "come", "to", "club", "today", "because", "she", "is", "sick", "."], grammarNote: "can't + verb + because + clause" },
    ]},
  { week: 6, title: "Asking Questions", grammarFocus: "What is? / Where is? (WH questions)",
    sentences: [
      { words: ["What", "is", "your", "favorite", "subject", "?"], grammarNote: "What is + possessive + adjective + noun?" },
      { words: ["Where", "is", "the", "nearest", "convenience", "store", "?"], grammarNote: "Where is the + adjective + noun?" },
      { words: ["What", "time", "does", "school", "finish", "?"], grammarNote: "What time does + subject + verb?" },
      { words: ["Where", "are", "the", "scissors", "?", "I", "need", "them", "."], grammarNote: "Where are + article + noun?" },
      { words: ["What", "does", "this", "word", "mean", "in", "Japanese", "?"], grammarNote: "What does + noun + mean + in + language?" },
      { words: ["Where", "do", "you", "usually", "study", "at", "home", "?"], grammarNote: "Where do you + adverb + verb + location?" },
      { words: ["What", "is", "the", "homework", "for", "tomorrow", "?"], grammarNote: "What is the + noun + for + time?" },
      { words: ["Where", "does", "the", "soccer", "club", "practice", "?"], grammarNote: "Where does + article + noun + verb?" },
    ]},
  { week: 7, title: "Daily Routine Questions", grammarFocus: "Who / When / How often? (WH questions with frequency)",
    sentences: [
      { words: ["Who", "is", "your", "homeroom", "teacher", "this", "year", "?"], grammarNote: "Who is + possessive + noun + time?" },
      { words: ["How", "often", "do", "you", "study", "English", "at", "home", "?"], grammarNote: "How often do you + verb + noun + location?" },
      { words: ["When", "does", "summer", "vacation", "start", "in", "Japan", "?"], grammarNote: "When does + subject + verb + location?" },
      { words: ["How", "long", "does", "it", "take", "to", "get", "to", "school", "?"], grammarNote: "How long does it take + to + verb + location?" },
      { words: ["Who", "taught", "you", "to", "speak", "English", "?"], grammarNote: "Who + past tense + pronoun + to + verb?" },
      { words: ["When", "is", "the", "school", "sports", "festival", "?"], grammarNote: "When is + article + noun + noun?" },
      { words: ["I", "usually", "study", "for", "one", "hour", "every", "evening", "."], grammarNote: "I usually + verb + for + number + noun + every + time" },
      { words: ["How", "do", "you", "get", "to", "school", "every", "morning", "?"], grammarNote: "How do you + verb + to + place + every + time?" },
    ]},
  { week: 8, title: "School Routines", grammarFocus: "I study / We have / They eat (present simple – I/we/you/they)",
    sentences: [
      { words: ["I", "study", "English", "for", "one", "hour", "every", "evening", "."], grammarNote: "I + verb + noun + for + time + every + time" },
      { words: ["We", "have", "club", "activities", "three", "times", "a", "week", "."], grammarNote: "We have + noun + frequency" },
      { words: ["I", "always", "eat", "a", "balanced", "breakfast", "before", "school", "."], grammarNote: "I always + verb + adjective + noun + before + time" },
      { words: ["They", "clean", "their", "classroom", "every", "day", "after", "lessons", "."], grammarNote: "They + verb + possessive + noun + every day + after + noun" },
      { words: ["Do", "you", "practice", "any", "sports", "on", "weekends", "?"], grammarNote: "Do you + verb + any + noun + on + time?" },
      { words: ["We", "study", "English", "grammar", "on", "Mondays", "."], grammarNote: "We + verb + noun + on + day" },
      { words: ["I", "usually", "walk", "to", "school", ",", "but", "sometimes", "I", "take", "the", "bus", "."], grammarNote: "I usually + verb, but sometimes + verb" },
      { words: ["You", "need", "to", "bring", "your", "PE", "clothes", "on", "Wednesday", "."], grammarNote: "You need to + verb + possessive + noun + on + day" },
    ]},
  { week: 9, title: "Family Members & Jobs", grammarFocus: "She teaches / He lives / My mother works (3rd person -s)",
    sentences: [
      { words: ["She", "teaches", "English", "at", "our", "junior", "high", "school", "."], grammarNote: "She teaches + noun + at + possessive + noun" },
      { words: ["He", "lives", "near", "the", "train", "station", "."], grammarNote: "He lives + near + article + noun" },
      { words: ["My", "mother", "works", "at", "a", "hospital", "as", "a", "nurse", "."], grammarNote: "My + noun + works + at + article + noun + as + article + noun" },
      { words: ["Our", "science", "teacher", "always", "explains", "things", "clearly", "."], grammarNote: "Our + noun + always + verb + noun + adverb" },
      { words: ["She", "goes", "to", "judo", "club", "every", "Tuesday", "and", "Thursday", "."], grammarNote: "She goes to + noun + every + day + and + day" },
      { words: ["He", "reads", "the", "newspaper", "every", "morning", "before", "work", "."], grammarNote: "He reads + noun + every + time + before + noun" },
      { words: ["Does", "your", "father", "cook", "dinner", "at", "home", "?"], grammarNote: "Does + possessive + noun + verb + noun + location?" },
      { words: ["She", "doesn't", "drink", "coffee", "—", "she", "prefers", "green", "tea", "."], grammarNote: "She doesn't + verb + noun / she prefers + noun" },
    ]},
  { week: 10, title: "Right Now", grammarFocus: "I am studying / She is reading (present progressive)",
    sentences: [
      { words: ["I", "am", "studying", "for", "my", "English", "test", "right", "now", "."], grammarNote: "I am + -ing + for + possessive + noun + right now" },
      { words: ["Is", "she", "reading", "a", "book", "in", "the", "library", "?"], grammarNote: "Is she + -ing + article + noun + location?" },
      { words: ["We", "are", "practicing", "hard", "for", "the", "sports", "festival", "."], grammarNote: "We are + -ing + adverb + for + article + noun" },
      { words: ["What", "are", "you", "doing", "after", "school", "today", "?"], grammarNote: "What are you + -ing + time?" },
      { words: ["It", "is", "raining", "heavily", "outside", "right", "now", "."], grammarNote: "It is + -ing + adverb + location + time" },
      { words: ["He", "is", "not", "listening", "to", "the", "teacher", "right", "now", "."], grammarNote: "He is not + -ing + article + noun + time" },
      { words: ["Are", "you", "enjoying", "your", "new", "club", "activities", "?"], grammarNote: "Are you + -ing + possessive + adjective + noun?" },
      { words: ["She", "is", "wearing", "her", "school", "uniform", "today", "."], grammarNote: "She is + -ing + possessive + noun + today" },
    ]},
  { week: 11, title: "Dates and Schedules", grammarFocus: "on + date / in + month / ordinal numbers",
    sentences: [
      { words: ["My", "birthday", "is", "on", "April", "3rd", "."], grammarNote: "My birthday is on + month + ordinal" },
      { words: ["School", "starts", "in", "April", "every", "year", "in", "Japan", "."], grammarNote: "Noun starts in + month + every year + in + place" },
      { words: ["There", "are", "two", "semesters", "in", "a", "Japanese", "school", "year", "."], grammarNote: "There are + number + noun + in + article + noun" },
      { words: ["Please", "open", "your", "textbook", "to", "page", "twenty-five", "."], grammarNote: "Please + verb + possessive + noun + to + page + number" },
      { words: ["She", "came", "first", "in", "the", "class", "English", "speech", "contest", "."], grammarNote: "She came + ordinal + in + article + noun" },
      { words: ["The", "school", "year", "is", "divided", "into", "three", "terms", "."], grammarNote: "The + noun + is divided into + number + noun" },
      { words: ["My", "grandfather", "will", "turn", "eighty", "years", "old", "in", "December", "."], grammarNote: "My + noun + will turn + number + years old + in + month" },
      { words: ["The", "midterm", "exam", "is", "on", "the", "fifth", "of", "October", "."], grammarNote: "The + noun + is on the + ordinal + of + month" },
    ]},
  { week: 12, title: "Last Weekend", grammarFocus: "I was / She was / Were you? (past be verb)",
    sentences: [
      { words: ["I", "was", "very", "nervous", "before", "my", "first", "English", "class", "."], grammarNote: "I was + adverb + adjective + before + noun" },
      { words: ["Were", "you", "at", "school", "yesterday", "?"], grammarNote: "Were you + location + time?" },
      { words: ["The", "math", "test", "was", "more", "difficult", "than", "I", "expected", "."], grammarNote: "Noun + was + more + adjective + than + clause" },
      { words: ["I", "was", "not", "happy", "with", "my", "test", "score", "."], grammarNote: "I was not + adjective + with + possessive + noun" },
      { words: ["Where", "were", "you", "last", "Saturday", "afternoon", "?"], grammarNote: "Where were you + time?" },
      { words: ["She", "was", "excited", "because", "the", "school", "festival", "was", "tomorrow", "."], grammarNote: "She was + adjective + because + clause" },
      { words: ["They", "were", "busy", "preparing", "for", "the", "school", "play", "."], grammarNote: "They were + adjective + -ing + for + article + noun" },
      { words: ["Was", "the", "new", "ALT", "teacher", "interesting", "?", "Yes", ",", "she", "was", "very", "funny", "."], grammarNote: "Was + noun + adjective? / Yes, she was + adverb + adjective" },
    ]},
  { week: 13, title: "School Trip", grammarFocus: "I visited / We cleaned / She practiced (past simple – regular verbs)",
    sentences: [
      { words: ["I", "visited", "Kyoto", "with", "my", "family", "last", "summer", "."], grammarNote: "I + past verb + place + with + noun + time" },
      { words: ["She", "practiced", "piano", "for", "two", "hours", "yesterday", "."], grammarNote: "She + past verb + noun + for + time + time" },
      { words: ["We", "cleaned", "our", "classroom", "after", "the", "school", "festival", "."], grammarNote: "We + past verb + possessive + noun + after + article + noun" },
      { words: ["Did", "you", "watch", "the", "baseball", "game", "on", "TV", "last", "night", "?"], grammarNote: "Did you + base verb + article + noun + on + noun + time?" },
      { words: ["He", "studied", "hard", "and", "passed", "the", "test", "."], grammarNote: "He + past verb + adverb + and + past verb + article + noun" },
      { words: ["I", "cooked", "dinner", "for", "my", "family", "when", "my", "mother", "was", "sick", "."], grammarNote: "I + past verb + noun + for + noun + when + clause" },
      { words: ["They", "talked", "for", "a", "long", "time", "about", "their", "summer", "plans", "."], grammarNote: "They + past verb + for + article + time + about + possessive + noun" },
      { words: ["She", "walked", "home", "in", "the", "rain", "and", "arrived", "completely", "wet", "."], grammarNote: "She + past verb + noun + and + past verb + adverb + adjective" },
    ]},
  { week: 14, title: "Irregular Past", grammarFocus: "I went / She had / We saw (past simple – irregular verbs)",
    sentences: [
      { words: ["I", "went", "to", "Osaka", "with", "my", "family", "last", "Golden", "Week", "."], grammarNote: "I went + to + place + with + noun + time" },
      { words: ["She", "had", "a", "great", "time", "at", "the", "school", "festival", "."], grammarNote: "She had + article + adjective + noun + at + article + noun" },
      { words: ["We", "saw", "a", "beautiful", "sunrise", "from", "the", "mountaintop", "."], grammarNote: "We saw + article + adjective + noun + from + article + noun" },
      { words: ["He", "bought", "a", "souvenir", "for", "his", "grandmother", "in", "Kyoto", "."], grammarNote: "He bought + article + noun + for + possessive + noun + location" },
      { words: ["She", "made", "a", "delicious", "cake", "for", "her", "mother's", "birthday", "."], grammarNote: "She made + article + adjective + noun + for + possessive + noun" },
      { words: ["They", "came", "to", "school", "early", "to", "prepare", "for", "the", "presentation", "."], grammarNote: "They came + to + place + adverb + to + verb" },
      { words: ["I", "took", "many", "photos", "on", "the", "class", "field", "trip", "to", "Nara", "."], grammarNote: "I took + quantifier + noun + on + article + noun + to + place" },
      { words: ["She", "gave", "me", "advice", "about", "how", "to", "study", "for", "the", "exam", "."], grammarNote: "She gave + me + noun + about + how + to + verb" },
    ]},
  { week: 15, title: "What Did You Do?", grammarFocus: "Did you...? / I didn't... (past simple questions & negatives)",
    sentences: [
      { words: ["Did", "you", "finish", "your", "homework", "last", "night", "?"], grammarNote: "Did you + base verb + possessive + noun + time?" },
      { words: ["I", "didn't", "go", "to", "the", "library", "yesterday", "because", "it", "was", "closed", "."], grammarNote: "I didn't + verb + because + clause" },
      { words: ["What", "did", "you", "do", "during", "the", "long", "weekend", "?"], grammarNote: "What did you + base verb + during + article + noun?" },
      { words: ["She", "didn't", "eat", "breakfast", "because", "she", "was", "in", "a", "hurry", "."], grammarNote: "She didn't + verb + because + clause" },
      { words: ["Did", "he", "study", "for", "the", "test", ",", "or", "did", "he", "forget", "?"], grammarNote: "Did + subject + verb, or did + subject + verb?" },
      { words: ["I", "didn't", "understand", "the", "teacher's", "explanation", "at", "all", "."], grammarNote: "I didn't + verb + article + possessive + noun + at all" },
      { words: ["Did", "they", "win", "the", "basketball", "tournament", "last", "month", "?"], grammarNote: "Did + subject + irregular verb + article + noun + time?" },
      { words: ["Where", "did", "you", "go", "for", "your", "school", "trip", "this", "year", "?"], grammarNote: "Where did you + base verb + for + possessive + noun + time?" },
    ]},
  { week: 16, title: "Quantities & Measurements", grammarFocus: "How many / How much / How long / How far?",
    sentences: [
      { words: ["How", "many", "students", "are", "in", "your", "class", "?"], grammarNote: "How many + noun + are + location?" },
      { words: ["How", "much", "does", "a", "school", "lunch", "cost", "in", "Japan", "?"], grammarNote: "How much does + article + noun + verb + location?" },
      { words: ["How", "long", "does", "it", "take", "to", "get", "to", "school", "by", "bicycle", "?"], grammarNote: "How long does it take + to + verb + by + transport?" },
      { words: ["How", "often", "do", "you", "have", "English", "class", "per", "week", "?"], grammarNote: "How often do you + verb + noun + per + time?" },
      { words: ["There", "are", "thirty-two", "students", "in", "our", "homeroom", "class", "."], grammarNote: "There are + number + noun + in + possessive + noun" },
      { words: ["The", "school", "gymnasium", "is", "about", "twenty", "meters", "long", "."], grammarNote: "The + noun + is about + number + unit + adjective" },
      { words: ["How", "far", "is", "your", "school", "from", "the", "nearest", "station", "?"], grammarNote: "How far is + possessive + noun + from + article + noun?" },
      { words: ["She", "practices", "kendo", "for", "two", "hours", "every", "Tuesday", "evening", "."], grammarNote: "She practices + noun + for + number + noun + every + day + time" },
    ]},
  { week: 17, title: "Comparing Things", grammarFocus: "Tokyo is bigger than Osaka (comparative adjectives)",
    sentences: [
      { words: ["Tokyo", "is", "bigger", "than", "Osaka", "."], grammarNote: "Noun + is + comparative + than + noun" },
      { words: ["The", "Shinkansen", "is", "faster", "than", "a", "regular", "train", "."], grammarNote: "The + noun + is + comparative + than + article + adjective + noun" },
      { words: ["English", "is", "more", "interesting", "than", "I", "thought", "."], grammarNote: "Noun + is + more + adjective + than + clause" },
      { words: ["My", "sister", "is", "two", "years", "older", "than", "me", "."], grammarNote: "My + noun + is + number + noun + comparative + than + pronoun" },
      { words: ["Summer", "in", "Japan", "is", "much", "hotter", "than", "in", "England", "."], grammarNote: "Noun + is + much + comparative + than + location" },
      { words: ["Which", "is", "more", "popular", ",", "soccer", "or", "baseball", ",", "in", "Japan", "?"], grammarNote: "Which is more + adjective, noun or noun + location?" },
      { words: ["Healthy", "food", "is", "better", "for", "you", "than", "fast", "food", "."], grammarNote: "Adjective + noun + is + irregular comparative + for + pronoun" },
      { words: ["His", "test", "score", "was", "higher", "than", "everyone", "else", "in", "the", "class", "."], grammarNote: "Possessive + noun + was + comparative + than + everyone else" },
    ]},
  { week: 18, title: "The Best and The Worst", grammarFocus: "Mt. Fuji is the tallest (superlative adjectives)",
    sentences: [
      { words: ["Mt.", "Fuji", "is", "the", "tallest", "mountain", "in", "Japan", "."], grammarNote: "Noun + is the + superlative + noun + in + place" },
      { words: ["What", "is", "the", "most", "popular", "sport", "in", "your", "school", "?"], grammarNote: "What is the most + adjective + noun + in + possessive + noun?" },
      { words: ["She", "is", "the", "best", "student", "in", "our", "English", "class", "."], grammarNote: "She is the + irregular superlative + noun + in + possessive + noun" },
      { words: ["The", "Pacific", "Ocean", "is", "the", "largest", "ocean", "in", "the", "world", "."], grammarNote: "The + proper noun + is the + superlative + noun + in + article + noun" },
      { words: ["That", "was", "the", "most", "exciting", "game", "I", "have", "ever", "seen", "."], grammarNote: "That was the most + adjective + noun + I have ever + past participle" },
      { words: ["Summer", "is", "the", "hottest", "season", "in", "Japan", "."], grammarNote: "Noun + is the + superlative + noun + in + place" },
      { words: ["Which", "is", "the", "longest", "river", "in", "Japan", "?"], grammarNote: "Which is the + superlative + noun + in + place?" },
      { words: ["This", "is", "the", "most", "difficult", "test", "we", "have", "taken", "this", "year", "."], grammarNote: "This is the most + adjective + noun + we have + past participle + time" },
    ]},
  { week: 19, title: "Future Predictions", grammarFocus: "I will / It will / She won't (will – future)",
    sentences: [
      { words: ["I", "will", "study", "harder", "next", "semester", "."], grammarNote: "I will + verb + adverb + time" },
      { words: ["It", "will", "probably", "rain", "tomorrow", ",", "so", "bring", "an", "umbrella", "."], grammarNote: "It will + adverb + verb + time, so + imperative" },
      { words: ["She", "won't", "be", "able", "to", "come", "to", "the", "club", "meeting", "."], grammarNote: "She won't + be able to + verb + article + noun" },
      { words: ["I", "will", "help", "you", "with", "your", "English", "homework", "."], grammarNote: "I will + verb + pronoun + with + possessive + noun (offer)" },
      { words: ["The", "school", "festival", "will", "be", "held", "in", "October", "this", "year", "."], grammarNote: "Noun + will + be + past participle + location + time" },
      { words: ["Will", "you", "be", "at", "school", "tomorrow", "?"], grammarNote: "Will + subject + be + location + time?" },
      { words: ["I", "think", "technology", "will", "change", "our", "lives", "completely", "."], grammarNote: "I think + subject + will + verb + possessive + noun + adverb" },
      { words: ["She", "will", "tell", "you", "the", "answer", "when", "she", "arrives", "."], grammarNote: "She will + verb + noun + when + clause" },
    ]},
  { week: 20, title: "Making Plans", grammarFocus: "I am going to / She is going to (be going to – future plans)",
    sentences: [
      { words: ["I", "am", "going", "to", "study", "for", "the", "exam", "this", "weekend", "."], grammarNote: "I am going to + verb + article + noun + time" },
      { words: ["She", "is", "going", "to", "join", "the", "English", "speech", "contest", "."], grammarNote: "She is going to + verb + article + noun" },
      { words: ["Are", "you", "going", "to", "attend", "the", "school", "open", "day", "?"], grammarNote: "Are you going to + verb + article + noun?" },
      { words: ["We", "are", "going", "to", "clean", "the", "park", "as", "a", "class", "project", "."], grammarNote: "We are going to + verb + article + noun + as + article + noun" },
      { words: ["He", "is", "not", "going", "to", "give", "up", "on", "his", "dream", "."], grammarNote: "He is not going to + verb + on + possessive + noun" },
      { words: ["What", "are", "you", "going", "to", "do", "during", "the", "summer", "holiday", "?"], grammarNote: "What are you going to + verb + during + article + noun?" },
      { words: ["My", "sister", "is", "going", "to", "start", "high", "school", "in", "April", "."], grammarNote: "My + noun + is going to + verb + noun + in + month" },
      { words: ["They", "are", "going", "to", "visit", "Hiroshima", "on", "the", "school", "trip", "."], grammarNote: "They are going to + verb + place + on + article + noun" },
    ]},
  { week: 21, title: "Rules & Obligations", grammarFocus: "I have to / She has to / I don't have to",
    sentences: [
      { words: ["We", "have", "to", "wear", "a", "school", "uniform", "every", "day", "."], grammarNote: "We have to + verb + article + noun + time" },
      { words: ["She", "has", "to", "submit", "her", "homework", "by", "Friday", "."], grammarNote: "She has to + verb + possessive + noun + by + day" },
      { words: ["You", "don't", "have", "to", "come", "to", "school", "on", "Saturdays", "."], grammarNote: "You don't have to + verb + location + on + day" },
      { words: ["Do", "I", "have", "to", "bring", "my", "own", "lunch", "?"], grammarNote: "Do I have to + verb + possessive + adjective + noun?" },
      { words: ["Students", "have", "to", "be", "at", "school", "by", "eight", "fifteen", "."], grammarNote: "Noun + have to + be + location + by + time" },
      { words: ["He", "has", "to", "see", "the", "school", "nurse", "because", "he", "feels", "unwell", "."], grammarNote: "He has to + verb + article + noun + because + clause" },
      { words: ["We", "don't", "have", "to", "memorize", "every", "word", "in", "the", "textbook", "."], grammarNote: "We don't have to + verb + article + noun + location" },
      { words: ["She", "has", "to", "clean", "the", "classroom", "because", "it", "is", "her", "turn", "."], grammarNote: "She has to + verb + article + noun + because + it is + possessive + noun" },
    ]},
  { week: 22, title: "Health Advice", grammarFocus: "You should / You must / You shouldn't",
    sentences: [
      { words: ["You", "should", "exercise", "for", "at", "least", "thirty", "minutes", "every", "day", "."], grammarNote: "You should + verb + for + at least + number + noun + every + time" },
      { words: ["She", "must", "take", "her", "medicine", "before", "she", "goes", "to", "bed", "."], grammarNote: "She must + verb + possessive + noun + before + clause" },
      { words: ["You", "shouldn't", "eat", "too", "much", "sugar", "or", "junk", "food", "."], grammarNote: "You shouldn't + verb + too much + noun + or + noun" },
      { words: ["We", "must", "wash", "our", "hands", "before", "eating", "and", "after", "using", "the", "toilet", "."], grammarNote: "We must + verb + possessive + noun + before + gerund + and + after + gerund" },
      { words: ["You", "should", "sleep", "for", "at", "least", "eight", "hours", "every", "night", "."], grammarNote: "You should + verb + for + at least + number + noun + every + time" },
      { words: ["Students", "must", "not", "use", "their", "smartphones", "during", "class", "."], grammarNote: "Noun + must not + verb + possessive + noun + during + noun" },
      { words: ["You", "should", "drink", "plenty", "of", "water", ",", "especially", "in", "summer", "."], grammarNote: "You should + verb + plenty of + noun, especially + time" },
      { words: ["She", "shouldn't", "stay", "up", "so", "late", "the", "night", "before", "an", "exam", "."], grammarNote: "She shouldn't + verb + adverb + time + before + article + noun" },
    ]},
  { week: 23, title: "Goals & Ambitions", grammarFocus: "I want to / I need to / I try to (to-infinitive after verbs)",
    sentences: [
      { words: ["I", "want", "to", "become", "a", "doctor", "and", "help", "people", "."], grammarNote: "I want to + verb + article + noun + and + verb" },
      { words: ["She", "needs", "to", "improve", "her", "English", "speaking", "skills", "."], grammarNote: "She needs to + verb + possessive + noun" },
      { words: ["He", "is", "trying", "to", "learn", "guitar", "in", "his", "free", "time", "."], grammarNote: "He is trying to + verb + noun + in + possessive + noun" },
      { words: ["I", "decided", "to", "join", "the", "English", "debate", "club", "this", "year", "."], grammarNote: "I decided to + verb + article + noun + time" },
      { words: ["She", "hopes", "to", "study", "abroad", "in", "New", "Zealand", "someday", "."], grammarNote: "She hopes to + verb + adverb + location + time" },
      { words: ["Do", "you", "plan", "to", "take", "any", "language", "tests", "this", "year", "?"], grammarNote: "Do you plan to + verb + any + noun + time?" },
      { words: ["He", "promised", "to", "study", "harder", "after", "his", "low", "test", "score", "."], grammarNote: "He promised to + verb + adverb + after + possessive + adjective + noun" },
      { words: ["I", "want", "to", "travel", "around", "the", "world", "before", "I", "get", "too", "old", "."], grammarNote: "I want to + verb + around + article + noun + before + clause" },
    ]},
  { week: 24, title: "Hobbies & Interests", grammarFocus: "I enjoy swimming / I'm good at cooking (gerunds after verbs)",
    sentences: [
      { words: ["I", "enjoy", "reading", "novels", "in", "English", "before", "bed", "."], grammarNote: "I enjoy + gerund + noun + location + time" },
      { words: ["She", "is", "good", "at", "playing", "the", "piano", "."], grammarNote: "She is good at + gerund + article + noun" },
      { words: ["He", "finished", "writing", "his", "report", "just", "before", "midnight", "."], grammarNote: "He finished + gerund + possessive + noun + time" },
      { words: ["I", "can't", "stop", "watching", "English", "YouTube", "videos", "."], grammarNote: "I can't stop + gerund + adjective + noun" },
      { words: ["She", "started", "learning", "Korean", "last", "spring", "."], grammarNote: "She started + gerund + noun + time" },
      { words: ["I", "spend", "my", "free", "time", "practicing", "basketball", "at", "the", "park", "."], grammarNote: "I spend + possessive + noun + gerund + noun + location" },
      { words: ["He", "keeps", "making", "the", "same", "grammar", "mistake", "."], grammarNote: "He keeps + gerund + article + same + noun" },
      { words: ["Eating", "slowly", "is", "important", "for", "good", "digestion", "."], grammarNote: "Gerund + adverb + is + adjective + for + noun" },
    ]},
  { week: 25, title: "Describing Places", grammarFocus: "There is / There are / Is there a...?",
    sentences: [
      { words: ["There", "is", "a", "new", "vending", "machine", "near", "the", "gym", "."], grammarNote: "There is + article + adjective + noun + location" },
      { words: ["There", "are", "thirty-six", "students", "in", "our", "homeroom", "class", "."], grammarNote: "There are + number + noun + in + possessive + noun" },
      { words: ["Is", "there", "a", "convenience", "store", "near", "your", "school", "?"], grammarNote: "Is there + article + noun + near + possessive + noun?" },
      { words: ["There", "isn't", "enough", "space", "in", "the", "classroom", "for", "everyone", "."], grammarNote: "There isn't + enough + noun + in + article + noun + for + noun" },
      { words: ["There", "are", "many", "interesting", "clubs", "to", "join", "at", "our", "school", "."], grammarNote: "There are + quantifier + adjective + noun + to + verb + location" },
      { words: ["Is", "there", "a", "hospital", "near", "the", "school", ",", "in", "case", "of", "an", "emergency", "?"], grammarNote: "Is there + article + noun + location + in case of + noun?" },
      { words: ["There", "are", "four", "floors", "in", "our", "school", "building", "."], grammarNote: "There are + number + noun + in + possessive + noun" },
      { words: ["There", "is", "a", "beautiful", "cherry", "blossom", "tree", "in", "the", "schoolyard", "."], grammarNote: "There is + article + adjective + noun + location" },
    ]},
  { week: 26, title: "Giving & Showing", grammarFocus: "Give me the book / Show her the way (SVOO – double object)",
    sentences: [
      { words: ["Please", "give", "me", "a", "moment", "to", "think", "."], grammarNote: "Please give + indirect object + article + noun + to + verb" },
      { words: ["She", "showed", "me", "her", "collection", "of", "Japanese", "stamps", "."], grammarNote: "She showed + me + possessive + noun + of + adjective + noun" },
      { words: ["My", "teacher", "taught", "us", "a", "new", "grammar", "point", "today", "."], grammarNote: "My + noun + taught + us + article + adjective + noun + time" },
      { words: ["Can", "you", "lend", "me", "your", "dictionary", "for", "a", "moment", "?"], grammarNote: "Can you lend + me + possessive + noun + for + article + noun?" },
      { words: ["I", "bought", "my", "mother", "a", "souvenir", "from", "Kyoto", "."], grammarNote: "I bought + indirect object + article + noun + from + place" },
      { words: ["He", "sent", "his", "friend", "a", "long", "letter", "during", "the", "holidays", "."], grammarNote: "He sent + indirect object + article + adjective + noun + time" },
      { words: ["The", "teacher", "gave", "every", "student", "a", "copy", "of", "the", "worksheet", "."], grammarNote: "The + noun + gave + every + noun + article + noun + of + article + noun" },
      { words: ["She", "made", "me", "a", "beautiful", "card", "for", "my", "birthday", "."], grammarNote: "She made + me + article + adjective + noun + for + possessive + noun" },
    ]},
  { week: 27, title: "Life Experiences", grammarFocus: "I have visited / She has won (present perfect – experience)",
    sentences: [
      { words: ["I", "have", "visited", "Okinawa", "twice", "with", "my", "family", "."], grammarNote: "I have + past participle + place + frequency + with + noun" },
      { words: ["She", "has", "won", "the", "English", "speech", "contest", "three", "times", "."], grammarNote: "She has + past participle + article + noun + number + times" },
      { words: ["Have", "you", "ever", "tried", "eating", "natto", "?"], grammarNote: "Have you ever + past participle + gerund + noun?" },
      { words: ["He", "has", "never", "seen", "snow", "in", "his", "life", "."], grammarNote: "He has never + past participle + noun + in + possessive + noun" },
      { words: ["I", "have", "already", "finished", "my", "summer", "homework", "."], grammarNote: "I have already + past participle + possessive + noun" },
      { words: ["Has", "she", "ever", "performed", "on", "stage", "before", "?"], grammarNote: "Has + subject + ever + past participle + location?" },
      { words: ["We", "have", "studied", "English", "together", "for", "three", "years", "."], grammarNote: "We have + past participle + noun + adverb + for + number + noun" },
      { words: ["I", "haven't", "eaten", "yet", "—", "I", "was", "too", "busy", "studying", "."], grammarNote: "I haven't + past participle + yet — I was too + adjective + gerund" },
    ]},
  { week: 28, title: "Have You Ever...?", grammarFocus: "ever / never / already / yet / just (present perfect adverbs)",
    sentences: [
      { words: ["Have", "you", "ever", "met", "a", "famous", "person", "?"], grammarNote: "Have you ever + past participle + article + adjective + noun?" },
      { words: ["I", "have", "never", "been", "outside", "of", "Japan", "."], grammarNote: "I have never + past participle + location" },
      { words: ["She", "has", "already", "read", "the", "whole", "textbook", "."], grammarNote: "She has already + past participle + article + adjective + noun" },
      { words: ["Have", "you", "done", "your", "homework", "yet", "?"], grammarNote: "Have you + past participle + possessive + noun + yet?" },
      { words: ["I", "have", "just", "arrived", "at", "school", "—", "sorry", "I'm", "late", "!"], grammarNote: "I have just + past participle + location — apology" },
      { words: ["He", "has", "visited", "that", "museum", "several", "times", "."], grammarNote: "He has + past participle + demonstrative + noun + frequency" },
      { words: ["She", "has", "never", "tried", "skiing", ",", "but", "she", "wants", "to", "."], grammarNote: "She has never + past participle + gerund, but + clause" },
      { words: ["I", "have", "met", "the", "new", "ALT", "teacher", "before", "—", "she", "is", "very", "kind", "."], grammarNote: "I have + past participle + article + adjective + noun + before" },
    ]},
  { week: 29, title: "How Long?", grammarFocus: "I have studied for three years / since I was a child (for / since)",
    sentences: [
      { words: ["I", "have", "studied", "English", "for", "six", "years", "."], grammarNote: "I have + past participle + noun + for + number + noun" },
      { words: ["She", "has", "lived", "in", "Tokyo", "since", "she", "was", "five", "years", "old", "."], grammarNote: "She has + past participle + location + since + clause" },
      { words: ["How", "long", "have", "you", "been", "a", "member", "of", "the", "soccer", "club", "?"], grammarNote: "How long have you + past participle + article + noun + of + article + noun?" },
      { words: ["He", "has", "played", "the", "guitar", "since", "elementary", "school", "."], grammarNote: "He has + past participle + article + noun + since + noun" },
      { words: ["We", "have", "been", "friends", "for", "almost", "ten", "years", "."], grammarNote: "We have been + noun + for + almost + number + noun" },
      { words: ["I", "haven't", "seen", "my", "grandparents", "since", "last", "New", "Year", "."], grammarNote: "I haven't + past participle + possessive + noun + since + time" },
      { words: ["She", "has", "worked", "as", "an", "ALT", "in", "Japan", "for", "two", "years", "."], grammarNote: "She has + past participle + as + article + noun + location + for + time" },
      { words: ["This", "school", "has", "stood", "here", "for", "more", "than", "one", "hundred", "years", "."], grammarNote: "This + noun + has + past participle + location + for + more than + time" },
    ]},
  { week: 30, title: "How Things Are Made", grammarFocus: "This book is written in English (passive voice – present)",
    sentences: [
      { words: ["Japanese", "cars", "are", "made", "in", "factories", "across", "Japan", "."], grammarNote: "Noun + are + past participle + location" },
      { words: ["English", "is", "spoken", "in", "many", "countries", "around", "the", "world", "."], grammarNote: "Noun + is + past participle + location" },
      { words: ["Rice", "is", "grown", "in", "most", "regions", "of", "Japan", "."], grammarNote: "Noun + is + past participle + location" },
      { words: ["This", "textbook", "is", "used", "by", "students", "all", "over", "Japan", "."], grammarNote: "This + noun + is + past participle + by + noun + location" },
      { words: ["Cherry", "blossoms", "are", "loved", "by", "people", "of", "all", "ages", "."], grammarNote: "Noun + are + past participle + by + noun + of + all + noun" },
      { words: ["The", "school", "lunch", "is", "prepared", "every", "morning", "by", "the", "kitchen", "staff", "."], grammarNote: "Article + noun + is + past participle + time + by + article + noun" },
      { words: ["Is", "this", "building", "used", "for", "club", "activities", "after", "school", "?"], grammarNote: "Is + this + noun + past participle + for + noun + time?" },
      { words: ["Japanese", "food", "is", "enjoyed", "by", "people", "all", "over", "the", "world", "."], grammarNote: "Adjective + noun + is + past participle + by + noun + location" },
    ]},
  { week: 31, title: "Historical Facts", grammarFocus: "The bridge was built in 1945 (passive voice – past)",
    sentences: [
      { words: ["The", "Eiffel", "Tower", "was", "built", "in", "1889", "."], grammarNote: "The + noun + was + past participle + in + year" },
      { words: ["The", "telephone", "was", "invented", "by", "Alexander", "Graham", "Bell", "."], grammarNote: "The + noun + was + past participle + by + proper noun" },
      { words: ["Our", "school", "was", "founded", "more", "than", "one", "hundred", "years", "ago", "."], grammarNote: "Possessive + noun + was + past participle + time" },
      { words: ["Many", "temples", "in", "Kyoto", "were", "built", "over", "a", "thousand", "years", "ago", "."], grammarNote: "Quantifier + noun + were + past participle + time" },
      { words: ["The", "Olympic", "Games", "were", "held", "in", "Tokyo", "in", "1964", "."], grammarNote: "Article + proper noun + were + past participle + location + year" },
      { words: ["Was", "this", "castle", "built", "during", "the", "Edo", "period", "?"], grammarNote: "Was + this + noun + past participle + during + article + proper noun?" },
      { words: ["The", "old", "bridge", "was", "destroyed", "in", "the", "earthquake", "."], grammarNote: "Article + adjective + noun + was + past participle + in + article + noun" },
      { words: ["This", "famous", "painting", "was", "created", "by", "a", "young", "Japanese", "artist", "."], grammarNote: "This + adjective + noun + was + past participle + by + article + noun" },
    ]},
  { week: 32, title: "Describing People & Things", grammarFocus: "The student who won / The book which is popular (relative pronouns – who / which / that)",
    sentences: [
      { words: ["The", "student", "who", "won", "the", "speech", "contest", "is", "in", "our", "class", "."], grammarNote: "The + noun + who + past verb + article + noun + is + location" },
      { words: ["I", "have", "a", "friend", "who", "speaks", "four", "languages", "."], grammarNote: "I have + article + noun + who + verb + number + noun" },
      { words: ["This", "is", "the", "book", "which", "my", "teacher", "recommended", "."], grammarNote: "This is the + noun + which + possessive + noun + past verb" },
      { words: ["The", "train", "that", "goes", "to", "Tokyo", "is", "very", "crowded", "."], grammarNote: "Article + noun + that + verb + to + place + is + adjective" },
      { words: ["She", "is", "the", "person", "who", "helped", "me", "most", "during", "my", "first", "year", "."], grammarNote: "She is the + noun + who + past verb + pronoun + adverb + time" },
      { words: ["The", "app", "which", "I", "use", "to", "study", "English", "is", "free", "."], grammarNote: "The + noun + which + subject + verb + to + verb + noun + is + adjective" },
      { words: ["Do", "you", "know", "anyone", "who", "can", "speak", "French", "?"], grammarNote: "Do you know + pronoun + who + can + verb + noun?" },
      { words: ["I", "like", "movies", "that", "are", "based", "on", "true", "stories", "."], grammarNote: "I like + noun + that + are + past participle + on + adjective + noun" },
    ]},
  { week: 33, title: "Describing Places", grammarFocus: "This is the school where I study (relative pronoun – where)",
    sentences: [
      { words: ["Japan", "is", "a", "country", "where", "people", "bow", "to", "greet", "each", "other", "."], grammarNote: "Noun + is + article + noun + where + people + verb" },
      { words: ["That", "is", "the", "park", "where", "I", "played", "as", "a", "child", "."], grammarNote: "That is the + noun + where + subject + past verb + time" },
      { words: ["A", "library", "is", "a", "place", "where", "you", "can", "borrow", "books", "for", "free", "."], grammarNote: "Article + noun + is + article + noun + where + you + can + verb" },
      { words: ["This", "is", "the", "classroom", "where", "I", "had", "my", "first", "English", "lesson", "."], grammarNote: "This is the + noun + where + subject + had + possessive + ordinal + noun" },
      { words: ["Is", "there", "a", "place", "where", "we", "can", "practice", "speaking", "English", "?"], grammarNote: "Is there + article + noun + where + we + can + verb + gerund?" },
      { words: ["Hiroshima", "is", "a", "city", "where", "history", "teaches", "us", "about", "peace", "."], grammarNote: "Proper noun + is + article + noun + where + noun + verb + us + about + noun" },
      { words: ["The", "staffroom", "is", "the", "place", "where", "teachers", "have", "their", "breaks", "."], grammarNote: "Article + noun + is the + noun + where + noun + verb + possessive + noun" },
      { words: ["She", "wants", "to", "work", "in", "a", "hospital", "where", "she", "can", "help", "patients", "."], grammarNote: "She wants to + verb + location + where + she + can + verb + noun" },
    ]},
  { week: 34, title: "Degrees & Extremes", grammarFocus: "too cold to go out / so hot that we stayed inside (too ~ to / so ~ that)",
    sentences: [
      { words: ["It", "is", "too", "cold", "to", "go", "outside", "without", "a", "coat", "."], grammarNote: "It is too + adjective + to + verb + prepositional phrase" },
      { words: ["The", "bag", "is", "too", "heavy", "for", "me", "to", "carry", "by", "myself", "."], grammarNote: "Article + noun + is too + adjective + for + pronoun + to + verb" },
      { words: ["The", "music", "was", "so", "loud", "that", "I", "couldn't", "hear", "the", "teacher", "."], grammarNote: "Article + noun + was so + adjective + that + clause" },
      { words: ["She", "was", "so", "nervous", "that", "she", "forgot", "her", "speech", "."], grammarNote: "She was so + adjective + that + clause" },
      { words: ["The", "suitcase", "was", "too", "big", "to", "fit", "in", "the", "overhead", "compartment", "."], grammarNote: "Article + noun + was too + adjective + to + verb + location" },
      { words: ["He", "ran", "so", "fast", "that", "nobody", "could", "catch", "him", "."], grammarNote: "He ran so + adverb + that + clause" },
      { words: ["The", "question", "was", "too", "difficult", "for", "anyone", "to", "answer", "."], grammarNote: "Article + noun + was too + adjective + for + pronoun + to + verb" },
      { words: ["She", "was", "so", "tired", "that", "she", "fell", "asleep", "on", "the", "train", "home", "."], grammarNote: "She was so + adjective + that + clause + location" },
    ]},
  { week: 35, title: "Opinions & Ideas", grammarFocus: "It is important to study / It is fun to play (it is + adj + to-infinitive)",
    sentences: [
      { words: ["It", "is", "important", "to", "study", "English", "every", "day", "."], grammarNote: "It is + adjective + to + verb + noun + time" },
      { words: ["It", "is", "not", "easy", "to", "speak", "a", "foreign", "language", "fluently", "."], grammarNote: "It is not + adjective + to + verb + article + adjective + noun + adverb" },
      { words: ["Is", "it", "possible", "to", "become", "fluent", "in", "English", "in", "one", "year", "?"], grammarNote: "Is it + adjective + to + verb + adjective + time?" },
      { words: ["It", "is", "helpful", "to", "use", "a", "dictionary", "when", "you", "read", "in", "English", "."], grammarNote: "It is + adjective + to + verb + article + noun + when + clause" },
      { words: ["It", "is", "dangerous", "to", "use", "your", "smartphone", "while", "cycling", "."], grammarNote: "It is + adjective + to + verb + possessive + noun + while + gerund" },
      { words: ["It", "is", "exciting", "to", "meet", "students", "from", "different", "countries", "."], grammarNote: "It is + adjective + to + verb + noun + from + adjective + noun" },
      { words: ["It", "is", "essential", "to", "get", "enough", "sleep", "before", "an", "exam", "."], grammarNote: "It is + adjective + to + verb + enough + noun + before + article + noun" },
      { words: ["I", "think", "it", "is", "worthwhile", "to", "join", "a", "club", "activity", "."], grammarNote: "I think + it is + adjective + to + verb + article + noun" },
    ]},
  { week: 36, title: "If-Then Situations", grammarFocus: "If it rains, I will stay home (real conditional – if + present → will)",
    sentences: [
      { words: ["If", "you", "study", "hard", ",", "you", "will", "pass", "the", "exam", "."], grammarNote: "If + subject + present verb, subject + will + base verb" },
      { words: ["If", "it", "rains", "tomorrow", ",", "the", "sports", "day", "will", "be", "postponed", "."], grammarNote: "If + it + present verb + time, clause + will + be + past participle" },
      { words: ["If", "you", "need", "help", ",", "please", "ask", "your", "teacher", "."], grammarNote: "If + you + present verb + noun, imperative" },
      { words: ["What", "will", "happen", "if", "we", "don't", "protect", "the", "environment", "?"], grammarNote: "What will + verb + if + subject + don't + verb + article + noun?" },
      { words: ["If", "she", "practices", "every", "day", ",", "she", "will", "improve", "quickly", "."], grammarNote: "If + she + present verb + time, she + will + verb + adverb" },
      { words: ["If", "you", "miss", "the", "bus", ",", "you", "will", "have", "to", "walk", "to", "school", "."], grammarNote: "If + you + present verb + noun, you + will + have to + verb" },
      { words: ["If", "we", "recycle", "more", ",", "we", "will", "produce", "less", "waste", "."], grammarNote: "If + we + present verb + adverb, we + will + verb + less + noun" },
      { words: ["I", "will", "call", "you", "if", "I", "am", "going", "to", "be", "late", "."], grammarNote: "I will + verb + if + I + am + going to + be + adjective" },
    ]},
  { week: 37, title: "When I Grow Up", grammarFocus: "When I grow up / If technology improves (when / if + present → future)",
    sentences: [
      { words: ["When", "I", "grow", "up", ",", "I", "want", "to", "work", "as", "an", "interpreter", "."], grammarNote: "When + I + verb, I want to + verb + as + article + noun" },
      { words: ["If", "robots", "do", "all", "the", "work", ",", "what", "will", "people", "do", "?"], grammarNote: "If + subject + verb + article + noun, what will + people + verb?" },
      { words: ["When", "I", "pass", "the", "high", "school", "entrance", "exam", ",", "I", "will", "celebrate", "."], grammarNote: "When + I + present verb + article + noun, I will + verb" },
      { words: ["If", "Japan", "develops", "better", "AI", ",", "education", "will", "change", "a", "lot", "."], grammarNote: "If + proper noun + present verb + adjective + noun, noun + will + verb" },
      { words: ["When", "the", "cherry", "blossoms", "bloom", ",", "we", "will", "have", "a", "hanami", "party", "."], grammarNote: "When + article + noun + present verb, we + will + verb + article + noun" },
      { words: ["If", "you", "practice", "speaking", "every", "day", ",", "your", "English", "will", "improve", "."], grammarNote: "If + you + present verb + gerund + time, possessive + noun + will + verb" },
      { words: ["When", "I", "visit", "the", "UK", ",", "I", "will", "finally", "use", "my", "English", "."], grammarNote: "When + I + present verb + place, I will + adverb + verb + possessive + noun" },
      { words: ["If", "we", "work", "together", ",", "we", "can", "solve", "any", "problem", "."], grammarNote: "If + we + present verb + adverb, we + can + verb + any + noun" },
    ]},
  { week: 38, title: "Reporting Speech", grammarFocus: "She said that she was tired / He told me that (indirect speech)",
    sentences: [
      { words: ["She", "said", "that", "she", "was", "tired", "after", "the", "long", "practice", "."], grammarNote: "She said that + subject + was + adjective + after + article + noun" },
      { words: ["He", "told", "me", "that", "the", "test", "would", "be", "on", "Friday", "."], grammarNote: "He told + me + that + article + noun + would + be + time" },
      { words: ["The", "teacher", "announced", "that", "school", "would", "finish", "early", "that", "day", "."], grammarNote: "Article + noun + announced + that + clause" },
      { words: ["She", "said", "that", "she", "had", "already", "finished", "the", "project", "."], grammarNote: "She said that + she + had + already + past participle + article + noun" },
      { words: ["He", "told", "us", "that", "the", "field", "trip", "was", "cancelled", "."], grammarNote: "He told + us + that + article + noun + was + past participle" },
      { words: ["I", "heard", "that", "our", "school", "won", "the", "regional", "soccer", "tournament", "."], grammarNote: "I heard that + possessive + noun + past verb + article + noun" },
      { words: ["She", "explained", "that", "she", "had", "been", "studying", "English", "since", "Grade", "4", "."], grammarNote: "She explained + that + she + had been + gerund + noun + since + time" },
      { words: ["He", "promised", "that", "he", "would", "help", "me", "with", "my", "presentation", "."], grammarNote: "He promised + that + he + would + verb + pronoun + with + possessive + noun" },
    ]},
  { week: 39, title: "Wishes & Imagining", grammarFocus: "I wish I could fly / If I were you (subjunctive – unreal situations)",
    sentences: [
      { words: ["I", "wish", "I", "could", "speak", "English", "as", "fluently", "as", "a", "native", "speaker", "."], grammarNote: "I wish I could + verb + noun + as + adverb + as + article + noun" },
      { words: ["If", "I", "were", "the", "school", "principal", ",", "I", "would", "give", "students", "more", "free", "time", "."], grammarNote: "If I were + article + noun, I would + verb + noun + more + noun" },
      { words: ["She", "wishes", "she", "had", "more", "time", "to", "practice", "her", "English", "."], grammarNote: "She wishes + she + had + more + noun + to + verb + possessive + noun" },
      { words: ["If", "I", "were", "a", "bird", ",", "I", "would", "fly", "around", "the", "whole", "world", "."], grammarNote: "If I were + article + noun, I would + verb + around + article + noun" },
      { words: ["I", "wish", "our", "school", "had", "a", "larger", "gymnasium", "."], grammarNote: "I wish + possessive + noun + had + article + comparative + noun" },
      { words: ["If", "I", "were", "taller", ",", "I", "could", "join", "the", "basketball", "team", "."], grammarNote: "If I were + comparative, I could + verb + article + noun" },
      { words: ["She", "wishes", "she", "could", "travel", "to", "every", "country", "in", "the", "world", "."], grammarNote: "She wishes + she + could + verb + to + every + noun + location" },
      { words: ["I", "wish", "I", "had", "studied", "harder", "before", "the", "final", "exam", "."], grammarNote: "I wish + I + had + past participle + adverb + before + article + noun (past regret)" },
    ]},
  { week: 40, title: "Grand Review", grammarFocus: "Mixed grammar — all JHS grammar points",
    sentences: [
      { words: ["I", "have", "been", "studying", "English", "since", "I", "was", "in", "Grade", "4", "."], grammarNote: "I have been + gerund + noun + since + clause (present perfect continuous)" },
      { words: ["If", "you", "work", "hard", ",", "you", "will", "achieve", "your", "dreams", "."], grammarNote: "Conditional: If + present, + will + future" },
      { words: ["This", "school", "was", "founded", "over", "a", "hundred", "years", "ago", "."], grammarNote: "Passive past: This + noun + was + past participle + time" },
      { words: ["The", "student", "who", "gave", "the", "best", "speech", "received", "a", "prize", "."], grammarNote: "Relative pronoun: The + noun + who + verb + article + noun" },
      { words: ["She", "said", "that", "she", "would", "try", "her", "best", "at", "the", "tournament", "."], grammarNote: "Indirect speech: She said that + clause" },
      { words: ["It", "is", "important", "to", "respect", "others", "and", "cooperate", "as", "a", "team", "."], grammarNote: "It is + adjective + to + verb + noun + and + verb" },
      { words: ["I", "wish", "everyone", "could", "live", "in", "peace", "and", "harmony", "."], grammarNote: "Subjunctive: I wish + everyone + could + verb" },
      { words: ["English", "is", "spoken", "by", "more", "than", "one", "billion", "people", "worldwide", "."], grammarNote: "Passive present: Noun + is + past participle + by + number + noun" },
    ]},
];

export function getWeek(weekNumber: number): SBWeek | undefined {
  return sentenceWeeks.find((w) => w.week === weekNumber);
}
