export const academicYearWeeks2 = {

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 11  |  July, 1st Week  (Term 2 Begins)            ║
// ║  JHS1: Past simple — regular verbs (-ed)                ║
// ║  JHS2: Passive voice continued (was/were + pp)          ║
// ║  JHS3: Infinitive constructions (It is ... for ... to)  ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_11: {
  JHS1: [
    { h1: "Neil Armstrong <span class='grammar-underline'>walked</span> on the moon in July 1969.", h2: "He <span class='grammar-underline'>said</span> 'One small step for man' when he <span class='grammar-underline'>landed</span>.", h3: "Millions of people <span class='grammar-underline'>watched</span> this moment on live television.", ans: "Moon Landing", query: "neil-armstrong-moon-1969" },
    { h1: "Marie Curie <span class='grammar-underline'>discovered</span> two new chemical elements.", h2: "She <span class='grammar-underline'>worked</span> in her Paris laboratory for many long years.", h3: "Her research <span class='grammar-underline'>changed</span> the world of science completely.", ans: "Marie Curie", query: "marie-curie-lab-discovery" },
    { h1: "The fire at Notre Dame Cathedral <span class='grammar-underline'>shocked</span> the whole world.", h2: "Firefighters <span class='grammar-underline'>worked</span> through the night to save the building.", h3: "People around the world <span class='grammar-underline'>cried</span> as the spire <span class='grammar-underline'>collapsed</span>.", ans: "Notre Dame", query: "notre-dame-paris-fire" },
    { h1: "This basketball player <span class='grammar-underline'>scored</span> 81 points in a single game.", h2: "Kobe Bryant <span class='grammar-underline'>amazed</span> the crowd at the Staples Center that night.", h3: "Fans <span class='grammar-underline'>cheered</span> as he <span class='grammar-underline'>finished</span> one of the greatest performances.", ans: "Kobe Bryant", query: "kobe-bryant-basketball-81" },
    { h1: "The Titanic <span class='grammar-underline'>sank</span> in the Atlantic Ocean in April 1912.", h2: "The ship <span class='grammar-underline'>hit</span> an iceberg on its very first voyage.", h3: "Thousands of passengers <span class='grammar-underline'>lost</span> their lives in the cold sea.", ans: "Titanic", query: "titanic-sinking-1912" },
    { h1: "The Wright Brothers <span class='grammar-underline'>flew</span> the first airplane at Kitty Hawk.", h2: "Their plane <span class='grammar-underline'>stayed</span> in the air for only 12 seconds at first.", h3: "They <span class='grammar-underline'>changed</span> the history of transportation forever.", ans: "Wright Brothers", query: "wright-brothers-first-flight" },
    { h1: "Japan <span class='grammar-underline'>hosted</span> the first Tokyo Olympics in the summer of 1964.", h2: "Athletes from many countries <span class='grammar-underline'>competed</span> in this historic games.", h3: "The Shinkansen also <span class='grammar-underline'>started</span> running in that same year.", ans: "1964 Tokyo Olympics", query: "tokyo-olympics-1964-shinkansen" },
    { h1: "A young girl <span class='grammar-underline'>climbed</span> a beanstalk and <span class='grammar-underline'>met</span> a giant.", h2: "Wait — a boy named Jack <span class='grammar-underline'>climbed</span> up and <span class='grammar-underline'>stole</span> the giant's gold.", h3: "He <span class='grammar-underline'>escaped</span> safely and <span class='grammar-underline'>lived</span> happily ever after.", ans: "Jack and the Beanstalk", query: "jack-beanstalk-fairy-tale" },
    { h1: "The ancient Romans <span class='grammar-underline'>constructed</span> roads across their empire.", h2: "They <span class='grammar-underline'>built</span> aqueducts that <span class='grammar-underline'>carried</span> water to cities.", h3: "Their engineers <span class='grammar-underline'>created</span> structures that <span class='grammar-underline'>lasted</span> for centuries.", ans: "Roman Engineering", query: "roman-aqueduct-engineering" },
    { h1: "She <span class='grammar-underline'>escaped</span> from her stepsisters and <span class='grammar-underline'>danced</span> with the prince.", h2: "At midnight she <span class='grammar-underline'>rushed</span> away and <span class='grammar-underline'>lost</span> her glass slipper.", h3: "The prince <span class='grammar-underline'>searched</span> everywhere until he <span class='grammar-underline'>found</span> her.", ans: "Cinderella", query: "cinderella-glass-slipper" }
  ],
  JHS2: [
    { h1: "Sushi <span class='grammar-underline'>was first created</span> as a way to preserve fish in Japan.", h2: "Rice <span class='grammar-underline'>was used</span> to ferment the fish for months.", h3: "Modern sushi <span class='grammar-underline'>was invented</span> in Edo, today's Tokyo.", ans: "Sushi History", query: "sushi-history-origin-japan" },
    { h1: "The first Harry Potter novel <span class='grammar-underline'>was rejected</span> by 12 publishers.", h2: "J.K. Rowling <span class='grammar-underline'>was encouraged</span> to keep trying despite failures.", h3: "Millions of copies <span class='grammar-underline'>were sold</span> worldwide after it was published.", ans: "Harry Potter Book", query: "harry-potter-jk-rowling-book" },
    { h1: "The Nobel Peace Prize <span class='grammar-underline'>was awarded</span> to this young Pakistani activist.", h2: "Malala Yousafzai <span class='grammar-underline'>was shot</span> for going to school under the Taliban.", h3: "She <span class='grammar-underline'>was recognized</span> as the youngest Nobel Prize winner.", ans: "Malala", query: "malala-yousafzai-nobel-peace" },
    { h1: "The Great Wall of China <span class='grammar-underline'>was built</span> over many centuries.", h2: "It <span class='grammar-underline'>was constructed</span> to protect China from northern invasions.", h3: "Millions of workers <span class='grammar-underline'>were forced</span> to build this massive structure.", ans: "Great Wall of China", query: "great-wall-china-construction" },
    { h1: "The Mona Lisa <span class='grammar-underline'>was painted</span> by Leonardo da Vinci around 1503.", h2: "It <span class='grammar-underline'>was stolen</span> from the Louvre in 1911 and recovered later.", h3: "It <span class='grammar-underline'>is protected</span> behind bulletproof glass in Paris today.", ans: "Mona Lisa", query: "mona-lisa-stolen-louvre" },
    { h1: "Anime characters <span class='grammar-underline'>were first drawn</span> by Tezuka Osamu in the 1960s.", h2: "His style <span class='grammar-underline'>was inspired</span> by Walt Disney animation from America.", h3: "The big-eyes style <span class='grammar-underline'>was adopted</span> by most manga artists after him.", ans: "Tezuka Osamu Art", query: "tezuka-manga-big-eyes-style" },
    { h1: "The Internet <span class='grammar-underline'>was invented</span> by Tim Berners-Lee in 1989.", h2: "The World Wide Web <span class='grammar-underline'>was designed</span> to share information freely.", h3: "Today billions of people <span class='grammar-underline'>are connected</span> through his invention.", ans: "World Wide Web", query: "world-wide-web-inventor" },
    { h1: "The first Pokemon game <span class='grammar-underline'>was released</span> in Japan in 1996.", h2: "Pikachu <span class='grammar-underline'>was chosen</span> as the franchise mascot by Game Freak.", h3: "Over 1000 Pokemon species <span class='grammar-underline'>have been created</span> since then.", ans: "Pokemon Origins", query: "pokemon-gamefreak-1996" },
    { h1: "This school tradition <span class='grammar-underline'>was introduced</span> in the Meiji era.", h2: "School uniforms <span class='grammar-underline'>were designed</span> to promote equality among students.", h3: "The sailor uniform for girls <span class='grammar-underline'>was inspired</span> by naval clothing.", ans: "School Uniform Japan", query: "japanese-school-uniform-history" },
    { h1: "The bullet train Shinkansen <span class='grammar-underline'>was opened</span> for the 1964 Tokyo Olympics.", h2: "It <span class='grammar-underline'>was engineered</span> to run at 200 km per hour safely.", h3: "Japan's rail system <span class='grammar-underline'>is admired</span> by countries around the world.", ans: "Shinkansen 1964", query: "shinkansen-1964-opening" }
  ],
  JHS3: [
    { h1: "It is <span class='grammar-underline'>important for</span> students <span class='grammar-underline'>to understand</span> this historical event.", h2: "It is <span class='grammar-underline'>necessary for</span> Japan <span class='grammar-underline'>to remember</span> the Meiji Restoration.", h3: "It was <span class='grammar-underline'>essential for</span> Japan <span class='grammar-underline'>to modernize</span> to stay independent.", ans: "Meiji Restoration", query: "meiji-restoration-modernization" },
    { h1: "It is <span class='grammar-underline'>difficult for</span> astronauts <span class='grammar-underline'>to sleep</span> in zero gravity.", h2: "It is <span class='grammar-underline'>important for</span> them <span class='grammar-underline'>to exercise</span> every day in space.", h3: "It is <span class='grammar-underline'>impossible for</span> them <span class='grammar-underline'>to eat</span> soup from a bowl in space!", ans: "Life in Space", query: "astronaut-daily-life-iss" },
    { h1: "It is <span class='grammar-underline'>easy for</span> this small creature <span class='grammar-underline'>to build</span> a dam in a river.", h2: "It is <span class='grammar-underline'>remarkable for</span> an animal <span class='grammar-underline'>to change</span> an entire ecosystem.", h3: "It is <span class='grammar-underline'>important for</span> the beaver <span class='grammar-underline'>to protect</span> its lodge.", ans: "Beaver", query: "beaver-dam-ecosystem" },
    { h1: "It is <span class='grammar-underline'>possible for</span> humans <span class='grammar-underline'>to go</span> without food for three weeks.", h2: "It is <span class='grammar-underline'>impossible for</span> most people <span class='grammar-underline'>to survive</span> without water for three days.", h3: "It is <span class='grammar-underline'>vital for</span> athletes <span class='grammar-underline'>to drink</span> enough water every day.", ans: "Hydration", query: "water-hydration-health-science" },
    { h1: "It is <span class='grammar-underline'>amazing for</span> a tree <span class='grammar-underline'>to live</span> for over 5000 years.", h2: "It is <span class='grammar-underline'>hard for</span> us <span class='grammar-underline'>to imagine</span> such ancient life.", h3: "Bristlecone pines are <span class='grammar-underline'>known for</span> being the oldest trees alive.", ans: "Bristlecone Pine", query: "bristlecone-pine-oldest-tree" },
    { h1: "It is <span class='grammar-underline'>necessary for</span> farmers <span class='grammar-underline'>to plant</span> rice in flooded paddies.", h2: "It is <span class='grammar-underline'>important for</span> Japan <span class='grammar-underline'>to preserve</span> its rice culture.", h3: "It is <span class='grammar-underline'>common for</span> Japanese people <span class='grammar-underline'>to eat</span> rice three times daily.", ans: "Rice Culture Japan", query: "rice-paddy-japan-farming" },
    { h1: "It is <span class='grammar-underline'>difficult for</span> anyone <span class='grammar-underline'>to beat</span> this Japanese tennis player consistently.", h2: "It is <span class='grammar-underline'>inspiring for</span> young athletes <span class='grammar-underline'>to watch</span> Nishikori Kei compete.", h3: "It is <span class='grammar-underline'>rare for</span> Asian men <span class='grammar-underline'>to reach</span> a Grand Slam final.", ans: "Nishikori Kei", query: "nishikori-kei-tennis-japan" },
    { h1: "It is <span class='grammar-underline'>possible for</span> one song <span class='grammar-underline'>to change</span> a whole generation.", h2: "It was <span class='grammar-underline'>significant for</span> John Lennon <span class='grammar-underline'>to write</span> 'Imagine'.", h3: "It is <span class='grammar-underline'>important for</span> people today <span class='grammar-underline'>to listen</span> to its message.", ans: "John Lennon Imagine", query: "john-lennon-imagine-song" },
    { h1: "It is <span class='grammar-underline'>vital for</span> cities <span class='grammar-underline'>to reduce</span> their carbon emissions now.", h2: "It is <span class='grammar-underline'>possible for</span> Japan <span class='grammar-underline'>to reach</span> carbon neutrality by 2050.", h3: "It is <span class='grammar-underline'>necessary for</span> all countries <span class='grammar-underline'>to cooperate</span> on this goal.", ans: "Carbon Neutrality", query: "carbon-neutrality-japan-2050" },
    { h1: "It is <span class='grammar-underline'>exciting for</span> students <span class='grammar-underline'>to study</span> the life of this manga legend.", h2: "It is <span class='grammar-underline'>interesting for</span> fans <span class='grammar-underline'>to know</span> Mizuki Shigeru drew Gegege no Kitaro.", h3: "It is <span class='grammar-underline'>important for</span> Japanese culture <span class='grammar-underline'>to preserve</span> his folklore art.", ans: "Mizuki Shigeru", query: "mizuki-shigeru-gegege-kitaro" }
  ]
},

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 12  |  July, 2nd Week                             ║
// ║  JHS1: Past simple — irregular verbs                    ║
// ║  JHS2: "as ~ as" comparative structures                 ║
// ║  JHS3: Reported speech — statements                     ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_12: {
  JHS1: [
    { h1: "He <span class='grammar-underline'>went</span> on a journey to destroy a magical ring.", h2: "Frodo <span class='grammar-underline'>took</span> the ring to Mount Doom in Middle Earth.", h3: "His friend Sam <span class='grammar-underline'>came</span> with him and never <span class='grammar-underline'>gave up</span>.", ans: "Lord of the Rings", query: "lord-rings-frodo-sam" },
    { h1: "She <span class='grammar-underline'>sang</span> a song about letting go and <span class='grammar-underline'>built</span> an ice palace.", h2: "Elsa <span class='grammar-underline'>ran</span> away from her kingdom into the frozen mountains.", h3: "She <span class='grammar-underline'>found</span> her freedom and <span class='grammar-underline'>became</span> the Snow Queen.", ans: "Frozen Elsa", query: "frozen-elsa-ice-palace" },
    { h1: "He <span class='grammar-underline'>rose</span> to be the most powerful general in all of Japan.", h2: "Oda Nobunaga <span class='grammar-underline'>fought</span> battles across the country for years.", h3: "He <span class='grammar-underline'>built</span> Azuchi Castle and <span class='grammar-underline'>changed</span> Japanese history.", ans: "Oda Nobunaga", query: "oda-nobunaga-castle" },
    { h1: "She <span class='grammar-underline'>swam</span> across the Channel between England and France.", h2: "This athlete <span class='grammar-underline'>beat</span> all records and <span class='grammar-underline'>became</span> famous overnight.", h3: "She <span class='grammar-underline'>proved</span> that women <span class='grammar-underline'>could</span> achieve anything.", ans: "Channel Swimming", query: "english-channel-swim-female" },
    { h1: "He <span class='grammar-underline'>wrote</span> symphonies even after he <span class='grammar-underline'>lost</span> his hearing.", h2: "Beethoven <span class='grammar-underline'>composed</span> his greatest works while deaf.", h3: "He <span class='grammar-underline'>gave</span> the world music that still <span class='grammar-underline'>makes</span> people cry.", ans: "Beethoven", query: "beethoven-deaf-composer" },
    { h1: "A boy <span class='grammar-underline'>found</span> a magic lamp and <span class='grammar-underline'>made</span> three wishes.", h2: "A genie <span class='grammar-underline'>came</span> out and <span class='grammar-underline'>gave</span> him everything he wanted.", h3: "Aladdin <span class='grammar-underline'>fell</span> in love with Princess Jasmine.", ans: "Aladdin", query: "aladdin-magic-lamp-genie" },
    { h1: "She <span class='grammar-underline'>ran</span> away from home and <span class='grammar-underline'>ate</span> porridge in a little house.", h2: "She <span class='grammar-underline'>slept</span> in a small bed and <span class='grammar-underline'>woke up</span> to three bears.", h3: "Goldilocks <span class='grammar-underline'>escaped</span> out the window and <span class='grammar-underline'>ran</span> into the woods.", ans: "Goldilocks", query: "goldilocks-three-bears" },
    { h1: "This player <span class='grammar-underline'>won</span> the World Cup three times with Brazil.", h2: "Pelé <span class='grammar-underline'>scored</span> over 1000 goals in his career.", h3: "He <span class='grammar-underline'>became</span> the greatest soccer player the world has ever seen.", ans: "Pelé", query: "pele-brazil-soccer-legend" },
    { h1: "She <span class='grammar-underline'>spoke</span> to world leaders and <span class='grammar-underline'>told</span> them to act on climate.", h2: "Greta Thunberg <span class='grammar-underline'>stood</span> outside her school alone at first.", h3: "Millions of young people <span class='grammar-underline'>joined</span> her global protest movement.", ans: "Greta Thunberg", query: "greta-thunberg-climate" },
    { h1: "He <span class='grammar-underline'>dreamed</span> of flying and <span class='grammar-underline'>drew</span> designs for a helicopter.", h2: "Leonardo da Vinci <span class='grammar-underline'>thought</span> about ideas centuries before their time.", h3: "He <span class='grammar-underline'>painted</span> the Last Supper and <span class='grammar-underline'>left</span> the world in awe.", ans: "Da Vinci", query: "leonardo-davinci-helicopter-sketch" }
  ],
  JHS2: [
    { h1: "The Arctic Ocean is <span class='grammar-underline'>not as warm as</span> the Pacific Ocean.", h2: "Polar bears are <span class='grammar-underline'>not as fast as</span> cheetahs, but they are strong.", h3: "The Arctic ice is <span class='grammar-underline'>as important as</span> any rainforest for Earth's climate.", ans: "Arctic Ocean", query: "arctic-ocean-polar-bear" },
    { h1: "Traditional manga <span class='grammar-underline'>is as popular as</span> digital anime in Japan.", h2: "Drawing manga by hand <span class='grammar-underline'>is not as easy as</span> using software.", h3: "A manga artist's skill <span class='grammar-underline'>is just as impressive as</span> any painter's.", ans: "Manga Art", query: "manga-drawing-digital-vs-hand" },
    { h1: "Tokyo Disneyland <span class='grammar-underline'>is just as magical as</span> the original Disney in America.", h2: "The rides there <span class='grammar-underline'>are as exciting as</span> any park in the world.", h3: "The food there <span class='grammar-underline'>is not as cheap as</span> normal restaurants!", ans: "Tokyo Disneyland", query: "tokyo-disneyland-japan" },
    { h1: "Sumo wrestlers train <span class='grammar-underline'>as hard as</span> any Olympic athlete.", h2: "Their stability <span class='grammar-underline'>is as important as</span> their strength in a match.", h3: "A sumo stable <span class='grammar-underline'>is not as comfortable as</span> a normal dormitory!", ans: "Sumo Training", query: "sumo-training-stable-japan" },
    { h1: "A bee's intelligence <span class='grammar-underline'>is not as simple as</span> most people think.", h2: "Bees communicate <span class='grammar-underline'>as precisely as</span> humans use language.", h3: "Honey production <span class='grammar-underline'>is as complex as</span> any food manufacturing process.", ans: "Bee Intelligence", query: "bee-waggle-dance-communication" },
    { h1: "Playing baseball <span class='grammar-underline'>is as popular as</span> soccer in Japanese high schools.", h2: "Koshien tournament matches <span class='grammar-underline'>are as intense as</span> professional games.", h3: "A pitcher's fastball <span class='grammar-underline'>is not as easy as</span> it looks to hit.", ans: "Koshien Baseball", query: "koshien-baseball-tournament" },
    { h1: "Life in ancient Rome <span class='grammar-underline'>was not as comfortable as</span> modern Japan.", h2: "Roman bread <span class='grammar-underline'>was not as soft as</span> today's bakery loaves.", h3: "But their engineering skills <span class='grammar-underline'>were just as impressive as</span> ours.", ans: "Ancient Rome Daily Life", query: "ancient-rome-daily-life" },
    { h1: "Natto <span class='grammar-underline'>is not as popular as</span> sushi among foreign visitors.", h2: "Its smell <span class='grammar-underline'>is not as pleasant as</span> miso soup for beginners.", h3: "But its nutrition <span class='grammar-underline'>is just as powerful as</span> any health food.", ans: "Natto", query: "natto-fermented-soybean-japan" },
    { h1: "A dolphin's brain <span class='grammar-underline'>is just as complex as</span> a human's in many ways.", h2: "They are <span class='grammar-underline'>not as big as</span> orcas but <span class='grammar-underline'>as smart as</span> apes.", h3: "Their teamwork <span class='grammar-underline'>is as organized as</span> a professional sports team.", ans: "Dolphin Intelligence", query: "dolphin-intelligence-brain" },
    { h1: "Learning Japanese calligraphy <span class='grammar-underline'>is not as fast as</span> typing on a phone.", h2: "The brush strokes <span class='grammar-underline'>are just as expressive as</span> a signature in English.", h3: "Practicing shodo <span class='grammar-underline'>is as calming as</span> meditation for many people.", ans: "Shodo Calligraphy", query: "shodo-japanese-calligraphy-art" }
  ],
  JHS3: [
    { h1: "He said <span class='grammar-underline'>that</span> the Earth <span class='grammar-underline'>revolved</span> around the sun.", h2: "Galileo told the church <span class='grammar-underline'>that</span> the sun <span class='grammar-underline'>was</span> at the center.", h3: "He claimed <span class='grammar-underline'>that</span> his telescope <span class='grammar-underline'>showed</span> the truth.", ans: "Galileo", query: "galileo-heliocentric-telescope" },
    { h1: "She told the court <span class='grammar-underline'>that</span> she <span class='grammar-underline'>had heard</span> voices from God.", h2: "Joan of Arc claimed <span class='grammar-underline'>that</span> France <span class='grammar-underline'>would</span> be free.", h3: "History proved <span class='grammar-underline'>that</span> her courage <span class='grammar-underline'>changed</span> the war.", ans: "Joan of Arc", query: "joan-of-arc-france-history" },
    { h1: "The manga artist said <span class='grammar-underline'>that</span> he <span class='grammar-underline'>wanted</span> to make people smile.", h2: "Fujiko F. Fujio revealed <span class='grammar-underline'>that</span> Doraemon <span class='grammar-underline'>was</span> based on a cat.", h3: "He explained <span class='grammar-underline'>that</span> the story <span class='grammar-underline'>was about</span> a boy's dreams.", ans: "Fujiko F. Fujio", query: "fujiko-fujio-doraemon-creator" },
    { h1: "Researchers announced <span class='grammar-underline'>that</span> a new dinosaur species <span class='grammar-underline'>had been found</span> in Japan.", h2: "Scientists confirmed <span class='grammar-underline'>that</span> it <span class='grammar-underline'>was</span> a hadrosaurid dinosaur.", h3: "They said <span class='grammar-underline'>that</span> the fossil <span class='grammar-underline'>had been discovered</span> in Hokkaido.", ans: "Mukawaryu", query: "mukawaryu-dinosaur-hokkaido" },
    { h1: "She announced <span class='grammar-underline'>that</span> she <span class='grammar-underline'>would</span> retire after the world championship.", h2: "Yoshida Saori said <span class='grammar-underline'>that</span> wrestling <span class='grammar-underline'>had been</span> her whole life.", h3: "She reported <span class='grammar-underline'>that</span> she <span class='grammar-underline'>had won</span> three Olympic gold medals.", ans: "Yoshida Saori", query: "yoshida-saori-wrestler" },
    { h1: "The prime minister declared <span class='grammar-underline'>that</span> Japan <span class='grammar-underline'>would</span> rebuild quickly.", h2: "After the 2011 tsunami, leaders said <span class='grammar-underline'>that</span> recovery <span class='grammar-underline'>was</span> their top priority.", h3: "Survivors told reporters <span class='grammar-underline'>that</span> they <span class='grammar-underline'>had never</span> expected it.", ans: "2011 Tsunami Japan", query: "2011-japan-tsunami-tohoku" },
    { h1: "The explorer wrote in his diary <span class='grammar-underline'>that</span> the land <span class='grammar-underline'>was</span> unlike anything he had seen.", h2: "Columbus believed <span class='grammar-underline'>that</span> he <span class='grammar-underline'>had reached</span> the East Indies.", h3: "He wrote <span class='grammar-underline'>that</span> the people <span class='grammar-underline'>were</span> peaceful and generous.", ans: "Columbus Discovery", query: "columbus-1492-new-world" },
    { h1: "The coach told the team <span class='grammar-underline'>that</span> they <span class='grammar-underline'>could</span> win the championship.", h2: "He said <span class='grammar-underline'>that</span> their training <span class='grammar-underline'>had been</span> the best he had seen.", h3: "He promised <span class='grammar-underline'>that</span> the next game <span class='grammar-underline'>would</span> be their greatest ever.", ans: "Championship Team", query: "soccer-coach-championship-speech" },
    { h1: "The reporter said <span class='grammar-underline'>that</span> the giant panda <span class='grammar-underline'>had been born</span> at Ueno Zoo.", h2: "Zoo staff announced <span class='grammar-underline'>that</span> the cub <span class='grammar-underline'>was</span> healthy and growing.", h3: "Scientists confirmed <span class='grammar-underline'>that</span> she <span class='grammar-underline'>had been named</span> Xiang Xiang.", ans: "Xiang Xiang Panda", query: "xiang-xiang-ueno-zoo-panda" },
    { h1: "The author explained <span class='grammar-underline'>that</span> her book <span class='grammar-underline'>had been</span> inspired by her own life.", h2: "Kawakami Hiromi said <span class='grammar-underline'>that</span> Japanese emotions <span class='grammar-underline'>were</span> hard to express.", h3: "She revealed <span class='grammar-underline'>that</span> writing fiction <span class='grammar-underline'>helped</span> her understand herself.", ans: "Kawakami Hiromi", query: "kawakami-hiromi-japanese-author" }
  ]
},

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 13  |  July, 3rd Week  (Pre-summer break review)  ║
// ║  JHS1: Past continuous (was/were + -ing)                ║
// ║  JHS2: Mixed review — Term 2 mid grammar                ║
// ║  JHS3: Reduced relative clauses                         ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_13: {
  JHS1: [
    { h1: "The ninja <span class='grammar-underline'>was training</span> in the mountains every morning.", h2: "His students <span class='grammar-underline'>were learning</span> to throw shuriken at targets.", h3: "The master <span class='grammar-underline'>was watching</span> carefully while they <span class='grammar-underline'>were practicing</span>.", ans: "Ninja", query: "ninja-training-japan" },
    { h1: "The audience <span class='grammar-underline'>was cheering</span> when the player scored the winning goal.", h2: "The commentator <span class='grammar-underline'>was shouting</span> with excitement into his microphone.", h3: "Players <span class='grammar-underline'>were running</span> and hugging each other on the field.", ans: "Winning Goal", query: "soccer-winning-goal-celebration" },
    { h1: "She <span class='grammar-underline'>was singing</span> a lullaby while her baby <span class='grammar-underline'>was sleeping</span>.", h2: "Outside, birds <span class='grammar-underline'>were chirping</span> in the morning light.", h3: "The scene <span class='grammar-underline'>was describing</span> peaceful family life in Japan.", ans: "Lullaby", query: "lullaby-baby-japan" },
    { h1: "Explorers <span class='grammar-underline'>were searching</span> for a hidden city of gold in the jungle.", h2: "They <span class='grammar-underline'>were following</span> an ancient map through the Amazon.", h3: "El Dorado <span class='grammar-underline'>was waiting</span> somewhere deep in South America.", ans: "El Dorado", query: "el-dorado-lost-city-gold" },
    { h1: "The chef <span class='grammar-underline'>was chopping</span> vegetables while his assistant <span class='grammar-underline'>was stirring</span> the soup.", h2: "Steam <span class='grammar-underline'>was rising</span> and delicious smells <span class='grammar-underline'>were filling</span> the kitchen.", h3: "They <span class='grammar-underline'>were preparing</span> ramen for the evening rush.", ans: "Ramen Restaurant", query: "ramen-restaurant-kitchen" },
    { h1: "The children <span class='grammar-underline'>were playing</span> around the village well long ago.", h2: "Suddenly a big wolf <span class='grammar-underline'>was coming</span> from the dark forest.", h3: "The boy <span class='grammar-underline'>was crying</span> 'Wolf!' — but nobody believed him this time.", ans: "Boy Who Cried Wolf", query: "boy-cried-wolf-fable" },
    { h1: "Scientists <span class='grammar-underline'>were observing</span> the sky when the comet suddenly appeared.", h2: "Students <span class='grammar-underline'>were sleeping</span> at the observatory during the night watch.", h3: "One astronomer <span class='grammar-underline'>was looking</span> through the lens at the right moment.", ans: "Comet Discovery", query: "comet-observatory-discovery" },
    { h1: "While they <span class='grammar-underline'>were rowing</span> across the river, a crocodile appeared.", h2: "The safari guide <span class='grammar-underline'>was pointing</span> calmly at the enormous creature.", h3: "Tourists <span class='grammar-underline'>were holding</span> their cameras and <span class='grammar-underline'>were breathing</span> quietly.", ans: "Nile Crocodile", query: "nile-crocodile-safari" },
    { h1: "A cat <span class='grammar-underline'>was sitting</span> on the wizard's hat and <span class='grammar-underline'>was watching</span> the magic.", h2: "Kiki <span class='grammar-underline'>was flying</span> across a city on her broomstick.", h3: "Jiji the black cat <span class='grammar-underline'>was talking</span> to Kiki in the Ghibli film.", ans: "Kiki's Delivery Service", query: "kiki-delivery-service-ghibli" },
    { h1: "Reporters <span class='grammar-underline'>were waiting</span> outside when the gold medalist arrived.", h2: "Her fans <span class='grammar-underline'>were screaming</span> and <span class='grammar-underline'>were waving</span> Japanese flags.", h3: "She <span class='grammar-underline'>was smiling</span> broadly while holding her medal.", ans: "Olympic Gold Medalist", query: "japan-olympic-gold-medalist" }
  ],
  JHS2: [
    { h1: "I <span class='grammar-underline'>think that</span> ancient Egypt <span class='grammar-underline'>is more fascinating than</span> any modern country.", h2: "Do you <span class='grammar-underline'>know how to</span> read Egyptian hieroglyphics?", h3: "I <span class='grammar-underline'>am sure that</span> the Rosetta Stone <span class='grammar-underline'>was used</span> to decode them.", ans: "Rosetta Stone", query: "rosetta-stone-egypt-hieroglyphics" },
    { h1: "<span class='grammar-underline'>Playing</span> the shamisen is a traditional Japanese art.", h2: "I <span class='grammar-underline'>think that</span> no instrument <span class='grammar-underline'>is as beautiful as</span> this three-stringed wonder.", h3: "Do you <span class='grammar-underline'>know how to</span> play traditional Japanese music?", ans: "Shamisen", query: "shamisen-japanese-instrument" },
    { h1: "I <span class='grammar-underline'>must</span> learn about this man who created the periodic table.", h2: "Do you <span class='grammar-underline'>know how to</span> use Mendeleev's table in chemistry class?", h3: "I <span class='grammar-underline'>think that</span> he <span class='grammar-underline'>was</span> ahead of his time by 30 years.", ans: "Mendeleev", query: "mendeleev-periodic-table-chemistry" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this sport <span class='grammar-underline'>is more popular than</span> ever in Japan.", h2: "Do you <span class='grammar-underline'>know how to</span> serve properly in volleyball?", h3: "<span class='grammar-underline'>Watching</span> the national team compete always makes me proud.", ans: "Volleyball Japan", query: "japan-volleyball-national-team" },
    { h1: "I <span class='grammar-underline'>must</span> visit this island that <span class='grammar-underline'>is known as</span> Japan's Hawaii.", h2: "Do you <span class='grammar-underline'>know how to</span> get to Okinawa from Tokyo?", h3: "I <span class='grammar-underline'>think that</span> its ocean <span class='grammar-underline'>is as beautiful as</span> any in the world.", ans: "Okinawa", query: "okinawa-japan-tropical-island" },
    { h1: "<span class='grammar-underline'>Studying</span> space exploration <span class='grammar-underline'>is more exciting than</span> almost anything.", h2: "I <span class='grammar-underline'>am sure that</span> Japan's JAXA <span class='grammar-underline'>has been launched</span> many great missions.", h3: "Do you <span class='grammar-underline'>know how to</span> find JAXA's website to learn more?", ans: "JAXA", query: "jaxa-space-japan-mission" },
    { h1: "This place <span class='grammar-underline'>is visited</span> by over 30 million tourists each year.", h2: "I <span class='grammar-underline'>think that</span> the Louvre <span class='grammar-underline'>is</span> <span class='grammar-underline'>the most visited</span> museum in the world.", h3: "Do you <span class='grammar-underline'>know how to</span> book tickets in advance online?", ans: "The Louvre", query: "louvre-museum-paris-tourists" },
    { h1: "I <span class='grammar-underline'>must</span> say this anime about a volleyball team <span class='grammar-underline'>was made</span> brilliantly.", h2: "<span class='grammar-underline'>Watching</span> Haikyuu <span class='grammar-underline'>is as motivating as</span> going to the gym.", h3: "Do you <span class='grammar-underline'>know how to</span> spike a volleyball like Hinata?", ans: "Haikyuu", query: "haikyuu-volleyball-anime" },
    { h1: "I <span class='grammar-underline'>am going to</span> learn to cook this dish <span class='grammar-underline'>using</span> egg, mirin, and dashi.", h2: "<span class='grammar-underline'>Making</span> tamagoyaki <span class='grammar-underline'>is not as easy as</span> scrambled eggs.", h3: "I <span class='grammar-underline'>must</span> practice rolling the egg in the pan without breaking it.", ans: "Tamagoyaki", query: "tamagoyaki-rolled-omelette-japan" },
    { h1: "I <span class='grammar-underline'>think that</span> Japan's traditional Noh theater <span class='grammar-underline'>is as mysterious as</span> a dream.", h2: "I <span class='grammar-underline'>must</span> learn about Zeami, who <span class='grammar-underline'>was considered</span> the father of Noh.", h3: "Do you <span class='grammar-underline'>know how to</span> recognize a Noh mask character?", ans: "Noh Theater", query: "noh-theater-zeami-mask" }
  ],
  JHS3: [
    { h1: "This anime features a boy <span class='grammar-underline'>living</span> alone on a deserted island.", h2: "It shows a character <span class='grammar-underline'>struggling</span> to survive in a harsh world.", h3: "Children <span class='grammar-underline'>stranded</span> without adults must make their own rules.", ans: "Lord of the Flies", query: "lord-flies-stranded-survival" },
    { h1: "The woman <span class='grammar-underline'>standing</span> next to the emperor was his advisor.", h2: "The manuscript <span class='grammar-underline'>written</span> by Murasaki Shikibu is the world's first novel.", h3: "This story, <span class='grammar-underline'>set</span> in ancient Japan, follows Prince Genji.", ans: "Tale of Genji", query: "tale-of-genji-murasaki" },
    { h1: "The scientist <span class='grammar-underline'>known</span> for relativity changed physics forever.", h2: "The equation <span class='grammar-underline'>written</span> on the blackboard is E=mc².", h3: "A theory <span class='grammar-underline'>developed</span> by Einstein still guides science today.", ans: "Einstein E=mc2", query: "einstein-emc2-theory" },
    { h1: "The country <span class='grammar-underline'>called</span> the 'Hermit Kingdom' rarely opens to the world.", h2: "A nation <span class='grammar-underline'>divided</span> after World War Two still seeks reunification.", h3: "North Korea, <span class='grammar-underline'>bordered</span> by China and South Korea, remains isolated.", ans: "North Korea", query: "north-korea-hermit-kingdom" },
    { h1: "The tower <span class='grammar-underline'>built</span> in 1889 was once considered an eyesore.", h2: "A structure <span class='grammar-underline'>designed</span> by Gustave Eiffel now attracts millions.", h3: "The iron monument, <span class='grammar-underline'>located</span> in Paris, is France's greatest symbol.", ans: "Eiffel Tower History", query: "eiffel-tower-1889-history" },
    { h1: "A student <span class='grammar-underline'>born</span> in Scotland became a world-famous inventor.", h2: "The device <span class='grammar-underline'>created</span> by Alexander Bell revolutionized communication.", h3: "The patent <span class='grammar-underline'>filed</span> in 1876 changed the world forever.", ans: "Telephone Patent", query: "bell-telephone-patent-1876" },
    { h1: "The tradition <span class='grammar-underline'>practiced</span> during obon involves dancing in circles.", h2: "Bon Odori, <span class='grammar-underline'>performed</span> across Japan, honors the dead.", h3: "The drums <span class='grammar-underline'>played</span> at these festivals keep the beat alive.", ans: "Bon Odori", query: "bon-odori-obon-circle-dance" },
    { h1: "The singer <span class='grammar-underline'>loved</span> by millions was born in Osaka, Japan.", h2: "The songs <span class='grammar-underline'>written</span> by Utada Hikaru defined a generation.", h3: "Her voice, <span class='grammar-underline'>heard</span> in Final Fantasy X, still moves fans.", ans: "Utada Hikaru", query: "utada-hikaru-jpop-singer" },
    { h1: "The explorer <span class='grammar-underline'>named</span> Amerigo Vespucci gave America its name.", h2: "A continent <span class='grammar-underline'>discovered</span> later was labeled after him on maps.", h3: "Maps <span class='grammar-underline'>printed</span> in 1507 were the first to use the name America.", ans: "Amerigo Vespucci", query: "amerigo-vespucci-explorer" },
    { h1: "A robot <span class='grammar-underline'>designed</span> in Japan helped care for elderly people.", h2: "Technology <span class='grammar-underline'>created</span> by Honda called ASIMO amazed the world.", h3: "The machine, <span class='grammar-underline'>built</span> to walk like humans, opened a new era.", ans: "ASIMO Honda", query: "asimo-honda-robot-japan" }
  ]
},

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 14  |  July, 4th Week  (Summer Break begins)      ║
// ║  JHS1: Mixed review — fun summer topics                 ║
// ║  JHS2: Mixed review — fun summer topics                 ║
// ║  JHS3: Mixed review — fun summer topics                 ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_14: {
  JHS1: [
    { h1: "<span class='grammar-underline'>What</span> festival in Japan <span class='grammar-underline'>has</span> giant floats and music in Akita?", h2: "I <span class='grammar-underline'>want to</span> see the tall bamboo poles with paper lanterns.", h3: "The Kanto Matsuri performers <span class='grammar-underline'>can balance</span> the poles on their bodies.", ans: "Kanto Matsuri", query: "kanto-matsuri-akita-festival" },
    { h1: "I <span class='grammar-underline'>like eating</span> this cold noodle dish popular in Japanese summers.", h2: "<span class='grammar-underline'>How do</span> you eat somen? Dip it in cold tsuyu broth!", h3: "The noodles <span class='grammar-underline'>flow</span> down a bamboo water slide in Nagashi Somen.", ans: "Somen", query: "somen-noodles-japan-summer" },
    { h1: "I <span class='grammar-underline'>can see</span> millions of stars at this famous summer astronomy festival.", h2: "<span class='grammar-underline'>Where is</span> it? In the dark skies of Nagano in late summer.", h3: "Stargazers <span class='grammar-underline'>are setting</span> up telescopes to see the Milky Way.", ans: "Stargazing Japan", query: "milky-way-summer-japan-night" },
    { h1: "These tiny yellow insects <span class='grammar-underline'>glow</span> near rivers on warm summer nights.", h2: "<span class='grammar-underline'>Where can</span> you see them? Near streams in rural Japan.", h3: "Children <span class='grammar-underline'>love catching</span> these magical lights in the dark.", ans: "Fireflies", query: "fireflies-hotaru-japan-summer" },
    { h1: "<span class='grammar-underline'>What is</span> the traditional Japanese game where you <span class='grammar-underline'>try</span> to catch goldfish?", h2: "I <span class='grammar-underline'>played</span> this at the natsu matsuri last year!", h3: "You <span class='grammar-underline'>use</span> a thin paper scoop that <span class='grammar-underline'>breaks</span> easily.", ans: "Kingyo Sukui", query: "kingyo-sukui-goldfish-scooping" },
    { h1: "I <span class='grammar-underline'>am going to</span> eat this tropical fruit with a hard shell and sweet yellow flesh.", h2: "The pineapple <span class='grammar-underline'>grows</span> in places like Hawaii, Taiwan, and Thailand.", h3: "<span class='grammar-underline'>How many</span> pineapples <span class='grammar-underline'>do</span> you need for pineapple juice?", ans: "Pineapple", query: "pineapple-tropical-fruit" },
    { h1: "<span class='grammar-underline'>Who is</span> the Summer Wars character who <span class='grammar-underline'>fights</span> an AI in a virtual world?", h2: "The Mamoru Hosoda film <span class='grammar-underline'>shows</span> family teamwork saving the world.", h3: "Kenji <span class='grammar-underline'>is trying</span> to fix a network called OZ.", ans: "Summer Wars", query: "summer-wars-anime-hosoda" },
    { h1: "I <span class='grammar-underline'>love</span> this cold sweet purple drink popular in Japan summer festivals.", h2: "<span class='grammar-underline'>What is</span> it called? Ramune soda in grape flavor!", h3: "You <span class='grammar-underline'>have to</span> push the glass marble to open the bottle.", ans: "Ramune", query: "ramune-soda-japan" },
    { h1: "The children <span class='grammar-underline'>were splashing</span> water at each other in this famous summer fight.", h2: "In Somin Sai festival, participants <span class='grammar-underline'>throw</span> buckets of cold water.", h3: "<span class='grammar-underline'>How many</span> people <span class='grammar-underline'>join</span> these water festivals across Japan?", ans: "Water Festival Japan", query: "water-festival-japan-summer" },
    { h1: "I <span class='grammar-underline'>can hear</span> this insect's loud summer song in Japanese forests.", h2: "<span class='grammar-underline'>When do</span> cicadas appear? From July to September in Japan.", h3: "The sound they <span class='grammar-underline'>make</span> is called 'min-min-min' or 'tsuku-tsuku'.", ans: "Cicada", query: "cicada-semi-japan-summer" }
  ],
  JHS2: [
    { h1: "I <span class='grammar-underline'>am going to</span> watch the Tanabata fireworks in Sendai this August.", h2: "I <span class='grammar-underline'>am sure that</span> Sendai's decorations <span class='grammar-underline'>are the most beautiful</span> in Japan.", h3: "<span class='grammar-underline'>Hanging</span> colorful strips on bamboo <span class='grammar-underline'>is the most popular</span> tradition.", ans: "Tanabata Sendai", query: "tanabata-sendai-festival" },
    { h1: "I <span class='grammar-underline'>think that</span> this sport combining surfing and paddling <span class='grammar-underline'>is becoming</span> more popular.", h2: "Do you <span class='grammar-underline'>know how to</span> stand and balance on a SUP board?", h3: "SUP paddleboarding <span class='grammar-underline'>is as relaxing as</span> meditation on the water.", ans: "Paddleboarding", query: "stand-up-paddleboard-sup" },
    { h1: "I <span class='grammar-underline'>must</span> learn about this Japanese sport played on a beach in summer.", h2: "<span class='grammar-underline'>Playing</span> beach volleyball <span class='grammar-underline'>requires</span> agility and teamwork.", h3: "Japanese pairs <span class='grammar-underline'>have been competing</span> at the Olympics in this sport.", ans: "Beach Volleyball", query: "beach-volleyball-japan-olympics" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this Japanese delicacy eaten in summer <span class='grammar-underline'>is</span> eel.", h2: "<span class='grammar-underline'>Eating</span> unaju <span class='grammar-underline'>is said to give</span> you energy for the heat.", h3: "Do you <span class='grammar-underline'>know how to</span> prepare kabayaki grilled eel properly?", ans: "Unagi Eel", query: "unagi-eel-summer-japan" },
    { h1: "I <span class='grammar-underline'>think that</span> this tropical island group <span class='grammar-underline'>is more beautiful than</span> anywhere in Japan.", h2: "Do you <span class='grammar-underline'>know how to</span> reach Miyako Island from Tokyo by plane?", h3: "<span class='grammar-underline'>Snorkeling</span> in Miyako's waters <span class='grammar-underline'>is as amazing as</span> the Great Barrier Reef.", ans: "Miyako Island", query: "miyako-island-okinawa-snorkeling" },
    { h1: "I <span class='grammar-underline'>must</span> visit the country where Songkran water festival <span class='grammar-underline'>is celebrated</span>.", h2: "I <span class='grammar-underline'>think that</span> Thailand's New Year festival <span class='grammar-underline'>is more fun than</span> any other.", h3: "<span class='grammar-underline'>Getting soaked</span> with water <span class='grammar-underline'>is</span> the whole point of this celebration!", ans: "Songkran Thailand", query: "songkran-water-festival-thailand" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this sea creature stings painfully in summer waters.", h2: "<span class='grammar-underline'>Swimming</span> near jellyfish <span class='grammar-underline'>is not as safe as</span> people think.", h3: "Do you <span class='grammar-underline'>know how to</span> treat a jellyfish sting on the beach?", ans: "Jellyfish", query: "jellyfish-sting-beach" },
    { h1: "I <span class='grammar-underline'>am going to</span> try this Okinawan dish made with bitter melon and tofu.", h2: "I <span class='grammar-underline'>think that</span> goya chanpuru <span class='grammar-underline'>is more nutritious than</span> most summer foods.", h3: "Do you <span class='grammar-underline'>know how to</span> cook this famous Okinawan superfood?", ans: "Goya Chanpuru", query: "goya-chanpuru-okinawa-food" },
    { h1: "I <span class='grammar-underline'>must</span> see the famous outdoor art festival on this Japanese island.", h2: "I <span class='grammar-underline'>think that</span> Naoshima Island <span class='grammar-underline'>is more beautiful than</span> any art museum.", h3: "<span class='grammar-underline'>Exploring</span> modern art in nature <span class='grammar-underline'>is as inspiring as</span> a gallery visit.", ans: "Naoshima Island", query: "naoshima-island-art-japan" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this food competition <span class='grammar-underline'>is</span> one of Japan's most unusual events.", h2: "Do you <span class='grammar-underline'>know how to</span> eat a whole bowl of kakigori ice shavings quickly?", h3: "The brain freeze from <span class='grammar-underline'>eating</span> it fast <span class='grammar-underline'>is as painful as</span> hitting a wall!", ans: "Kakigori", query: "kakigori-shaved-ice-japan" }
  ],
  JHS3: [
    { h1: "I <span class='grammar-underline'>have been looking forward to</span> visiting this cold waterfall in Nachi, Wakayama.", h2: "Nachi Falls is <span class='grammar-underline'>a waterfall that</span> drops 133 meters in one single plunge.", h3: "It is <span class='grammar-underline'>a sacred site that</span> attracts pilgrims on the Kumano Kodo trail.", ans: "Nachi Falls", query: "nachi-falls-wakayama-japan" },
    { h1: "I <span class='grammar-underline'>wish I could</span> dive with whale sharks in this island prefecture.", h2: "Okinawa is <span class='grammar-underline'>a place where</span> you can snorkel with gentle giants.", h3: "It is <span class='grammar-underline'>the most peaceful</span> experience <span class='grammar-underline'>that</span> divers ever describe.", ans: "Whale Shark Okinawa", query: "whale-shark-okinawa-diving" },
    { h1: "This dance <span class='grammar-underline'>performed</span> in August in Awa, Tokushima, involves marching steps.", h2: "It is <span class='grammar-underline'>a festival that</span> over 1 million people attend each year.", h3: "The dancers <span class='grammar-underline'>dressed</span> in yukata chant 'Yattosa!' as they move.", ans: "Awa Odori", query: "awa-odori-tokushima-festival" },
    { h1: "He said <span class='grammar-underline'>that</span> his greatest album <span class='grammar-underline'>had been</span> inspired by a hot summer.", h2: "If Stevie Wonder <span class='grammar-underline'>were</span> performing tonight, tickets <span class='grammar-underline'>would</span> sell in seconds.", h3: "Songs <span class='grammar-underline'>written</span> by true legends <span class='grammar-underline'>are enjoyed</span> across generations.", ans: "Stevie Wonder", query: "stevie-wonder-musician" },
    { h1: "This ice festival <span class='grammar-underline'>held</span> in Sapporo every February draws millions of visitors.", h2: "It is <span class='grammar-underline'>an event where</span> ice sculptors carve giant frozen buildings.", h3: "The sculptures, <span class='grammar-underline'>lit</span> at night, look like frozen dreams.", ans: "Sapporo Snow Festival", query: "sapporo-snow-festival-hokkaido" },
    { h1: "I <span class='grammar-underline'>have been reading</span> this classic story about a boy <span class='grammar-underline'>raised</span> by wolves.", h2: "Mowgli is <span class='grammar-underline'>a character who</span> learns life lessons from jungle animals.", h3: "The Jungle Book, <span class='grammar-underline'>written</span> by Kipling, <span class='grammar-underline'>has been adapted</span> into films.", ans: "Jungle Book", query: "jungle-book-mowgli-kipling" },
    { h1: "I <span class='grammar-underline'>wish I could</span> attend this famous surf contest held in Hawaii every winter.", h2: "The Banzai Pipeline is <span class='grammar-underline'>a wave that</span> only the bravest surfers ride.", h3: "It is <span class='grammar-underline'>a sport where</span> athletes read the ocean like a language.", ans: "Pipeline Surfing Hawaii", query: "pipeline-surfing-hawaii-banzai" },
    { h1: "Scientists said <span class='grammar-underline'>that</span> this year's heat wave <span class='grammar-underline'>was</span> the worst in recorded history.", h2: "The temperature <span class='grammar-underline'>recorded</span> in southern Japan <span class='grammar-underline'>was</span> above 38°C.", h3: "Experts warned <span class='grammar-underline'>that</span> climate change <span class='grammar-underline'>was making</span> summers dangerous.", ans: "Heat Wave", query: "heat-wave-japan-climate" },
    { h1: "If I <span class='grammar-underline'>could</span> visit any sea in the world, I <span class='grammar-underline'>would</span> choose the Maldives.", h2: "It is <span class='grammar-underline'>a place where</span> bioluminescent plankton <span class='grammar-underline'>glow</span> on the beach at night.", h3: "Scientists <span class='grammar-underline'>have confirmed</span> that the Maldives <span class='grammar-underline'>may be submerged</span> by 2100.", ans: "Maldives", query: "maldives-bioluminescent-beach" },
    { h1: "I <span class='grammar-underline'>have been watching</span> this Ghibli film about a girl living by the ocean.", h2: "Umi ga Kikoeru is <span class='grammar-underline'>a story that</span> was made before the Ghibli classics.", h3: "It is <span class='grammar-underline'>a film where</span> teenage romance unfolds against a Kochi backdrop.", ans: "Ocean Waves Ghibli", query: "ocean-waves-ghibli-film" }
  ]
},

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 15  |  September, 1st Week  (Term 2 Resumes)      ║
// ║  JHS1: 3rd person singular -s (he/she/it + verb)        ║
// ║  JHS2: Mixed review — back to school refresh            ║
// ║  JHS3: Mixed review — back to school refresh            ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_15: {
  JHS1: [
    { h1: "This superhero <span class='grammar-underline'>wears</span> a red cape and <span class='grammar-underline'>flies</span> faster than a bullet.", h2: "He <span class='grammar-underline'>lives</span> in Metropolis and <span class='grammar-underline'>works</span> as a reporter by day.", h3: "Clark Kent <span class='grammar-underline'>hides</span> his identity and <span class='grammar-underline'>fights</span> for justice.", ans: "Superman", query: "superman-clark-kent-hero" },
    { h1: "This planet <span class='grammar-underline'>has</span> beautiful rings made of ice and rocks.", h2: "It <span class='grammar-underline'>orbits</span> the sun but <span class='grammar-underline'>takes</span> 29 Earth years to go around once.", h3: "Saturn <span class='grammar-underline'>looks</span> stunning through a telescope.", ans: "Saturn", query: "saturn-rings-planet" },
    { h1: "This chef <span class='grammar-underline'>cooks</span> ramen in his famous shop in Sapporo every day.", h2: "He <span class='grammar-underline'>wakes up</span> at 4 AM and <span class='grammar-underline'>prepares</span> fresh broth for hours.", h3: "The miso ramen he <span class='grammar-underline'>makes</span> <span class='grammar-underline'>has</span> a hundred-year family recipe.", ans: "Ramen Chef", query: "sapporo-ramen-chef-miso" },
    { h1: "This character <span class='grammar-underline'>fights</span> with a lightsaber and <span class='grammar-underline'>uses</span> the Force.", h2: "He <span class='grammar-underline'>trains</span> in the Jedi Academy and <span class='grammar-underline'>defeats</span> the Dark Side.", h3: "Luke Skywalker <span class='grammar-underline'>believes</span> in good even when evil <span class='grammar-underline'>seems</span> stronger.", ans: "Luke Skywalker", query: "star-wars-luke-skywalker" },
    { h1: "This traditional puppet <span class='grammar-underline'>dances</span> on strings controlled by a master.", h2: "It <span class='grammar-underline'>wears</span> colorful costumes and <span class='grammar-underline'>tells</span> old Japanese stories.", h3: "Bunraku puppet theater <span class='grammar-underline'>uses</span> three puppeteers for one figure.", ans: "Bunraku", query: "bunraku-puppet-theater-japan" },
    { h1: "This Japanese deer <span class='grammar-underline'>lives</span> freely in Nara Park and <span class='grammar-underline'>bows</span> for crackers.", h2: "It <span class='grammar-underline'>approaches</span> tourists and <span class='grammar-underline'>eats</span> senbei from their hands.", h3: "The deer <span class='grammar-underline'>runs</span> wild among ancient temple buildings.", ans: "Nara Deer", query: "nara-deer-park-japan" },
    { h1: "This musician <span class='grammar-underline'>plays</span> classical piano and <span class='grammar-underline'>tours</span> the world.", h2: "She <span class='grammar-underline'>practices</span> eight hours a day and <span class='grammar-underline'>performs</span> at Carnegie Hall.", h3: "Lang Lang <span class='grammar-underline'>inspires</span> millions of young pianists globally.", ans: "Lang Lang", query: "lang-lang-pianist" },
    { h1: "This sea creature <span class='grammar-underline'>moves</span> by shooting water jets backwards.", h2: "It <span class='grammar-underline'>changes</span> color and <span class='grammar-underline'>hides</span> by imitating rocks and coral.", h3: "The cuttlefish <span class='grammar-underline'>has</span> one of the highest intelligence levels in the ocean.", ans: "Cuttlefish", query: "cuttlefish-color-change-ocean" },
    { h1: "This woman <span class='grammar-underline'>rules</span> Wakanda and <span class='grammar-underline'>fights</span> for her people in the Marvel universe.", h2: "The Dora Milaje warrior <span class='grammar-underline'>trains</span> every day and <span class='grammar-underline'>never backs down</span>.", h3: "The Black Panther story <span class='grammar-underline'>celebrates</span> African strength and culture.", ans: "Black Panther", query: "black-panther-wakanda-marvel" },
    { h1: "This island <span class='grammar-underline'>sits</span> between Honshu and Kyushu and <span class='grammar-underline'>has</span> many onsen.", h2: "Beppu hot spring <span class='grammar-underline'>produces</span> more geothermal steam than almost anywhere.", h3: "Beppu <span class='grammar-underline'>attracts</span> millions of visitors who <span class='grammar-underline'>come</span> to relax in the heat.", ans: "Beppu", query: "beppu-hot-springs-oita" }
  ],
  JHS2: [
    { h1: "I <span class='grammar-underline'>think that</span> this country with a red maple leaf flag <span class='grammar-underline'>is one of the friendliest</span> in the world.", h2: "I <span class='grammar-underline'>am sure that</span> Niagara Falls <span class='grammar-underline'>is more impressive</span> in person than in photos.", h3: "Do you <span class='grammar-underline'>know how to</span> say hello in both English and French there?", ans: "Canada", query: "canada-niagara-falls-maple" },
    { h1: "<span class='grammar-underline'>Returning</span> to school after summer <span class='grammar-underline'>is</span> a mix of excitement and nerves.", h2: "I <span class='grammar-underline'>must</span> organize my textbooks and check my school supply list.", h3: "I <span class='grammar-underline'>am going to</span> work harder this term and improve my English test score.", ans: "Back to School", query: "back-to-school-japan-september" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this country <span class='grammar-underline'>is known as</span> the 'Land of Fire and Ice'.", h2: "Iceland <span class='grammar-underline'>is not as warm as</span> most people expect year round.", h3: "Do you <span class='grammar-underline'>know how to</span> see the Northern Lights there in winter?", ans: "Iceland", query: "iceland-fire-ice-aurora" },
    { h1: "I <span class='grammar-underline'>think that</span> this ancient Greek structure <span class='grammar-underline'>is</span> <span class='grammar-underline'>one of the most important</span> in history.", h2: "The Parthenon <span class='grammar-underline'>was built</span> to honor the goddess Athena.", h3: "Do you <span class='grammar-underline'>know how to</span> find Athens on a map of Europe?", ans: "Parthenon", query: "parthenon-athens-acropolis" },
    { h1: "I <span class='grammar-underline'>must</span> try this fermented rice drink popular in Japanese autumn festivals.", h2: "Do you <span class='grammar-underline'>know how to</span> tell the difference between nigori and clear sake?", h3: "<span class='grammar-underline'>Tasting</span> local sake at an autumn harvest festival <span class='grammar-underline'>is a special</span> experience.", ans: "Sake", query: "sake-japanese-rice-wine" },
    { h1: "I <span class='grammar-underline'>am going to</span> study the life of this scientist who won the Nobel Prize in Physics.", h2: "Yukawa Hideki <span class='grammar-underline'>was</span> <span class='grammar-underline'>the first</span> Japanese person to win a Nobel Prize.", h3: "Do you <span class='grammar-underline'>know how to</span> explain what a meson particle is?", ans: "Yukawa Hideki Nobel", query: "yukawa-hideki-meson-nobel" },
    { h1: "I <span class='grammar-underline'>think that</span> this anime about a young chef <span class='grammar-underline'>is</span> <span class='grammar-underline'>more motivating than</span> any sports anime.", h2: "<span class='grammar-underline'>Watching</span> Shokugeki no Soma <span class='grammar-underline'>makes</span> me want to cook immediately.", h3: "I <span class='grammar-underline'>must</span> try making the omurice Soma <span class='grammar-underline'>is famous for</span>.", ans: "Food Wars", query: "food-wars-shokugeki-soma-anime" },
    { h1: "I <span class='grammar-underline'>am sure that</span> this structure connects two continents across a narrow sea.", h2: "The Bosphorus Bridge <span class='grammar-underline'>was built</span> to connect Europe and Asia in Istanbul.", h3: "Do you <span class='grammar-underline'>know how to</span> travel from one continent to the other in minutes?", ans: "Bosphorus Bridge", query: "bosphorus-bridge-istanbul-turkey" },
    { h1: "I <span class='grammar-underline'>must</span> learn about this volcanic archipelago discovered by Darwin.", h2: "I <span class='grammar-underline'>think that</span> Galapagos tortoises <span class='grammar-underline'>are the most ancient</span> creatures alive.", h3: "Do you <span class='grammar-underline'>know how to</span> get to the Galapagos Islands from Japan?", ans: "Galapagos Islands", query: "galapagos-islands-tortoises" },
    { h1: "I <span class='grammar-underline'>am going to</span> read this classic manga about a boy who can see ghosts.", h2: "I <span class='grammar-underline'>think that</span> Bleach <span class='grammar-underline'>is just as exciting as</span> Naruto or Dragon Ball.", h3: "Do you <span class='grammar-underline'>know how to</span> distinguish between a Shinigami and a Hollow?", ans: "Bleach", query: "bleach-ichigo-shinigami-manga" }
  ],
  JHS3: [
    { h1: "I <span class='grammar-underline'>have been practicing</span> for this exam that <span class='grammar-underline'>determines</span> high school entry.", h2: "The entrance exam <span class='grammar-underline'>is taken</span> by most 3rd year JHS students in February.", h3: "Students <span class='grammar-underline'>who prepare well</span> have <span class='grammar-underline'>a much better chance</span> of success.", ans: "High School Entrance Exam", query: "japan-high-school-entrance-exam" },
    { h1: "The organization <span class='grammar-underline'>that</span> promotes peace between nations <span class='grammar-underline'>was founded</span> in 1945.", h2: "The United Nations <span class='grammar-underline'>is an institution that</span> Japan joined in 1956.", h3: "It is <span class='grammar-underline'>a body where</span> world leaders discuss war, hunger, and health.", ans: "United Nations", query: "united-nations-peacekeeping" },
    { h1: "This concept <span class='grammar-underline'>that</span> makes Japanese people continue despite challenges <span class='grammar-underline'>is called</span> grit.", h2: "It is <span class='grammar-underline'>an attitude that</span> values effort over natural ability.", h3: "Students <span class='grammar-underline'>who apply</span> ganbaru spirit <span class='grammar-underline'>tend to</span> achieve their goals.", ans: "Ganbaru / Grit", query: "ganbaru-japanese-grit-spirit" },
    { h1: "The musician <span class='grammar-underline'>who</span> composed Beethoven's Fifth <span class='grammar-underline'>was</span> deaf when he wrote it.", h2: "It is <span class='grammar-underline'>a symphony that</span> begins with four of history's most famous notes.", h3: "The piece <span class='grammar-underline'>that opens</span> with 'ta-ta-ta-TAA' <span class='grammar-underline'>has been performed</span> countless times.", ans: "Beethoven's 5th", query: "beethoven-fifth-symphony" },
    { h1: "I <span class='grammar-underline'>have been thinking about</span> how this French writer <span class='grammar-underline'>predicted</span> submarines.", h2: "Jules Verne is <span class='grammar-underline'>an author who</span> imagined technology 100 years early.", h3: "Twenty Thousand Leagues Under the Sea is <span class='grammar-underline'>a novel that</span> still fascinates readers.", ans: "Jules Verne", query: "jules-verne-twenty-thousand-leagues" },
    { h1: "The invention <span class='grammar-underline'>that</span> made long-distance travel possible <span class='grammar-underline'>was</span> the steam engine.", h2: "James Watt is <span class='grammar-underline'>the person who</span> improved steam power in the 18th century.", h3: "It is <span class='grammar-underline'>a technology that</span> powered the Industrial Revolution worldwide.", ans: "Steam Engine", query: "steam-engine-james-watt-industrial" },
    { h1: "The volcanic island <span class='grammar-underline'>where</span> a famous 1945 battle took place <span class='grammar-underline'>is Iwo Jima</span>.", h2: "The flag <span class='grammar-underline'>raised</span> on Mount Suribachi <span class='grammar-underline'>became</span> one of history's most iconic photos.", h3: "It is <span class='grammar-underline'>a moment that</span> <span class='grammar-underline'>has been remembered</span> for its courage.", ans: "Iwo Jima", query: "iwo-jima-battle-flag-ww2" },
    { h1: "She is <span class='grammar-underline'>a writer who</span> created the children's book series Momo.", h2: "Michael Ende is <span class='grammar-underline'>the German author who</span> also wrote The Neverending Story.", h3: "It is <span class='grammar-underline'>a novel that</span> teaches children the value of time and imagination.", ans: "Momo Michael Ende", query: "momo-michael-ende-book" },
    { h1: "I <span class='grammar-underline'>have been admiring</span> this singer <span class='grammar-underline'>who</span> performs in five languages.", h2: "Celine Dion is <span class='grammar-underline'>an artist who</span> sold over 200 million records.", h3: "My Heart Will Go On is <span class='grammar-underline'>the song that</span> made the Titanic film unforgettable.", ans: "Celine Dion", query: "celine-dion-titanic-singer" },
    { h1: "The ancient sport <span class='grammar-underline'>practiced</span> in Greece 2700 years ago <span class='grammar-underline'>inspired</span> our Olympics.", h2: "Athletes <span class='grammar-underline'>competing</span> in ancient Olympia <span class='grammar-underline'>were</span> treated like gods.", h3: "It is <span class='grammar-underline'>a tradition that</span> <span class='grammar-underline'>has survived</span> and grown into a global event.", ans: "Ancient Olympics", query: "ancient-greek-olympics-history" }
  ]
},

// ╔══════════════════════════════════════════════════════════╗
// ║  WEEK 16  |  September, 2nd Week                        ║
// ║  JHS1: Does/doesn't — 3rd person questions/negatives    ║
// ║  JHS2: "want + object + to" / "tell + object + to"      ║
// ║  JHS3: Present perfect — "for / since / already / yet" ║
// ╚══════════════════════════════════════════════════════════╝
WEEK_16: {
  JHS1: [
    { h1: "<span class='grammar-underline'>Does</span> this small country in Western Europe produce the most chocolate?", h2: "Belgium <span class='grammar-underline'>doesn't have</span> much land but <span class='grammar-underline'>has</span> amazing chocolate shops.", h3: "It <span class='grammar-underline'>produces</span> over 250,000 tons of chocolate every year.", ans: "Belgium", query: "belgium-chocolate-production" },
    { h1: "<span class='grammar-underline'>Does</span> this insect really dance to communicate with its friends?", h2: "A honeybee <span class='grammar-underline'>doesn't use</span> words but <span class='grammar-underline'>uses</span> a waggle dance.", h3: "It <span class='grammar-underline'>tells</span> other bees exactly where flowers are.", ans: "Honeybee", query: "honeybee-waggle-dance" },
    { h1: "<span class='grammar-underline'>Does</span> this blue Pokemon ever evolve from a small sea creature?", h2: "Magikarp <span class='grammar-underline'>doesn't do</span> much in battle — only splashes.", h3: "But it <span class='grammar-underline'>evolves</span> into the powerful Gyarados later!", ans: "Magikarp", query: "magikarp-gyarados-pokemon" },
    { h1: "This city <span class='grammar-underline'>doesn't</span> have any cars — it only <span class='grammar-underline'>uses</span> boats and walking.", h2: "<span class='grammar-underline'>Does</span> Venice in Italy really have canals as streets?", h3: "Yes, a gondola <span class='grammar-underline'>glides</span> through its waterways every day.", ans: "Venice", query: "venice-gondola-canal" },
    { h1: "<span class='grammar-underline'>Does</span> this anime protagonist ever give up on his dream to become a hero?", h2: "No, Deku <span class='grammar-underline'>doesn't stop</span> — he trains harder every day.", h3: "He <span class='grammar-underline'>believes</span> in himself even when others <span class='grammar-underline'>doubt</span> him.", ans: "Deku Midoriya", query: "deku-midoriya-my-hero-academia" },
    { h1: "The moon <span class='grammar-underline'>doesn't produce</span> its own light — it only reflects the sun.", h2: "<span class='grammar-underline'>Does</span> the moon really affect ocean tides on Earth?", h3: "Yes, it <span class='grammar-underline'>pulls</span> on ocean water and <span class='grammar-underline'>causes</span> tides.", ans: "Moon Tides", query: "moon-tides-gravity-earth" },
    { h1: "This Japanese TV host <span class='grammar-underline'>doesn't just</span> read news — he <span class='grammar-underline'>makes</span> people laugh.", h2: "<span class='grammar-underline'>Does</span> Tamori still <span class='grammar-underline'>host</span> TV shows on NHK and Fuji TV?", h3: "Yes, he <span class='grammar-underline'>presents</span> shows that <span class='grammar-underline'>run</span> for decades.", ans: "Tamori", query: "tamori-japanese-tv-host" },
    { h1: "This fast food chain <span class='grammar-underline'>doesn't only</span> sell hamburgers — it also <span class='grammar-underline'>sells</span> rice burgers.", h2: "<span class='grammar-underline'>Does</span> Japan have a unique McDonald's menu compared to other countries?", h3: "Yes, McDonalds Japan <span class='grammar-underline'>offers</span> shrimp burgers and sakura flavors.", ans: "McDonald's Japan", query: "mcdonalds-japan-rice-burger" },
    { h1: "<span class='grammar-underline'>Does</span> this marine mammal actually sleep with one eye open?", h2: "The dolphin <span class='grammar-underline'>doesn't sleep</span> like a human — half its brain stays awake.", h3: "It <span class='grammar-underline'>breathes</span> consciously so it <span class='grammar-underline'>can't</span> fully shut down.", ans: "Dolphin Sleep", query: "dolphin-sleep-one-eye-open" },
    { h1: "The Great Wall of China <span class='grammar-underline'>doesn't appear</span> from outer space — that's a myth!", h2: "<span class='grammar-underline'>Does</span> the wall really stretch over 21,000 kilometers long?", h3: "Yes, it <span class='grammar-underline'>winds</span> across mountains and deserts over millennia.", ans: "Great Wall Myth", query: "great-wall-myth-space-visible" }
  ],
  JHS2: [
    { h1: "The teacher <span class='grammar-underline'>wants her students to read</span> more books over the holidays.", h2: "She <span class='grammar-underline'>tells them to write</span> a short summary of each book.", h3: "She <span class='grammar-underline'>encourages them to visit</span> the city library every week.", ans: "Reading Habit", query: "reading-habit-library-students" },
    { h1: "The coach <span class='grammar-underline'>wants the team to practice</span> passing drills before the match.", h2: "He <span class='grammar-underline'>tells the players to arrive</span> thirty minutes before warm-up.", h3: "He <span class='grammar-underline'>asks them to believe</span> in each other and work as one.", ans: "Soccer Practice", query: "soccer-team-training-coach" },
    { h1: "The documentary <span class='grammar-underline'>wants viewers to think about</span> climate change seriously.", h2: "It <span class='grammar-underline'>tells people to reduce</span> single-use plastic starting today.", h3: "It <span class='grammar-underline'>encourages everyone to use</span> reusable bags and bottles.", ans: "Climate Documentary", query: "climate-documentary-plastic-pollution" },
    { h1: "Miyazaki Hayao <span class='grammar-underline'>wants his films to teach</span> children about nature's beauty.", h2: "He <span class='grammar-underline'>tells animators to draw</span> every leaf and raindrop by hand.", h3: "He <span class='grammar-underline'>asks audiences to feel</span> deeply when watching his work.", ans: "Hayao Miyazaki", query: "hayao-miyazaki-film-philosophy" },
    { h1: "The chef <span class='grammar-underline'>wants his students to understand</span> the importance of fresh ingredients.", h2: "He <span class='grammar-underline'>tells them to visit</span> the market every morning before cooking.", h3: "He <span class='grammar-underline'>encourages them to taste</span> every ingredient before adding it.", ans: "Culinary School", query: "culinary-school-chef-training" },
    { h1: "The doctor <span class='grammar-underline'>wants patients to sleep</span> at least eight hours every night.", h2: "She <span class='grammar-underline'>tells teenagers to put</span> their phones away before bed.", h3: "She <span class='grammar-underline'>encourages everyone to exercise</span> three times a week.", ans: "Healthy Lifestyle", query: "healthy-sleep-exercise-doctor" },
    { h1: "The anime director <span class='grammar-underline'>wants young fans to pursue</span> their dreams fearlessly.", h2: "Makoto Shinkai <span class='grammar-underline'>tells students to look</span> for beauty in everyday things.", h3: "He <span class='grammar-underline'>encourages people to find</span> magic in rain and city lights.", ans: "Makoto Shinkai", query: "makoto-shinkai-your-name-director" },
    { h1: "The government <span class='grammar-underline'>wants citizens to prepare</span> for natural disasters.", h2: "It <span class='grammar-underline'>tells families to keep</span> a three-day emergency supply kit.", h3: "It <span class='grammar-underline'>encourages everyone to join</span> community disaster training drills.", ans: "Disaster Preparedness", query: "disaster-preparedness-japan" },
    { h1: "The museum guide <span class='grammar-underline'>wants visitors to appreciate</span> traditional Japanese lacquerware.", h2: "She <span class='grammar-underline'>tells them to look closely</span> at the gold maki-e patterns.", h3: "She <span class='grammar-underline'>asks them to imagine</span> craftsmen spending years on one piece.", ans: "Lacquerware Urushi", query: "lacquerware-urushi-japan-craft" },
    { h1: "Yuzuru Hanyu <span class='grammar-underline'>wants young skaters to believe</span> that hard work creates miracles.", h2: "He <span class='grammar-underline'>tells aspiring athletes to fall</span> and get up again, every time.", h3: "He <span class='grammar-underline'>encourages everyone to push</span> beyond what they think is possible.", ans: "Yuzuru Hanyu", query: "yuzuru-hanyu-figure-skating" }
  ],
  JHS3: [
    { h1: "Japan <span class='grammar-underline'>has had</span> the same imperial family <span class='grammar-underline'>for over</span> 1500 years.", h2: "The Chrysanthemum Throne <span class='grammar-underline'>has existed since</span> ancient times.", h3: "Emperor Naruhito <span class='grammar-underline'>has reigned since</span> 2019 in the Reiwa era.", ans: "Japanese Imperial Family", query: "japanese-emperor-imperial-family" },
    { h1: "Researchers <span class='grammar-underline'>have not yet found</span> a cure for Alzheimer's disease.", h2: "Scientists <span class='grammar-underline'>have already identified</span> the protein that causes damage.", h3: "Clinical trials <span class='grammar-underline'>have been underway for</span> more than twenty years.", ans: "Alzheimer's Research", query: "alzheimers-research-cure-progress" },
    { h1: "The Jomon people <span class='grammar-underline'>have lived</span> in Japan <span class='grammar-underline'>for over</span> 14,000 years.", h2: "Their pottery <span class='grammar-underline'>has been</span> the oldest in the world <span class='grammar-underline'>for</span> decades.", h3: "Archaeologists <span class='grammar-underline'>have uncovered</span> their villages <span class='grammar-underline'>since</span> the Meiji era.", ans: "Jomon Culture", query: "jomon-pottery-ancient-japan" },
    { h1: "Messi and Ronaldo <span class='grammar-underline'>have dominated</span> soccer <span class='grammar-underline'>for</span> over 15 years.", h2: "Messi <span class='grammar-underline'>has already won</span> eight Ballon d'Or awards.", h3: "Fans <span class='grammar-underline'>have been debating</span> who is greater <span class='grammar-underline'>since</span> the early 2000s.", ans: "Messi vs Ronaldo", query: "messi-ronaldo-soccer-debate" },
    { h1: "Hayashi Fumio <span class='grammar-underline'>has served</span> as Japan's prime minister <span class='grammar-underline'>since</span> 2023.", h2: "Japan <span class='grammar-underline'>has had</span> many prime ministers <span class='grammar-underline'>over</span> the past two decades.", h3: "Voters <span class='grammar-underline'>have not yet seen</span> a female prime minister in Japan.", ans: "Japan Prime Minister", query: "japan-prime-minister-fumio" },
    { h1: "This anime series <span class='grammar-underline'>has aired</span> <span class='grammar-underline'>for</span> over 25 years without stopping.", h2: "Crayon Shin-chan <span class='grammar-underline'>has been</span> on Japanese TV <span class='grammar-underline'>since</span> 1992.", h3: "Parents and children <span class='grammar-underline'>have watched</span> together <span class='grammar-underline'>for</span> generations.", ans: "Crayon Shin-chan", query: "crayon-shinchan-anime-japan" },
    { h1: "Scientists <span class='grammar-underline'>have already sequenced</span> the entire human genome.", h2: "Researchers <span class='grammar-underline'>have been working</span> on gene therapy <span class='grammar-underline'>for</span> decades.", h3: "CRISPR technology <span class='grammar-underline'>has not yet been approved</span> for human use everywhere.", ans: "Human Genome", query: "human-genome-crispr-gene-editing" },
    { h1: "Tokyo <span class='grammar-underline'>has held</span> the Olympics twice — in 1964 and 2020.", h2: "Japan <span class='grammar-underline'>has competed</span> in the summer Games <span class='grammar-underline'>since</span> 1912.", h3: "Japanese athletes <span class='grammar-underline'>have not yet</span> hosted a third time.", ans: "Japan Olympics History", query: "japan-olympics-1964-2020-history" },
    { h1: "This manga <span class='grammar-underline'>has sold</span> over 500 million copies <span class='grammar-underline'>since</span> 1997.", h2: "Oda Eiichiro <span class='grammar-underline'>has been drawing</span> One Piece <span class='grammar-underline'>for</span> nearly 30 years.", h3: "Fans <span class='grammar-underline'>have been waiting for</span> the final arc <span class='grammar-underline'>for</span> a long time.", ans: "One Piece Longevity", query: "one-piece-manga-500-million" },
    { h1: "This island <span class='grammar-underline'>has been</span> a UNESCO World Heritage Site <span class='grammar-underline'>since</span> 1993.", h2: "Yakushima <span class='grammar-underline'>has had</span> ancient cedar trees <span class='grammar-underline'>for over</span> 7000 years.", h3: "Princess Mononoke's forest <span class='grammar-underline'>was inspired</span> by Yakushima's beauty.", ans: "Yakushima", query: "yakushima-island-cedar-mononoke" }
  ]
},
};
