// Revision Mode Question Banks for Class Quiz
// Grade 1 → reviews Elementary School English
// Grade 2 → reviews JHS Grade 1 content
// Grade 3 → reviews JHS Grade 2 content
// Sources: Here We Go!, New Crown, New Horizon, One World, Sunshine, Blue Sky, New Treasure (2021-2025 editions)

export const revisionQuizData: Record<string, any[]> = {

  // ═══════════════════════════════════════════════════════
  // GRADE 1 — Week 1 Revision (Elementary School English)
  // Focus: greetings, self-introduction, I like / I don't like, Do you...?
  // ═══════════════════════════════════════════════════════
  "rev-1-w1": [
    { id: 1,  question: "Hello! My ___ is Yuki.", options: ["name", "names", "naming", "named"], answer: 0, explanation: "'My name is ___' is the standard way to introduce yourself in English.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "___ are you? I'm fine, thank you!", options: ["How", "What", "Who", "Where"], answer: 0, explanation: "'How are you?' asks about someone's wellbeing. 'I'm fine' is a common reply.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "Which sentence means you LIKE something?", options: ["I can it.", "I have it.", "I like it.", "I do it."], answer: 2, explanation: "'I like ___' expresses that you enjoy or are fond of something.", type: "Best Answer", difficulty: "Easy" },
    { id: 4,  question: "I ___ soccer. It is my favorite sport.", options: ["like", "likes", "am like", "does like"], answer: 0, explanation: "With 'I', use the base form of the verb: 'I like'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 5,  question: "Do you like apples? Yes, I ___.", options: ["do", "does", "am", "can"], answer: 0, explanation: "'Do you like...?' → 'Yes, I do.' / 'No, I don't.'", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 6,  question: "I ___ not like natto.", options: ["do", "does", "am", "is"], answer: 0, explanation: "Negative: 'I do not / don't like ___.' Use 'do' with 'I'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 7,  question: "Which of these is a GREETING?", options: ["Thank you!", "Sorry!", "Hello!", "Goodbye!"], answer: 2, explanation: "'Hello!' is used to greet someone when you first see them.", type: "Best Answer", difficulty: "Easy" },
    { id: 8,  question: "Nice to ___ you!", options: ["meet", "see", "know", "find"], answer: 0, explanation: "'Nice to meet you' is a fixed phrase used the first time you meet someone.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 9,  question: "Excuse ___, can you help me?", options: ["me", "my", "I", "mine"], answer: 0, explanation: "'Excuse me' is a polite phrase to get someone's attention.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 10, question: "Which sentence says you CANNOT do something?", options: ["I can swim.", "I can't swim.", "I like swim.", "I swim."], answer: 1, explanation: "'Can't' (cannot) means you are NOT able to do something.", type: "Best Answer", difficulty: "Easy" },
    { id: 11, question: "I ___ play the piano.", options: ["can", "cans", "do can", "am can"], answer: 0, explanation: "'Can + base verb' expresses ability. No -s is needed.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 12, question: "Can you ride a bike? No, I ___.", options: ["can't", "don't", "am not", "isn't"], answer: 0, explanation: "'Can you...?' → 'No, I can't.' is the correct negative answer.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 13, question: "Which word is a COLOR?", options: ["cat", "run", "blue", "happy"], answer: 2, explanation: "'Blue' is a color. The others are a noun, a verb, and an adjective.", type: "Best Answer", difficulty: "Easy" },
    { id: 14, question: "Which word is a SPORT?", options: ["sushi", "soccer", "sakura", "soba"], answer: 1, explanation: "'Soccer' is a sport. The others are food or a flower.", type: "Best Answer", difficulty: "Easy" },
    { id: 15, question: "I have ___ dogs — Shiro and Kuro.", options: ["two", "second", "twice", "twin"], answer: 0, explanation: "Use numbers (two, three…) to say how many of something.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 16, question: "How ___ apples do you have?", options: ["many", "much", "old", "long"], answer: 0, explanation: "'How many' is used with countable things you can count one by one.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 17, question: "Which is a correct self-introduction?", options: ["I name Ken.", "My name is Ken.", "Name Ken is my.", "Ken is name my."], answer: 1, explanation: "The correct pattern is: 'My name is ___.'", type: "Best Answer", difficulty: "Easy" },
    { id: 18, question: "She ___ from Japan. She is Japanese.", options: ["is", "am", "are", "be"], answer: 0, explanation: "Use 'is' with he, she, and it.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 19, question: "My birthday is ___ March.", options: ["in", "on", "at", "of"], answer: 0, explanation: "Use 'in' with months: 'in March', 'in April'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 20, question: "What does 'Thank you' express?", options: ["a greeting", "an apology", "gratitude", "a question"], answer: 2, explanation: "'Thank you' is used to express thanks or gratitude.", type: "Best Answer", difficulty: "Easy" },
    { id: 21, question: "___ you like pizza? Yes, I do!", options: ["Do", "Does", "Are", "Is"], answer: 0, explanation: "Questions with 'you' use 'Do'. → 'Do you like...?'", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 22, question: "Which word is an ANIMAL?", options: ["blue", "run", "cat", "happy"], answer: 2, explanation: "'Cat' is an animal. The others are a color, verb, and adjective.", type: "Best Answer", difficulty: "Easy" },
    { id: 23, question: "'I'm' is short for ___.", options: ["I am", "I have", "I will", "I can"], answer: 0, explanation: "'I'm' is a contraction (short form) of 'I am'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 24, question: "Find the mistake: 'Nice to meets you!'", options: ["Nice → Good", "to → for", "meets → meet", "you → your"], answer: 2, explanation: "'Nice to meet you' — after 'to', use the base verb: 'meet', not 'meets'.", type: "Error Correction", difficulty: "Medium" },
    { id: 25, question: "Which is the correct sentence?", options: ["I don't like not fish.", "I no like fish.", "I don't like fish.", "I am not like fish."], answer: 2, explanation: "'I don't like fish' = 'I do not like fish'. This is the standard negative pattern.", type: "Best Answer", difficulty: "Easy" },
  ],

  // ═══════════════════════════════════════════════════════
  // GRADE 1 — Week 2 Revision (Elementary School English)
  // Focus: I can/have, What...? How many?, colors, animals, food, He/She is
  // ═══════════════════════════════════════════════════════
  "rev-1-w2": [
    { id: 1,  question: "What ___ your name?", options: ["is", "am", "are", "be"], answer: 0, explanation: "'What is your name?' — use 'is' with singular subjects.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "I have a cat. ___ is white.", options: ["Its", "Them", "It's", "They're"], answer: 2, explanation: "'It's' = 'It is'. We use 'it' to refer to an animal or thing.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "Which is the correct sentence with 'I'?", options: ["I eat sushi yesterday.", "I eats sushi.", "I eating sushi.", "I eat sushi."], answer: 3, explanation: "'I eat ___' is correct simple present with 'I'. No -s needed.", type: "Best Answer", difficulty: "Easy" },
    { id: 4,  question: "What ___ you want for lunch?", options: ["do", "does", "are", "is"], answer: 0, explanation: "'What do you want?' — questions with 'you' use 'Do'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 5,  question: "Which question is CORRECT?", options: ["What do you like?", "What likes you?", "What you do like?", "What does like you?"], answer: 0, explanation: "'What do you like?' = Do + subject + base verb.", type: "Best Answer", difficulty: "Easy" },
    { id: 6,  question: "How ___ is this bag?", options: ["much", "many", "long", "old"], answer: 0, explanation: "'How much' asks about price.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 7,  question: "Which of these is a NUMBER?", options: ["green", "banana", "soccer", "seven"], answer: 3, explanation: "'Seven' is a number. The others are a color, food, and sport.", type: "Best Answer", difficulty: "Easy" },
    { id: 8,  question: "Find the mistake: 'I cans play tennis.'", options: ["I → She", "cans → can", "play → plays", "tennis → the tennis"], answer: 1, explanation: "'Can' never takes -s. The correct form is always 'can' for every subject.", type: "Error Correction", difficulty: "Easy" },
    { id: 9,  question: "She likes music. ___ favorite singer is Kenshi Yonezu.", options: ["Her", "She", "Hers", "Him"], answer: 0, explanation: "Use 'her' to show possession for a female subject.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 10, question: "'Do you like spiders?' — Which answer is CORRECT?", options: ["Yes, I likes.", "Yes, I am.", "Yes, I do.", "Yes, I does."], answer: 2, explanation: "'Do you...?' → 'Yes, I do.' or 'No, I don't.'", type: "Best Answer", difficulty: "Easy" },
    { id: 11, question: "Which is NOT a farewell?", options: ["Goodbye!", "See you later!", "Hello!", "Take care!"], answer: 2, explanation: "'Hello!' is a greeting. The others are all ways to say goodbye.", type: "Best Answer", difficulty: "Easy" },
    { id: 12, question: "My mother ___ cooking. She is a great chef.", options: ["like", "likes", "is like", "do like"], answer: 1, explanation: "With 'she', add -s to the verb: 'likes'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 13, question: "Which sentence uses 'have' correctly?", options: ["She have a dog.", "I have a dog.", "He have a dog.", "They has a dog."], answer: 1, explanation: "'I have a dog' is correct. Use 'has' with he/she/it.", type: "Best Answer", difficulty: "Easy" },
    { id: 14, question: "I ___ swim, but I can't ski.", options: ["can", "cans", "am can", "does can"], answer: 0, explanation: "'Can' expresses ability. It does not change for any subject.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 15, question: "How ___ students are in your class?", options: ["many", "much", "long", "old"], answer: 0, explanation: "'How many' is used for countable things (students, apples, etc.).", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 16, question: "Find the mistake: 'My names is Kenji.'", options: ["My → Mine", "names → name", "is → are", "Kenji → Kenji-san"], answer: 1, explanation: "'Name' is singular here — 'My name is Kenji'.", type: "Error Correction", difficulty: "Easy" },
    { id: 17, question: "What does 'I have a dog' tell us?", options: ["The dog has me.", "I own a dog.", "I want a dog.", "I am a dog."], answer: 1, explanation: "'I have a dog' means the dog belongs to you.", type: "Best Answer", difficulty: "Easy" },
    { id: 18, question: "Which word is a FOOD?", options: ["red", "run", "happy", "banana"], answer: 3, explanation: "'Banana' is a food. The others are a color, verb, and adjective.", type: "Best Answer", difficulty: "Easy" },
    { id: 19, question: "I like animals. My favorite ___ is the dolphin.", options: ["animal", "sport", "color", "food"], answer: 0, explanation: "A dolphin is an animal, so 'My favorite animal is the dolphin'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 20, question: "He ___ from Australia. He speaks English.", options: ["is", "am", "are", "be"], answer: 0, explanation: "Use 'is' with he, she, it.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 21, question: "Which is a correct answer to 'Can you sing?'", options: ["Yes, I can.", "Yes, I do.", "Yes, I am.", "Yes, I have."], answer: 0, explanation: "'Can you...?' → 'Yes, I can.' / 'No, I can't.'", type: "Best Answer", difficulty: "Easy" },
    { id: 22, question: "I have ___ brothers and one sister.", options: ["two", "second", "twice", "both"], answer: 0, explanation: "'Two' is the cardinal number used to count.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 23, question: "Which is correct?", options: ["I don't like fish.", "I not like fish.", "I doesn't like fish.", "I no like fish."], answer: 0, explanation: "'I don't like fish' = 'I do not like fish'. Always use 'don't' with 'I'.", type: "Best Answer", difficulty: "Easy" },
    { id: 24, question: "What color is the sky on a clear day?", options: ["red", "blue", "green", "orange"], answer: 1, explanation: "The sky is blue on a clear day — 'The sky is blue.'", type: "Best Answer", difficulty: "Easy" },
    { id: 25, question: "Find the mistake: 'Do she like cats?'", options: ["Do → Does", "she → her", "like → likes", "cats → cat"], answer: 0, explanation: "With 'she', use 'Does': 'Does she like cats?'", type: "Error Correction", difficulty: "Easy" },
  ],

  // ═══════════════════════════════════════════════════════
  // GRADE 2 — Week 1 Revision (JHS Grade 1 Content)
  // Focus: be verbs, simple present, WH-questions, this/that/these/those, there is/are, articles
  // ═══════════════════════════════════════════════════════
  "rev-2-w1": [
    { id: 1,  question: "I ___ a student at Sakura Junior High School.", options: ["am", "is", "are", "be"], answer: 0, explanation: "Use 'am' with the subject 'I'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "She ___ thirteen years old.", options: ["is", "am", "are", "be"], answer: 0, explanation: "Use 'is' with he, she, and it.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "We ___ in the same class this year.", options: ["are", "is", "am", "be"], answer: 0, explanation: "Use 'are' with we, you, and they.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 4,  question: "Find the mistake: 'He are a nice teacher.'", options: ["He → She", "are → is", "a → an", "nice → kind"], answer: 1, explanation: "'He' uses 'is', not 'are'.", type: "Error Correction", difficulty: "Easy" },
    { id: 5,  question: "___ you a member of the soccer club?", options: ["Are", "Is", "Am", "Do"], answer: 0, explanation: "Question with 'you': 'Are you...?'", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 6,  question: "She ___ tennis every day after school.", options: ["plays", "play", "is play", "do play"], answer: 0, explanation: "With she/he/it, add -s to the verb: 'plays'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 7,  question: "___ he like ramen?", options: ["Does", "Do", "Is", "Are"], answer: 0, explanation: "Questions with he/she/it use 'Does'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 8,  question: "Which sentence is CORRECT?", options: ["He don't eat meat.", "She plays the piano.", "They plays games.", "He go to school."], answer: 1, explanation: "'She plays the piano' is correct — add -s for she/he/it.", type: "Best Answer", difficulty: "Easy" },
    { id: 9,  question: "Find the mistake: 'She don't study math.'", options: ["She → He", "don't → doesn't", "study → studies", "math → science"], answer: 1, explanation: "With 'she', use 'doesn't' (does not), not 'don't'.", type: "Error Correction", difficulty: "Easy" },
    { id: 10, question: "Which WH-question asks about a PLACE?", options: ["What do you eat?", "Where do you live?", "When do you sleep?", "Who is your teacher?"], answer: 1, explanation: "'Where' asks about a place. 'Where do you live?' is correct.", type: "Best Answer", difficulty: "Easy" },
    { id: 11, question: "___ is your birthday?", options: ["When", "Where", "What", "Who"], answer: 0, explanation: "'When' asks about time — birthdays are dates, so use 'When'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 12, question: "___ is your English teacher? — Mr. Tanaka.", options: ["Who", "What", "When", "Where"], answer: 0, explanation: "'Who' asks about a person.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 13, question: "Which is correct?", options: ["This are my books.", "These is my book.", "This is my book.", "That are books."], answer: 2, explanation: "'This is my book' — 'this' is singular and needs 'is'.", type: "Best Answer", difficulty: "Easy" },
    { id: 14, question: "___ are my pencils. Don't take them!", options: ["These", "This", "That", "It"], answer: 0, explanation: "'These' is the plural of 'this' — used for nearby plural things.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 15, question: "___ is the Tokyo Skytree over there.", options: ["That", "This", "These", "Those"], answer: 0, explanation: "'That' refers to something visible but farther away.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 16, question: "There ___ a cat in the garden.", options: ["is", "are", "am", "be"], answer: 0, explanation: "'There is' + singular noun.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 17, question: "There ___ many students in the gym.", options: ["are", "is", "am", "be"], answer: 0, explanation: "'There are' + plural noun.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 18, question: "Find the mistake: 'There is five books on the desk.'", options: ["There → It", "is → are", "five → a", "books → book"], answer: 1, explanation: "'Five books' is plural — use 'There are'.", type: "Error Correction", difficulty: "Easy" },
    { id: 19, question: "The cat is ___ the box. (inside)", options: ["in", "on", "under", "near"], answer: 0, explanation: "'In' means inside something.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 20, question: "My bag is ___ the chair. (on top)", options: ["on", "in", "under", "near"], answer: 0, explanation: "'On' means resting on top of a surface.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 21, question: "I have ___ umbrella. (starts with a vowel sound)", options: ["an", "a", "the", "some"], answer: 0, explanation: "Use 'an' before words that start with a vowel sound (a, e, i, o, u).", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 22, question: "She is ___ artist. She paints beautiful pictures.", options: ["an", "a", "the", "—"], answer: 0, explanation: "'An' is used before vowel sounds. 'Artist' starts with 'a'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 23, question: "Which uses the article correctly?", options: ["I have an dog.", "I have a dog.", "She is an student.", "He is a engineer."], answer: 1, explanation: "'A dog' is correct — 'dog' starts with a consonant, so use 'a'.", type: "Best Answer", difficulty: "Easy" },
    { id: 24, question: "___ time is it? It's 3:30.", options: ["What", "When", "Where", "How"], answer: 0, explanation: "'What time is it?' asks for the current time.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 25, question: "Find the mistake: 'Does she lives in Osaka?'", options: ["Does → Do", "she → her", "lives → live", "in → at"], answer: 2, explanation: "After 'does' in a question, always use the base verb: 'live', not 'lives'.", type: "Error Correction", difficulty: "Medium" },
  ],

  // ═══════════════════════════════════════════════════════
  // GRADE 2 — Week 2 Revision (JHS Grade 1 Content)
  // Focus: can, simple past, present progressive, prepositions
  // ═══════════════════════════════════════════════════════
  "rev-2-w2": [
    { id: 1,  question: "I ___ swim, but I can't ski.", options: ["can", "cans", "am able", "does"], answer: 0, explanation: "'Can + base verb' expresses ability. No -s, no 'to'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "She ___ play the violin. She practices every day.", options: ["can", "cans", "is can", "does can"], answer: 0, explanation: "'Can' works for all subjects — no -s even for she/he/it.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "Find the mistake: 'Can he speaks French?'", options: ["Can → Does", "he → she", "speaks → speak", "French → English"], answer: 2, explanation: "After 'can' in a question, use the base verb: 'speak', not 'speaks'.", type: "Error Correction", difficulty: "Easy" },
    { id: 4,  question: "We ___ a lot of fun at the sports festival last year.", options: ["had", "have", "has", "having"], answer: 0, explanation: "'Had' is the past form of 'have'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 5,  question: "She ___ to Osaka last summer.", options: ["went", "go", "goes", "going"], answer: 0, explanation: "'Went' is the irregular past form of 'go'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 6,  question: "Find the mistake: 'Did he went to school today?'", options: ["Did → Does", "he → she", "went → go", "school → class"], answer: 2, explanation: "After 'did' in a question, use the base verb: 'go', not 'went'.", type: "Error Correction", difficulty: "Medium" },
    { id: 7,  question: "I ___ not go to the party because I was sick.", options: ["did", "do", "does", "was"], answer: 0, explanation: "'Did not / didn't' is the past simple negative form.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 8,  question: "Which sentence is in the PAST tense?", options: ["I eat breakfast.", "She plays piano.", "He watched TV.", "They study English."], answer: 2, explanation: "'Watched' is the past form of 'watch'. The others are present tense.", type: "Best Answer", difficulty: "Easy" },
    { id: 9,  question: "Look! It ___ raining outside.", options: ["is", "are", "am", "be"], answer: 0, explanation: "Present progressive: is/am/are + verb-ing. 'It is raining'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 10, question: "They are ___ in the park right now.", options: ["playing", "play", "played", "plays"], answer: 0, explanation: "Present progressive: are + verb-ing. 'They are playing'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 11, question: "Find the mistake: 'She is run in the gym.'", options: ["She → He", "is → are", "run → running", "gym → school"], answer: 2, explanation: "Progressive needs -ing: 'She is running'.", type: "Error Correction", difficulty: "Easy" },
    { id: 12, question: "I ___ eating right now. Can I call you back?", options: ["am", "is", "are", "be"], answer: 0, explanation: "'I am eating' — use 'am' with 'I' in progressive.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 13, question: "Which sentence uses progressive correctly?", options: ["He is play games.", "She is reading a book.", "They is swimming.", "I are dancing."], answer: 1, explanation: "'She is reading a book' — is + verb-ing is the correct pattern.", type: "Best Answer", difficulty: "Easy" },
    { id: 14, question: "What ___ you doing now?", options: ["are", "is", "am", "do"], answer: 0, explanation: "'What are you doing?' — use 'are' with 'you'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 15, question: "Can ___ open the window? It's hot in here.", options: ["I", "me", "my", "mine"], answer: 0, explanation: "'Can I...?' is used to politely ask for permission.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 16, question: "What is the past form of 'eat'?", options: ["eated", "eaten", "ate", "eats"], answer: 2, explanation: "'Eat' is irregular. Its simple past form is 'ate'.", type: "Best Answer", difficulty: "Easy" },
    { id: 17, question: "What is the past form of 'make'?", options: ["maked", "makes", "making", "made"], answer: 3, explanation: "'Make' is irregular. Its past form is 'made'.", type: "Best Answer", difficulty: "Easy" },
    { id: 18, question: "What is the past form of 'buy'?", options: ["buyed", "buys", "bought", "buying"], answer: 2, explanation: "'Buy' is irregular. Its past form is 'bought'.", type: "Best Answer", difficulty: "Easy" },
    { id: 19, question: "Which is the correct past negative?", options: ["I didn't went there.", "I didn't gone there.", "I didn't go there.", "I not went there."], answer: 2, explanation: "After 'didn't', always use the base verb: 'go'.", type: "Best Answer", difficulty: "Medium" },
    { id: 20, question: "The dog is ___ the table. (below)", options: ["under", "on", "in", "near"], answer: 0, explanation: "'Under' means below something.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 21, question: "The library is ___ the school. (next to)", options: ["near", "in", "on", "under"], answer: 0, explanation: "'Near' means close to something.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 22, question: "Find the mistake: 'She is study English now.'", options: ["She → He", "is → are", "study → studying", "English → math"], answer: 2, explanation: "Progressive form needs -ing: 'studying'.", type: "Error Correction", difficulty: "Easy" },
    { id: 23, question: "Which sentence shows an action happening NOW?", options: ["I studied last night.", "She will go tomorrow.", "He is sleeping right now.", "I go to school."], answer: 2, explanation: "Present progressive ('is sleeping') shows an action happening at this moment.", type: "Best Answer", difficulty: "Easy" },
    { id: 24, question: "I ___ English for two years now. (still ongoing)", options: ["study", "studied", "have studied", "was studying"], answer: 0, explanation: "For general present facts or habits, use simple present: 'I study English'.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 25, question: "Find the mistake: 'He didn't came to school yesterday.'", options: ["He → She", "didn't → did", "came → come", "yesterday → today"], answer: 2, explanation: "After 'didn't', always use the base verb: 'come', not 'came'.", type: "Error Correction", difficulty: "Medium" },
  ],

  // ═══════════════════════════════════════════════════════
  // GRADE 3 — Week 1 Revision (JHS Grade 2 Content)
  // Focus: be going to, will, must/have to, should, comparative, superlative
  // ═══════════════════════════════════════════════════════
  "rev-3-w1": [
    { id: 1,  question: "I ___ going to study math tonight.", options: ["am", "is", "are", "be"], answer: 0, explanation: "'Am going to' with 'I'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "She ___ going to visit her grandparents this weekend.", options: ["is", "am", "are", "be"], answer: 0, explanation: "'Is going to' with she/he/it.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "Find the mistake: 'He is going to plays soccer.'", options: ["He → She", "is → are", "going to → going", "plays → play"], answer: 3, explanation: "After 'going to', use the base verb: 'play', not 'plays'.", type: "Error Correction", difficulty: "Easy" },
    { id: 4,  question: "Don't worry. I ___ help you carry that.", options: ["will", "am", "going", "is"], answer: 0, explanation: "'Will' is used for promises and decisions made at the moment of speaking.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 5,  question: "Which sentence shows a PRE-PLANNED future action?", options: ["I will probably eat out.", "I am going to meet Ken at 3.", "Maybe she will come.", "I think it will rain."], answer: 1, explanation: "'Am going to meet' = a pre-decided plan. 'Will' is used for in-the-moment decisions or predictions.", type: "Best Answer", difficulty: "Hard" },
    { id: 6,  question: "You ___ wash your hands before eating. It's important!", options: ["must", "musts", "must to", "must be"], answer: 0, explanation: "'Must + base verb' expresses strong obligation.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 7,  question: "We ___ have to wear a uniform on weekends.", options: ["don't", "doesn't", "mustn't", "aren't"], answer: 0, explanation: "'Don't have to' means it is NOT necessary (optional).", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 8,  question: "What is the difference between 'must not' and 'don't have to'?", options: ["They are the same.", "'Must not' = forbidden; 'don't have to' = not necessary.", "'Don't have to' = forbidden; 'must not' = not necessary.", "Both mean 'not possible'."], answer: 1, explanation: "'Must not' means NOT allowed. 'Don't have to' means not required — it's optional.", type: "Best Answer", difficulty: "Hard" },
    { id: 9,  question: "You ___ exercise more. Your health is important!", options: ["should", "shoulds", "should to", "should be"], answer: 0, explanation: "'Should + base verb' gives advice or a recommendation.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 10, question: "You ___ stay up so late. You'll be tired!", options: ["shouldn't", "don't should", "should not to", "not should"], answer: 0, explanation: "'Shouldn't' (should not) gives negative advice.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 11, question: "Which sentence gives ADVICE?", options: ["You must go now.", "You should drink more water.", "You have to pay.", "You will feel better."], answer: 1, explanation: "'Should' is used to give advice or a recommendation.", type: "Best Answer", difficulty: "Easy" },
    { id: 12, question: "Mt. Fuji is ___ than Mt. Aso.", options: ["taller", "tall", "tallest", "more tall"], answer: 0, explanation: "Use -er (taller) to compare two things.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 13, question: "English is ___ than math for me.", options: ["more interesting", "interestinger", "most interesting", "interesting"], answer: 0, explanation: "For longer adjectives, use 'more + adjective' for comparisons.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 14, question: "The Shinkansen is the ___ train in Japan.", options: ["fastest", "faster", "fast", "most fast"], answer: 0, explanation: "Use -est (fastest) for the superlative — the most of all.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 15, question: "Which uses comparative correctly?", options: ["She is more tall than me.", "He is taller than me.", "This is the most tall building.", "She is tallest than me."], answer: 1, explanation: "Short adjectives: add -er for comparison. 'Taller than' is correct.", type: "Best Answer", difficulty: "Easy" },
    { id: 16, question: "This problem is ___ difficult than I thought.", options: ["more", "most", "much", "the most"], answer: 0, explanation: "For long adjectives, comparison uses 'more + adjective'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 17, question: "She has ___ hair in the class.", options: ["the longest", "longer", "the most long", "more long"], answer: 0, explanation: "Superlative: 'the longest' (long → longest).", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 18, question: "Find the mistake: 'This movie is more better than that one.'", options: ["This → That", "more better → better", "than → as", "that → this"], answer: 1, explanation: "'Better' is already comparative. Don't add 'more'. Just say 'better than'.", type: "Error Correction", difficulty: "Hard" },
    { id: 19, question: "She ___ have to wake up early on Sundays. It's her day off.", options: ["doesn't", "don't", "mustn't", "isn't"], answer: 0, explanation: "'Doesn't have to' with she/he/it means not necessary.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 20, question: "Which uses 'will' correctly for a PROMISE?", options: ["I will probably be late.", "I will go to school every day.", "I will call you back right away.", "I will it rain tomorrow."], answer: 2, explanation: "'I will call you back' is a promise — a decision made at the moment of speaking.", type: "Best Answer", difficulty: "Medium" },
    { id: 21, question: "Tokyo is ___ than my hometown.", options: ["bigger", "more big", "most big", "biggest"], answer: 0, explanation: "Short adjectives: add -er for comparison. 'big' → 'bigger'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 22, question: "This is the ___ pizza I have ever eaten!", options: ["most delicious", "more delicious", "deliciouser", "deliciousest"], answer: 0, explanation: "Long adjectives use 'most' for superlative.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 23, question: "Find the mistake: 'Are they going to comes tomorrow?'", options: ["Are → Is", "they → she", "comes → come", "tomorrow → today"], answer: 2, explanation: "After 'going to', use the base verb: 'come', not 'comes'.", type: "Error Correction", difficulty: "Easy" },
    { id: 24, question: "Find the mistake: 'She have to finish the report by Friday.'", options: ["She → He", "have → has", "finish → finishes", "by → until"], answer: 1, explanation: "With 'she', use 'has to', not 'have to'.", type: "Error Correction", difficulty: "Easy" },
    { id: 25, question: "Which is the SUPERLATIVE of 'good'?", options: ["gooder", "goodest", "better", "best"], answer: 3, explanation: "'Good' is irregular. Comparative: 'better'. Superlative: 'best'.", type: "Best Answer", difficulty: "Medium" },
  ],

  // ═══════════════════════════════════════════════════════
  // GRADE 3 — Week 2 Revision (JHS Grade 2 Content)
  // Focus: infinitives, gerunds, when/if clauses, SVOO, SVOC, past progressive
  // ═══════════════════════════════════════════════════════
  "rev-3-w2": [
    { id: 1,  question: "I want ___ go to America someday.", options: ["to", "for", "of", "—"], answer: 0, explanation: "'Want to + base verb' — the infinitive pattern.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 2,  question: "She tried ___ fix the problem by herself.", options: ["to", "for", "of", "in"], answer: 0, explanation: "'Try to + base verb' is a common infinitive pattern.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 3,  question: "Which uses an infinitive correctly?", options: ["She wants eat pizza.", "He wants to eat pizza.", "She wants eating pizza.", "He to wants eat pizza."], answer: 1, explanation: "'Want to + base verb' is the infinitive pattern.", type: "Best Answer", difficulty: "Easy" },
    { id: 4,  question: "I enjoy ___. Music makes me happy.", options: ["singing", "to sing", "sing", "sang"], answer: 0, explanation: "'Enjoy' is followed by a gerund (-ing form), not an infinitive.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 5,  question: "He finished ___ the book last night.", options: ["reading", "to read", "reads", "read"], answer: 0, explanation: "'Finish' is followed by a gerund (-ing form).", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 6,  question: "She was ___ tired to study.", options: ["too", "very", "so", "much"], answer: 0, explanation: "'Too...to...' means the degree prevents the action.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 7,  question: "What does 'He was too busy to come' mean?", options: ["He came even though he was busy.", "He was busy, so he could not come.", "He was not busy and came.", "He was busy but came late."], answer: 1, explanation: "'Too...to...' = so much that you cannot do something.", type: "Best Answer", difficulty: "Medium" },
    { id: 8,  question: "I went to the library ___ return some books.", options: ["to", "for", "and", "so"], answer: 0, explanation: "'To + base verb' expresses purpose — why you did something.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 9,  question: "Which sentence uses 'to' for PURPOSE?", options: ["I have homework to do.", "She went to the shop to buy milk.", "I want to sleep.", "It is nice to meet you."], answer: 1, explanation: "'She went to the shop to buy milk' — 'to buy' explains WHY she went.", type: "Best Answer", difficulty: "Medium" },
    { id: 10, question: "___ it is sunny tomorrow, we will have a picnic.", options: ["If", "When", "Because", "So"], answer: 0, explanation: "'If' is used for conditions that might or might not happen.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 11, question: "Please call me ___ you arrive at the station.", options: ["when", "if", "because", "so"], answer: 0, explanation: "'When' is used for a specific moment something will happen.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 12, question: "Find the mistake: 'If it will rain, we will cancel the plan.'", options: ["If → When", "it → that", "will rain → rains", "cancel → cancelled"], answer: 2, explanation: "In an 'if' clause, use present tense (not 'will'): 'if it rains'.", type: "Error Correction", difficulty: "Hard" },
    { id: 13, question: "My teacher gave ___ some homework.", options: ["us", "we", "our", "ours"], answer: 0, explanation: "SVOO: give + indirect object (us) + direct object. 'Us' is the object form of 'we'.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 14, question: "She sent ___ a letter.", options: ["him", "he", "his", "himself"], answer: 0, explanation: "SVOO: send + indirect object (him) + direct object (a letter).", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 15, question: "Which sentence follows the SVOO pattern?", options: ["She made him angry.", "She gave him a gift.", "She called him Ken.", "She found it interesting."], answer: 1, explanation: "SVOO = Subject + Verb + Object1 + Object2. 'Gave him a gift' = gave [to him] [a gift].", type: "Best Answer", difficulty: "Hard" },
    { id: 16, question: "Her smile made me ___.", options: ["happy", "happily", "to happy", "happiness"], answer: 0, explanation: "SVOC: make + object + adjective. 'Made me happy'.", type: "Fill in the Blank", difficulty: "Medium" },
    { id: 17, question: "We call this dish ___.", options: ["sukiyaki", "sukiyaki-ly", "a sukiyaki", "the sukiyakis"], answer: 0, explanation: "SVOC: call + object + complement (name). 'We call it sukiyaki'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 18, question: "Which sentence uses SVOC correctly?", options: ["She named him happy.", "They call the dog Shiro.", "He gave her beautiful.", "She told him fast."], answer: 1, explanation: "SVOC: 'They call the dog Shiro' = call (V) + the dog (O) + Shiro (C, the name).", type: "Best Answer", difficulty: "Hard" },
    { id: 19, question: "I was ___ a book when you called.", options: ["reading", "reads", "read", "to read"], answer: 0, explanation: "Past progressive: was/were + -ing. 'I was reading'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 20, question: "They ___ playing soccer at 4 p.m. yesterday.", options: ["were", "was", "are", "be"], answer: 0, explanation: "Past progressive: were + -ing for 'they'.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 21, question: "Find the mistake: 'She was watch TV when it started to rain.'", options: ["She → He", "was → were", "watch → watching", "started → start"], answer: 2, explanation: "Past progressive: was + -ing. 'She was watching TV'.", type: "Error Correction", difficulty: "Easy" },
    { id: 22, question: "He wants me ___ help him with his project.", options: ["to", "for", "of", "—"], answer: 0, explanation: "'Want + object + to + base verb': He wants me to help him.", type: "Fill in the Blank", difficulty: "Hard" },
    { id: 23, question: "Which is a correct WHEN/IF sentence?", options: ["If it rains, we will stay home.", "When it will snow, we play outside.", "If it will be cold, wear a coat.", "When he comes, we waited."], answer: 0, explanation: "'If it rains, we will stay home' — present tense in the if-clause is correct.", type: "Best Answer", difficulty: "Hard" },
    { id: 24, question: "My dad bought ___ a new bike for my birthday.", options: ["me", "I", "my", "mine"], answer: 0, explanation: "SVOO: buy + indirect object (me) + direct object. 'Me' is correct object form.", type: "Fill in the Blank", difficulty: "Easy" },
    { id: 25, question: "Which verb is followed by -ing (gerund)?", options: ["want", "plan", "enjoy", "try"], answer: 2, explanation: "'Enjoy + -ing': I enjoy playing. 'Want', 'plan', and 'try' use 'to + verb'.", type: "Best Answer", difficulty: "Hard" },
  ],
};
