export const quizDataWeek1 = {
  JHS1: [
    {
      h1: "<span class='grammar-underline'>What</span> Japanese food is round and has rice on the outside?",
      h2: "<span class='grammar-underline'>Where</span> can you eat it? At a Japanese restaurant?",
      h3: "I <span class='grammar-underline'>like eating</span> this with wasabi and soy sauce.",
      ans: "Sushi",
      query: "sushi-roll",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the fun and famous mouse with big round ears?",
      h2: "<span class='grammar-underline'>What</span> color are his shorts? Are they red?",
      h3: "He <span class='grammar-underline'>can</span> be seen at Disney theme parks.",
      ans: "Mickey Mouse",
      query: "mickey-mouse",
    },
    {
      h1: "<span class='grammar-underline'>What</span> sport uses a racket and a shuttlecock?",
      h2: "<span class='grammar-underline'>Where</span> do people play it? In a gym or court?",
      h3: "This game <span class='grammar-underline'>is</span> very popular in Japan and Indonesia.",
      ans: "Badminton",
      query: "badminton-game",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> is the famous red gate in Tokyo called Kaminarimon?",
      h2: "<span class='grammar-underline'>What</span> can you see there? A big lantern?",
      h3: "This temple <span class='grammar-underline'>is</span> called Senso-ji in Asakusa.",
      ans: "Asakusa",
      query: "asakusa-temple",
    },
    {
      h1: "<span class='grammar-underline'>What</span> small yellow fruit is sour and round?",
      h2: "<span class='grammar-underline'>When</span> do people eat this fruit? Is it in summer?",
      h3: "This citrus fruit <span class='grammar-underline'>make</span> popular juice and drink in Japan.",
      ans: "Yuzu",
      query: "yellow-citrus",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the orange-haired boy who wants to be a Soul Reaper?",
      h2: "<span class='grammar-underline'>What</span> weapon does he use? A big sword?",
      h3: "He <span class='grammar-underline'>can</span> fight hollows in this anime called Bleach.",
      ans: "Ichigo",
      query: "bleach-ichigo",
    },
    {
      h1: "<span class='grammar-underline'>What</span> traditional Japanese clothing has wide sleeves?",
      h2: "<span class='grammar-underline'>When</span> do people wear it? At festivals?",
      h3: "I <span class='grammar-underline'>like wearing</span> this beautiful robe to go to festivals.",
      ans: "Kimono",
      query: "traditional-kimono",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> do you go to watch new movies on a big screen?",
      h2: "<span class='grammar-underline'>What</span> do you eat there? Popcorn?",
      h3: "This place <span class='grammar-underline'>is</span> dark and has many seats.",
      ans: "Cinema",
      query: "movie-theater",
    },
    {
      h1: "<span class='grammar-underline'>What</span> is the tallest mountain in the world?",
      h2: "<span class='grammar-underline'>Where</span> is it located? In Nepal and Tibet?",
      h3: "This mountain <span class='grammar-underline'>is</span> 8,849 meters tall.",
      ans: "Everest",
      query: "mount-everest",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> was the first person to walk on the moon?",
      h2: "<span class='grammar-underline'>When</span> did he do it? In 1969?",
      h3: "This American <span class='grammar-underline'>can</span> be remembered for saying 'one small step'.",
      ans: "Armstrong",
      query: "neil-armstrong",
    },
    {
      h1: "<span class='grammar-underline'>What</span> Japanese festival has floating lanterns on water?",
      h2: "<span class='grammar-underline'>When</span> does it happen? In summer?",
      h3: "This popular festival <span class='grammar-underline'>is</span> there in August.",
      ans: "Obon",
      query: "obon-festival",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> is the famous clock tower called Big Ben?",
      h2: "<span class='grammar-underline'>What</span> city is it in? Is it London?",
      h3: "This tower <span class='grammar-underline'>is</span> next to the River Thames.",
      ans: "London",
      query: "london-bigben",
    },
    {
      h1: "<span class='grammar-underline'>What</span> sea animal is pink and has eight arms?",
      h2: "<span class='grammar-underline'>Where</span> does it live? Under the ocean?",
      h3: "This creature <span class='grammar-underline'>is</span> very intelligent.",
      ans: "Octopus",
      query: "pink-octopus",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the Japanese hero who defeated demons at Onigashima?",
      h2: "<span class='grammar-underline'>What</span> did he bring? Dango and animal friends?",
      h3: "He <span class='grammar-underline'>can</span> be found in this old folktale.",
      ans: "Momotaro",
      query: "momotaro-hero",
    },
    {
      h1: "<span class='grammar-underline'>What</span> device helps you take pictures and videos?",
      h2: "<span class='grammar-underline'>Where</span> do you use it? Everywhere you go?",
      h3: "This <span class='grammar-underline'>is</span> built into most smartphones today.",
      ans: "Camera",
      query: "digital-camera",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the boy wizard with a lightning scar?",
      h2: "<span class='grammar-underline'>What</span> school does he go to? Hogwarts?",
      h3: "He <span class='grammar-underline'>can</span> use magic and fight Voldemort.",
      ans: "Harry Potter",
      query: "harry-potter-wizard",
    },
    {
      h1: "<span class='grammar-underline'>What</span> season comes after winter in Japan?",
      h2: "<span class='grammar-underline'>When</span> do cherry blossoms bloom? In this season?",
      h3: "This season <span class='grammar-underline'>is</span> called haru and starts in March.",
      ans: "Spring",
      query: "spring-season",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> can you borrow books for free to read?",
      h2: "<span class='grammar-underline'>What</span> must you do? Return them on time?",
      h3: "This place <span class='grammar-underline'>is</span> quiet and full of shelves.",
      ans: "Library",
      query: "public-library",
    },
    {
      h1: "<span class='grammar-underline'>What</span> brown drink is made from cocoa beans?",
      h2: "<span class='grammar-underline'>Where</span> can you buy it? At convenience stores?",
      h3: "I <span class='grammar-underline'>like eating</span> this sweet treat as a snack.",
      ans: "Chocolate",
      query: "chocolate-bar",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the robot cat from the future with a pocket?",
      h2: "<span class='grammar-underline'>What</span> does he give? Magic gadgets?",
      h3: "He <span class='grammar-underline'>can</span> help Nobita with his problems.",
      ans: "Doraemon",
      query: "doraemon-robot",
    },
  ],
  JHS2: [
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this ancient city was buried by a volcano in 79 AD.",
      h2: "It <span class='grammar-underline'>is important to</span> visit this archaeological site in Italy.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about Pompeii's preserved ruins.",
      ans: "Pompeii",
      query: "pompeii-ruins",
    },
    {
      h1: "You <span class='grammar-underline'>have to</span> use flour and eggs to make this Japanese pancake.",
      h2: "I <span class='grammar-underline'>know how to</span> cook it on a hot plate with cabbage.",
      h3: "I <span class='grammar-underline'>am sure that</span> it is delicious with sauce.",
      ans: "Okonomiyaki",
      query: "okonomiyaki-japanese",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this Egyptian structure has four triangular sides.",
      h2: "It <span class='grammar-underline'>is important to</span> see this in Giza.",
      h3: "I enjoy <span class='grammar-underline'>studying</span> how ancient people built these tombs.",
      ans: "Pyramid",
      query: "egyptian-pyramid",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> learn about this scientist who discovered radium.",
      h2: "I <span class='grammar-underline'>can show you how to</span> remember her achievements.",
      h3: "I <span class='grammar-underline'>am sure that</span> she won two Nobel Prizes.",
      ans: "Marie Curie",
      query: "marie-curie-scientist",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this festival celebrates dolls in Japan every March.",
      h2: "You <span class='grammar-underline'>have to</span> display them on special platforms.",
      h3: "I enjoy <span class='grammar-underline'>celebrating</span> this festival with my family.",
      ans: "Hinamatsuri",
      query: "hinamatsuri-festival",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this Korean dish is made of fermented vegetables.",
      h2: "It <span class='grammar-underline'>is important to</span> try this spicy side dish.",
      h3: "I enjoy <span class='grammar-underline'>eating</span> kimchi with rice and meat.",
      ans: "Kimchi",
      query: "korean-kimchi",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> protect this endangered animal from China.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize the red panda by its tail.",
      h3: "I <span class='grammar-underline'>am sure that</span> they live in mountain forests.",
      ans: "Red Panda",
      query: "red-panda",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this athlete won 8 gold medals in 2008 Olympics.",
      h2: "You <span class='grammar-underline'>have to</span> be a great swimmer like him.",
      h3: "I enjoyed <span class='grammar-underline'>watching him</span> swimming at the Olympics.",
      ans: "Michael Phelps",
      query: "phelps-swimmer",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this wall separated East and West Germany.",
      h2: "It <span class='grammar-underline'>is important to</span> remember it fell in 1989.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about this wall's history.",
      ans: "Berlin Wall",
      query: "berlin-wall-history",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> visit this famous bridge in San Francisco.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize the bridge by its color.",
      h3: "<span class='grammar-underline'>Crossing</span> this bridge gives amazing views of the bay.",
      ans: "Golden Gate",
      query: "golden-gate-bridge",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this Japanese castle is white and located in Hyogo.",
      h2: "You <span class='grammar-underline'>have to</span> visit Himeji to see this UNESCO site.",
      h3: "I enjoy <span class='grammar-underline'>exploring</span> the beautiful architecture of this castle.",
      ans: "Himeji Castle",
      query: "himeji-castle",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this sport uses a round ball and 11 players.",
      h2: "It <span class='grammar-underline'>is important to</span> practice teamwork in this game.",
      h3: "I enjoy <span class='grammar-underline'>playing</span> this on the field every Saturday.",
      ans: "Soccer",
      query: "soccer-football",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> learn about this leader who unified Japan in 1603.",
      h2: "I <span class='grammar-underline'>can show you how to</span> remember his legacy.",
      h3: "I <span class='grammar-underline'>am sure that</span> he started the Edo Period.",
      ans: "Tokugawa Ieyasu",
      query: "tokugawa-shogun",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this anime film features a boy and a dragon.",
      h2: "You <span class='grammar-underline'>have to</span> watch Spirited Away by Studio Ghibli.",
      h3: "I enjoy <span class='grammar-underline'>watching</span> the adventures of Chihiro.",
      ans: "Chihiro",
      query: "spirited-away-chihiro",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this planet is known for its beautiful rings.",
      h2: "It <span class='grammar-underline'>is important to</span> study it in astronomy class.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about the solar system's sixth planet.",
      ans: "Saturn",
      query: "planet-saturn",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> remember this person who painted the Mona Lisa.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize his work.",
      h3: "I <span class='grammar-underline'>am sure that</span> he was a genius inventor too.",
      ans: "Leonardo da Vinci",
      query: "da-vinci-artist",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this traditional Japanese art uses paper folding.",
      h2: "You <span class='grammar-underline'>have to</span> make cranes and other shapes.",
      h3: "I enjoy <span class='grammar-underline'>practicing</span> it in my free time.",
      ans: "Origami",
      query: "origami-paper",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this river is the longest in the world.",
      h2: "It <span class='grammar-underline'>is important to</span> know it flows through Egypt.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about the Nile's ancient history.",
      ans: "Nile",
      query: "nile-river",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> study this superhero who can climb walls.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize him by his web.",
      h3: "<span class='grammar-underline'>Watching</span> Marvel movies about him is very exciting.",
      ans: "Spider-Man",
      query: "spiderman-hero",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this Japanese YouTuber is famous for cooking videos.",
      h2: "You <span class='grammar-underline'>have to</span> watch his simple and peaceful style of cooking.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> recipes from this channel on Youtube.",
      ans: "Peaceful Cuisine",
      query: "peaceful-cuisine",
    },
  ],
  JHS3: [
    {
      h1: "I <span class='grammar-underline'>have been studying</span> this French monument that was a gift to America.",
      h2: "This is <span class='grammar-underline'>a statue that</span> welcomes immigrants in New York Harbor.",
      h3: "The woman <span class='grammar-underline'>holds</span> a torch representing freedom and liberty.",
      ans: "Statue of Liberty",
      query: "liberty-statue-nyc",
    },
    {
      h1: "The emperor <span class='grammar-underline'>ruling</span> Japan during World War II surrendered in 1945.",
      h2: "This is <span class='grammar-underline'>a person who</span> became a symbol of peace after the war.",
      h3: "I <span class='grammar-underline'>have learned</span> that Emperor Hirohito lived until 1989.",
      ans: "Emperor Hirohito",
      query: "japanese-emperor",
    },
    {
      h1: "I <span class='grammar-underline'>have been reading</span> this Japanese folktale about a bamboo cutter.",
      h2: "It is <span class='grammar-underline'>a story where</span> a tiny princess is found inside bamboo.",
      h3: "Princess Kaguya <span class='grammar-underline'>returns to</span> the moon at the end.",
      ans: "Kaguya-hime",
      query: "bamboo-princess",
    },
    {
      h1: "The physicist <span class='grammar-underline'>developing</span> the theory of relativity changed science forever.",
      h2: "This is <span class='grammar-underline'>a scientist who</span> showed E=mc².",
      h3: "I <span class='grammar-underline'>have heard</span> about Albert Einstein's brilliant mind.",
      ans: "Albert Einstein",
      query: "einstein-physicist",
    },
    {
      h1: "I <span class='grammar-underline'>have visited</span> this temple with a golden pavilion in Kyoto.",
      h2: "This is <span class='grammar-underline'>a building that</span> reflects beautifully in the pond.",
      h3: "If I <span class='grammar-underline'>lived</span> in Kyoto, I <span class='grammar-underline'>would</span> visit Kinkaku-ji every week.",
      ans: "Kinkaku-ji",
      query: "golden-pavilion",
    },
    {
      h1: "The singer <span class='grammar-underline'>performing</span> 'Rolling in the Deep' has a powerful voice.",
      h2: "This is <span class='grammar-underline'>a person who</span> won many Grammy Awards.",
      h3: "I <span class='grammar-underline'>have listened to</span> Adele's emotional songs many times.",
      ans: "Adele",
      query: "british-singer",
    },
    {
      h1: "I <span class='grammar-underline'>have been learning</span> about this invention that changed communication.",
      h2: "It is <span class='grammar-underline'>a device that</span> Alexander Graham Bell created in 1876.",
      h3: "The world <span class='grammar-underline'>became connected</span> when people could talk from far away.",
      ans: "Telephone",
      query: "bell-invention",
    },
    {
      h1: "The explorer <span class='grammar-underline'>traveling</span> around the world proved Earth was round.",
      h2: "This is <span class='grammar-underline'>a person who</span> led the first circumnavigation.",
      h3: "I <span class='grammar-underline'>have studied</span> Ferdinand Magellan's dangerous voyage.",
      ans: "Magellan",
      query: "circumnavigation-explorer",
    },
    {
      h1: "I <span class='grammar-underline'>have just finished</span> watching this anime about a boy with a demon sister.",
      h2: "It is <span class='grammar-underline'>a movie that</span> features Tanjiro and Nezuko.",
      h3: "The characters <span class='grammar-underline'>fight demons</span> in this popular series.",
      ans: "Demon Slayer",
      query: "tanjiro-anime",
    },
    {
      h1: "I <span class='grammar-underline'>have been watching</span> this winter sport where athletes slide on ice.",
      h2: "This is <span class='grammar-underline'>a sport that</span> uses blades attached to boots.",
      h3: "Tell me <span class='grammar-underline'>which figure skater</span> you admire the most.",
      ans: "Ice Skating",
      query: "figure-skating",
    },
    {
      h1: "I <span class='grammar-underline'>have never climbed</span> this famous volcanic mountain in Japan.",
      h2: "This is <span class='grammar-underline'>a mountain that</span> is sacred and iconic.",
      h3: "Tell me <span class='grammar-underline'>when Mt. Fuji</span> last erupted.",
      ans: "Mt. Fuji",
      query: "fuji-mountain",
    },
    {
      h1: "The author <span class='grammar-underline'>writing</span> about wizarding schools created Hogwarts.",
      h2: "This is <span class='grammar-underline'>a writer who</span> brought us Harry Potter.",
      h3: "I <span class='grammar-underline'>wish I could</span> meet J.K. Rowling in person.",
      ans: "J.K. Rowling",
      query: "potter-author",
    },
    {
      h1: "I <span class='grammar-underline'>have been studying</span> this war between the North and South in America.",
      h2: "It is <span class='grammar-underline'>a conflict that</span> ended slavery in the United States.",
      h3: "Many soldiers <span class='grammar-underline'>fought to preserve</span> the Union from 1861 to 1865.",
      ans: "Civil War",
      query: "american-civil-war",
    },
    {
      h1: "The athlete <span class='grammar-underline'>playing</span> basketball became a global icon.",
      h2: "This is <span class='grammar-underline'>a person who</span> wore number 23 for the Chicago Bulls.",
      h3: "I <span class='grammar-underline'>have seen</span> Michael Jordan win six NBA championships.",
      ans: "Michael Jordan",
      query: "basketball-legend",
    },
    {
      h1: "I <span class='grammar-underline'>have just learned</span> about this ancient wonder in Peru.",
      h2: "This is <span class='grammar-underline'>a city that</span> was built by the Inca Empire.",
      h3: "Tell me <span class='grammar-underline'>how to reach</span> Machu Picchu in the mountains.",
      ans: "Machu Picchu",
      query: "inca-ruins",
    },
    {
      h1: "The inventor <span class='grammar-underline'>creating</span> the light bulb illuminated the world.",
      h2: "This is <span class='grammar-underline'>a person who</span> founded General Electric.",
      h3: "I <span class='grammar-underline'>have read</span> about Thomas Edison's many patents.",
      ans: "Thomas Edison",
      query: "lightbulb-inventor",
    },
    {
      h1: "I <span class='grammar-underline'>have been practicing</span> this martial art that originated in Okinawa.",
      h2: "It is <span class='grammar-underline'>an art form that</span> emphasizes striking techniques.",
      h3: "Students <span class='grammar-underline'>learn discipline</span> through karate training.",
      ans: "Karate",
      query: "japanese-martial-art",
    },
    {
      h1: "The composer <span class='grammar-underline'>writing</span> 'The Four Seasons' lived in Italy.",
      h2: "This is <span class='grammar-underline'>a musician who</span> was a master of baroque music.",
      h3: "I <span class='grammar-underline'>have listened to</span> Antonio Vivaldi's violin concertos.",
      ans: "Vivaldi",
      query: "baroque-composer",
    },
    {
      h1: "I <span class='grammar-underline'>have just learned</span> about this canal connecting two oceans.",
      h2: "This is <span class='grammar-underline'>a waterway that</span> ships use in Central America.",
      h3: "Tell me <span class='grammar-underline'>which countries</span> border the Panama Canal.",
      ans: "Panama Canal",
      query: "canal-waterway",
    },
    {
      h1: "The actress <span class='grammar-underline'>starring</span> in Black Widow is also a talented singer.",
      h2: "This is <span class='grammar-underline'>a person who</span> played Natasha Romanoff in Marvel films.",
      h3: "I <span class='grammar-underline'>have watched</span> Scarlett Johansson in many movies.",
      ans: "Scarlett Johansson",
      query: "black-widow-actress",
    },
  ],
};
