export const quizDataWeek2 = {
  JHS1: [
    {
      h1: "<span class='grammar-underline'>What</span> Japanese noodle soup is eaten on New Year's Eve?",
      h2: "<span class='grammar-underline'>Where</span> can you eat it? At home or restaurants?",
      h3: "I <span class='grammar-underline'>like eating</span> these long noodles for good luck.",
      ans: "Soba",
      query: "soba-noodles",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the pink round character who can copy abilities?",
      h2: "<span class='grammar-underline'>What</span> does he do? Inhale enemies?",
      h3: "He <span class='grammar-underline'>can</span> float in the air in this Nintendo game.",
      ans: "Kirby",
      query: "kirby-character",
    },
    {
      h1: "<span class='grammar-underline'>What</span> sport do you play with an orange ball and a hoop?",
      h2: "<span class='grammar-underline'>Where</span> do people play it? On a court?",
      h3: "This game <span class='grammar-underline'>is</span> very popular in America and Japan.",
      ans: "Basketball",
      query: "basketball-sport",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> is the famous tower in Paris made of iron?",
      h2: "<span class='grammar-underline'>What</span> can you do there? Go to the top?",
      h3: "This tower <span class='grammar-underline'>is</span> the symbol of France.",
      ans: "Eiffel Tower",
      query: "eiffel-tower-paris",
    },
    {
      h1: "<span class='grammar-underline'>What</span> red fruit grows on trees and keeps doctors away?",
      h2: "<span class='grammar-underline'>When</span> do people eat it? As a snack?",
      h3: "This fruit <span class='grammar-underline'>is</span> crunchy and sweet or sour.",
      ans: "Apple",
      query: "red-apple",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the boy with spiky black hair who fights titans?",
      h2: "<span class='grammar-underline'>What</span> does he want? Freedom outside the walls?",
      h3: "He <span class='grammar-underline'>can</span> transform in Attack on Titan anime.",
      ans: "Eren",
      query: "eren-yeager",
    },
    {
      h1: "<span class='grammar-underline'>What</span> Japanese hot spring do people bathe in?",
      h2: "<span class='grammar-underline'>Where</span> can you find them? In mountains?",
      h3: "I <span class='grammar-underline'>like going</span> to these relaxing natural baths.",
      ans: "Onsen",
      query: "hot-spring",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> do you go to buy food and groceries?",
      h2: "<span class='grammar-underline'>What</span> can you find there? Fruits and vegetables?",
      h3: "This place <span class='grammar-underline'>is</span> called a supermarket or konbini.",
      ans: "Store",
      query: "grocery-store",
    },
    {
      h1: "<span class='grammar-underline'>What</span> planet is called the Red Planet?",
      h2: "<span class='grammar-underline'>Where</span> is it? Next to Earth?",
      h3: "This planet <span class='grammar-underline'>is</span> fourth from the sun.",
      ans: "Mars",
      query: "red-planet",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> was the American president with a tall black hat?",
      h2: "<span class='grammar-underline'>When</span> did he lead? During the Civil War?",
      h3: "He <span class='grammar-underline'>can</span> be seen on the five-dollar bill.",
      ans: "Lincoln",
      query: "abraham-lincoln",
    },
    {
      h1: "<span class='grammar-underline'>What</span> Japanese art uses ink and brush on paper?",
      h2: "<span class='grammar-underline'>When</span> do students learn it? In school?",
      h3: "This art <span class='grammar-underline'>is</span> called shodo or calligraphy.",
      ans: "Calligraphy",
      query: "japanese-calligraphy",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> is the ancient pyramid city in Mexico?",
      h2: "<span class='grammar-underline'>What</span> can you see? Sun and Moon pyramids?",
      h3: "This place <span class='grammar-underline'>is</span> called Teotihuacan near Mexico City.",
      ans: "Mexico",
      query: "mexico-pyramids",
    },
    {
      h1: "<span class='grammar-underline'>What</span> black and white animal eats bamboo?",
      h2: "<span class='grammar-underline'>Where</span> does it live? In China?",
      h3: "This animal <span class='grammar-underline'>is</span> a giant panda bear.",
      ans: "Panda",
      query: "panda-bear",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the Japanese samurai who helped unify Japan?",
      h2: "<span class='grammar-underline'>What</span> did he build? Osaka Castle?",
      h3: "He <span class='grammar-underline'>can</span> be remembered as Toyotomi Hideyoshi.",
      ans: "Toyotomi",
      query: "toyotomi-hideyoshi",
    },
    {
      h1: "<span class='grammar-underline'>What</span> instrument has six strings and you play with fingers?",
      h2: "<span class='grammar-underline'>Where</span> do musicians use it? In concerts?",
      h3: "This <span class='grammar-underline'>is</span> used in rock and classical music.",
      ans: "Guitar",
      query: "guitar-instrument",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the princess in the Disney movie with ice powers?",
      h2: "<span class='grammar-underline'>What</span> can she create? Snow and ice castles?",
      h3: "She <span class='grammar-underline'>can</span> sing 'Let It Go' in Frozen.",
      ans: "Elsa",
      query: "frozen-elsa",
    },
    {
      h1: "<span class='grammar-underline'>What</span> season comes after spring in Japan?",
      h2: "<span class='grammar-underline'>When</span> is it hot? From June to August?",
      h3: "This season <span class='grammar-underline'>is</span> called natsu with festivals.",
      ans: "Summer",
      query: "summer-season",
    },
    {
      h1: "<span class='grammar-underline'>Where</span> do students go to study and learn every day?",
      h2: "<span class='grammar-underline'>What</span> do you do there? Read and write?",
      h3: "This place <span class='grammar-underline'>is</span> where teachers work.",
      ans: "School",
      query: "school-building",
    },
    {
      h1: "<span class='grammar-underline'>What</span> yellow fruit do monkeys love to eat?",
      h2: "<span class='grammar-underline'>Where</span> does it grow? On trees in warm places?",
      h3: "I <span class='grammar-underline'>like eating</span> this curved tropical fruit.",
      ans: "Banana",
      query: "yellow-banana",
    },
    {
      h1: "<span class='grammar-underline'>Who</span> is the electric yellow Pokemon who says 'Pika Pika'?",
      h2: "<span class='grammar-underline'>What</span> type is he? Electric type?",
      h3: "He <span class='grammar-underline'>can</span> shock enemies with thunderbolt.",
      ans: "Pikachu",
      query: "pikachu-pokemon",
    },
  ],
  JHS2: [
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this country is shaped like a boot in Europe.",
      h2: "It <span class='grammar-underline'>is important to</span> visit Rome and Venice there.",
      h3: "I enjoy <span class='grammar-underline'>eating</span> pasta and gelato in Italy.",
      ans: "Italy",
      query: "italy-country",
    },
    {
      h1: "You <span class='grammar-underline'>have to</span> use rice and seaweed to make this Japanese food.",
      h2: "I <span class='grammar-underline'>know how to</span> roll it with bamboo mat.",
      h3: "I <span class='grammar-underline'>am sure that</span> onigiri is perfect for lunch.",
      ans: "Onigiri",
      query: "rice-ball",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this ancient wonder in Jordan was carved in rock.",
      h2: "It <span class='grammar-underline'>is important to</span> see Petra's pink stone buildings.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about this lost city.",
      ans: "Petra",
      query: "petra-jordan",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> learn about this nurse who helped soldiers in wars.",
      h2: "I <span class='grammar-underline'>can show you how to</span> remember Florence Nightingale's work.",
      h3: "I <span class='grammar-underline'>am sure that</span> she founded modern nursing.",
      ans: "Florence Nightingale",
      query: "nightingale-nurse",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this festival has cherry blossoms in spring.",
      h2: "You <span class='grammar-underline'>have to</span> enjoy hanami parties under trees.",
      h3: "I enjoy <span class='grammar-underline'>celebrating</span> sakura season in Japan.",
      ans: "Hanami",
      query: "cherry-blossom-viewing",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this Thai dish has rice noodles and peanuts.",
      h2: "It <span class='grammar-underline'>is important to</span> try this sweet and sour meal.",
      h3: "I enjoy <span class='grammar-underline'>eating</span> pad thai with lime.",
      ans: "Pad Thai",
      query: "thai-noodles",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> protect this large gray animal with tusks.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize elephants by their trunk.",
      h3: "I <span class='grammar-underline'>am sure that</span> they are the largest land animals.",
      ans: "Elephant",
      query: "elephant-animal",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this athlete is the fastest woman runner.",
      h2: "You <span class='grammar-underline'>have to</span> be very quick like Florence Griffith-Joyner.",
      h3: "I enjoy <span class='grammar-underline'>watching</span> track and field at Olympics.",
      ans: "Florence Griffith",
      query: "flojo-runner",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this tower in Italy is famous for leaning.",
      h2: "It <span class='grammar-underline'>is important to</span> visit Pisa to see it.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> why the tower tilts.",
      ans: "Leaning Tower",
      query: "pisa-tower",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> visit this famous gate in Berlin, Germany.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize Brandenburg Gate.",
      h3: "<span class='grammar-underline'>Walking</span> through this gate is very special.",
      ans: "Brandenburg Gate",
      query: "berlin-gate",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this Japanese garden has a sand garden in Kyoto.",
      h2: "You <span class='grammar-underline'>have to</span> visit Ryoan-ji temple to see it.",
      h3: "I enjoy <span class='grammar-underline'>meditating</span> in this peaceful zen garden.",
      ans: "Ryoan-ji",
      query: "rock-garden",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this sport uses a small white ball and clubs.",
      h2: "It <span class='grammar-underline'>is important to</span> practice your swing in golf.",
      h3: "I enjoy <span class='grammar-underline'>playing</span> on the green course.",
      ans: "Golf",
      query: "golf-sport",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> learn about this explorer who reached India by sea.",
      h2: "I <span class='grammar-underline'>can show you how to</span> remember Vasco da Gama's voyage.",
      h3: "I <span class='grammar-underline'>am sure that</span> he sailed around Africa.",
      ans: "Vasco da Gama",
      query: "portuguese-explorer",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this anime features a boy who becomes a hero.",
      h2: "You <span class='grammar-underline'>have to</span> watch My Hero Academia.",
      h3: "I enjoy <span class='grammar-underline'>watching</span> Deku gain superpowers.",
      ans: "Deku",
      query: "my-hero-deku",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this gas giant planet has a big red spot.",
      h2: "It <span class='grammar-underline'>is important to</span> study Jupiter in space.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about the largest planet in our solar system.",
      ans: "Jupiter",
      query: "planet-jupiter",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> remember this person who painted the Starry Night.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize Vincent van Gogh's art style.",
      h3: "I <span class='grammar-underline'>am sure that</span> he was a Dutch post-impressionist painter.",
      ans: "Van Gogh",
      query: "van-gogh-artist",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this traditional Japanese food is fermented soy beans.",
      h2: "You <span class='grammar-underline'>have to</span> mix it until it becomes sticky.",
      h3: "I enjoy <span class='grammar-underline'>eating</span> natto with rice and mustard.",
      ans: "Natto",
      query: "fermented-beans",
    },
    {
      h1: "I <span class='grammar-underline'>think that</span> this river flows through Brazil and South America.",
      h2: "It <span class='grammar-underline'>is important to</span> protect the rainforest around it.",
      h3: "I enjoy <span class='grammar-underline'>learning</span> about the Amazon River's biodiversity.",
      ans: "Amazon",
      query: "amazon-river",
    },
    {
      h1: "We <span class='grammar-underline'>must</span> study this character who can stretch his body like rubber.",
      h2: "I <span class='grammar-underline'>can show you how to</span> recognize Monkey D. Luffy by his straw hat.",
      h3: "<span class='grammar-underline'>Watching</span> One Piece anime is very exciting.",
      ans: "Luffy",
      query: "one-piece-luffy",
    },
    {
      h1: "I <span class='grammar-underline'>am sure that</span> this Japanese city is famous for its delicious ramen.",
      h2: "You <span class='grammar-underline'>have to</span> visit Fukuoka to try Tonkotsu ramen.",
      h3: "I enjoy <span class='grammar-underline'>eating</span> ramen at yatai food stalls.",
      ans: "Fukuoka",
      query: "fukuoka-city",
    },
  ],
  JHS3: [
    {
      h1: "I <span class='grammar-underline'>have been studying</span> this English monument of large standing stones.",
      h2: "This is <span class='grammar-underline'>a structure that</span> was built thousands of years ago.",
      h3: "The stones <span class='grammar-underline'>are arranged</span> in a circular pattern in Salisbury.",
      ans: "Stonehenge",
      query: "stonehenge-monument",
    },
    {
      h1: "The leader <span class='grammar-underline'>founding</span> the first modern Olympic Games was French.",
      h2: "This is <span class='grammar-underline'>a person who</span> wanted to promote world peace through sport.",
      h3: "I <span class='grammar-underline'>have learned</span> that Pierre de Coubertin started the IOC.",
      ans: "Coubertin",
      query: "olympic-founder",
    },
    {
      h1: "I <span class='grammar-underline'>have been reading</span> this Japanese folktale about an old man who makes trees bloom.",
      h2: "It is <span class='grammar-underline'>a story where</span> a kind man spreads ash on dead cherry trees.",
      h3: "The trees <span class='grammar-underline'>bloom beautifully</span> even in winter.",
      ans: "Hanasaka Jiisan",
      query: "blooming-trees",
    },
    {
      h1: "The scientist <span class='grammar-underline'>discovering</span> penicillin changed medicine forever.",
      h2: "This is <span class='grammar-underline'>a person who</span> found the first antibiotic in 1928.",
      h3: "I <span class='grammar-underline'>have heard</span> about Alexander Fleming's life-saving discovery.",
      ans: "Fleming",
      query: "penicillin-discovery",
    },
    {
      h1: "I <span class='grammar-underline'>have visited</span> this historical site in Nara with a giant Buddha statue.",
      h2: "This is <span class='grammar-underline'>a temple that</span> is the largest wooden building in the world.",
      h3: "If I <span class='grammar-underline'>lived</span> in Nara, I <span class='grammar-underline'>would</span> visit Todai-ji every month.",
      ans: "Todai-ji",
      query: "nara-temple",
    },
    {
      h1: "The singer <span class='grammar-underline'>performing</span> 'Shape of You' is from England.",
      h2: "This is <span class='grammar-underline'>a person who</span> plays the guitar and loop pedal.",
      h3: "I <span class='grammar-underline'>have listened to</span> Ed Sheeran's pop songs many times.",
      ans: "Ed Sheeran",
      query: "british-pop-singer",
    },
    {
      h1: "I <span class='grammar-underline'>have been learning</span> about this invention that helps us fly across oceans.",
      h2: "It is <span class='grammar-underline'>a machine that</span> the Wright Brothers first flew in 1903.",
      h3: "The world <span class='grammar-underline'>became smaller</span> when people could travel by airplane.",
      ans: "Airplane",
      query: "flight-airplane",
    },
    {
      h1: "The explorer <span class='grammar-underline'>finding</span> the source of the Nile was a famous Scotsman.",
      h2: "This is <span class='grammar-underline'>a person who</span> traveled deep into Africa.",
      h3: "I <span class='grammar-underline'>have studied</span> David Livingstone's African explorations.",
      ans: "Livingstone",
      query: "african-explorer",
    },
    {
      h1: "I <span class='grammar-underline'>have just finished</span> watching this anime about a boy with a notebook that kills.",
      h2: "It is <span class='grammar-underline'>a series that</span> features Light Yagami and Ryuk.",
      h3: "The characters <span class='grammar-underline'>play a game</span> of cat and mouse in Death Note.",
      ans: "Death Note",
      query: "death-note-anime",
    },
    {
      h1: "I <span class='grammar-underline'>have been watching</span> this summer sport where players hit a ball over a net.",
      h2: "This is <span class='grammar-underline'>a sport that</span> is played on sand or a court.",
      h3: "Tell me <span class='grammar-underline'>which volleyball player</span> you support the most.",
      ans: "Volleyball",
      query: "volleyball-sport",
    },
    {
      h1: "I <span class='grammar-underline'>have never climbed</span> this famous mountain in Switzerland shaped like a tooth.",
      h2: "This is <span class='grammar-underline'>a mountain that</span> is iconically steep and rocky.",
      h3: "Tell me <span class='grammar-underline'>where the Matterhorn</span> is located.",
      ans: "Matterhorn",
      query: "matterhorn-mountain",
    },
    {
      h1: "The author <span class='grammar-underline'>writing</span> about a boy who never grows up lived in London.",
      h2: "This is <span class='grammar-underline'>a writer who</span> created Peter Pan and Neverland.",
      h3: "I <span class='grammar-underline'>wish I could</span> meet J.M. Barrie in person.",
      ans: "J.M. Barrie",
      query: "peter-pan-author",
    },
    {
      h1: "I <span class='grammar-underline'>have been studying</span> this period of history in Europe called the Rebirth.",
      h2: "It is <span class='grammar-underline'>a time when</span> art and science flourished.",
      h3: "Many artists <span class='grammar-underline'>created masterpieces</span> during the Renaissance.",
      ans: "Renaissance",
      query: "renaissance-art",
    },
    {
      h1: "The athlete <span class='grammar-underline'>playing</span> tennis won many Grand Slam titles.",
      h2: "This is <span class='grammar-underline'>a person who</span> is from Switzerland and called King of Grass.",
      h3: "I <span class='grammar-underline'>have seen</span> Roger Federer play many classic matches.",
      ans: "Federer",
      query: "tennis-legend",
    },
    {
      h1: "I <span class='grammar-underline'>have just learned</span> about this ancient city in Greece.",
      h2: "This is <span class='grammar-underline'>a city that</span> was the birthplace of democracy.",
      h3: "Tell me <span class='grammar-underline'>what can be seen</span> at the Acropolis in Athens.",
      ans: "Athens",
      query: "athens-acropolis",
    },
    {
      h1: "The inventor <span class='grammar-underline'>creating</span> the steam engine powered the Industrial Revolution.",
      h2: "This is <span class='grammar-underline'>a person who</span> improved Newcomen's design in 1776.",
      h3: "I <span class='grammar-underline'>have read</span> about James Watt's engineering genius.",
      ans: "James Watt",
      query: "steam-engine-inventor",
    },
    {
      h1: "I <span class='grammar-underline'>have been practicing</span> this traditional Japanese dance for festivals.",
      h2: "It is <span class='grammar-underline'>a dance form that</span> people perform around a tower.",
      h3: "Dancers <span class='grammar-underline'>wear yukata</span> during Bon Odori celebrations.",
      ans: "Bon Odori",
      query: "japanese-festival-dance",
    },
    {
      h1: "The composer <span class='grammar-underline'>writing</span> 'The Magic Flute' was a child prodigy.",
      h2: "This is <span class='grammar-underline'>a musician who</span> was born in Salzburg, Austria.",
      h3: "I <span class='grammar-underline'>have listened to</span> Wolfgang Amadeus Mozart's operas.",
      ans: "Mozart",
      query: "mozart-composer",
    },
    {
      h1: "I <span class='grammar-underline'>have just learned</span> about this wall that is the longest in the world.",
      h2: "This is <span class='grammar-underline'>a barrier that</span> protects the northern border of China.",
      h3: "Tell me <span class='grammar-underline'>how long the Great Wall</span> of China is.",
      ans: "Great Wall",
      query: "great-wall-china",
    },
    {
      h1: "The actress <span class='grammar-underline'>starring</span> in La La Land won an Oscar.",
      h2: "This is <span class='grammar-underline'>a person who</span> played Mia in the musical film.",
      h3: "I <span class='grammar-underline'>have watched</span> Emma Stone in many movies.",
      ans: "Emma Stone",
      query: "lalaland-actress",
    },
  ],
};
