export interface GGQuestion {
  sentence: string;
  blank: string;
  options: string[];
  hint: string;
}
export interface GGWeek {
  week: number;
  title: string;
  grammarFocus: string;
  questions: GGQuestion[];
}

// 40 weeks following MEXT JHS grammar progression (New Horizon / Here We Go / Sunshine)
// 中1 Weeks 1-13 → 中2 Weeks 14-26 → 中3 Weeks 27-40
export const grammarGolfWeeks: GGWeek[] = [
  { week: 1, title: "Self-Introduction", grammarFocus: "I am / She is / We are (be verb)",
    questions: [
      { sentence: "I ___ a Grade 7 student at Sakura Junior High.", blank: "am", options: ["am", "is", "are", "be"], hint: "Be verb for the subject 'I'" },
      { sentence: "She ___ my English teacher.", blank: "is", options: ["is", "am", "are", "be"], hint: "Be verb for 'she'" },
      { sentence: "We ___ in the same homeroom class.", blank: "are", options: ["are", "is", "am", "be"], hint: "Be verb for 'we'" },
      { sentence: "My name ___ Yuki. Nice to meet you.", blank: "is", options: ["is", "am", "are", "be"], hint: "Be verb with 'my name'" },
      { sentence: "___ you from Australia?", blank: "Are", options: ["Are", "Am", "Is", "Do"], hint: "Be verb question with 'you'" },
      { sentence: "I ___ not very confident at speaking yet.", blank: "am", options: ["am", "is", "are", "was"], hint: "Negative be verb for 'I'" },
      { sentence: "He ___ the captain of the basketball team.", blank: "is", options: ["is", "am", "are", "has"], hint: "Be verb for 'he'" },
      { sentence: "They ___ new exchange students from Canada.", blank: "are", options: ["are", "is", "am", "be"], hint: "Be verb for 'they'" },
      { sentence: "Our school ___ very large and modern.", blank: "is", options: ["is", "am", "are", "has"], hint: "Be verb for 'our school'" },
      { sentence: "___ you ready to start the lesson?", blank: "Are", options: ["Are", "Am", "Is", "Do"], hint: "Be verb question with 'you'" },
    ]},
  { week: 2, title: "Having Things", grammarFocus: "I have / She has / Do you have? (have/has)",
    questions: [
      { sentence: "I ___ a Japanese-English dictionary.", blank: "have", options: ["have", "has", "had", "am"], hint: "Possession verb for 'I'" },
      { sentence: "She ___ three younger brothers.", blank: "has", options: ["has", "have", "had", "is"], hint: "Possession verb for 'she' (3rd person)" },
      { sentence: "Do you ___ a ruler I can borrow?", blank: "have", options: ["have", "has", "had", "are"], hint: "Base form after 'Do you'" },
      { sentence: "___ she have a calculator for math class?", blank: "Does", options: ["Does", "Do", "Has", "Is"], hint: "Helper verb for 3rd person question" },
      { sentence: "Our school ___ a wonderful library.", blank: "has", options: ["has", "have", "had", "is"], hint: "Possession verb for 'our school'" },
      { sentence: "I don't ___ my textbook today — I forgot it.", blank: "have", options: ["have", "has", "had", "am"], hint: "Base form after 'don't'" },
      { sentence: "He ___ a dream to become a professional soccer player.", blank: "has", options: ["has", "have", "had", "is"], hint: "Possession verb for 'he'" },
      { sentence: "___ you have any questions about the instructions?", blank: "Do", options: ["Do", "Does", "Have", "Are"], hint: "Helper verb for 'you' questions" },
      { sentence: "We ___ club practice three times a week.", blank: "have", options: ["have", "has", "had", "are"], hint: "Possession verb for 'we'" },
      { sentence: "Does your father ___ a car?", blank: "have", options: ["have", "has", "had", "own"], hint: "Base form after 'Does'" },
    ]},
  { week: 3, title: "Likes and Dislikes", grammarFocus: "I like / I don't like / Do you like?",
    questions: [
      { sentence: "I ___ playing soccer with my friends after school.", blank: "like", options: ["like", "likes", "liked", "am"], hint: "Like verb for 'I'" },
      { sentence: "Does she ___ spicy food?", blank: "like", options: ["like", "likes", "liked", "is"], hint: "Base form after 'Does she'" },
      { sentence: "He ___ reading manga and watching anime.", blank: "likes", options: ["likes", "like", "liked", "enjoyed"], hint: "Like verb for 'he' (3rd person -s)" },
      { sentence: "I don't ___ getting up early on school days.", blank: "like", options: ["like", "likes", "liked", "am"], hint: "Base form after 'don't'" },
      { sentence: "What kind of music ___ you like?", blank: "do", options: ["do", "does", "is", "are"], hint: "Helper verb for 'you' questions" },
      { sentence: "She ___ studying English but doesn't like tests.", blank: "likes", options: ["likes", "like", "liked", "prefers"], hint: "Like verb for 'she' (3rd person -s)" },
      { sentence: "___ you like Japanese traditional food?", blank: "Do", options: ["Do", "Does", "Is", "Are"], hint: "Helper verb for 'you' questions" },
      { sentence: "My sister ___ dancing more than singing.", blank: "likes", options: ["likes", "like", "liked", "prefer"], hint: "Like verb for 'my sister' (3rd person)" },
      { sentence: "I really ___ living in Japan.", blank: "like", options: ["like", "likes", "liked", "love"], hint: "Like verb for 'I' (with adverb 'really')" },
      { sentence: "What do you ___ most about your school?", blank: "like", options: ["like", "likes", "liked", "enjoy"], hint: "Base form after 'do you'" },
    ]},
  { week: 4, title: "This and That", grammarFocus: "This is / That is / It is (demonstratives)",
    questions: [
      { sentence: "What is ___? It is a compass.", blank: "this", options: ["this", "that", "it", "those"], hint: "Demonstrative for something close to you" },
      { sentence: "___ is my homeroom teacher, Mr. Tanaka.", blank: "This", options: ["This", "That", "It", "He"], hint: "Introducing someone near you" },
      { sentence: "Is ___ your pencil case over there?", blank: "that", options: ["that", "this", "it", "those"], hint: "Demonstrative for something far away" },
      { sentence: "___ is very cold today, isn't it?", blank: "It", options: ["It", "This", "That", "There"], hint: "Used to talk about the weather" },
      { sentence: "___ is Yuki. She is my best friend.", blank: "This", options: ["This", "That", "It", "He"], hint: "Introducing a person near you" },
      { sentence: "Is ___ the new gymnasium over there?", blank: "that", options: ["that", "this", "it", "these"], hint: "Pointing to something far away" },
      { sentence: "___ is a really interesting question.", blank: "That", options: ["That", "This", "It", "These"], hint: "Referring to something just said" },
      { sentence: "What is ___? It is a Japanese-English dictionary.", blank: "this", options: ["this", "that", "those", "these"], hint: "Demonstrative for something held in your hand" },
      { sentence: "___ takes about ten minutes to walk to school.", blank: "It", options: ["It", "That", "This", "There"], hint: "Used for distance or time — 'It takes'" },
      { sentence: "___ is 8:30 AM — time to start class!", blank: "It", options: ["It", "This", "That", "There"], hint: "Used to state the time — 'It is + time'" },
    ]},
  { week: 5, title: "Abilities", grammarFocus: "Can / Can't + ability verb",
    questions: [
      { sentence: "I ___ speak English and a little French.", blank: "can", options: ["can", "could", "am", "will"], hint: "Modal verb for present ability" },
      { sentence: "___ you play any musical instruments?", blank: "Can", options: ["Can", "Do", "Are", "Will"], hint: "Modal verb question for ability" },
      { sentence: "She ___ swim very fast — she's on the team.", blank: "can", options: ["can", "could", "is", "will"], hint: "Modal verb for present ability" },
      { sentence: "He ___ come to practice today — he has a cold.", blank: "can't", options: ["can't", "couldn't", "doesn't", "won't"], hint: "Negative modal for inability (contracted)" },
      { sentence: "Can I ___ your dictionary for a moment, please?", blank: "use", options: ["use", "uses", "using", "used"], hint: "Base form verb after 'Can I'" },
      { sentence: "I ___ cook simple meals like rice and miso soup.", blank: "can", options: ["can", "could", "am", "will"], hint: "Modal verb for ability" },
      { sentence: "She ___ play piano yet, but she is practicing.", blank: "can't", options: ["can't", "doesn't", "won't", "isn't"], hint: "Negative ability — she is still learning" },
      { sentence: "___ you help me with this math problem?", blank: "Can", options: ["Can", "Do", "Will", "Are"], hint: "Polite request using modal verb" },
      { sentence: "My little brother ___ read yet — he is only four.", blank: "can't", options: ["can't", "doesn't", "won't", "isn't"], hint: "Negative ability — too young" },
      { sentence: "What ___ you do well in English?", blank: "can", options: ["can", "could", "do", "are"], hint: "Modal verb for asking about skills" },
    ]},
  { week: 6, title: "Asking Questions", grammarFocus: "What is / Where is (WH questions)",
    questions: [
      { sentence: "What ___ your favorite subject at school?", blank: "is", options: ["is", "are", "do", "have"], hint: "Be verb for singular subject" },
      { sentence: "Where ___ the school library?", blank: "is", options: ["is", "are", "do", "does"], hint: "Be verb for singular place" },
      { sentence: "What time ___ school finish every day?", blank: "does", options: ["does", "do", "is", "are"], hint: "Helper verb for 3rd person question" },
      { sentence: "Where ___ you usually study at home?", blank: "do", options: ["do", "does", "is", "are"], hint: "Helper verb for 'you' questions" },
      { sentence: "What ___ this word mean in Japanese?", blank: "does", options: ["does", "do", "is", "are"], hint: "Helper verb for 3rd person ('this word')" },
      { sentence: "Where ___ the soccer club practice after school?", blank: "does", options: ["does", "do", "is", "are"], hint: "Helper verb for 3rd person subject" },
      { sentence: "What ___ in your pencil case?", blank: "is", options: ["is", "are", "do", "have"], hint: "Be verb — asking about singular content" },
      { sentence: "Where ___ the nearest hospital?", blank: "is", options: ["is", "are", "do", "does"], hint: "Be verb for location question" },
      { sentence: "What ___ your homeroom teacher's name?", blank: "is", options: ["is", "are", "do", "does"], hint: "Be verb for singular noun" },
      { sentence: "___ is the science lab? — It's on the third floor.", blank: "Where", options: ["Where", "What", "Who", "When"], hint: "WH word for asking about location" },
    ]},
  { week: 7, title: "Daily Routines", grammarFocus: "Who / When / How often? (WH questions with frequency)",
    questions: [
      { sentence: "How ___ do you study English at home?", blank: "often", options: ["often", "many", "long", "much"], hint: "Asking about frequency — how many times" },
      { sentence: "When ___ summer vacation start in Japan?", blank: "does", options: ["does", "do", "is", "will"], hint: "Helper verb for 3rd person question" },
      { sentence: "Who ___ your favorite teacher this year?", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for singular person" },
      { sentence: "I ___ study for at least one hour every evening.", blank: "always", options: ["always", "never", "rarely", "sometimes"], hint: "Frequency adverb meaning 100% of the time" },
      { sentence: "She ___ goes to her grandmother's house on Sundays.", blank: "usually", options: ["usually", "never", "rarely", "always"], hint: "Frequency adverb meaning 'most of the time'" },
      { sentence: "How ___ time does it take to get to school?", blank: "long", options: ["long", "many", "much", "often"], hint: "Asking about duration — time length" },
      { sentence: "When ___ the school sports festival held every year?", blank: "is", options: ["is", "does", "was", "are"], hint: "Be verb for event question" },
      { sentence: "He ___ practices basketball — only before tournaments.", blank: "rarely", options: ["rarely", "always", "usually", "often"], hint: "Frequency adverb — almost never" },
      { sentence: "How ___ students are in your class?", blank: "many", options: ["many", "much", "often", "long"], hint: "Asking about countable number" },
      { sentence: "How ___ does the school bus come?", blank: "often", options: ["often", "long", "many", "much"], hint: "Asking about frequency of transport" },
    ]},
  { week: 8, title: "School Routines", grammarFocus: "I study / We have / They eat (present simple – I/we/you/they)",
    questions: [
      { sentence: "I ___ English for one hour every evening.", blank: "study", options: ["study", "studies", "studied", "studying"], hint: "Present simple for 'I'" },
      { sentence: "We ___ club activities three times a week.", blank: "have", options: ["have", "has", "had", "having"], hint: "Present simple for 'we'" },
      { sentence: "I always ___ breakfast before school.", blank: "eat", options: ["eat", "eats", "ate", "eating"], hint: "Present simple for 'I' (always)" },
      { sentence: "They ___ their classroom every day after school.", blank: "clean", options: ["clean", "cleans", "cleaned", "cleaning"], hint: "Present simple for 'they'" },
      { sentence: "___ you practice any sports on weekends?", blank: "Do", options: ["Do", "Does", "Is", "Are"], hint: "Helper verb for 'you' questions" },
      { sentence: "We ___ English grammar on Monday mornings.", blank: "study", options: ["study", "studies", "studied", "studying"], hint: "Present simple for 'we'" },
      { sentence: "I usually ___ to school, but sometimes take the bus.", blank: "walk", options: ["walk", "walks", "walked", "walking"], hint: "Present simple for 'I' (with usually)" },
      { sentence: "You ___ to bring your PE clothes on Wednesday.", blank: "need", options: ["need", "needs", "needed", "needing"], hint: "Present simple for 'you'" },
      { sentence: "They ___ lunch in the cafeteria every day.", blank: "eat", options: ["eat", "eats", "ate", "eating"], hint: "Present simple for 'they'" },
      { sentence: "We ___ a homeroom meeting every Monday morning.", blank: "have", options: ["have", "has", "had", "are"], hint: "Present simple for 'we'" },
    ]},
  { week: 9, title: "My Family", grammarFocus: "She teaches / He lives / My mother works (3rd person -s)",
    questions: [
      { sentence: "She ___ English at our junior high school.", blank: "teaches", options: ["teaches", "teach", "taught", "teaching"], hint: "3rd person -s form of 'teach' (irregular)" },
      { sentence: "He ___ near the train station.", blank: "lives", options: ["lives", "live", "lived", "living"], hint: "3rd person -s form of 'live'" },
      { sentence: "My father ___ to work very early every morning.", blank: "goes", options: ["goes", "go", "went", "going"], hint: "3rd person -s form of 'go' (irregular)" },
      { sentence: "She ___ the piano for an hour every day.", blank: "practices", options: ["practices", "practice", "practiced", "practicing"], hint: "3rd person -s form of 'practice'" },
      { sentence: "___ your mother work at a hospital?", blank: "Does", options: ["Does", "Do", "Is", "Has"], hint: "Helper verb for 3rd person question" },
      { sentence: "He ___ soccer on weekends with neighborhood friends.", blank: "plays", options: ["plays", "play", "played", "playing"], hint: "3rd person -s form of 'play'" },
      { sentence: "The bus ___ at 8:10 every morning.", blank: "leaves", options: ["leaves", "leave", "left", "leaving"], hint: "3rd person -s form of 'leave'" },
      { sentence: "Our English teacher always ___ interesting activities.", blank: "prepares", options: ["prepares", "prepare", "prepared", "preparing"], hint: "3rd person -s form of 'prepare'" },
      { sentence: "___ she like eating Japanese traditional food?", blank: "Does", options: ["Does", "Do", "Is", "Has"], hint: "Helper verb for 'she' question" },
      { sentence: "My grandmother ___ in a small village in Nagano.", blank: "lives", options: ["lives", "live", "lived", "living"], hint: "3rd person -s form of 'live'" },
    ]},
  { week: 10, title: "Right Now", grammarFocus: "I am studying / She is reading (present progressive)",
    questions: [
      { sentence: "I am ___ for my English test right now.", blank: "studying", options: ["studying", "study", "studied", "studies"], hint: "-ing form of 'study' (drop the y, add -ying)" },
      { sentence: "___ she reading a book in the library?", blank: "Is", options: ["Is", "Are", "Am", "Does"], hint: "Be verb for 'she' in progressive" },
      { sentence: "We are ___ hard for the school sports festival.", blank: "practicing", options: ["practicing", "practice", "practiced", "practices"], hint: "-ing form of 'practice'" },
      { sentence: "What are you ___? — I am writing a letter.", blank: "doing", options: ["doing", "do", "did", "does"], hint: "-ing form of 'do'" },
      { sentence: "It is ___ heavily outside right now.", blank: "raining", options: ["raining", "rain", "rained", "to rain"], hint: "-ing form of 'rain'" },
      { sentence: "He is not ___ to music — he is sleeping!", blank: "listening", options: ["listening", "listen", "listened", "listens"], hint: "-ing form of 'listen'" },
      { sentence: "___ they practicing for the school play?", blank: "Are", options: ["Are", "Is", "Am", "Do"], hint: "Be verb for 'they' in progressive" },
      { sentence: "She ___ her school uniform today.", blank: "is wearing", options: ["is wearing", "wears", "wore", "has worn"], hint: "Present progressive — happening now" },
      { sentence: "Look! The teacher ___ something on the board.", blank: "is writing", options: ["is writing", "writes", "wrote", "has written"], hint: "Present progressive — happening right now" },
      { sentence: "Why ___ you crying? Did something happen?", blank: "are", options: ["are", "am", "is", "do"], hint: "Be verb for 'you' in progressive question" },
    ]},
  { week: 11, title: "Dates & Schedules", grammarFocus: "on + date / in + month / ordinal numbers",
    questions: [
      { sentence: "My birthday is ___ April 15th.", blank: "on", options: ["on", "in", "at", "for"], hint: "Preposition with a specific date" },
      { sentence: "School starts ___ April every year in Japan.", blank: "in", options: ["in", "on", "at", "by"], hint: "Preposition with months" },
      { sentence: "She came ___ in the English speech contest.", blank: "first", options: ["first", "one", "once", "firstly"], hint: "Ordinal number for position 1" },
      { sentence: "There are ___ semesters in a Japanese school year.", blank: "two", options: ["two", "three", "four", "twice"], hint: "Japan has two main school terms per year" },
      { sentence: "The school festival is on the ___ Friday of October.", blank: "second", options: ["second", "two", "twice", "twofold"], hint: "Ordinal for 2 — the 2nd Friday" },
      { sentence: "The opening ceremony was ___ 2020.", blank: "in", options: ["in", "on", "at", "by"], hint: "Preposition with years" },
      { sentence: "She finished ___ place in the school marathon.", blank: "third", options: ["third", "three", "three-th", "thrice"], hint: "Ordinal for position 3" },
      { sentence: "Class 3-A is on the ___ floor of the school building.", blank: "third", options: ["third", "three", "thrice", "trio"], hint: "Ordinal number for a floor level" },
      { sentence: "Today is the ___ of June.", blank: "fifteenth", options: ["fifteenth", "fifteen", "fifth-teen", "five-ten"], hint: "Ordinal for 15" },
      { sentence: "The school year ends ___ March in Japan.", blank: "in", options: ["in", "on", "at", "by"], hint: "Preposition with months" },
    ]},
  { week: 12, title: "Last Weekend", grammarFocus: "I was / She was / Were you? (past be verb)",
    questions: [
      { sentence: "I ___ very nervous before my first English speech.", blank: "was", options: ["was", "were", "am", "is"], hint: "Past be verb for 'I'" },
      { sentence: "___ you at school yesterday?", blank: "Were", options: ["Were", "Was", "Are", "Did"], hint: "Past be verb question for 'you'" },
      { sentence: "The math test ___ harder than I expected.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past be verb for singular subject" },
      { sentence: "I ___ not happy with my test score.", blank: "was", options: ["was", "were", "am", "had"], hint: "Negative past be verb for 'I'" },
      { sentence: "Where ___ you last Saturday afternoon?", blank: "were", options: ["were", "was", "are", "did"], hint: "Past be verb question for 'you'" },
      { sentence: "She ___ excited because the school trip was tomorrow.", blank: "was", options: ["was", "were", "is", "had"], hint: "Past be verb for 'she'" },
      { sentence: "They ___ busy preparing for the school play.", blank: "were", options: ["were", "was", "are", "had"], hint: "Past be verb for 'they'" },
      { sentence: "___ the new ALT teacher interesting? Yes, she was!", blank: "Was", options: ["Was", "Were", "Is", "Did"], hint: "Past be verb question for singular subject" },
      { sentence: "The classroom ___ very quiet during the exam.", blank: "was", options: ["was", "were", "is", "had"], hint: "Past be verb for singular noun" },
      { sentence: "We ___ at the gym when the earthquake happened.", blank: "were", options: ["were", "was", "are", "had"], hint: "Past be verb for 'we'" },
    ]},
  { week: 13, title: "School Trip", grammarFocus: "I visited / We cleaned / She practiced (past simple – regular verbs)",
    questions: [
      { sentence: "I ___ Kyoto with my family last summer.", blank: "visited", options: ["visited", "visit", "visits", "visiting"], hint: "Past simple of 'visit' (add -ed)" },
      { sentence: "She ___ piano for two hours yesterday.", blank: "practiced", options: ["practiced", "practice", "practices", "practicing"], hint: "Past simple of 'practice'" },
      { sentence: "We ___ our classroom after the school festival.", blank: "cleaned", options: ["cleaned", "clean", "cleans", "cleaning"], hint: "Past simple of 'clean' (add -ed)" },
      { sentence: "___ you watch the baseball game on TV last night?", blank: "Did", options: ["Did", "Do", "Were", "Have"], hint: "Helper verb for past simple question" },
      { sentence: "He ___ hard and passed the final exam.", blank: "studied", options: ["studied", "study", "studies", "studying"], hint: "Past simple of 'study' (y → ied)" },
      { sentence: "I ___ dinner for my family when my mother was sick.", blank: "cooked", options: ["cooked", "cook", "cooks", "cooking"], hint: "Past simple of 'cook' (add -ed)" },
      { sentence: "She ___ home in the rain and arrived completely wet.", blank: "walked", options: ["walked", "walk", "walks", "walking"], hint: "Past simple of 'walk' (add -ed)" },
      { sentence: "They ___ for a long time about their summer plans.", blank: "talked", options: ["talked", "talk", "talks", "talking"], hint: "Past simple of 'talk' (add -ed)" },
      { sentence: "I didn't ___ the answer, so I asked my teacher.", blank: "know", options: ["know", "knew", "known", "knowing"], hint: "Base form after 'didn't'" },
      { sentence: "Where did you ___ last Sunday?", blank: "go", options: ["go", "went", "gone", "going"], hint: "Base form after 'did you'" },
    ]},
  { week: 14, title: "Irregular Past Verbs", grammarFocus: "I went / She had / We saw (past simple – irregular)",
    questions: [
      { sentence: "I ___ to Osaka with my family last Golden Week.", blank: "went", options: ["went", "go", "goes", "going"], hint: "Irregular past of 'go'" },
      { sentence: "She ___ a great time at the school festival.", blank: "had", options: ["had", "have", "has", "having"], hint: "Irregular past of 'have'" },
      { sentence: "We ___ a beautiful sunrise from the mountaintop.", blank: "saw", options: ["saw", "see", "seen", "seeing"], hint: "Irregular past of 'see'" },
      { sentence: "He ___ a souvenir for his grandmother in Kyoto.", blank: "bought", options: ["bought", "buy", "buys", "buying"], hint: "Irregular past of 'buy'" },
      { sentence: "She ___ a delicious cake for her mother's birthday.", blank: "made", options: ["made", "make", "makes", "making"], hint: "Irregular past of 'make'" },
      { sentence: "They ___ to school early to prepare for the presentation.", blank: "came", options: ["came", "come", "comes", "coming"], hint: "Irregular past of 'come'" },
      { sentence: "I ___ many photos on the class field trip to Nara.", blank: "took", options: ["took", "take", "takes", "taking"], hint: "Irregular past of 'take'" },
      { sentence: "She ___ me advice about studying for the exam.", blank: "gave", options: ["gave", "give", "gives", "giving"], hint: "Irregular past of 'give'" },
      { sentence: "I ___ sushi for the first time in Tsukiji Market.", blank: "ate", options: ["ate", "eat", "eats", "eating"], hint: "Irregular past of 'eat'" },
      { sentence: "He ___ a cold last week, so he couldn't attend club.", blank: "got", options: ["got", "get", "gets", "getting"], hint: "Irregular past of 'get'" },
    ]},
  { week: 15, title: "What Did You Do?", grammarFocus: "Did you...? / I didn't... (past simple questions & negatives)",
    questions: [
      { sentence: "___ you finish your homework last night?", blank: "Did", options: ["Did", "Do", "Were", "Have"], hint: "Helper verb for past simple question" },
      { sentence: "I ___ go to the library yesterday because it was closed.", blank: "didn't", options: ["didn't", "don't", "wasn't", "haven't"], hint: "Negative helper for past simple" },
      { sentence: "What ___ you do during the long weekend?", blank: "did", options: ["did", "do", "were", "have"], hint: "Helper verb for past 'what' question" },
      { sentence: "She ___ eat breakfast because she was in a hurry.", blank: "didn't", options: ["didn't", "doesn't", "wasn't", "hasn't"], hint: "Negative past simple for 'she'" },
      { sentence: "___ he study for the test, or did he forget?", blank: "Did", options: ["Did", "Do", "Was", "Has"], hint: "Helper verb for past simple question" },
      { sentence: "I ___ understand the teacher's explanation at all.", blank: "didn't", options: ["didn't", "don't", "wasn't", "haven't"], hint: "Negative past simple for 'I'" },
      { sentence: "___ they win the basketball tournament last month?", blank: "Did", options: ["Did", "Do", "Were", "Have"], hint: "Helper verb for past question with 'they'" },
      { sentence: "Where ___ you go for your school trip this year?", blank: "did", options: ["did", "do", "were", "have"], hint: "Helper verb for past 'where' question" },
      { sentence: "I ___ buy the book because it was too expensive.", blank: "didn't", options: ["didn't", "don't", "wasn't", "haven't"], hint: "Negative past simple for 'I'" },
      { sentence: "Why ___ she come to school yesterday?", blank: "didn't", options: ["didn't", "doesn't", "wasn't", "hasn't"], hint: "Negative helper verb in past question" },
    ]},
  { week: 16, title: "Quantities", grammarFocus: "How many / How much / How long / How far?",
    questions: [
      { sentence: "How ___ students are in your class?", blank: "many", options: ["many", "much", "often", "long"], hint: "Asking about a countable number" },
      { sentence: "How ___ does a school lunch cost in Japan?", blank: "much", options: ["much", "many", "long", "often"], hint: "Asking about price (uncountable)" },
      { sentence: "How ___ does it take to get to school by bus?", blank: "long", options: ["long", "many", "much", "often"], hint: "Asking about duration — time" },
      { sentence: "How ___ do you have English class per week?", blank: "often", options: ["often", "many", "long", "much"], hint: "Asking about frequency" },
      { sentence: "There ___ thirty-two students in our homeroom class.", blank: "are", options: ["are", "is", "have", "has"], hint: "Be verb for plural number" },
      { sentence: "The school gymnasium is about twenty ___ long.", blank: "meters", options: ["meters", "kilos", "grams", "liters"], hint: "Unit of length measurement" },
      { sentence: "How ___ is your school from the nearest station?", blank: "far", options: ["far", "long", "many", "much"], hint: "Asking about distance" },
      { sentence: "She ___ kendo for two hours every Tuesday evening.", blank: "practices", options: ["practices", "practice", "practiced", "practicing"], hint: "3rd person -s form of 'practice'" },
      { sentence: "How ___ water do you drink every day?", blank: "much", options: ["much", "many", "often", "long"], hint: "Asking about uncountable noun (water)" },
      { sentence: "How ___ clubs can a student join at your school?", blank: "many", options: ["many", "much", "often", "long"], hint: "Asking about countable number of clubs" },
    ]},
  { week: 17, title: "Comparing Things", grammarFocus: "Tokyo is bigger than Osaka (comparative adjectives)",
    questions: [
      { sentence: "Tokyo is ___ than Osaka.", blank: "bigger", options: ["bigger", "biggest", "more big", "big"], hint: "Comparative of 'big' (double g)" },
      { sentence: "The Shinkansen is ___ than a regular train.", blank: "faster", options: ["faster", "fastest", "more fast", "fast"], hint: "Comparative of 'fast'" },
      { sentence: "English is ___ interesting than I thought.", blank: "more", options: ["more", "most", "very", "much"], hint: "Use 'more' for long adjectives" },
      { sentence: "My sister is two years ___ than me.", blank: "older", options: ["older", "eldest", "elder", "more old"], hint: "Comparative of 'old'" },
      { sentence: "Summer in Japan is much ___ than in England.", blank: "hotter", options: ["hotter", "hottest", "more hot", "hot"], hint: "Comparative of 'hot' (double t)" },
      { sentence: "Healthy food is ___ for you than fast food.", blank: "better", options: ["better", "best", "more good", "gooder"], hint: "Irregular comparative of 'good'" },
      { sentence: "His test score was ___ than everyone else in the class.", blank: "higher", options: ["higher", "highest", "more high", "high"], hint: "Comparative of 'high'" },
      { sentence: "This bag is ___ than the one I saw yesterday.", blank: "cheaper", options: ["cheaper", "cheapest", "more cheap", "cheap"], hint: "Comparative of 'cheap'" },
      { sentence: "Which is ___ popular in Japan, soccer or baseball?", blank: "more", options: ["more", "most", "much", "very"], hint: "Use 'more' for multi-syllable adjectives" },
      { sentence: "She is ___ at math than anyone in our class.", blank: "better", options: ["better", "best", "more good", "gooder"], hint: "Irregular comparative of 'good'" },
    ]},
  { week: 18, title: "Superlatives & Records", grammarFocus: "The tallest / The most popular (superlative adjectives)",
    questions: [
      { sentence: "Mt. Fuji is the ___ mountain in Japan.", blank: "tallest", options: ["tallest", "taller", "most tall", "tall"], hint: "Superlative of 'tall'" },
      { sentence: "What is the ___ popular sport at your school?", blank: "most", options: ["most", "more", "very", "much"], hint: "Use 'the most' for multi-syllable adjectives" },
      { sentence: "She is the ___ student in our English class.", blank: "best", options: ["best", "better", "most good", "goodest"], hint: "Irregular superlative of 'good'" },
      { sentence: "The Pacific Ocean is the ___ ocean in the world.", blank: "largest", options: ["largest", "larger", "most large", "large"], hint: "Superlative of 'large'" },
      { sentence: "That was the ___ exciting game I have ever seen.", blank: "most", options: ["most", "more", "very", "much"], hint: "Use 'the most' before long adjectives" },
      { sentence: "Summer is the ___ season in Japan.", blank: "hottest", options: ["hottest", "hotter", "most hot", "hot"], hint: "Superlative of 'hot' (double t)" },
      { sentence: "Which is the ___ river in Japan?", blank: "longest", options: ["longest", "longer", "most long", "long"], hint: "Superlative of 'long'" },
      { sentence: "This is the ___ difficult test we have taken.", blank: "most", options: ["most", "more", "very", "much"], hint: "Use 'the most' for multi-syllable adjectives" },
      { sentence: "He is the ___ runner in the whole school.", blank: "fastest", options: ["fastest", "faster", "most fast", "fast"], hint: "Superlative of 'fast'" },
      { sentence: "Tokyo is one of the ___ crowded cities in the world.", blank: "most", options: ["most", "more", "very", "many"], hint: "Use 'the most' for multi-syllable adjectives" },
    ]},
  { week: 19, title: "Future Predictions", grammarFocus: "I will / It will / She won't (will – future)",
    questions: [
      { sentence: "I ___ study harder next semester.", blank: "will", options: ["will", "would", "am", "going to"], hint: "Modal verb for future intention" },
      { sentence: "It ___ probably rain tomorrow — bring an umbrella.", blank: "will", options: ["will", "would", "is", "going to"], hint: "Modal verb for weather prediction" },
      { sentence: "She ___ be able to come — she has another event.", blank: "won't", options: ["won't", "wouldn't", "can't", "isn't"], hint: "Negative future modal (contracted)" },
      { sentence: "I ___ help you with your English homework.", blank: "will", options: ["will", "would", "can", "am going to"], hint: "Future offer — will + verb" },
      { sentence: "The school festival ___ be held in October.", blank: "will", options: ["will", "would", "is", "has"], hint: "Scheduled future event with 'will'" },
      { sentence: "___ you be at school tomorrow morning?", blank: "Will", options: ["Will", "Would", "Are", "Do"], hint: "Modal verb question for future" },
      { sentence: "I think technology ___ change our lives completely.", blank: "will", options: ["will", "would", "must", "should"], hint: "Future prediction with 'I think'" },
      { sentence: "She ___ tell you the answer when she arrives.", blank: "will", options: ["will", "would", "can", "shall"], hint: "Future promise — will + verb" },
      { sentence: "He ___ probably not come to the party.", blank: "will", options: ["will", "would", "might", "can"], hint: "Negative future — will + probably not" },
      { sentence: "I promise I ___ never be late for class again.", blank: "will", options: ["will", "would", "can", "shall"], hint: "Future promise — will + base verb" },
    ]},
  { week: 20, title: "Making Plans", grammarFocus: "I am going to / She is going to (be going to – future plans)",
    questions: [
      { sentence: "I am going to ___ for the exam this weekend.", blank: "study", options: ["study", "studies", "studied", "studying"], hint: "Base form after 'going to'" },
      { sentence: "She is going to ___ the English speech contest.", blank: "join", options: ["join", "joins", "joined", "joining"], hint: "Base form after 'is going to'" },
      { sentence: "Are you going to ___ the school open day?", blank: "attend", options: ["attend", "attends", "attended", "attending"], hint: "Base form after 'going to' in a question" },
      { sentence: "We ___ going to clean the park as a class project.", blank: "are", options: ["are", "is", "am", "will"], hint: "Be verb for 'we' in 'going to'" },
      { sentence: "He is not going to ___ up on his dream.", blank: "give", options: ["give", "gives", "gave", "giving"], hint: "Base form in negative 'going to'" },
      { sentence: "What are you going to ___ during the summer holiday?", blank: "do", options: ["do", "does", "did", "doing"], hint: "Base form after 'going to' (what question)" },
      { sentence: "My sister ___ going to start high school in April.", blank: "is", options: ["is", "are", "am", "will"], hint: "Be verb for 'my sister' in 'going to'" },
      { sentence: "They are going to ___ Hiroshima on the school trip.", blank: "visit", options: ["visit", "visits", "visited", "visiting"], hint: "Base form after 'going to'" },
      { sentence: "___ she going to present her project today?", blank: "Is", options: ["Is", "Are", "Am", "Will"], hint: "Be verb question for 'she' in 'going to'" },
      { sentence: "I am going to ___ my best at the tournament.", blank: "do", options: ["do", "does", "did", "doing"], hint: "Base form after 'am going to' — 'do my best'" },
    ]},
  { week: 21, title: "Rules & Obligations", grammarFocus: "Have to / Has to / Don't have to",
    questions: [
      { sentence: "We ___ wear a school uniform every day.", blank: "have to", options: ["have to", "has to", "must to", "need"], hint: "Obligation for 'we'" },
      { sentence: "She ___ submit her homework by Friday.", blank: "has to", options: ["has to", "have to", "must to", "needs"], hint: "Obligation for 'she' (3rd person)" },
      { sentence: "You ___ come to school on Saturdays.", blank: "don't have to", options: ["don't have to", "can't", "mustn't", "shouldn't"], hint: "No obligation — it is not required" },
      { sentence: "___ I bring my own lunch to the field trip?", blank: "Do", options: ["Do", "Does", "Have", "Must"], hint: "Helper verb for 'I have to' question" },
      { sentence: "Students ___ be at school by 8:15 AM.", blank: "have to", options: ["have to", "has to", "must to", "need"], hint: "Obligation for plural noun" },
      { sentence: "He ___ see the school nurse because he feels unwell.", blank: "has to", options: ["has to", "have to", "must to", "needs"], hint: "Obligation for 'he' (3rd person)" },
      { sentence: "We ___ memorize every word — just the key vocabulary.", blank: "don't have to", options: ["don't have to", "can't", "mustn't", "shouldn't"], hint: "No obligation — not necessary" },
      { sentence: "Does she ___ wear glasses for reading?", blank: "have to", options: ["have to", "has to", "must", "need"], hint: "Base form 'have to' after 'Does'" },
      { sentence: "You ___ ask permission before leaving the classroom.", blank: "have to", options: ["have to", "has to", "must to", "need"], hint: "Obligation for 'you'" },
      { sentence: "___ students have to bring PE clothes on Wednesdays?", blank: "Do", options: ["Do", "Does", "Have", "Must"], hint: "Helper verb for 'have to' question" },
    ]},
  { week: 22, title: "Health Advice", grammarFocus: "You should / You must / You shouldn't",
    questions: [
      { sentence: "You ___ exercise for at least thirty minutes every day.", blank: "should", options: ["should", "must", "can", "will"], hint: "Advice — recommended but not forced" },
      { sentence: "She ___ take her medicine before going to bed.", blank: "must", options: ["must", "should", "can", "will"], hint: "Strong necessity or medical requirement" },
      { sentence: "You ___ eat too much sugar or junk food.", blank: "shouldn't", options: ["shouldn't", "mustn't", "can't", "won't"], hint: "Advice against something (negative should)" },
      { sentence: "We ___ wash our hands before eating and after using the toilet.", blank: "must", options: ["must", "should", "can", "will"], hint: "Strong necessity — hygiene rule" },
      { sentence: "You ___ sleep for at least eight hours every night.", blank: "should", options: ["should", "must", "can", "will"], hint: "Health advice — recommended amount of sleep" },
      { sentence: "Students ___ not use smartphones during class.", blank: "must", options: ["must", "should", "can", "will"], hint: "Strong rule — prohibition" },
      { sentence: "You ___ drink plenty of water, especially in summer.", blank: "should", options: ["should", "must", "can", "will"], hint: "Advice — important but not a rule" },
      { sentence: "She ___ stay up so late the night before an exam.", blank: "shouldn't", options: ["shouldn't", "mustn't", "can't", "won't"], hint: "Advice against bad habit" },
      { sentence: "You ___ eat breakfast — it helps you concentrate.", blank: "should", options: ["should", "must", "can", "will"], hint: "Healthy recommendation" },
      { sentence: "We ___ litter in the school or the local area.", blank: "mustn't", options: ["mustn't", "shouldn't", "can't", "won't"], hint: "Strict prohibition — a school rule" },
    ]},
  { week: 23, title: "Goals & Ambitions", grammarFocus: "I want to / I need to / I try to (to-infinitive after verbs)",
    questions: [
      { sentence: "I want ___ become a doctor and help people.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'want'" },
      { sentence: "She needs ___ improve her English speaking skills.", blank: "to", options: ["to", "for", "at", "in"], hint: "Infinitive marker after 'needs'" },
      { sentence: "He is trying ___ learn guitar in his free time.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'trying'" },
      { sentence: "I decided ___ join the English debate club this year.", blank: "to", options: ["to", "for", "at", "by"], hint: "Infinitive marker after 'decided'" },
      { sentence: "She hopes ___ study abroad in New Zealand someday.", blank: "to", options: ["to", "for", "at", "in"], hint: "Infinitive marker after 'hopes'" },
      { sentence: "Do you plan ___ take any language tests this year?", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'plan'" },
      { sentence: "He promised ___ study harder after his low test score.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'promised'" },
      { sentence: "I want ___ travel around the world before I get old.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'want'" },
      { sentence: "She agreed ___ help me practice my English speech.", blank: "to", options: ["to", "for", "at", "in"], hint: "Infinitive marker after 'agreed'" },
      { sentence: "I am trying ___ speak more English every day.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'trying'" },
    ]},
  { week: 24, title: "Hobbies as Gerunds", grammarFocus: "I enjoy swimming / I'm good at cooking (gerunds after verbs/prepositions)",
    questions: [
      { sentence: "I enjoy ___ novels in English before bed.", blank: "reading", options: ["reading", "read", "to read", "reads"], hint: "-ing form after 'enjoy'" },
      { sentence: "She is good at ___ the piano.", blank: "playing", options: ["playing", "play", "to play", "plays"], hint: "-ing form after 'good at'" },
      { sentence: "He finished ___ his report just before midnight.", blank: "writing", options: ["writing", "write", "to write", "writes"], hint: "-ing form after 'finished'" },
      { sentence: "I can't stop ___ English YouTube videos.", blank: "watching", options: ["watching", "watch", "to watch", "watches"], hint: "-ing form after 'stop'" },
      { sentence: "She started ___ Korean last spring.", blank: "learning", options: ["learning", "learn", "to learn", "learns"], hint: "-ing form after 'started'" },
      { sentence: "I spend my free time ___ basketball at the park.", blank: "practicing", options: ["practicing", "practice", "to practice", "practices"], hint: "-ing form after 'spend time'" },
      { sentence: "He keeps ___ the same grammar mistake.", blank: "making", options: ["making", "make", "to make", "makes"], hint: "-ing form after 'keeps'" },
      { sentence: "___ slowly is important for good digestion.", blank: "Eating", options: ["Eating", "Eat", "To eat", "Eats"], hint: "Gerund as the subject of the sentence" },
      { sentence: "Are you interested in ___ the art club?", blank: "joining", options: ["joining", "join", "to join", "joins"], hint: "-ing form after 'interested in'" },
      { sentence: "I am thinking of ___ up swimming this summer.", blank: "taking", options: ["taking", "take", "to take", "takes"], hint: "-ing form after 'thinking of'" },
    ]},
  { week: 25, title: "Describing Places", grammarFocus: "There is / There are / Is there a...?",
    questions: [
      { sentence: "There ___ a new vending machine near the gym.", blank: "is", options: ["is", "are", "has", "have"], hint: "There + be verb for singular noun" },
      { sentence: "There ___ thirty-six students in our homeroom class.", blank: "are", options: ["are", "is", "has", "have"], hint: "There + be verb for plural noun" },
      { sentence: "Is there ___ convenience store near your school?", blank: "a", options: ["a", "an", "the", "some"], hint: "Article for singular consonant-sound noun" },
      { sentence: "There ___ enough space in the classroom for everyone.", blank: "isn't", options: ["isn't", "aren't", "hasn't", "don't"], hint: "Negative 'there is' for singular noun" },
      { sentence: "There ___ many interesting clubs to join at our school.", blank: "are", options: ["are", "is", "has", "have"], hint: "There + be verb for plural noun (many)" },
      { sentence: "___ there a hospital near the school?", blank: "Is", options: ["Is", "Are", "Has", "Do"], hint: "Be verb for 'there is' question (singular)" },
      { sentence: "There ___ four floors in our school building.", blank: "are", options: ["are", "is", "has", "have"], hint: "There + be verb for plural noun (four floors)" },
      { sentence: "There ___ a beautiful cherry tree in the schoolyard.", blank: "is", options: ["is", "are", "has", "have"], hint: "There + be verb for singular noun" },
      { sentence: "___ there any students in the classroom right now?", blank: "Are", options: ["Are", "Is", "Have", "Do"], hint: "Be verb for 'there are' question (plural)" },
      { sentence: "How many desks ___ there in the science lab?", blank: "are", options: ["are", "is", "have", "has"], hint: "Be verb for 'how many' question (plural)" },
    ]},
  { week: 26, title: "Giving & Showing", grammarFocus: "Give me the book / Show her the way (SVOO – double object)",
    questions: [
      { sentence: "Please give ___ a moment to think.", blank: "me", options: ["me", "I", "my", "mine"], hint: "Object pronoun — indirect object after 'give'" },
      { sentence: "She showed ___ her collection of stamps.", blank: "me", options: ["me", "I", "my", "mine"], hint: "Object pronoun — indirect object after 'showed'" },
      { sentence: "My teacher taught ___ a new grammar point today.", blank: "us", options: ["us", "we", "our", "ours"], hint: "Object pronoun — indirect object for a group" },
      { sentence: "Can you lend ___ your dictionary for a moment?", blank: "me", options: ["me", "I", "my", "mine"], hint: "Object pronoun — indirect object after 'lend'" },
      { sentence: "I bought my mother ___ souvenir from Kyoto.", blank: "a", options: ["a", "an", "the", "some"], hint: "Article for a singular direct object" },
      { sentence: "He sent his friend ___ long letter during the holidays.", blank: "a", options: ["a", "an", "the", "some"], hint: "Article before 'long' (consonant sound)" },
      { sentence: "The teacher gave every student ___ copy of the worksheet.", blank: "a", options: ["a", "an", "the", "some"], hint: "Article for a singular countable noun" },
      { sentence: "She made ___ a beautiful card for my birthday.", blank: "me", options: ["me", "I", "my", "mine"], hint: "Object pronoun — indirect object after 'made'" },
      { sentence: "Please tell ___ your name and school.", blank: "me", options: ["me", "I", "my", "mine"], hint: "Object pronoun — indirect object after 'tell'" },
      { sentence: "He showed ___ how to use the new lab equipment.", blank: "us", options: ["us", "we", "our", "ours"], hint: "Object pronoun — indirect object for a group" },
    ]},
  { week: 27, title: "Life Experiences", grammarFocus: "I have visited / She has won (present perfect – experience)",
    questions: [
      { sentence: "I ___ visited Okinawa twice.", blank: "have", options: ["have", "has", "had", "am"], hint: "Present perfect helper for 'I'" },
      { sentence: "She ___ won the English speech contest three times.", blank: "has", options: ["has", "have", "had", "is"], hint: "Present perfect helper for 'she'" },
      { sentence: "Have you ever ___ eating natto?", blank: "tried", options: ["tried", "try", "tries", "trying"], hint: "Past participle after 'Have you ever'" },
      { sentence: "He has ___ seen snow — he is from Okinawa.", blank: "never", options: ["never", "ever", "already", "yet"], hint: "Adverb meaning 'not at any time'" },
      { sentence: "I have ___ finished my summer homework.", blank: "already", options: ["already", "yet", "ever", "never"], hint: "Adverb meaning 'before now'" },
      { sentence: "Has she ever ___ on stage before?", blank: "performed", options: ["performed", "perform", "performs", "performing"], hint: "Past participle after 'Has she ever'" },
      { sentence: "We ___ studied English together for three years.", blank: "have", options: ["have", "has", "had", "are"], hint: "Present perfect helper for 'we'" },
      { sentence: "I haven't eaten ___  — I was too busy studying.", blank: "yet", options: ["yet", "already", "ever", "never"], hint: "Used in negative sentences — 'not yet'" },
      { sentence: "Have you ___ visited a foreign country?", blank: "ever", options: ["ever", "never", "already", "yet"], hint: "Used in questions — 'at any time?'" },
      { sentence: "She has ___ her goal of running a marathon.", blank: "achieved", options: ["achieved", "achieve", "achieves", "achieving"], hint: "Past participle after 'has'" },
    ]},
  { week: 28, title: "Have You Ever?", grammarFocus: "ever / never / already / yet / just (present perfect adverbs)",
    questions: [
      { sentence: "Have you ___ met a famous person?", blank: "ever", options: ["ever", "never", "already", "yet"], hint: "Used in questions — 'at any time?'" },
      { sentence: "I have ___ been outside of Japan.", blank: "never", options: ["never", "ever", "already", "yet"], hint: "Negative experience — not at any time" },
      { sentence: "She has ___ read the whole textbook.", blank: "already", options: ["already", "yet", "ever", "never"], hint: "Completed before expected — before now" },
      { sentence: "Have you done your homework ___?", blank: "yet", options: ["yet", "already", "ever", "never"], hint: "Used in questions — 'up to now?'" },
      { sentence: "I have ___ arrived at school — sorry I'm late!", blank: "just", options: ["just", "ever", "already", "yet"], hint: "Very recently — a moment ago" },
      { sentence: "He has visited that museum ___ times.", blank: "several", options: ["several", "ever", "never", "yet"], hint: "More than twice but not many" },
      { sentence: "She has ___ tried skiing, but she wants to.", blank: "never", options: ["never", "ever", "already", "yet"], hint: "Zero times — has not experienced it" },
      { sentence: "I have met the new ALT teacher ___ — she is very kind.", blank: "before", options: ["before", "ever", "never", "yet"], hint: "At a previous time — not for the first time" },
      { sentence: "Have you ___ seen a traditional kabuki performance?", blank: "ever", options: ["ever", "never", "already", "yet"], hint: "Used in experience questions" },
      { sentence: "I have ___ finished — let me check my answers again.", blank: "just", options: ["just", "already", "yet", "ever"], hint: "Completed a moment ago" },
    ]},
  { week: 29, title: "How Long?", grammarFocus: "for + duration / since + point in time (present perfect)",
    questions: [
      { sentence: "I have studied English ___ six years.", blank: "for", options: ["for", "since", "in", "from"], hint: "Use ___ for a length or period of time" },
      { sentence: "She has lived in Tokyo ___ she was five years old.", blank: "since", options: ["since", "for", "from", "in"], hint: "Use ___ for a specific starting point in time" },
      { sentence: "How long have you ___ a member of the soccer club?", blank: "been", options: ["been", "be", "are", "was"], hint: "Past participle of 'be'" },
      { sentence: "He has played the guitar ___ elementary school.", blank: "since", options: ["since", "for", "from", "in"], hint: "Use ___ for a specific starting point" },
      { sentence: "We have been friends ___ almost ten years.", blank: "for", options: ["for", "since", "from", "in"], hint: "Use ___ for a length of time" },
      { sentence: "I haven't seen my grandparents ___ last New Year.", blank: "since", options: ["since", "for", "from", "in"], hint: "Use ___ for a specific point in the past" },
      { sentence: "She has worked as an ALT in Japan ___ two years.", blank: "for", options: ["for", "since", "from", "in"], hint: "Use ___ for a length or period of time" },
      { sentence: "This school has stood here ___ more than 100 years.", blank: "for", options: ["for", "since", "from", "in"], hint: "Use ___ for a length of time" },
      { sentence: "I have lived in this neighborhood ___ I was born.", blank: "since", options: ["since", "for", "from", "in"], hint: "Use ___ for the beginning point of a period" },
      { sentence: "He hasn't eaten anything ___ this morning.", blank: "since", options: ["since", "for", "from", "in"], hint: "Use ___ for a specific time point" },
    ]},
  { week: 30, title: "How Things Are Made", grammarFocus: "is made / are produced (passive voice – present)",
    questions: [
      { sentence: "Japanese cars ___ made in factories across Japan.", blank: "are", options: ["are", "is", "were", "have"], hint: "Be verb for plural subject in passive" },
      { sentence: "English ___ spoken in many countries around the world.", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for singular uncountable noun" },
      { sentence: "This textbook ___ used by students all over Japan.", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for singular noun in passive" },
      { sentence: "Cherry blossoms ___ loved by people of all ages.", blank: "are", options: ["are", "is", "were", "have"], hint: "Be verb for plural noun in passive" },
      { sentence: "The school lunch ___ prepared every morning by the staff.", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for singular noun in passive" },
      { sentence: "___ this building used for club activities?", blank: "Is", options: ["Is", "Are", "Was", "Has"], hint: "Passive question with singular noun" },
      { sentence: "Japanese food ___ enjoyed by people all over the world.", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for uncountable noun in passive" },
      { sentence: "Rice ___ grown in most regions of Japan.", blank: "is", options: ["is", "are", "was", "has"], hint: "Be verb for uncountable noun in passive" },
      { sentence: "The test papers ___ collected by the teacher after class.", blank: "are", options: ["are", "is", "were", "have"], hint: "Be verb for plural noun in passive" },
      { sentence: "What language ___ spoken in Brazil?", blank: "is", options: ["is", "are", "was", "has"], hint: "Passive question with singular noun" },
    ]},
  { week: 31, title: "Historical Facts", grammarFocus: "was built / were established (passive voice – past)",
    questions: [
      { sentence: "The Eiffel Tower ___ built in 1889.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past passive be verb for singular noun" },
      { sentence: "The telephone ___ invented by Alexander Graham Bell.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past passive for singular noun" },
      { sentence: "Our school ___ founded more than one hundred years ago.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past passive be verb for singular noun" },
      { sentence: "Many temples in Kyoto ___ built over a thousand years ago.", blank: "were", options: ["were", "was", "are", "have been"], hint: "Past passive be verb for plural noun" },
      { sentence: "The Olympic Games ___ held in Tokyo in 1964.", blank: "were", options: ["were", "was", "are", "have been"], hint: "Past passive be verb for plural noun" },
      { sentence: "___ this castle built during the Edo period?", blank: "Was", options: ["Was", "Were", "Is", "Has"], hint: "Past passive question for singular noun" },
      { sentence: "The old bridge ___ destroyed in the earthquake.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past passive for singular noun" },
      { sentence: "This famous painting ___ created by a Japanese artist.", blank: "was", options: ["was", "were", "is", "has been"], hint: "Past passive for singular noun" },
      { sentence: "The two schools ___ united to form one large school.", blank: "were", options: ["were", "was", "are", "have been"], hint: "Past passive for plural noun" },
      { sentence: "When ___ this shrine built?", blank: "was", options: ["was", "were", "is", "has"], hint: "Past passive question word — singular" },
    ]},
  { week: 32, title: "Describing People & Things", grammarFocus: "who / which / that (relative pronouns – subject)",
    questions: [
      { sentence: "The student ___ won the speech contest is in our class.", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person" },
      { sentence: "I have a friend ___ speaks four languages.", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person" },
      { sentence: "This is the book ___ my teacher recommended.", blank: "that", options: ["that", "who", "where", "whose"], hint: "Relative pronoun for a thing (object clause)" },
      { sentence: "The train ___ goes to Tokyo is very crowded.", blank: "that", options: ["that", "who", "where", "whose"], hint: "Relative pronoun for a vehicle (thing)" },
      { sentence: "She is the person ___ helped me most during my first year.", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person" },
      { sentence: "The app ___ I use to study English is free.", blank: "which", options: ["which", "who", "where", "whose"], hint: "Relative pronoun for a thing" },
      { sentence: "Do you know anyone ___ can speak French?", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person (anyone)" },
      { sentence: "I like movies ___ are based on true stories.", blank: "that", options: ["that", "who", "where", "whose"], hint: "Relative pronoun for a thing (movies)" },
      { sentence: "She is the scientist ___ discovered the new species.", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person" },
      { sentence: "This is the app ___ can help you improve your English.", blank: "that", options: ["that", "who", "where", "whose"], hint: "Relative pronoun for a thing (app)" },
    ]},
  { week: 33, title: "Describing Places", grammarFocus: "where + clause (relative pronoun – place)",
    questions: [
      { sentence: "Japan is a country ___ people bow to greet each other.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a place" },
      { sentence: "That is the park ___ I played as a child.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a location" },
      { sentence: "A library is a place ___ you can borrow books for free.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a place" },
      { sentence: "This is the classroom ___ I had my first English lesson.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a room (place)" },
      { sentence: "Is there a place ___ we can practice speaking English?", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a location" },
      { sentence: "Hiroshima is a city ___ history teaches us about peace.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a city (place)" },
      { sentence: "The staffroom is the place ___ teachers take their breaks.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a room (place)" },
      { sentence: "She wants to work in a hospital ___ she can help patients.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a building (place)" },
      { sentence: "Do you know a restaurant ___ we can eat good sushi?", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a restaurant (place)" },
      { sentence: "This is the gym ___ the national judo competition was held.", blank: "where", options: ["where", "which", "who", "that"], hint: "Relative pronoun for a gym (place)" },
    ]},
  { week: 34, title: "Degrees & Extremes", grammarFocus: "too cold to go out / so hot that we stayed inside",
    questions: [
      { sentence: "It is too cold ___ go outside without a coat.", blank: "to", options: ["to", "for", "so", "that"], hint: "'too + adj + ___ + infinitive'" },
      { sentence: "The bag is too heavy for me ___ carry by myself.", blank: "to", options: ["to", "for", "so", "that"], hint: "'too + adj + for + person + ___ + infinitive'" },
      { sentence: "The music was so loud ___ I couldn't hear the teacher.", blank: "that", options: ["that", "to", "for", "as"], hint: "'so + adj + ___ + result clause'" },
      { sentence: "She was so nervous ___ she forgot her speech.", blank: "that", options: ["that", "to", "for", "as"], hint: "'so + adj + ___ + result clause'" },
      { sentence: "The suitcase was too big ___ fit in the overhead compartment.", blank: "to", options: ["to", "for", "so", "that"], hint: "'too + adj + ___ + infinitive'" },
      { sentence: "He ran so fast ___ nobody could catch him.", blank: "that", options: ["that", "to", "for", "as"], hint: "'so + adverb + ___ + result clause'" },
      { sentence: "The question was ___ difficult for anyone to answer.", blank: "too", options: ["too", "so", "very", "such"], hint: "'___ + adj + for + person + to + verb'" },
      { sentence: "She was ___ tired that she fell asleep on the train.", blank: "so", options: ["so", "too", "very", "such"], hint: "'___ + adj + that + result clause'" },
      { sentence: "It was ___ hot to play soccer outside at midday.", blank: "too", options: ["too", "so", "very", "such"], hint: "'___ + adj + to + infinitive'" },
      { sentence: "The food was ___ spicy that I drank three glasses of water.", blank: "so", options: ["so", "too", "very", "such"], hint: "'___ + adj + that + result clause'" },
    ]},
  { week: 35, title: "Opinions & Ideas", grammarFocus: "It is important to / It is fun to (it is + adjective + to-infinitive)",
    questions: [
      { sentence: "It is important ___ study English every day.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'important'" },
      { sentence: "It is not easy ___ speak a foreign language fluently.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'not easy'" },
      { sentence: "Is it ___ to become fluent in English in one year?", blank: "possible", options: ["possible", "possibly", "impossible", "possibly"], hint: "Adjective meaning 'able to be done'" },
      { sentence: "It is helpful ___ use a dictionary when reading in English.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'helpful'" },
      { sentence: "It is ___ to use your smartphone while cycling.", blank: "dangerous", options: ["dangerous", "dangerously", "danger", "safely"], hint: "Adjective describing risk or harm" },
      { sentence: "It is exciting ___ meet students from different countries.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'exciting'" },
      { sentence: "It is essential ___ get enough sleep before an exam.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'essential'" },
      { sentence: "I think it is ___ to join a club activity.", blank: "worthwhile", options: ["worthwhile", "worthlessly", "worthy", "unworthy"], hint: "Adjective meaning 'worth doing'" },
      { sentence: "It is ___ to make mistakes when learning a language.", blank: "natural", options: ["natural", "naturally", "strange", "unusual"], hint: "Adjective — it is OK and expected" },
      { sentence: "It is ___ for beginners to speak English without mistakes.", blank: "difficult", options: ["difficult", "difficulty", "difficultly", "diffuse"], hint: "Adjective meaning 'hard'" },
    ]},
  { week: 36, title: "If-Then Situations", grammarFocus: "If you study hard, you will pass (real conditional)",
    questions: [
      { sentence: "If you study hard, you ___ pass the exam.", blank: "will", options: ["will", "would", "can", "should"], hint: "Real conditional — result in the future" },
      { sentence: "If it ___ tomorrow, the sports day will be postponed.", blank: "rains", options: ["rains", "rained", "will rain", "is raining"], hint: "Present simple in the 'if' clause" },
      { sentence: "What will happen if we ___ protect the environment?", blank: "don't", options: ["don't", "didn't", "won't", "aren't"], hint: "Negative present simple in 'if' clause" },
      { sentence: "If she ___ every day, she will improve quickly.", blank: "practices", options: ["practices", "practiced", "will practice", "is practicing"], hint: "Present simple in 'if' clause (3rd person)" },
      { sentence: "If you miss the bus, you ___ have to walk to school.", blank: "will", options: ["will", "would", "can", "must"], hint: "Real result in the future" },
      { sentence: "If we recycle more, we ___ produce less waste.", blank: "will", options: ["will", "would", "can", "should"], hint: "Real conditional result" },
      { sentence: "I ___ call you if I am going to be late.", blank: "will", options: ["will", "would", "can", "shall"], hint: "Real conditional promise" },
      { sentence: "If you ___ any questions, please raise your hand.", blank: "have", options: ["have", "had", "will have", "are having"], hint: "Present simple in 'if' clause" },
      { sentence: "The teacher ___ be angry if we are late again.", blank: "will", options: ["will", "would", "is", "was"], hint: "Real conditional result" },
      { sentence: "If it ___ sunny tomorrow, let's go to the park.", blank: "is", options: ["is", "was", "will be", "were"], hint: "Present simple in 'if' clause" },
    ]},
  { week: 37, title: "When I Grow Up", grammarFocus: "When I grow up / If technology improves (when/if + present → future)",
    questions: [
      { sentence: "When I grow up, I want ___ work as an interpreter.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'want'" },
      { sentence: "If robots ___ all the work, what will people do?", blank: "do", options: ["do", "did", "will do", "are doing"], hint: "Present simple in 'if' clause" },
      { sentence: "When I pass the high school entrance exam, I ___ celebrate.", blank: "will", options: ["will", "would", "can", "must"], hint: "Future result clause" },
      { sentence: "If Japan ___ better AI, education will change a lot.", blank: "develops", options: ["develops", "developed", "will develop", "is developing"], hint: "Present simple in 'if' clause (3rd person)" },
      { sentence: "When the cherry blossoms ___, we will have a hanami party.", blank: "bloom", options: ["bloom", "bloomed", "will bloom", "are blooming"], hint: "Present simple in 'when' clause" },
      { sentence: "If you ___ speaking every day, your English will improve.", blank: "practice", options: ["practice", "practiced", "will practice", "are practicing"], hint: "Present simple in 'if' clause" },
      { sentence: "When I visit the UK, I ___ finally use my English.", blank: "will", options: ["will", "would", "can", "must"], hint: "Future result when the event happens" },
      { sentence: "If we work together, we ___ solve any problem.", blank: "can", options: ["can", "could", "will", "should"], hint: "Ability or possibility in the result clause" },
      { sentence: "When I ___ enough money, I will travel around the world.", blank: "save", options: ["save", "saved", "will save", "am saving"], hint: "Present simple in 'when' clause" },
      { sentence: "If technology ___, our lives will become much easier.", blank: "advances", options: ["advances", "advanced", "will advance", "is advancing"], hint: "Present simple in 'if' clause (3rd person)" },
    ]},
  { week: 38, title: "Reporting Speech", grammarFocus: "She said that she was tired / He told me that (indirect speech)",
    questions: [
      { sentence: "She said that she ___ tired after the long practice.", blank: "was", options: ["was", "is", "were", "has been"], hint: "Past form of 'is' — time shifts back in indirect speech" },
      { sentence: "He told me that the test ___ be on Friday.", blank: "would", options: ["would", "will", "can", "must"], hint: "Past form of 'will' in indirect speech" },
      { sentence: "The teacher announced ___ school would finish early.", blank: "that", options: ["that", "what", "which", "if"], hint: "Conjunction connecting the reporting verb and the clause" },
      { sentence: "She said that she ___ already finished the project.", blank: "had", options: ["had", "has", "have", "was"], hint: "Past perfect for completed action in indirect speech" },
      { sentence: "He told us ___ the field trip was cancelled.", blank: "that", options: ["that", "what", "which", "if"], hint: "Conjunction after 'told us'" },
      { sentence: "I heard ___ our school won the regional tournament.", blank: "that", options: ["that", "what", "which", "if"], hint: "Conjunction after 'heard'" },
      { sentence: "She said ___ she had been studying English since Grade 4.", blank: "that", options: ["that", "what", "which", "who"], hint: "Conjunction after 'said'" },
      { sentence: "He promised that he ___ help me with my presentation.", blank: "would", options: ["would", "will", "can", "must"], hint: "Past form of 'will' in indirect promise" },
      { sentence: "She explained that she ___ late because of the traffic.", blank: "was", options: ["was", "is", "were", "has been"], hint: "Past form of 'is' in indirect explanation" },
      { sentence: "They said ___ the meeting had been postponed.", blank: "that", options: ["that", "what", "which", "if"], hint: "Conjunction after 'said'" },
    ]},
  { week: 39, title: "Wishes & Imagining", grammarFocus: "I wish I could fly / If I were you (subjunctive)",
    questions: [
      { sentence: "I wish I ___ speak English as fluently as a native speaker.", blank: "could", options: ["could", "can", "would", "will"], hint: "Past modal in 'I wish' clauses — unreal ability" },
      { sentence: "If I ___ the school principal, I would give more free time.", blank: "were", options: ["were", "was", "am", "be"], hint: "Use 'were' for all subjects in 'If I were'" },
      { sentence: "She wishes she ___ more time to practice her English.", blank: "had", options: ["had", "has", "have", "would have"], hint: "Past form in 'she wishes' — unreal situation" },
      { sentence: "If I ___ a bird, I would fly around the whole world.", blank: "were", options: ["were", "was", "am", "be"], hint: "Subjunctive 'were' for all subjects" },
      { sentence: "I wish our school ___ a larger gymnasium.", blank: "had", options: ["had", "has", "have", "would have"], hint: "Past form in 'I wish' — unreal possession" },
      { sentence: "If I were taller, I ___ join the basketball team.", blank: "could", options: ["could", "can", "would", "will"], hint: "Past modal for ability in unreal condition" },
      { sentence: "She wishes she ___ travel to every country in the world.", blank: "could", options: ["could", "can", "would", "will"], hint: "Past modal for ability in 'she wishes'" },
      { sentence: "I wish I ___ studied harder before the final exam.", blank: "had", options: ["had", "have", "has", "would have"], hint: "Past perfect in 'I wish' — regret about the past" },
      { sentence: "If he ___ me, he would tell the truth.", blank: "were", options: ["were", "was", "is", "be"], hint: "Subjunctive 'were' — 'if he were in my position'" },
      { sentence: "I wish it ___ summer all year round in Japan.", blank: "were", options: ["were", "was", "is", "be"], hint: "Subjunctive 'were' after 'I wish it'" },
    ]},
  { week: 40, title: "Grand Review", grammarFocus: "Mixed grammar — all JHS grammar points",
    questions: [
      { sentence: "I have ___ studying English since I was in Grade 4.", blank: "been", options: ["been", "be", "was", "am"], hint: "Past participle of 'be' in present perfect continuous" },
      { sentence: "If you work hard, you ___ achieve your dreams.", blank: "will", options: ["will", "would", "can", "should"], hint: "Real conditional result clause" },
      { sentence: "This school was ___ over a hundred years ago.", blank: "founded", options: ["founded", "found", "founding", "founds"], hint: "Past participle in passive voice" },
      { sentence: "The student ___ gave the best speech received a prize.", blank: "who", options: ["who", "which", "that", "where"], hint: "Relative pronoun for a person" },
      { sentence: "She said that she ___ try her best at the tournament.", blank: "would", options: ["would", "will", "can", "must"], hint: "Past form of 'will' in indirect speech" },
      { sentence: "It is important ___ respect others and cooperate.", blank: "to", options: ["to", "for", "at", "of"], hint: "Infinitive marker after 'important'" },
      { sentence: "I wish everyone ___ live in peace and harmony.", blank: "could", options: ["could", "can", "would", "will"], hint: "Past modal in 'I wish' — unreal wish" },
      { sentence: "English ___ spoken by more than one billion people.", blank: "is", options: ["is", "are", "was", "has"], hint: "Present passive for singular uncountable noun" },
      { sentence: "She has ___ visited six countries since becoming an ALT.", blank: "already", options: ["already", "yet", "ever", "never"], hint: "Perfect adverb meaning 'before now'" },
      { sentence: "When I ___ up, I want to contribute to world peace.", blank: "grow", options: ["grow", "grew", "will grow", "am growing"], hint: "Present simple in 'when' clause" },
    ]},
];

export function getWeek(weekNumber: number): GGWeek | undefined {
  return grammarGolfWeeks.find((w) => w.week === weekNumber);
}
